- README.md
- src/config.js
- src/user/ZulipAccountsView.js
- src/user/ZulipPasswordAuthView.js
Includes in one place, any value a developer might want to configure
> Introduce config.js file

- .flowconfig
- package.json
- src/api/ApiClient.js
* Add User-Agent to calls (#18) 
* Add focusPing call (#9) 
* Add messagesFlags call (#21)
* Add Flow annotations for these calls
> Improve ApiClient

- docs/developer-guide.md
These are the basic steps required when running the app for the first time. This will be helpful to new contributors trying out the app, and makes it clear that it is a straightforward process.
> Add steps to run app on iOS device without dev vm

- .eslintrc
- src/common/Avatar.js
- src/common/ImageAvatar.js
- src/common/TextAvatar.js
- src/common/__tests__/TextAvatar-test.js
- src/message/MessageView.js
- src/userlist/UserItem.js
* Use name initials
* Calculate background by hashing name
* Tests
> Add alternative Avatar render, when no icon

- src/nav/MainNavBar.js
Removed search icon from MainNavBar as search functionality is has not implemented
Keep title centered
> removed search icon from MainNavBar

- src/accountlist/AccountPickScreen.js
- src/userlist/UserListCard.js
- src/userlist/UserListContainer.js
Based against latest of 'multilogin' branch.
Only last commit is relevant. 
Will rebase if more changes done to other branch.
> Account Switcher when logged in

- src/main/MainScreen.js
- src/nav/MainNavBar.js
Simple wiring to open the user list drawer when the people icon is pressed.
> Fixes #86: Wire up the people icon to open the user list drawer.

- src/main/MainScreen.js
This implements a stream button interaction, identical to what #87 proposes for user list button.
> stream sidebar: Stream button opens the stream sidebar.

- src/api/apiFetch.js
- src/api/getMessages.js
- src/api/pollForEvents.js
- src/api/registerForEvents.js
- src/api/sendMessage.js
- src/compose/ComposeText.js
- src/message/__tests__/__snapshots__/renderHtml-test.js.snap
- src/message/renderHtml.js
- src/realm/subscriptionsReducers.js
- src/stream/streamReducers.js
- src/userlist/UserList.js
First iteration. Works for private messages.
For streams, using a hard coded topic. TopicPicker to be done next.
Turn on 'apply_markdown' to improve message rendering.
> Add basic text message sending

- .eslintrc
- ios/ZulipNative.xcodeproj/xcshareddata/xcschemes/ZulipNative.xcscheme
- package.json
- src/account-info/LogoutButton.js
- src/account/__tests__/accounReducers-test.js
- src/app/appActions.js
- src/common/__tests__/TextAvatar-test.js
- src/compose/ComposeText.js
- src/compose/MessageFormattingHelp.js
- src/message-list/MessageList.js
- src/message/MessageBrief.js
- src/message/MessageGroupView.js
- src/message/TimeRow.js
- src/message/Timestamp.js
- src/userlist/UserListCard.js
- src/userlist/UserStatusIndicator.js
- src/userlist/userListSelectors.js
- src/utils/__tests__/color-test.js
- src/utils/__tests__/date-test.js
- src/utils/__tests__/message-test.js
- src/utils/date.js
(depends on the other PR)
* Group messages by the same recipient
* Rendering of time row when messages are on different day
* Do not group messages if on different days
* Tests
* Add spell-checker and fix misspellings for the last time ever
> Improve Message rendering

- src/api/apiFetch.js
- src/chat/Chat.js
- src/chat/ChatScreen.js
- src/common/platform.android.js
- src/common/platform.ios.js
- src/common/styles.js
- src/compose/ComposeText.js
- src/main-tabbed/MainTabBar.js
- src/main/MainScreen.js
- src/message-list/MessageList.js
- src/message/NoMessages.js
- src/message/Subheader.js
- src/message/headers/PrivateMessageHeader.js
- src/nav/MainNavBar.js
- src/title/TitleGroup.js
- src/userlist/UserListCard.js
* Make some constants platform specific (statusbar etc.)
* Make compose box move in sight when keyboard pops up
* Fix narrowing for compose text send
* Fix group subheader and title
> Several small fixes

- src/compose/ComposeText.js
- src/events/eventActions.js
* Improve vertical sizing
* Fix 'can I send to this narrow' logic
> Fix Compose Text

- src/common/Input.android.js
- src/common/Touchable.android.js
* Fixes input style/sizing
* Fixes Touchable effects for older Android versions
> Android Fixes

- src/common/styles.js
- src/nav/ModalNavBar.js
- src/nav/navReducers.js
- src/start/PasswordAuthScreen.js
- src/start/RealmScreen.js
> Fix login exstra screen flash. Better http prepend

- src/message-list/MessageList.js
- src/message-list/renderMessages.js
- src/message/Subheader.js
- src/message/headers/StreamMessageHeader.js
- src/message/headers/TopicMessageHeader.js
> Multiple style fixes/improvements for message list.

- src/api/apiFetch.js
- src/common/ErrorMsg.js
- src/common/styles.js
- src/nav/Navigation.js
- src/start/AuthTypeScreen.js
- src/start/PasswordAuthScreen.js
- src/start/RealmScreen.js
* Better error handling & validation in Email Login 
* Improve add server and auth type picker
> Improve Login flow

- src/compose/ComposeText.js
> Fix send button touch highlight

- src/common/ImageAvatar.js
- src/common/TextAvatar.js
- src/message/MessageLoading.js
- src/message/Subheader.js
> Make all avatars square with rounded corners

- src/start/PasswordAuthScreen.js
> Use email type keyboard while logging

- src/common/Avatar.js
- src/common/ImageAvatar.js
- src/common/TextAvatar.js
- src/userlist/UserItem.js
- src/userlist/UserStatusIndicator.js
If 'status' is provided to Avatar, it is displayed inline, just as Messenger, Skype and most other chat apps do it.
> Show user status inside Avatar

- src/message-list/MessageList.js
- src/message/headers/PrivateMessageHeader.js
- src/message/headers/StreamMessageHeader.js
> Clip subviews in MessageList to reduce memory usage.

- src/message/MessageContainer.js
- src/message/renderHtml.js
This significantly simplifies `MessageContainer` and possibly speeds up rendering.
> Parse and render messages synchronously.

- src/message/headers/PrivateMessageHeader.js
- src/message/headers/StreamMessageHeader.js
- src/message/headers/TopicMessageHeader.js
> Improve message header sizes and touch areas

- src/chat/__tests__/chatReducers-test.js
- src/message/headers/MessageHeader.js
- src/utils/__tests__/narrow-test.js
- src/utils/narrow.js
Fixes #231 
* Fix message headers
* Fix messaging self
* Add tests
> Handle messaging self

- src/account/AccountItem.js
- src/common/Button.js
> Distinguish current account on 'Switch Accounts'

- src/utils/userAgent.js
> Fix user-agent to matches other apps format

- src/message/MessageContainer.js
- src/reactions/Reaction.js
> Fix reaction voting. Use brand color for 'voted'

- .eslintrc
- src/api/checkCompatibility.js
- src/api/index.js
- src/config.js
- src/nav/Navigation.js
- src/nav/NavigationContainer.js
- src/start/CompatibilityScreen.js
- src/utils/userAgent.js
On startup do a check to an url loaded from config.js
If the response is anything but status === 400, it is ok (200 or 404 are ok).
If not compatible show a specialized screen.
> Add forced update

- android/app/src/main/AndroidManifest.xml
- src/api/apiFetch.js
- src/app/appActions.js
- src/app/appReducers.js
- src/common/OfflineNotice.js
- src/constants.js
- src/nav/NavigationContainer.js
- src/utils/activityManager.js
> Monitor network status. Show notice if offline

- src/message/Subheader.js
- src/message/Timestamp.js
Better aligned and font size exactly like Slack
> Better message username and time layout/size

- src/message/headers/StreamMessageHeader.js
- src/message/headers/TopicMessageHeader.js
> Fix message headers for different OS text sizes

- src/message/html/HtmlTagA.js
> Fix links and image links

- src/config.js
> Do not suggest any realm by default

- src/account/AccountPickScreen.js
- src/common/Screen.js
- src/common/ZulipStatusBar.js
- src/common/index.js
- src/common/platform.ios.js
- src/common/styles.js
- src/conversations/ConversationsCard.js
- src/main/MainScreenContainer.js
- src/nav/StreamSidebar.js
> Better status bar behavior

- src/common/LoadingIndicator.js
- src/message-list/MessageList.js
Also change the color to black to match the web app.
> Show loading indicator lines only when caught up.

- src/common/ImageAvatar.js
Decrease size of touchable area to size of the picture.
Fixes: #234.
> Fix clicking area of avatar.

- ios/ZulipMobile.xcodeproj/project.pbxproj
- ios/ZulipMobile/Info.plist
This updates the files to change the current version to 0.7.0, changes
our bundle ID to “org.zulip.Zulip”, and renews the development
certificate.
> Update project configuration files.

- src/message/html/HtmlNodeTag.js
- src/start/AuthScreen.js
Otherwise user mentions can span multiple lines when rendered which looks wrong.
> User mentions should use non-breaking spaces.

- src/api/apiFetch.js
- src/chat/ChatScreen.js
- src/common/SearchInput.js
- src/main-tabbed/HomeTab.js
- src/main-tabbed/MainScreen.js
- src/main/MainScreen.js
- src/main/MainScreenContainer.js
- src/message-list/MessageList.js
- src/nav/Navigation.js
- src/nav/StreamSidebar.js
- src/search/SearchScreen.js
- src/start/LoadingScreen.js
Based off of 'message cache' PRs.
* Add search UI and functionality
* Make MessageList more reusable. Use for search results
> Add Search

- src/message/html/HtmlCascadingStyles.js
- src/message/html/HtmlNodeTag.js
- src/message/html/HtmlTagBr.js
> Render <br /> elements.

- src/account-info/AccountDetailsScreen.js
- src/account/AccountPickScreen.js
- src/conversations/ConversationsCard.js
- src/main-tabbed/HomeTab.js
- src/nav/StreamSidebar.js
- src/title/TitleSpecial.js
- src/users/UsersScreen.js
> Make only first letter of titles capitalized. 

- src/search/SearchScreen.js
- src/streamlist/StreamIcon.js
- src/streamlist/StreamItem.js
- src/streamlist/StreamList.js
- src/subscriptions/SubscriptionsScreen.js
Fixes #376 
Also, fixes an icon sizing bug.
> Fix mute icon in sidebar and streams screen

- android/app/src/main/res/values/color.xml
- android/app/src/main/res/values/styles.xml
primaryColor as `#ffffff` (toolbar color) and primaryColorDark as `#d7ccc8` (status bar color).
Fix:#224
> Added default color in android.

- src/account-info/AccountDetails.js
- src/account/AccountItem.js
> Minor layout fixes

- src/common/SearchInput.js
- src/nav/ModalSearchNavBar.js
- src/search/SearchScreen.js
- src/subscriptions/SubscriptionsScreen.js
* Better sizing of the search button (and reuse of existing component)
* Fixes input sizing, that made it go outside screen
* Fixes centering of text
* Improves setState call (if setState depends on prev state, 2nd form of the call)
* Some simplifications of logic/naming
> Polish SearchBox in Screen nav bar

- src/account-info/AccountDetails.js
- src/config.js
- src/main/MainScreenContainer.js
- src/main/requestInitialServerData.js
- src/message-list/InfiniteScrollView.js
- src/message-list/MessageList.js
- src/users/UserListCard.js
Fixes #385 
Changes to how many messages are requested at once and when to start asking for more messages (optimal values after testing).
> Do not make multiple message requests

- android/app/src/main/java/com/zulipmobile/MainApplication.java
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
This is to match the latest React Native version.
> Update Android build files and java files

- src/common/SearchInput.js
- src/nav/NavButton.js
- src/nav/SidebarRow.js
- src/nav/StreamSidebar.js
* Fix NavButton sizing
* Fix Sidebar buttons sizing
* Fix SearchInput style
> Several Android fixes

- src/config.js
- src/main/MainScreenContainer.js
> Debounce read message updates.

- src/common/styles.js
Use the same color as the Zulip logo in the latest web app
> Update brand color

- ios/ZulipMobile.xcodeproj/project.pbxproj
- ios/ZulipMobile/AnchorScrollView.h
- ios/ZulipMobile/AnchorScrollView.m
- ios/ZulipMobile/AnchorScrollViewManager.h
- ios/ZulipMobile/AnchorScrollViewManager.m
- ios/ZulipMobile/OptimizedGifDecoder.h
- ios/ZulipMobile/OptimizedGifDecoder.m
- ios/ZulipMobile/TaggedViewManager.h
- ios/ZulipMobile/TaggedViewManager.m
- ios/ZulipMobile/UIView+Tag.h
- ios/ZulipMobile/UIView+Tag.m
- package.json
- src/message-list/InfiniteScrollView.js
- src/message-list/MessageList.js
- src/message-list/renderMessages.js
- src/message/MessageBrief.js
- src/message/MessageFull.js
- src/native/AnchorScrollView.js
- src/native/TaggedView.js
- yarn.lock
This diff removes the React Native fork. Not sure if this is much better though
> Use published version of React Native.

- src/chat/Chat.js
mute array was not being passed correctly to renderMessages!
> Fix: Muted topics were being displayed in homeView

- src/chat/__tests__/chatSelectors-test.js
- src/chat/chatReducers.js
- src/chat/chatSelectors.js
- src/main/MainScreenContainer.js
- src/nav/NavigationContainer.js
> Narrow to first unread message.

- src/main/MainScreen.js
> Fix: Components misalign on rotation (#414)

- README.md
- android/app/build.gradle
- android/app/src/main/java/com/zulipmobile/MainApplication.java
- docs/release-guide.md
In Android without this comment gradle will not build.
> Commented Crashlytics references in Android code.

- android/app/src/main/java/com/zulipmobile/MainApplication.java
Removing duplicate onCreate function, caused by an incorrect merge.
> Fix Android build

- android/app/src/main/AndroidManifest.xml
> Fix:Continous change in StatusBar when keyboard pops.

- README.md
for reference: https://github.com/zulip/zulip-android/blob/master/android-strategy.md
> README: Add info about android plan.

- .eslintrc
- src/reactions/Reaction.js
Implementation waits for network response before updating UI. Optimistic version in works at #485
> Animations: Added emoji counter update animation (non-optimistic)

- src/common/styles.js
> fix: Single line input field should not be scrollable.

- .eslintrc
- src/compose/ComposeText.js
- src/compose/SendButton.js
> Fix: Messages sent even when input field is empty

- src/nav/MainNavBar.js
> Change NavBar color to stream color in topic narrow.

- src/chat/Chat.js
- src/message/MessageList.js
* Move onScroll handler from MessageList to Chat
* Do not mark as read in search results
> Move onScroll handler from MessageList to Chat

- package.json
- src/common/Screen.js
- src/common/ZulipStatusBar.js
- src/common/index.js
- src/main/MainScreen.js
- src/nav/MainNavBar.js
- src/search/SearchScreen.js
- src/utils/__tests__/color-test.js
- src/utils/color.js
- yarn.lock
* Make sure status bars behave consistently between different screens
* Do not hide status bar in Android
* Fix bugs with text/bg color
> Consolidate all StatusBar logic

- ios/ZulipMobile.xcodeproj/project.pbxproj
- src/common/LoadingIndicator.js
- src/reactions/Reaction.js
This is enabled by default in projects created with RN39+
Since this project was created with much older project template, it has to be enabled by default.
> Enable native animations

- src/common/Icons.js
- src/nav/ModalNavBar.js
- src/nav/ModalSearchNavBar.js
- src/nav/NavButton.js
- src/nav/StreamSidebar.js
> Use icons for base-level narrows and search

- src/chat/Chat.js
- src/chat/UnreadNotice.js
- src/compose/ComposeBox.js
> Fix #573: Added unread count + offset for compose box

- .eslintrc
- package.json
- src/ZulipMobile.js
- yarn.lock
> Add Intl API polyfill for older iOS and Android devices

- src/common/ErrorMsg.js
- src/start/AuthScreen.js
Do not try to translate realm name.
> Fix i18n bug in Auth screen

- src/start/AuthScreen.js
- src/start/PasswordAuthView.js
- src/start/RealmScreen.js
> Hide soft keyboard on form submission. Submit form with done button in keyboard

- src/common/Popup.js
- src/compose/ComposeText.js
> fix: Autocomplete not being displayed.

- src/account-info/AccountDetailsScreen.js
- src/title/TitleGroup.js
- src/title/TitlePrivate.js
Several ways a user might not be found:
* trying to chat with a bot
* trying to see a user but the data has not yet loaded
> Fix several cases of user not found crashing the app

- android/app/src/main/AndroidManifest.xml
- src/chat/Chat.js
- src/common/Screen.js
- src/compose/ComposeText.js
> Fix compose offset when keyboard pops up.

- src/Providers.js
- src/ZulipMobile.js
- src/conversations/ConversationsCard.js
- src/i18n/translations/messages_de.json
- src/main/MainScreen.js
- src/nav/MainNavBar.js
- src/nav/NavigationContainer.js
- src/nav/StreamSidebar.js
- src/settings/LanguagePickerItem.js
* Makes StatusBar never hide, even on iOS with drawers (auto-hiding caused a lot of issues where it remains hidden for modals open from drawers)
* Better layout for Settings and
* Full reload of app on language change
> Fix several layout issues. Improve language change

- src/html/tags/HtmlTagA.js
> Make links and #streams clickable in messages.

- src/search/SearchMessagesScreen.js
> Fix: error on message long press in messageSearchScreen.

- src/autocomplete/EmojiAutocomplete.js
- src/autocomplete/PeopleAutocomplete.js
- src/autocomplete/StreamAutocomplete.js
- src/common/Popup.js
This enable user to get all the options which matches
input and is more convenient as now we don't have to type much.
fix:#623
> Make autocomplete suggestions scrollable.

- src/nav/ModalNavBar.js
1) added rightItem to ModalNavaBar
2) support custom text title/children views
These changes will be useful for lightbox as well.
> Improve ModalNavBar.

- src/common/ZulipButton.js
Just adding `icon="icon-name"` adds an icon to the button.
> Added icon support to ZulipButton

- src/html/HtmlNodeText.js
> Make message text color to black on Android.

- android/app/build.gradle
- android/app/src/main/java/com/zulipmobile/CustomTabsAndroid.java
- android/app/src/main/java/com/zulipmobile/ZulipNativePackage.java
- src/message/MessageContainer.js
- src/nativeModules/CustomTabsAndroid.js
- src/utils/openLink.android.js
- src/utils/openLink.ios.js
> Open link in customTabs on Android.

- package.json
- src/message/EditedTag.js
- src/message/MessageBrief.js
- src/message/MessageFull.js
- src/message/MessageTags.js
- yarn.lock
> Show edited tag if messages are edited.

- src/nav/StreamSidebar.js
> Open SubscriptionsScreen on clicking All Streams in left drawer.

- package.json
- src/account/__tests__/accountSelectors-test.js
- src/chat/__tests__/chatSelectors-test.js
- yarn.lock
* add 'deep-freeze'
* use deepFreeze to make a state immutable in tests
* tests fail if they mutate the state
> Add tests to selectors to detect mutation

- src/compose/ComposeBox.js
- src/compose/ComposeText.js
- src/compose/__tests__/getComposeInputPlaceholder-test.js
- src/compose/getComposeInputPlaceholder.js
- if PM to a person 'Message @ThisPerson'
- if PM to self 'Jot down something'
- if narrowed to a stream 'Message #streamname'
topic narrow
- if group PM => we should decide //TODO
> Show smart placeholder for compose input.

- src/html/HtmlStyles.js
- src/message/MessageContainer.js
> Highlight searched text with yellow color.

- src/settings/SettingsScreen.js
For next release , it's better to hide the night mode option.
> Hides non-working night mode from settings

- src/message/messageActionSheet.js
'Reply' and 'Narrow to conversation' works same so removed this.
> Removed 'Narrow to conversation' option

- src/message/MessageContainer.js
- src/message/renderMessages.js
because "EVENT_UPDATE_MESSAGE_FLAGS" is updated in flags.
> Better logic to determine whether message is starred or not.

- .eslintrc
- src/api/toggleMessageStarred.js
- src/chat/__tests__/flagsReducers-test.js
- src/chat/flagsReducers.js
- src/message/MessageList.js
- src/message/messageActionSheet.js
> Added star/unstar option in messageActionSheet.

- src/autocomplete/PeopleAutocomplete.js
- src/users/UserItem.js
- src/users/__tests__/usersSelectors-test.js
- src/users/usersSelectors.js
part of issue #705 
search in email
search by initials
> Search by initials and in email for people auto complete suggestions.

- src/search/SearchMessagesScreen.js
> Fix: 'undefined is not an object' in message search screen.

- .eslintrc
- android/app/build.gradle
- android/app/src/main/java/com/zulipmobile/MainApplication.java
- android/settings.gradle
- ios/ZulipMobile.xcodeproj/project.pbxproj
- package.json
- src/utils/showToast.js
This uses a better toast library [react-native-toast](https://github.com/remobile/react-native-toast)
Now toast shows up on ios too.
> Fix: Use react-native-toast for toast messages.

- src/api/registerForEvents.js
- src/main/MainScreenContainer.js
- src/message/renderMessages.js
It can be made user configurable from the app, this is fetching from the server right now!
> Fix: Receive twentyFourHourTime from the server on intital fetch

- src/account-info/AccountDetails.js
- src/account-info/AccountDetailsContent.landscape.js
- src/account-info/AccountDetailsContent.portrait.js
- src/account-info/AccountDetailsScreen.js
- src/common/Avatar.js
- src/common/ImageAvatar.js
- src/common/TextAvatar.js
- src/utils/mediumAvatar.js
1. Added one extra shape to `<Avatar/>`
2. Made profile picture in Account Details Screen larger
3. Different layouts for portrait and landscape orientations
> Improvements to Account Details Screen

- android/app/src/main/java/com/zulipmobile/notifications/GCMPushNotifications.java
- Use big view style for 1 conversation
- Shows number of messages 
- Changed the icon to a better clear icon
> Use big view styles for 1 conversation

- src/common/Input.js
- src/compose/ComposeText.js
- src/compose/__tests__/getComposeInputPlaceholder-test.js
- src/compose/getComposeInputPlaceholder.js
- src/i18n/messages.js
- src/i18n/translations/messages_ar.json
- src/i18n/translations/messages_bg.json
- src/i18n/translations/messages_cs.json
- src/i18n/translations/messages_de.json
- src/i18n/translations/messages_en.json
- src/i18n/translations/messages_es.json
- src/i18n/translations/messages_fr.json
- src/i18n/translations/messages_hi.json
- src/i18n/translations/messages_hu.json
- src/i18n/translations/messages_it.json
- src/i18n/translations/messages_ja.json
- src/i18n/translations/messages_ko.json
- src/i18n/translations/messages_ml.json
- src/i18n/translations/messages_nl.json
- src/i18n/translations/messages_pl.json
- src/i18n/translations/messages_pt.json
- src/i18n/translations/messages_ru.json
- src/i18n/translations/messages_sr.json
- src/i18n/translations/messages_sv.json
- src/i18n/translations/messages_ta.json
- src/i18n/translations/messages_zh-Hans.json
* Fix broken translation messages
* Add custom messages support for Input placeholders
* Add missing translations
> Fix and improve translations

- src/nav/MainNavBar.js
observed this bug when using dark theme.
> Fix: Use navBar background as statusbar color.

- src/account-info/AccountDetails.js
email text was difficult to see in dark theme. So added the brand color to email text.
> Adds email text color in Account screen to be visible in night theme

- .eslintrc
- ios/ZulipMobile.xcodeproj/project.pbxproj
- jestSetup.js
- package.json
- src/common/showToast.js
- src/message/__tests__/messageActionSheet-test.js
- src/message/messageActionSheet.js
- src/utils/__tests__/narrow-test.js
- src/utils/narrow.js
- yarn.lock
> Improvement in messageActionSheet

- src/message/messageActionSheet.js
Now one can easily share message on other apps.
> Added share option in messageActionSheet.

- src/users/UserItem.js
> Fix: email not visible in autocomplete on smaller devices.

- src/compose/ModeViews/StreamBox.js
This also fixes the placeholder color issue  which was not properly visible in dark theme.
Before : 
After :
> Use Input instead of TextInput in StreamBox

- .eslintrc
- src/common/Icons.js
- src/common/Input.js
- src/common/MultilineInput.js
- src/common/SearchInput.js
- src/compose/ComposeText.js
- src/compose/ModeViews/StreamBox.js
- src/start/PasswordAuthView.js
- src/start/RealmScreen.js
- src/styles/theme.js
Created custom button for Android.
clearbuttonmode only works for iOS.
Fix:#628
> Added clear button to clear search query.

- src/common/Input.js
Required for #791 
P.S: Couldn't include a screenshot because app's failing to load on latest merge :P
> Make ClearButton in SearchInput look native

- src/html/cascadingStylesText.js
> Added CSS styles for code rendering.

- src/chat/Chat.js
- src/chat/__tests__/chatReducers-test.js
- src/chat/chatReducers.js
- src/main/MainScreenContainer.js
- src/message/messagesActions.js
- src/realm/realmActions.js
fixes #773 
This solves the anchor bug on both platforms.
> Fix: Reset cache on first message request.

- jsconfig.json
- src/nav/ModalSearchNavBar.js
- src/search/SearchScreen.js
- src/subscriptions/SubscriptionsScreen.js
> Add option to escape search state when in SubscriptionSearchScreen

- src/lightbox/LightboxContainer.js
> Support both orientations for lightbox.

- src/chat/Chat.js
- src/message/NotSubscribed.js
- src/nav/MainNavBar.js
- src/title/Title.js
- src/title/TitleStream.js
- src/types.js
- src/utils/__tests__/narrow-test.js
- src/utils/narrow.js
> Handle narrow to unsubscribed stream.

- src/start/PasswordAuthView.js
- src/styles/theme.js
> Fixes : #784 Adds Forgot password option

- src/html/textStylesFromClass.js
Was going through the code and got this some.
> Remove duplicate codes

- src/start/PasswordAuthView.js
- src/styles/theme.js
> fix: overlapping of forgot password and google button.

- src/start/DevAuthScreen.js
> Use actions object to get loginSuccess method in DevAuthScreen.

- src/autocomplete/AutoCompleteView.js
- src/autocomplete/__tests__/getAutocompleteFilter-test.js
- src/autocomplete/getAutocompleteFilter.js
- Created new method to get filters from text.
- Added tests.
Complete fix for #823.
> Fix: @mention suggestions disappear after typing a space.

- .eslintrc
- package.json
- src/common/UnreadCount.js
- src/users/UserItem.js
- src/users/UserList.js
- src/users/UserListCard.js
- src/users/UsersScreen.js
- yarn.lock
This takes care of all the duplicate re-renders in users module. 
some data
before
after
> [Refactor]: Users module refactor to prevent rerenders.

- src/account/accountSelectors.js
- src/autocomplete/PeopleAutocomplete.js
- src/chat/__tests__/chatReducers-test.js
- src/chat/chatReducers.js
- src/chat/chatSelectors.js
- src/conversations/ConversationsContainer.js
- src/events/eventMiddleware.js
- src/events/eventToAction.js
- src/message/MessageBrief.js
- src/message/MessageContainer.js
- src/message/MessageFull.js
- src/reactions/ReactionList.js
- src/reactions/aggregateReactions.js
- src/start/AuthScreen.js
- src/start/PasswordAuthView.js
- src/title/Title.js
- src/typing/__tests__/typingReducers-test.js
- src/typing/typingReducers.js
- src/users/UserListCard.js
- src/users/UsersScreen.js
- src/utils/__tests__/message-test.js
- src/utils/__tests__/narrow-test.js
- src/utils/message.js
- src/utils/narrow.js
* do use only 'ownEmail' instead of both 'ownEmail' and 'selfEmai'
* use getCurrentRealm and getOwnEmail selectors
> Refactor for consistency: selfEmail => ownEmail

- src/lightbox/LightboxContainer.js
> Fix regression: Cancel button not working for lightbox.

- src/common/Input.js
This PR solves the issue of clear button.
@borisyankov Ready for review
> Fixes : #810 Improves the Clear Button

- .eslintrc
- src/html/HtmlNodeTag.js
- src/html/HtmlStyles.js
- src/html/cascadingStylesView.js
- src/html/indexedViewsStyles.js
- src/html/renderHtmlChildren.js
messages link https://chat.zulip.org/#narrow/stream/test.20here/topic/fractions
> Added mfrac tag to render fractions in messages.

- src/account/AccountList.js
- src/autocomplete/EmojiAutocomplete.js
- src/autocomplete/PeopleAutocomplete.js
- src/autocomplete/StreamAutocomplete.js
> Replaced maps with FlatList in AccountPickScreen.

- package.json
- yarn.lock
Downgraded action sheet library to 0.3.1.
fix: #867
> Fix: error on message long press.

- src/account-info/AccountDetailsScreen.js
- src/chat/GroupDetailsScreen.js
- src/i18n/translations/messages_en.json
- src/nav/AppNavigator.js
- src/nav/MainNavBar.js
- src/nav/__tests__/navigationSelector-test.js
- src/nav/navActions.js
- src/nav/navigationSelectors.js
- src/styles/theme.js
- src/styles/themeDark.js
- src/styles/themeLight.js
- src/title/TitleGroup.js
- src/types.js
- src/users/__tests__/usersSelectors-test.js
- src/users/userSelectors.js
Which is shown on touching Group Title.
this PR is against #312 
@borisyankov @nashvail I have used cards to show members list. What other UX you are thinking of?
> Added Group Details Screen.

- .eslintrc
- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/zulipmobile/MainActivity.java
- android/app/src/main/java/com/zulipmobile/MainApplication.java
- android/sentry.properties
- android/settings.gradle
- index.android.js
- ios/ZulipMobile.xcodeproj/project.pbxproj
- ios/ZulipMobile/AppDelegate.m
- ios/ZulipMobile/Info.plist
- ios/sentry.properties
- package.json
- src/ZulipMobile.js
- yarn.lock
Removed fabric from Android.
Removed fabtic from ios
> Initial Implementation of Sentry.

- src/search/SearchScreen.js
- src/subscriptions/SubscriptionsScreen.js
This PR removes the duplicate clear button from Search Screen and Subscription Screen
> Remove unused clear button

- src/subscriptions/SubscriptionsScreen.js
> Fix: undefined error on toggling subscribe switch in subsriptionsScreen.

- src/common/ZulipSwitch.js
- src/streams/StreamItem.js
fix: #568
also part of https://github.com/zulip/zulip-mobile/pull/564
fixes:
> Disable switch in Subscription screen for private stream which is not subscribed.

- src/account-info/SwitchAccountButton.js
> fix: error on clicking switch account button.

- src/lightbox/LightboxContainer.js
this PR
[current master](https://github.com/zulip/zulip-mobile/tree/81a481e765e3a9948374c711aea68287951b8c9f)
> Fix: undefined stream name in Lightbox.

- src/autocomplete/StreamAutocomplete.js
- src/baseSelectors.js
- src/streams/SubscriptionsContainer.js
- src/subscriptions/__tests__/subscriptionSelectors-test.js
- src/subscriptions/subscriptionSelectors.js
because streams change  events are updated in streams.
> Created selector to get subscribed streams.

- docs/performance.md
- docs/testing.md
This could be useful for future contributors.
> Docs: Add tips to avoid duplicate re-renders.

- src/i18n/translations/messages_en.json
- src/message/messageActionSheet.js
Fixes : https://github.com/zulip/zulip-mobile/issues/883
Used editing message api to update the message as `(deleted)` same as it is done on web.
> Implements deleting message

- docs/getting-started.md
Solves #916, more easy for users.
> Added react-native run-ios in Getting Started

- src/autocomplete/PeopleAutocomplete.js
- src/baseSelectors.js
- src/common/Avatar.js
- src/common/ImageAvatar.js
- src/common/TextAvatar.js
- src/conversations/ConversationUser.js
- src/nullObjects.js
- src/users/UserList.js
- src/users/UserListCard.js
- src/users/__tests__/usersSelectors-test.js
- src/users/userSelectors.js
> Show user status in UserScreen, PeopleAutocomplete and right drawer.

- src/app/appReducers.js
- src/chat/__tests__/chatReducers-test.js
- src/chat/__tests__/chatUpdater-test.js
- src/chat/chatUpdater.js
- src/html/HtmlNodeTag.js
- src/presence/__tests__/presenceReducers-test.js
- src/users/__tests__/usersReducers-test.js
- src/users/__tests__/usersSelectors-test.js
- src/users/userSelectors.js
Thanks to Boris for noticing this.
> Return original state when no change is needed in tests.

- src/types.js
- src/unread/__tests__/unreadReducers-test.js
- src/unread/__tests__/unreadSelectors-test.js
- src/unread/unreadReducers.js
- src/unread/unreadSelectors.js
> Renamed mentioned to  mentions.

- src/__tests__/StylesProvider-test.js
- src/common/SlideAnimationView.js
- src/html/__tests__/HtmlNodeText-test.js
- src/lightbox/LightboxContainer.js
- src/lightbox/LightboxFooter.js
- src/lightbox/LightboxHeader.js
- src/lightbox/LightboxScreen.js
- src/lightbox/__tests__/LightboxFooter-test.js
- src/lightbox/__tests__/LightboxHeader-test.js
- src/lightbox/__tests__/__snapshots__/LightboxFooter-test.js.snap
- src/lightbox/__tests__/__snapshots__/LightboxHeader-test.js.snap
- src/nav/navActions.js
- src/types.js
- src/utils/tests.js
I wanted to prevent such regressions and in the process added snapshot tests and refactored lightbox dir.
Followup
* components which are connected to redux store, need to provide Connector flow type, only then we would be able to detect flow errors in such cases.
example: https://github.com/reactjs/redux/tree/master/examples/todos-flow
* need to figure out connectActionSheet flow type since `expo/react-native-action-sheet` doesn't export it.
Suggestions welcome.
> Fix regressions in lightbox and add snapshot tests.

- src/common/ImageAvatar.js
- src/lightbox/__tests__/__snapshots__/LightboxHeader-test.js.snap
- src/title/TitleSpecial.js
Since RN v46, support for nested views inside Image component has been dropped and instead new component ImageBackground has been exposed for this use case.
https://github.com/facebook/react-native/commit/9637dd4a1b78d5f6da510b1b4ad10d45d67badbf
> Android: Fix avatar not visible

- .travis.yml
This might be issue of build falling on travis.
> Use precise distributor for travis build.

- src/start/RealmScreen.js
> Fix: Android crash on entering realm url without protocol.

- src/streams/StreamList.js
> Change sort order of streams list to match Zulip's standards.

- .eslintrc
- src/common/Icons.js
- src/nav/AppNavigator.js
- src/nav/navActions.js
- src/settings/SettingsCard.js
- src/settings/SettingsDetailScreen.js
> Separate language to another screen in settings screen

- src/nav/AppContainer.js
- src/realm/realmActions.js
- src/realm/realmSelectors.js
- src/selectors.js
This improves startup time during first login from ~9170ms to ~6160ms (benchmarked this on a  3.6MB/s connection)
> Perf: Fix issue with multiple realm initialisation calls on startup.

- src/common/MultilineInput.js
- src/compose/ComposeBox.js
[current master](https://github.com/zulip/zulip-mobile/tree/acd238db531689de937dc8c7c27cecfd7a61422c)
this PR
> Fix: autocomplete not being visible on current master.

- src/common/SearchEmptyState.js
- src/common/index.js
- src/i18n/translations/messages_en.json
- src/search/SearchMessagesCard.js
- src/streams/StreamList.js
- src/subscriptions/SubscriptionsCard.js
- src/users/UserList.js
> Conditionally render EmptyState or Search Results

- src/utils/color.js
> Fix: status bar style in dark theme for private narrow.

- src/baseSelectors.js
- src/chat/Chat.js
- src/chat/ChatContainer.js
- src/chat/chatSelectors.js
- src/message/MessageContainer.js
- src/message/MessageFull.js
- src/message/MessageList.js
- src/message/MessageListContainer.js
- src/message/__tests__/renderMessages-test.js
- src/message/headers/MessageHeader.js
- src/message/headers/MessageHeaderContainer.js
- src/message/messageActionSheet.js
- src/message/renderMessages.js
- src/search/SearchMessagesCard.js
first part of the message list refactor
> Refactor: MessageList and create container component.

- src/common/Avatar.js
- src/common/ComponentWithOverlay.js
- src/common/UserStatusIndicator.js
- src/common/index.js
- src/compose/ComposeMenu.js
- src/group/AvatarList.js
- src/group/GroupCard.js
- src/nav/NavButton.js
A generic component that allows you to place any component over another plus an optional circular background. To simplify manual usage of this pattern elsewhere.
> Add ComponentWithOverlay

- .eslintrc
- src/html/HtmlNodeTag.js
- src/html/cascadingStylesView.js
- src/html/tags/HtmlTagDiv.js
- src/message/MessageBrief.js
- src/message/MessageContainer.js
- src/message/MessageFull.js
- src/message/__tests__/getMessageContent-test.js
- src/message/getMessageContent.js
Use ScrollView to render div with class codehilite.
Render new entries inside <"pre"> on the same line. 
Do render new lines.
Complete fix for #741
messages link in the screenshots and gif
https://chat.zulip.org/#narrow/stream/development.20help/subject/apt.20repo/near/241568
https://chat.zulip.org/#narrow/stream/development.20help/subject/mypy.20imports/near/222405
(current master)[https://github.com/zulip/zulip-mobile/tree/98abd0d5e990ae724f05d3f33be7c517fb964d89] 
This PR
> Better code formatting

- src/api/focusPing.js
- src/config.js
- src/nav/AppContainer.js
- src/nullObjects.js
- src/presence/__tests__/presenceReducers-test.js
- src/presence/presenceReducers.js
- src/users/__tests__/usersSelectors-test.js
- src/users/userSelectors.js
- src/users/usersActions.js
Ready for first round of review.
fix:#927
> fix: only active status is shown in UserStatusIndicator.

- src/conversations/ConversationsCard.js
- src/message/MessageContainer.js
- src/message/messageActionSheet.js
- src/nav/StreamSidebar.js
- src/nav/__tests__/navigationSelector-test.js
- src/nav/navigationSelectors.js
- src/selectors.js
- Close drawer after selecting search or setting in StreamSidebar. 
- Close user drawer on selecting Search People.
- Navigate back on selecting narrow/reply from search screen. 
- Disable edit/delete option in special narrow.
> Improve options selections in messageActionSheet.

- src/api/apiFetch.js
- src/api/updateMessage.js
- src/compose/ComposeBox.js
- Fix: edit message not working.  |   |   | 4cc5abd
- Show a dialog if edit message time limit is over. |   |   | 9e27c77
- replaceEmoticonsWithEmoji in the edited message content. |   |   | 4de31ca
- Do nothing if edited content and original content is same. |   |   | 77a6efd
- Focus input after selecting Edit message. |   |   |  edf7b7b
> Fix message editing.

- src/message/HtmlChildrenContainer.js
- src/message/MessageBrief.js
- src/message/MessageFull.js
> Fix: message long press not working.

- src/common/MultilineInput.js
- src/common/SearchInput.js
- src/compose/ComposeBox.js
> Fix text not visible in Input/MultilineInput ComposeBox

- src/html/HtmlStyles.js
- src/message/InfiniteScrollView.js
conversation link https://chat.zulip.org/#narrow/stream/test.20here/topic/list.20inside.20list
Before
After
> Fix: list inside list message rendering.

- src/autocomplete/__tests__/getAutocompletedText-test.js
- src/autocomplete/getAutocompletedText.js
- yarn.lock
fix: error when emoji which starts with symbol is selected from autocomplete popup.
Select :+1 from autocomplete just after typing :+ in compose box.
fix:
> Rework on getAutocompletedText.

- src/chat/Chat.js
- src/compose/ComposeBox.js
- src/compose/ComposeMenuContainer.js
> Fix: Compose menu action sheet not visible in Android.

- src/message/InfiniteScrollView.js
Did a bisect and found it was this change that caused it. 
Not sure why this happened :/
> Fix: Message being requested in a loop on Android.

- android/app/src/main/java/com/zulipmobile/AnchorScrollView.java
Tested changes on an android device with/without clipped view optimisation.
> Fix: Scrollview anchor behaviour same with/without clipped view optimisation.

- src/message/messageActionSheet.js
- Don't show it on messages which are not sent by self.
- Show it in all narrows.
> Rework on delete option in message option.

- src/chat/Chat.js
- src/compose/ComposeBox.js
- src/message/InfiniteScrollView.js
- src/message/MessageContainer.js
- src/message/MessageList.js
- src/message/MessageListContainer.js
- src/message/MessageListItem.js
- src/message/cachedMessageRender.js
- src/message/messageActionSheet.js
> Focus message input after selecting reply from message action sheet.

- src/autocomplete/AutoCompleteView.js
- src/autocomplete/__tests__/getAutocompleteFilter-test.js
- src/autocomplete/__tests__/getAutocompletedText-test.js
- src/autocomplete/getAutocompleteFilter.js
- src/autocomplete/getAutocompletedText.js
- src/common/MultilineInput.js
- src/compose/ComposeBox.js
- src/types.js
> Show auto complete suggestion when user types in middle/start of the input.

- src/compose/ComposeBox.js
> Rework on compose box height.

- src/users/UserList.js
Added keyboardShouldPersistTaps in UserList.
> Fix: two taps needed to narrow from user search screen.

- src/nav/AppContainer.js
> Handle Android hardware back button press.

- src/common/Icons.js
- src/conversations/ConversationsCard.js
- src/main/MainScreen.js
- src/main/MainScreenWithDrawers.js
- src/nav/IconUnreadConversations.js
- src/nav/MainNavBar.js
- src/nav/ModalNavigation.js
- src/nav/NavButton.js
- src/nav/StreamSidebar.js
> Move Right drawer into the Left Drawer as a tab

- src/i18n/translations/messages_en.json
- src/unread/UnreadStreamsCard.js
> Fixes #1080: Show 'No unread messages' if unread list is empty

- src/start/DevAuthScreen.js
> Add marginTop to dev account list

- src/conversations/ConversationsCard.js
- src/nav/Sidebar.js
Fixes: Drawer left open after narrowing to new private chat from user screen.
> Close drawer after selecting Search People.

- src/animation/AnimatedRotateComponent.js
- src/common/LoadingIndicator.js
- src/message/MessageList.js
- src/message/MessageListFlatList.js
- src/nav/AppNavigator.js
- src/start/LoadingScreen.js
https://chat.zulip.org/user_uploads/2/bf/qwUG8EgcFbh1JcZwy5mUzyfe/Fix-Android-loading-indicator-spin.mov
Alternative for #1200
> Fix: LoadingIndicator spin is not being shown on Android.

- src/conversations/ConversationsCard.js
- src/start/AuthScreen.js
https://sentry.io/zulip/zulip-mobile/issues/355970622/
> Fix: TypeError getFullUrl for realm icon

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
> Android: Don't ask for device id permission.

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/zulipmobile/CloseAllCustomTabsAndroid.java
- android/app/src/main/java/com/zulipmobile/ZulipNativePackage.java
- src/start/oauth.android.js
And used it to close Custom Tabs after Google Auth.
**Which issue solves this PR?**
Custom tabs are left open after Google Auth.
> Implemented close browser method for Android.

- src/account/AccountPickScreen.js
- src/nav/navReducers.js
Fixes the keyboard flashing during account switch, and possibly other issues.
> Better navigation state when switching accounts

- package.json
- src/actionConstants.js
- src/actions.js
- src/boot/reducers.js
- src/events/eventActions.js
- src/utils/redux.js
- yarn.lock
Fixes a bug with batching and also simplified our code.
The library is based on the same Dan Abramov's code we used.
> Replace custom redux batching with 'redux-batched-actions'

- android/app/src/main/java/com/zulipmobile/AnchorScrollView.java
Now JS console
for Android
for iOS
> Android: fix mutiple fetch events got fired without any human interaction.

- ios/ZulipMobile.xcodeproj/project.pbxproj
- ios/ZulipMobile/AnchorScrollViewManager.m
- package.json
- yarn.lock
> Upgraded to RN 0.48.

- android/app/src/main/java/com/zulipmobile/AnchorScrollView.java
@kunall17 can you please verify https://github.com/zulip/zulip-mobile/issues/1267 got fixed by this.
> Fix:nullPointerException in AnchorScrollView on scrolling messageList in Android

- android/app/src/main/java/com/zulipmobile/AnchorScrollView.java
- android/app/src/main/java/com/zulipmobile/AnchorScrollViewManager.java
https://github.com/facebook/react-native/commit/2ceed954904e4097f37eb99655808452d3e28997#diff-49a8f2a72edb3b8c02365cd11a8f2984
> Fix: Android build due to some changes in RN.

- android/app/src/main/java/com/zulipmobile/CustomTabsAndroid.java
- android/app/src/main/java/com/zulipmobile/CustomTabsHelper.java
- android/app/src/main/res/values/strings.xml
fixing https://sentry.io/zulip/zulip-mobile/issues/364094539/
> Handle when custom tabs and browser is not installed.

- src/unread/unreadSelectors.js
fixing https://sentry.io/zulip/zulip-mobile/issues/365246484/
> Fix: crash after logging in and logout.

- src/common/Screen.js
> [Android]Fix: Screen scrollview not scrolling.

- android/app/src/main/AndroidManifest.xml
https://chat.zulip.org/#narrow/stream/mobile/topic/beta.202.2E1.2E33
Don't know why it was working on emulator before. 🤔
> [Android] Fix: browser doesn't close after oAuth on physical device.

- src/api/toggleMobilePushSettings.js
- src/settings/SettingsCard.js
> Fix: json not valid error on toggling push notification.

- src/nav/navReducers.js
[Android] Fix: scroll position automatically changes after few seconds of launching app.
I tested and not able to find any difference. (or am i missing out something?)
BTW it also improved pref issues :)
> Fix:full layout of app is updated after few seconds of launching app.

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/zulipmobile/MainActivity.java
- android/app/src/main/java/com/zulipmobile/MainApplication.java
- android/settings.gradle
- ios/ZulipMobile.xcodeproj/project.pbxproj
- package.json
- src/boot/AppEventHandlers.js
- yarn.lock
Works fine on iOS. But listener is not working on Android (tested on Genymotion emulator). Needs some debugging.
> Use react-native-orientation instead of out logic.

- android/app/src/main/java/com/zulipmobile/notifications/GCMPushNotifications.java
- android/app/src/main/java/com/zulipmobile/notifications/NotificationHelper.java
- android/app/src/main/res/values/strings.xml
> Use inbox style to make android notifications format better

- src/app/appReducers.js
- src/diagnostics/DiagnosticsScreen.js
- src/html/HtmlNodeTag.js
- src/html/HtmlNodeText.js
- src/html/__tests__/renderHtmlChildren-test.js
- src/html/renderHtmlChildren.js
- src/html/tags/HtmlTagLi.js
- src/settings/DebugScreen.js
- src/settings/settingsReducers.js
Fix: #1184
**Advantages**
We are having better rendering (no more extra white spaces)
**Disadvantages**
Now there are many elements (components), so this might increase bridge communication, but in my general testing i can't find any difference :)
(Now sure is this really a disadvantages or not)
BTW in next week or so, I am planning to improve our current scrollView so that there is minimal bridge communication, scroll events etc
> Fix: unexpected markdown rendering.

- src/boot/AppEventHandlers.js
- src/utils/notifications.ios.js
To be merged after server changes are merged https://github.com/zulip/zulip/pull/7080
This is untested though
> Open respective narrow on ios notification click

- src/i18n/translations/messages_en.json
- src/start/DevAuthScreen.js
This is my first pull request for Zulip. This should fix the visibility problem on the night theme on the affected screens. Label replaced Text as a component. Fixes issue #1234
> [WIP]Label instead of Text

- android/app/src/main/java/com/zulipmobile/AnchorScrollView.java
- android/app/src/main/java/com/zulipmobile/AnchorScrollViewManager.java
- src/app/appReducers.js
- src/message/InfiniteScrollView.js
- src/message/MessageList.js
- src/message/MessageListContainer.js
- src/message/messageSelectors.js
So that first unread message is visible.
Same as iOS.
> [Android] Scroll to first unread message.

- .eslintrc
- src/outbox/outboxActions.js
- src/users/__tests__/usersSelectors-test.js
- src/users/userSelectors.js
Slacks shows `@everyone` at the bottom of the list with different layout.
Thoughts?
> [WIP] Fix: error on sending message with '@all' or '@everyone'.

- src/nav/StreamTabs.js
- src/styles/tabs.js
> Fix tabs glitch

- src/search/SearchMessagesCard.js
Current Activity indicator above Zulip logo doesn't look good.
> Show Zulip logo with revolving border as loading indicator in SearchMessageScreen.

- src/common/SearchEmptyState.js
- src/streams/StreamList.js
- src/unread/UnreadStreamsCard.js
* Use SearchEmptyState in UnreadStreasCard.
* Removed All Stream buttom from All Stream tab.
Fix:#1233
> Fix:#1233 Improved layout of empty state text.

- android/app/src/main/java/com/zulipmobile/AnchorScrollEvent.java
- android/app/src/main/java/com/zulipmobile/AnchorScrollView.java
- android/app/src/main/java/com/zulipmobile/AnchorScrollViewHelper.java
- src/message/InfiniteScrollView.js
Alternative for #1424
Works on both Android & iOS :).
> Move message content up when keyboard pops up.

- src/autocomplete/TopicAutocomplete.js
> Fix: x.match is not a function error in suggest topic filter.

- src/html/HtmlNodeText.js
Solves:- https://chat.zulip.org/#narrow/stream/mobile/topic/Text.20wrapping
Message in screenshot https://chat.zulip.org/#narrow/stream/test.20here/subject/testing.20text.20rendering/near/335349
> message render: Don't join last word with space.

- src/chat/Chat.js
- src/chat/__tests__/chatReducers-test.js
- src/chat/chatReducers.js
Fix: messages not added in list if its narrow key is not present in messages reducer.
Fix: #1412
> Fix: app crash after sending first message in narrow.

- src/events/eventActions.js
Props to @jainkuniya for finding the cause of the bug.
> Fix state retrieval in the event loop

- src/styles/theme.js
> Fix: Center title text in ModalNavBar

- android/app/src/main/java/com/zulipmobile/CustomTabsAndroid.java
> [Android] Fix: app crashes when links are opened in browser.

- src/common/LoadingIndicator.js
> [Android] Fix: loading indicator misbehave.

- .eslintrc
- src/utils/__tests__/string-test.js
- src/utils/__tests__/url-test.js
- src/utils/string.js
- src/utils/url.js
fixing https://sentry.io/zulip/zulip-mobile/issues/415961375/
> Rework on identifying & getting narrow from URL.

- android/app/src/main/java/com/zulipmobile/AnchorScrollView.java
- src/message/InfiniteScrollView.js
Fix: blank screen is displayed just after render, little bit of scroll is required to get content displayed.
Fix: not scrolled to first unread messages in ~20% of time.
> [Android] Fix: regressions in AnchorScrollView.

- src/api/subscriptions/toggleStreamNotifications.js
- src/common/OptionRow.js
- src/i18n/translations/messages_en.json
- src/streams/StreamScreen.js
- src/subscriptions/subscriptionsActions.js
> Add an option to change stream push notifications in StreamScreen

- src/lightbox/LightboxFooter.js
- src/lightbox/LightboxHeader.js
> Fix: layout regressions in lightbox header.

- src/message/html/js.js
- src/message/webViewEventHandlers.js
part #1576 
@borisyankov which should be next part :)
> Detect webView scroll & fetch more older/newer messages.

- src/message/html/js.js
Inline comments are not supported in Android webView.
#1583
> webView: Fix: messages are not being posted on Android 7.1.0.

- src/message/html/js.js
- src/message/webViewEventHandlers.js
> webView: Initial implementation of handling urls click.

- src/nullObjects.js
- src/types.js
- src/users/userHelpers.js
Fix: https://sentry.io/zulip/zulip-mobile/issues/421835076/
Fixing
> Fix: undefined error in 'groupUsersByStatus' method.

- .eslintrc
- src/message/html/js.js
- src/message/webViewEventHandlers.js
- src/utils/url.js
Mostly same as @kunall17 PR https://github.com/zulip/zulip-mobile/pull/1598. 
In this PR I have added commits which fixes regressions due to rebasing after my commit https://github.com/zulip/zulip-mobile/commit/bfbaa4e06c03c7981fa4ff72c5302e777a637ab4
> webView: Fix: regressions in navigating to Lightbox. 

- src/title/TitleStream.js
> Rework on Stream Title.

- src/message/html/messageHeaderAsHtml.js
> webView: narrow to topic on clicking headers in stream narrow.

- src/main/MainScreenWithDrawers.js
- src/nav/AppWithNavigationState.js
> [Android] Fix: multiple hardware back button presses are required to navigate back.

- src/message/html/js.js
- src/message/webViewEventHandlers.js
> webView: Fix app crash on clicking images.

- src/message/html/js.js
>  webView: Adjust content when soft keyboard toggles.

- src/message/html/css.js
Make text un-selectable on longPress.
Fix: #1672
Part 1 of #1590 
#1590 is almost implemented, will submit PR soon after rebasing it with current master.
> webView: fix regression is css.

- src/start/RealmScreen.js
> Fix: undefined error in RealmScreen.

- src/message/MessageListContainer.js
- src/render-html/MessageListWeb.js
- src/render-html/html.js
- src/render-html/js-es3.js
- src/render-html/js.js
- src/render-html/webViewHandleUpdates.js
- src/render-native/MessageListScrollView.js
> webView: Rework on message loading view.

- src/animation/AnimatedComponent.js
- src/chat/UnreadNotice.js
Fix: #1697.
Let me know changes :)
> Fix: white space is shown when no messages are unread.

- src/render-html/css.js
- src/render-html/messageAsHtml.js
> webView: Do not render empty avatar for brief messsage.

- src/render-html/css.js
> webView: Limit avatar touchable area.

- src/render-html/css.js
- src/render-html/messageAsHtml.js
- src/render-html/renderMessagesAsHtml.js
Same as web: https://github.com/zulip/zulip/blob/a49fd446126b0d45d93ea3cf4954eb05b996c78c/static/styles/zulip.css#L1016
> Highlight mentioned messages

- CONTRIBUTING.md
- docs/developer-guide.md
> Update contributing, developers guide

- ios/ZulipMobile.xcodeproj/project.pbxproj
- ios/ZulipMobile/AppDelegate.m
- src/utils/notifications.ios.js
As the WIX react-native-notifications isn't working for the click event for notifications using getInitialNotification will work! 
But the localNotification doesn't work with getInitalNotificaiton so this is untested https://github.com/facebook/react-native/issues/8580
> Use PushNotificationIOS module to get the initial data

- .eslintrc
- src/render-html/es3.js
- src/render-html/js.js
> webView: Detect long press.

- src/render-html/es3.js
- src/render-html/js.js
- src/render-html/webViewEventHandlers.js
Another small part of #1680 :)
Now only create actionSheet function call is left, will be doing it in another part :)
Let me know changes :)
> webView: Send longPress events via message.

- src/render-html/css.js
> webView: Fix text selectable box is visible on long pressing text.

- src/diagnostics/DiagnosticsScreen.js
Make sure to call `react-native link react-native-version-check`
Also, this library can fetch the latest version from the play store so that can be a good feature too!
> Show current app version in settings card

- src/utils/__tests__/date-test.js
> tests: Fix daysInDate test

- src/search/SearchMessagesCard.js
- src/search/SearchMessagesContainer.js
Fixing
@borisyankov we need to include this in next release.
> search_view: Fix undefined realmEmoji error.

- src/render-html/css.js
> Improve HTML message rendering. Fix emoji popping

- src/message/MessageListContainer.js
- src/render-html/MessageListWeb.js
- src/render-html/webViewEventHandlers.js
- src/render-native/MessageContainer.js
- src/render-native/MessageListItem.js
- src/render-native/MessageListScrollView.js
- src/render-native/MessageListSection.js
- src/render-native/cachedMessageRender.js
- src/render-native/headers/MessageHeader.js
- src/render-native/headers/MessageHeaderContainer.js
- src/utils/__tests__/date-test.js
final part of #1680 & long press 😄
>  webView: Implement longPress method.

- src/render-html/es3.js
- src/render-html/js.js
Tested on Android physical device.
> webView: Improve longPress detection logic.

- src/message/fetchActions.js
- src/message/messagesActions.js
- src/nav/AppWithNavigationState.js
- src/utils/notifications.android.js
- src/utils/notifications.ios.js
- src/utils/notificationsCommon.js
Currently on the master the doNarrow function isn't doing anything with the anchor hence this is in WIP 
https://github.com/zulip/zulip-mobile/blob/bddd8739516ef37765fe7a0f929e0e349e572d79/src/message/messagesActions.js#L17
> [WIP] Use messages id from notification to anchor

- android/app/src/main/AndroidManifest.xml
To make sure support on Chromebooks.
#1834
> [Android] Make camera & touch permissions optional.

- src/account/AccountItem.js
- src/common/Touchable.android.js
Margins styles in TouchableNativeFeedback are not supported.
> [Android] Fix: alignment issues in the AccountItem.

- src/compose/ComposeBox.js
- src/styles/theme.js
> [Android] Fix extra space at the top of the message input.

- src/animation/AnimatedScaleComponent.js
Update display style after animation have successfully ended.
> animation: Fix out animation is broken in AnimatedScaleComponent.

- src/common/Popup.js
- src/compose/ComposeBox.js
> [Android] Fix: autocomplete popup is not visible.

- src/render-html/messageHeaderAsHtml.js
So that it is highlighted when it matches search query.
> webView: Consider match_subject in the header.

- src/streams/StreamItem.js
>  dark_theme: Fix stream name color in All Stream section.

- src/api/emoji_reactions/emojiReactionAdd.js
- src/api/emoji_reactions/emojiReactionRemove.js
- src/reactions/Reaction.js
- src/reactions/ReactionList.js
- src/reactions/aggregateReactions.js
- src/render-html/es3.js
- src/render-html/js.js
- src/render-html/messageReactionAsHtml.js
- src/render-html/webViewEventHandlers.js
> Migrate to newer version of reaction add/remove API.

- src/message/messageActionSheet.js
The function always returns true, even if **message.content** is equal to '(deleted)'
> Fixes #1923, Delete messages must not have delete message option

- src/common/ZulipSwitch.js
- src/styles/index.js
> Fixes: #1920(Changed the value of tintColor of the Switch.)

- src/render-html/css.js
>  webView: Improve styles of code blocks.

- src/presence/__tests__/presenceReducers-test.js
- src/presence/presenceReducers.js
Only update presence of particular client.
Fix: on presence event all existing cleint presence is replaced by the event presence.
> Better handeling of presence event.

- src/chat/Chat.js
- src/chat/ChatScreen.js
[Android] Fix: compose box & navBar are not focussed out when actionSheet pops.
Before
this PR
> Improve ActionSheet Dialog.

- src/render-html/css.js
- src/render-html/html.js
It is more common when phone is hanging. Also there is always flash on older phones (2 years old).
> [Android][WebView] Fix: momentary flash of horizontal scrollbars.

- src/common/OptionButton.js
This PR fixes #1989 by changing the icons color to BRAND_COLOR which is visible perfectly in both normal and night mode.
> Fix: Improves icons visibility in night mode.

- src/render-html/css.js
Minor design change, to have a comparable image preview to slack having high spatial efficiency.
> Enhancement: Improves Image Previews

- src/account/accountSelectors.js
- src/api/settings/getServerSettings.js
- src/lightbox/LightboxActionSheet.js
- src/message/messageActionSheet.js
- src/render-native/MessageBrief.js
- src/render-native/MessageFull.js
- src/render-native/html/HtmlNodeTag.js
- src/render-native/html/renderHtmlChildren.js
- src/start/RealmScreen.js
- src/types.js
- src/utils/notifications.ios.js
Disabled Flow in `renderHtmlChildren.js` as we no longer use it (may remove in future).
> Fix Auth flow types. Remove old native html render types

- src/common/SmartUrlInput.js
- src/start/RealmScreen.js
- src/styles/theme.js
- src/utils/__tests__/url-test.js
- src/utils/url.js
* better styles
* better autocomplete from the input (detect protocol, subdomain, full domain entered)
* on pressing any part of the static text input still focus the TextInput
> More awesome realm input

- src/nav/__tests__/navSelectors-test.js
- src/nav/navSelectors.js
After discussion with Rishi and Greg we decided to try the
navigation scheme WhatsApp uses. This allows for faster returning
to the Home screen. We should see how this feels in use.
> On back navigation from narrow move to Home screen

- src/nav/ModalNavBar.js
- src/streams/StreamCard.js
- src/streams/StreamItem.js
- src/users/UserItem.js
Make sure every native text component handles the long names in
a consistent manner, namely single line and show ellipsis.
> Handle long stream names, topics and user names

- src/message/MessageListContainer.js
- src/render-html/messageTypingAsHtml.js
- src/render-html/webViewHandleUpdates.js
- src/typing/__tests__/typingSelectors-test.js
- src/typing/typingSelectors.js
Instead of using `undefined` for empty `typing` use an empty array.
> Fix typing dots shown when searching

- src/autocomplete/TopicAutocomplete.js
- src/chat/flagsReducers.js
- src/compose/ComposeBox.js
Fixing
Basically this PR is follow up PR for issues/warning introduced in #2038, #2020, https://github.com/zulip/zulip-mobile/commit/e8e4e26af6afa968fca81c73d0870fbb58a94f04#diff-09104021d043b41d451f0a1a0576ad68 & https://github.com/zulip/zulip-mobile/commit/57b9e3481b5f32a0052a970340f1fbf28ffd2bee#diff-09104021d043b41d451f0a1a0576ad68
> Fix: app crash on focussing topic input in compose box. 

- src/account/__tests__/accountReducers-test.js
- src/account/accountReducers.js
- src/caughtup/caughtUpReducers.js
- src/chat/chatReducers.js
- src/chat/fetchingReducers.js
- src/diagnostics/NotificationDiagScreen.js
- src/directSelectors.js
- src/loading/loadingReducers.js
- src/presence/presenceReducers.js
- src/session/sessionReducers.js
- src/topics/topicsReducers.js
- src/types.js
- src/unread/unreadHuddlesReducers.js
- src/unread/unreadMentionsReducers.js
- src/unread/unreadPmsReducers.js
- src/unread/unreadStreamsReducers.js
- src/utils/immutability.js
Every reducer returns the same type it receives via its
first parameter. This PR makes sure the Flow types reflect that.
> Add Flow types to reducers

- src/loading/__tests__/loadingReducer-test.js
- src/loading/loadingReducers.js
We might need to add more specific actions in future.
> Update loading state with certain actions

- src/common/LoadingIndicator.js
- src/start/LoadingScreen.js
Also, remove a no longer used horizontal line visual
> Add option for a loading indicator without the logo

- src/lightbox/LightboxHeader.js
- src/nav/MainNavBar.js
- src/nav/ModalNavBar.js
- src/nav/navSelectors.js
- src/styles/theme.js
- src/title/TitleGroup.js
- src/title/TitleSpecial.js
- src/title/TitleStream.js
All titles on Android are aligned left, on iOS by default they
are centered, but many apps do also choose to align left.
This is to help with several buttons being added on the right
like 'show topics' in a stream narrow.
> Align left all title text

- src/utils/__tests__/url-test.js
They contained incorrect realm values
> Fix 'isUrlInAppLink' tests

- src/render-html/es3.js
- src/render-html/js.js
This is a general improvement and in addition a fix to the
scroll to bottom button.
> Send only one message per click from the WebView

- src/common/UnreadCount.js
- src/nav/MainNavBar.js
Minor visual improvements
* make sure unread count does not shorten via ellipsis
* add left margin for Screen with no 'back' button
> Fix UI spacing issues

- src/chat/__tests__/chatSelectors-test.js
- src/chat/chatSelectors.js
- src/compose/ComposeBox.js
- src/message/NotSubscribed.js
Fixing
Tests on this PR will be passed once #2021 is merged.
> Fix: app crash on narrowing to unsubscribed stream.

- src/api/apiFetch.js
Remove exception rethrow for 'Unauthorized' in favor of
throwing the exact error.
> Improve API error response handling

- src/main/MainTabs.js
- src/main/StreamTabs.js
- src/types.js
> Refactor tabs code & add types.

- src/i18n/translations/messages_ar.json
- src/i18n/translations/messages_bg.json
- src/i18n/translations/messages_ca.json
- src/i18n/translations/messages_cs.json
- src/i18n/translations/messages_de.json
- src/i18n/translations/messages_en.json
- src/i18n/translations/messages_es.json
- src/i18n/translations/messages_fr.json
- src/i18n/translations/messages_hi.json
- src/i18n/translations/messages_hu.json
- src/i18n/translations/messages_id_ID.json
- src/i18n/translations/messages_it.json
- src/i18n/translations/messages_ja.json
- src/i18n/translations/messages_ko.json
- src/i18n/translations/messages_ml.json
- src/i18n/translations/messages_nl.json
- src/i18n/translations/messages_pl.json
- src/i18n/translations/messages_pt.json
- src/i18n/translations/messages_ru.json
- src/i18n/translations/messages_sr.json
- src/i18n/translations/messages_sv.json
- src/i18n/translations/messages_ta.json
- src/i18n/translations/messages_tr.json
- src/i18n/translations/messages_zh-Hans.json
- src/i18n/translations/messages_zh-Hant.json
- src/start/RealmScreen.js
Also update translations and fix 'can not' to 'cannot'
> Add a better error message when realm connection fails

- src/autocomplete/AutoCompleteViewWrapper.js
- src/autocomplete/AutocompleteView.js
- src/autocomplete/AutocompleteViewWrapper.js
- src/common/MultilineInput.js
- src/common/SmartUrlInput.js
- src/compose/ComposeBox.js
- src/styles/theme.js
- src/utils/__tests__/url-test.js
- src/utils/url.js
> Improve compose box.

- src/actionTypes.js
- src/session/sessionActions.js
- src/types.js
This is a good example for how to implement Flow types
for the rest of the Redux actions.
> flow: Add types for sessionActions

- src/message/MessageListContainer.js
- src/message/MessageListLoading.js
- src/message/messageUpdates.js
Added concise path locations to components in the same folder
> Path refactor in import statements of message components

- src/common/SmartUrlInput.js
- src/start/RealmScreen.js
Added a checkURLInputIsEmptyOrNot helper method that checks if the server URL is empty and fires an alert asking the user to enter a server URL.
Fixes #2095
> Fix crash on submitting blank server URL

- src/render-html/MessageListWeb.js
These remain from old interations and have no function
> cleanup: Remove two properties passed to WebView

- src/common/Screen.js
- src/start/PasswordAuthScreen.js
- src/start/RealmScreen.js
Follow up for #2072 Fix input fields overlap with Nav bar in landscape mode (#2071)
>  search scrren: Fix message list is not visible.

- src/start/PasswordAuthScreen.js
- src/utils/__tests__/misc-test.js
- src/utils/misc.js
* email: Created isValidEmailFormat method f327ffb
* password auth view: Diable login button if form is not filled correctly. e60dfe8
* password auth view: Auto fill email if is in re-login flow. bd9f96b
* password auth view: Focus password field if email is auto filled. 24f4680
> Improve password auth view.

- src/diagnostics/TimeItem.js
- src/types.js
- src/utils/timing.js
Added type definition for timing operations.
**#2052**
> types: Add TimingItemType for elapsed time calculations

- ios/ZulipMobile.xcodeproj/project.pbxproj
This was caused by a change in react-native-device-info:
https://github.com/rebeccahughes/react-native-device-info/issues/378
> fix: Make sure iOS project bulds correctly

- src/nullObjects.js
- src/users/__tests__/userSelectors-test.js
Added missing properties for null user and fix the corresponding test case.
> Added  missing properties for null user

- src/main/MainTabs.js
- src/styles/tabs.js
> ui: Show both tab icons and labels on iPad

- src/main/MainTabs.js
- src/main/StreamTabs.js
- src/styles/tabs.js
Removed the two parameters, no need to pass them through the
function that didn't do anything with them
> refactor: Simplify tab options creator parameters

- src/account/accountActions.js
- src/account/accountReducers.js
- src/actionTypes.js
Splitting reducer helps with typing and is a nice improvement
for maintainability that will be implemented elsewhere too.
> flow: Add types to accountReducers and split reducer

- src/actionConstants.js
- src/compose/ComposeBoxContainer.js
- src/session/sessionActions.js
- src/session/sessionReducers.js
- src/types.js
This is a no longer used action. No functional changes intended
> refactor: Remove toggleComposeTools action

- src/actionConstants.js
- src/session/sessionReducers.js
- src/types.js
It is no longer used. No functional change intended
> cleanup: Remove lastActivity from session state

- package.json
- src/types.js
- yarn.lock
These are related to the legacy HTML parsing no longer used
> cleanup: Remove a type and dependency

- src/common/Icons.js
- src/common/OptionButton.js
- src/common/OptionRow.js
- src/settings/SettingsCard.js
- src/styles/theme.js
Added Feather icons to all the options in the Settings screen.
Closes #2068
> settingsScreen: Add icons to the menu options

- src/types.js
status is having three stages active, idle, offline. So I changed inactive to idle.
> types: changed inactive to idle in userStatus

- .eslintrc
- src/autocomplete/TopicAutocomplete.js
- src/boot/AppEventHandlers.js
- src/common/SectionSeparatorBetween.js
- src/compose/ComposeBox.js
- src/emoji/RealmEmoji.js
- src/main/HomeTab.js
- src/message/NotSubscribed.js
- src/settings/SettingsCard.js
- src/title-buttons/InfoNavButtonGroup.js
- src/title/TitleGroup.js
- src/topics/TopicList.js
- src/topics/TopicListScreen.js
- src/users/UserList.js
* enable eslint rule 'react/no-unused-prop-types'
* remove any unused props reported by it
* no functionality changes
> cleanup: Remove all unused props

- .eslintrc
- src/common/ZulipButton.js
- src/nav/AppWithNavigationState.js
- src/nav/IconUnreadConversations.js
- src/title/TitlePlain.js
Add stricter checks for missing types. Add them.
> flow: Enable eslint "react/prop-types" rule and add types

- src/group/GroupCard.js
- src/group/GroupScreen.js
- src/nullObjects.js
- src/types.js
I implemented a Search functionality to search for users when creating a new group.
> #1929 Implemented a search functionality for adding a new group

- src/render-html/generatedEs3.js
- src/render-html/js.js
Adds a check for element existence. Prevents potential exceptions.
Prparation for Flow types which catches this error.
> webview: Simplify toggling element visibility inside

- src/render-html/MessageListWeb.js
* ensures that relative URLs are resolved correctly
* allows loading of any resource needing authorization
> webview: Pass baseUrl and authorization headers

- src/render-html/generatedEs3.js
- src/render-html/js.js
Minor, functionality-preserving changes are made to make the
typing stricter.
> flow: Add types to function calls in js.js

- src/actionTypes.js
- src/alertWords/alertWordsReducer.js
Also, fixed an incorrect state initialization, caught by Flow
> flow: Add types for alertWords reducer

- src/chat/chatReducers.js
No functional changes, just moved two expressions out of the 'if'
and gave them names, making it more clear the intent of each.
> refactor: Make login in eventNewMessage more clear

- src/conversations/ConversationsCard.js
The current button to create a group chat is nicely hidden.
This exposes the button where peope expect it - in the people tab.
Also add icons for that button and the search button.
> ui: Add "create group" button

- src/users/__tests__/userSelectors-test.js
This change removes unnecessary values from tests and keeps only the values required for the test to pass.
> tests: Refactor tests for userSelectors.

- src/common/OptionDivider.js
- src/message/messageActionSheet.js
- src/message/messageSelectors.js
- src/users/__tests__/userSelectors-test.js
- src/users/userSelectors.js
- src/utils/__tests__/immutability-test.js
- src/utils/message.js
No functional changes, just a `yarn run prettier` run.
Ideally we do want every contributor running 'prettier' automatically.
If they do running this command will produce no diff.
> maintenance: Format all code with 'prettier'

- src/common/UserStatusIndicator.js
- src/users/userHelpers.js
This is a first step towards using the proper and more sophisticated
user status logic
> rework: Add statusFromPresence in UserStatus

- src/title/TitlePrivate.js
- src/title/TitlePrivateContainer.js
Pass presence corectly to the TitlePrivate component so Avatar
can calculate the status out of it.
> fix: Display user status in PM screen title

- src/account-info/AccountDetails.js
- src/account-info/AccountDetailsScreen.js
- src/common/Avatar.js
Do not show the status dot in the Avatar
> fix: Pass presence correctly to AccountDetails

- src/actionTypes.js
- src/group/AvatarItem.js
- src/nav/navActions.js
- src/nullObjects.js
- src/types.js
- src/users/UserList.js
- src/users/__tests__/userHelpers-test.js
- src/users/userHelpers.js
- src/users/usersActions.js
* use User and ApiUser in correct places
* make some types stricter
> flow: Use concrete User type instead of 'any'

- src/common/Avatar.js
- src/nav/navActions.js
- src/types.js
> lint: Fix ESLint issues introduced in last commit

- src/actionTypes.js
- src/api/getTopics.js
- src/topics/TopicList.js
- src/topics/TopicListScreen.js
- src/topics/topicActions.js
- src/topics/topicSelectors.js
- src/types.js
Rename TopicDetails to Topic for consistency
> flow: Add types for Topics

- src/account-info/AccountDetails.js
- src/api/emoji_reactions/emojiReactionAdd.js
- src/api/emoji_reactions/emojiReactionRemove.js
- src/api/focusPing.js
- src/conversations/ConversationList.js
- src/conversations/ConversationsCard.js
- src/group/GroupCard.js
- src/title/ActivityText.js
- src/types.js
- src/unread/UnreadCards.js
- src/unread/unreadSelectors.js
- src/users/UserList.js
- src/users/UsersCard.js
Remove duplicates ClientState and Presences
> flow: Add types for PresenceState

- src/styles/index.js
- src/styles/theme.js
- src/title/TitleGroup.js
- src/title/TitleHome.js
- src/title/TitlePlain.js
- src/title/TitlePrivate.js
- src/title/TitleSpecial.js
- src/title/TitleStream.js
* reuse all styles between the different Title* components
* increased height from 52px to 58px to be consistent with all other apps
* increased font size, again for consistency with other apps
> Navbar consistency

- src/unread/unreadSelectors.js
- src/utils/misc.js
Adding types for the remaining `any`s is surprisingly tricky.
> flow: Add types for utils/misc

- src/utils/timing.js
Added type for countMap , timingMap , now function
> FIX type Annotation for timing.js

- src/unread/__tests__/unreadSelectors-test.js
- src/unread/unreadSelectors.js
This better matches users expectations, matches the topic list
sorting and also the web UI behavior.
> Sort unread tab by last activity in topics

- src/start/AuthButton.js
- src/start/PasswordAuthScreen.js
- src/start/RealmScreen.js
- src/styles/theme.js
- src/styles/utilityStyles.js
* smallMarginTop becomes halfMarginTop
* added TopBottom and LeftRight sets
> ui: Replace old padding styles with new ones

- src/webview/webViewEventHandlers.js
* Add the missing type prop to all types
* Add a common MessageListEvent type
* Fix a missing `type` prop in handleUrl func
> flow: Add MessageListEvent type

- src/webview/__tests__/webViewHandleUpdates-test.js
* tests for fetching diffs producing a message
* tests for typing diffs producing a message
* tests for content diffs producing a message
* tests for mixed diffs producing messages
> tests: Add tests for webViewHandleUpdates

- src/actionTypes.js
- src/api/apiTypes.js
- src/nav/navActions.js
- src/start/RealmScreen.js
- src/types.js
* replace the current ServerSettings type with api-specific one
* add all the values returned to the already existing ones
> flow: Add types for server_settings api call

- src/types.js
* proper types for all data fields (they are mostly string)
* split into concrete private/group/stream types
> flow: Correct and enhance Flow types for Notifications

- src/utils/__tests__/notificationsCommon-test.js
* covers unknown notifications, stream and PMs
> Add tests for getNarrowFromNotificationData

- src/topics/TopicList.js
- src/topics/TopicListScreen.js
- src/types.js
* use the new data passed to the topic screen.
* add a new type ExtendedTopic for extended topic data
> ui: Display unread count and muted topics in Topic Screen

- src/api/emoji_reactions/emojiReactionAdd.js
- src/api/emoji_reactions/emojiReactionRemove.js
- src/api/mark_as_read/markAllAsRead.js
- src/api/mark_as_read/markStreamAsRead.js
- src/api/mark_as_read/markTopicAsRead.js
- src/api/messages/deleteMessage.js
- src/api/messages/messagesFlags.js
- src/api/messages/sendMessage.js
- src/api/messages/updateMessage.js
- src/api/settings/toggleMobilePushSettings.js
- src/api/streams/createStream.js
- src/api/streams/deleteStream.js
- src/api/streams/updateStream.js
- src/api/subscriptions/muteStream.js
- src/api/subscriptions/muteTopic.js
- src/api/subscriptions/subscriptionAdd.js
- src/api/subscriptions/subscriptionRemove.js
- src/api/subscriptions/toggleMuteStream.js
- src/api/subscriptions/togglePinStream.js
- src/api/subscriptions/toggleStreamNotifications.js
- src/api/subscriptions/unmuteTopic.js
- src/api/typing.js
- src/api/user_groups/createUserGroup.js
- src/api/user_groups/deleteUserGroup.js
- src/api/user_groups/editUserGroup.js
- src/api/user_groups/editUserGroupMembers.js
Previously missing any types and where there are types were
incorrectly specified.
> flow: Add types for post/patch API calls

- src/streams/StreamList.js
- src/streams/SubscriptionsCard.js
- src/title/TitleStream.js
- src/types.js
Move several properties from Stream to Subscription, as they should
have been thre already. The incorrect typing did miss an error we made.
> flow: Fix Stream type, fix Subscription type

- src/common/Screen.js
So that it doesn't repaints when nav isTransitioning or going back.
> screen: Connect to store with connectWithActionsPreserveOnBack.

- src/compose/ComposeBox.js
- src/compose/ComposeMenu.js
- src/styles/composeBoxStyles.js
* more consisntency in padding of compose input between platforms
* larger touch areas for all buttons
* move all related styles to composeBoxStyles
* buttons on left and right are precisely vertically aligned
> ui: Improve compose box buttons and spacing

- src/actionTypes.js
- src/realm/realmActions.js
- src/types.js
* this is to differentiate from upcomming 'realm' specific subset
* added two fields that are recently added to the initial response
> flow: Rename InitialRealmData to InitialData

- src/account-info/AccountDetails.js
- src/common/UserStatusIndicator.js
- src/styles/theme.js
This is just a follow up to the simplification of AccountDetails,
and reuse the better styles we have now.
> ui: Refactor/simplify AccountDetails styling

- src/nav/MainNavBar.js
- src/nav/ModalNavBar.js
- src/nav/NavButton.js
- src/styles/navStyles.js
- src/styles/theme.js
- src/title/ActivityText.js
- src/title/TitleGroup.js
- src/title/TitlePrivate.js
- src/title/TitleStream.js
Extract navbar styles from components and main theme file to a
dedicated file to improve maintainability and remove duplication.
No visual changes intended.
> Extract navbar-related styles to separate file

- src/api/apiFetch.js
* Add api HEAD call
* Split `fetchWithAuth` from `apiFetch` and reuse
> Enhance core API calls

- .eslintrc.yaml
- package.json
- src/account-info/AccountDetails.js
- src/account-info/AccountDetailsScreen.js
- src/utils/date.js
- yarn.lock
* refactor: Pass User directly to AccountDetails
* Add 'active since' information to AccountDetails
* Add 'local time' information in AccountDetails
> More account details

- src/webview/css/css.js
* more consistent styles between brief and full messages
* more exact spacing between different messages (1st vs rest)
* more precise avatar spacing
> webview: Rework message list css for more precise layout

- src/chat/GroupDetailsScreen.js
- src/styles/miscStyles.js
Removed a view and the corresponding style (it was not being used anywhere else)
Before:
After:
> Removed redundant view from GroupDetailsScreen

- src/autocomplete/EmojiAutocomplete.js
- src/message/MessageListContainer.js
- src/reactions/__tests__/aggregateReactions-test.js
- src/reactions/aggregateReactions.js
- src/types.js
- src/webview/html/messageAsHtml.js
- src/webview/html/messageReactionAsHtml.js
- src/webview/html/messageReactionListAsHtml.js
I'm fairly confident about the first commit, but not about the second commit. There should probably be a more streamlined approach to annotating Reactions, I just couldn't find one.
> Add proper type annotations for RealmEmojiType and ReactionType.

- docs/debugging.md
- docs/developer-guide.md
@gnprice it'd be cool if you could add your adb shell debugging workflowto this section once this is merged.
> developer guide: Add debugging section.

- src/account-info/LogoutButton.js
- src/account-info/SwitchAccountButton.js
- src/account/AccountPickScreen.js
- src/boot/AppDataFetcher.js
- src/compose/ComposeMenu.js
- src/message/fetchActions.js
- src/typing/clearTypingNotification.js
- src/utils/notifications.android.js
- src/utils/notifications.ios.js
This makes existing import statements shorter
and establishes an easier pattern for new imports.
> Import all actions from actions.js

- src/nav/ModalNavBar.js
- src/styles/composeBoxStyles.js
- src/styles/index.js
- src/styles/miscStyles.js
- src/styles/navStyles.js
- src/styles/utilityStyles.js
Did a sweep through all components and removed `SPACING` and `HALF_SPACING` from `styles/index.js` in the last commit.
Closes #2641
> Replace SPACING and HALF_SPACING with 16 and 8

- src/common/PasswordInput.js
- src/common/SmartUrlInput.js
- src/start/DevAuthScreen.js
- src/styles/miscStyles.js
Removed styles that were not being used anywhere and moved styles that was only being used in one component and didn't seem like it could be reused for some other component later on was moved to that particular component's file.
> Cleaned up miscStyles

- src/conversations/ConversationsCard.js
All action should be imported from actions.js
This is a followup for c02f277.
> conversations card: Import actions from actions.js

- src/message/MessageList.js
- src/settings/DebugScreen.js
- src/webview/webViewEventHandlers.js
This type already exists, but was not used in the props.
> flow: Add Debug type to 'debug' props

- docs/howto/build-run.md
> docs: Add troubleshooting tip for java.lang.UnsupportedClassVersionError.

- src/actionTypes.js
- src/events/eventToAction.js
- src/unread/unreadHelpers.js
This is a continuation of the previous PR, turning `any` definitions into the specific types actually used.
> Add flow types for server event actions

- .vscode/settings.json
- docs/howto/editor.md
Install extension from
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
> vscode: Add prettier configurations in the setting.

- src/webview/css/css.js
See #2671.
Before:
Updated:
@gnprice
> Fix layout of <ul> in messages

- src/settings/LanguagePickerItem.js
> language-settings: Fix layout.

- src/actionTypes.js
For reference, see https://reactnavigation.org/docs/en/navigation-actions.html#navigate.
> flow: Annotate NavigateAction with NavigationNavigateAction. 

- src/topics/TopicList.js
This screen uses a FlatList and SectionSeparatorComponent is not a valid property of FlatList and hence does nothing.
> TopicList: Removed SectionSeparator

- docs/howto/dev-server.md
- docs/howto/ios-tips.md
Notes from collaboration with @gnprice today.
> Document developing on an iOS device and dev server.

- src/actionTypes.js
- src/conversations/ConversationList.js
- src/conversations/ConversationsCard.js
- src/conversations/conversationsSelectors.js
- src/types.js
- src/unread/UnreadCards.js
(https://github.com/zulip/zulip-mobile/issues/2722#issuecomment-400121439)
> flow: Add type annotation on the conversation list item.

- src/__tests__/baseSelectors-test.js
- src/account-info/AccountDetailsScreen.js
- src/baseSelectors.js
- src/streams/EditStreamScreen.js
- src/streams/InviteUsersScreen.js
- src/streams/StreamScreen.js
- src/subscriptions/subscriptionSelectors.js
- src/topics/TopicListScreen.js
- src/topics/__tests__/topicsSelectors-test.js
- src/topics/topicSelectors.js
- src/users/__tests__/userSelectors-test.js
- src/users/userSelectors.js
Need to do some testing. But ya ready for initial review.
(This PR is basically combination of old dated PR #2455, #2456 and #2452 )
Fix for #2746.
> Pass data using navigation props instead of getting from global state/selectors.

- src/compose/ComposeBox.android.js
- src/compose/ComposeBox.ios.js
- src/i18n/translations/messages_en.json
- src/message/AnnouncementOnly.js
- src/message/NotSubscribed.js
- src/nullObjects.js
- src/styles/composeBoxStyles.js
- src/subscriptions/subscriptionSelectors.js
- src/types.js
> Handle announcement only streams.

- docs/push-notifications.md
This is a copy of #2742. Relevant discussion thread [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/testing.20notifications).
> [WIP] docs: Draft instructions for testing push notifications.

- src/unread/UnreadCards.js
> UnreadCards: Give visual feedback on pressing a topic

- src/webview/webViewEventHandlers.js
This type corresponds to: https://github.com/zulip/zulip-mobile/blob/2024f14880ee60c0f06b7a564aeb3d1c5eb75dee/src/webview/js/js.js#L349.
> flow: Annotate MessageListEventLongPress.target.

- src/common/InputWithClearButton.js
> InputWithClearButton: Refactor clear button

- src/common/Icons.js
- src/nav/AppNavigator.js
- src/nav/navActions.js
- src/settings/LegalScreen.js
- src/settings/SettingsCard.js
Settings Screen, Before:
Settings Screen, After:
Legal Screen:
> settings: Create 'Legal' screen.

- src/outbox/outboxActions.js
Fixes #2903
When sending a message we try to parse the markdown so we can show an HTML preview.
This is done via this project:
https://github.com/zulip/zulip-markdown-parser
Sometimes parsing fails, throwing an exception.
In that case we do not send the message which makes no sense.
Instead, we wrap the parsing inside a try-catch block. If the
parsing fails use the raw message as preview and still send the message.
> Fix message sending sometimes failing

- src/common/FloatingActionButton.js
- src/common/MultilineInput.js
- src/common/Screen.js
- src/common/TranslatedText.js
- src/common/WebLink.js
- src/common/ZulipButton.js
- src/common/ZulipSwitch.js
- src/compose/ComposeBox.android.js
- src/compose/ComposeBox.ios.js
- src/message/fetchActions.js
- src/streams/SubscriptionsCard.js
These typos were found by an experimental upgrade to
eslint-plugin-spellcheck v0.0.9
> Fix various typos.

- package.json
- yarn.lock
(Reminder to run `yarn reinstall` after updating package.json)
@gnprice
> Update react-native-photo-view dependency to resolve #2654.

- .travis.yml
- tools/verify-webview-js
This script will help in maintaining consistency between js.js and
generatedEs3.js file.
Fixes: #3035
> travis: Add verify generatedEs3 js script.

- src/webview/MessageListWeb.js
- src/webview/js/generatedEs3.js
- src/webview/js/js.js
- src/webview/webViewHandleUpdates.js
Implement a two way hand shake. Send a ping from app to webView till a
ping is received from webView.
Refer #3080 for more details.
Fixes: #3080
> webView: Improve hand shake mechanism with app.

- .eslintrc.yaml
- src/message/MessageList.js
- src/webview/__tests__/webViewHandleUpdates-test.js
- src/webview/css/css.js
- src/webview/html/__tests__/processAlertWords-test.js
- src/webview/html/messageAsHtml.js
- src/webview/html/processAlertWords.js
- src/webview/html/renderMessagesAsHtml.js
> Fix #3082. Highlight alert words in message content.

- src/title/ActivityText.js
- src/title/TitlePrivate.js
Subscribe to exactly to which the component cares.
This is first step, doing more in further commmits.
> title-private, activity text: Subscribe to more deeper object in presence.

- src/account/AccountList.js
- src/account/AccountPickScreen.js
- src/common/ComponentList.js
- src/common/Screen.js
- src/common/ZulipButton.js
- src/streams/StreamIcon.js
- src/streams/StreamItem.js
- src/users/UserItem.js
Fixes issues that were found by experimentally enabling `@flow strict` on all files.
Unfortunately, we can not do that as any imported file needs to also be strictly typed.
While the non-strict Flow does not recognize these as issues it is good to do these fixes.
> Stricter Flow

- docs/howto/windows.md
Issue in focus: #3178. 
Updated the WSL draft guide with step by step instructions and re-organized the document flow for better readability.  Also removed some suggestions that could lead users down some frustrating dead ends.
> Update WSL Setup documentation

- src/chat/Chat.js
- src/chat/ChatScreen.js
- src/styles/miscStyles.js
read more at https://github.com/zulip/zulip-mobile/issues/3089#issuecomment-448695350
Fixes #3089
> android, chatScreen: Fix navBar rendering is delayed. Fixes #3089

- src/api/__tests__/apiFetch-test.js
- src/api/apiFetch.js
- src/api/registerForEvents.js
- src/config.js
- src/message/fetchActions.js
Rework `registerForEvents` call completely.
Start registering for all server events.
> Register for all events

- src/account/AccountPickScreen.js
- src/common/Screen.js
- src/nav/ModalNavBar.js
- src/nav/ModalSearchNavBar.js
- src/nav/__tests__/navReducers-test.js
- src/nav/navSelectors.js
- src/start/WelcomeScreen.js
- src/utils/redux.js
Removed from `MainNavBar`, `ModalSearchNavBar`, where it will always be true.
Currently WIP, need to handle cases where it will be false in `ModalNavBar`. (Also a rebase)
Edit: Completed.
> Remove usage of connectPreserveOnBackOption.

- src/api/apiTypes.js
- src/api/deleteEventQueue.js
- src/api/index.js
- src/api/messages/getMessageHistory.js
- src/api/realm/createRealmFilter.js
- src/api/streams/getStreamId.js
- src/api/users/createUser.js
- src/api/users/getUserProfile.js
These were extracted from #2819 for easier merging.
> Add new API functions

- src/api/messages/sendMessage.js
- src/api/messages/updateMessage.js
- src/api/pollForEvents.js
- src/api/settings/getServerSettings.js
- src/api/streams/createStream.js
- src/api/streams/getStreams.js
- src/api/subscriptions/getSubscriptions.js
- src/api/subscriptions/muteTopic.js
- src/api/subscriptions/subscriptionAdd.js
- src/api/subscriptions/subscriptionRemove.js
- src/api/typing.js
- src/api/users/getUsers.js
Adds links to all API calls that have a corresponding online documentation page.
> api: Add JSDoc links to API calls

- src/unread/unreadSelectors.js
Issues in focus: #2971, #3166 
I finished adding all the Flowtypes for the selectors in this file as mentioned in #3351 
Tests ran:
> Added more Flowtypes to unreadSelectors

- src/chat/narrowsSelectors.js
- src/nav/__tests__/navSelectors-test.js
- src/nav/navSelectors.js
- src/types.js
- src/users/userSelectors.js
Issues in focus: #2971, #3166 
As suggested in #3357, I added Flowtypes to all of the selector files that lack them(navSelectors, userSelectors, narrowsSelectors). 
Tests ran:
> Completed adding all Flowtypes to more Selector files

- src/account/accountsSelectors.js
> Fixes: #3334 Fix splash of header & footer in light-box screen pushing route and getting new event from server.

- src/compose/ComposeBox.js
> composeBox, UI: Paint the safe area with BG color of composeBox.

- src/api/settings/getServerSettings.js
- src/common/Icons.js
- src/start/AuthScreen.js
- src/start/__tests__/authentications-test.js
- src/start/authentications.js
Authentication with Microsoft AzureAD SSO (see zulip/zulip#10618)
Fixes: #3225
> Add Azure AD authentication

- src/events/eventActions.js
- src/message/fetchActions.js
- src/utils/__tests__/async-test.js
- src/utils/async.js
If a 4xx error is encountered when registering for an event, log out.
Fixes #3253
Details in each commit.
> Logout if API key is invalid

- src/session/sessionReducers.js
- src/settings/DebugScreen.js
- src/types.js
- src/webview/MessageList.js
- src/webview/__tests__/webViewHandleUpdates-test.js
- src/webview/css/css.js
- src/webview/html/html.js
- src/webview/html/htmlBody.js
- src/webview/js/generatedEs3.js
- src/webview/js/js.js
- src/webview/webViewHandleUpdates.js
- tools/generate-webview-js
Adds a visual indicator of which messages are read, which are unread, and animates that visual when a message becomes read.
> Display indicator for unread messages to the user

- src/message/fetchActions.js
> Retry on failed fetch messages

- src/webview/css/css.js
Mentions while writing this PR get cut off if they appear in the
beginning of a message. This commit adds a very slight margin to
mentions to prevent this from happening.
> Mentions: spacing breaks when it appears at the beginning of line.

- docs/architecture/realtime.md
Details are mentioned in the commit messages :).
(this doc is written excellently otherwise, just these few points were a little hard to understand; corrected it so that things are easier to understand for those who read this doc after me)
> Improve the Realtime docs very slightly.

- src/realm/__tests__/realmReducer-test.js
- src/realm/realmReducer.js
- src/reduxTypes.js
- src/users/userSelectors.js
* realm state: Persist user_id int REALM_INIT.
* accountSelector: Export user_id from realm.
>  accountSelector: Export user_id from realm.

- docs/howto/build-run.md
Add a paragraph concerning a misleading error message observed during
initial setup.
> docs: add troubleshooting section to setup

- src/message/fetchActions.js
- src/users/usersActions.js
> Fix immediate presence was not updated on app open 

- src/api/__tests__/apiErrors-test.js
- src/api/apiErrors.js
- src/api/apiFetch.js
- src/api/transportTypes.js
- src/events/eventActions.js
- src/utils/async.js
Update of PR #3484. Addresses most (hopefully all) review feedback therein.
Fixes #2902. Supersedes PRs #2781 and #3484.
> Make API errors better (v2)

- src/common/CountOverlay.js
- src/common/index.js
- src/main/HomeTab.js
- src/nav/IconUnreadConversations.js
- src/nav/IconUnreadMentions.js
- src/nav/NavButton.js
- src/nav/NavButtonGeneral.js
Currently there is no way to get unread mentions count, So show it on
the icon itself as unread PM count is show over conversation icon.
> home tab: Show unread mentions count on mentions icon.

- android/app/src/main/java/com/zulipmobile/notifications/FcmMessage.kt
- docs/howto/push-notifications.md
- src/account/accountsSelectors.js
- src/notification/index.js
- src/notification/notificationActions.js
This fixes most of #2295. Details in commit messages.
> Switch to the right org when opening a notification

- .flowconfig
- docs/howto/release.md
- docs/howto/yarn-link.md
- jest.config.js
- metro.config.js
- package.json
- src/users/usersActions.js
- yarn.lock
This is the mobile-side companion to zulip/zulip#13253 .
> Try sharing some code from the webapp

- src/boot/AppEventHandlers.js
- src/common/OfflineNotice.js
Fixes #3602. Confirmed on a physical Pie device.
It wasn't obvious to me what was going wrong with the banner's animation, so I've left it on the cutting room floor for now to avoid delaying the more important half of this PR.
> Update NetInfo API use

- docs/howto/windows.md
... with lessons learned from recent experimentation.
(Note that WSL is still not confidently supported, as we have no
automatic tests for this configuration.)
> docs: update WSL instructions

- docs/howto/push-notifications.md
> docs: add a link to the server docs

- src/webview/MessageList.js
Make it clear who's doing the resolution, and with respect to what.
> webview [nfc]: demystify the relative base URL

- package.json
- tools/test
- yarn.lock
Also add a linter (in the form of another tools/test "suite")
to keep it that way.
Inspired by zulip/zulip@e57ede942 (zulip/zulip#13118). (thanks @andersk !)
> Deduplicate indirect deps with yarn-deduplicate.

- src/webview/html/html.js
> webview: work around WebKit bug involving CSS transitions

- src/webview/js/generatedEs3.js
- src/webview/js/rewriteImageUrls.js
This is the promised series of URL-related refactors discussed at https://github.com/zulip/zulip-mobile/pull/3636#issuecomment-548080745 (and upthread of there).
> rewriteImageUrls: followup refactors, using `URL` more

- src/message/__tests__/messageActionSheet-test.js
- src/message/messageActionSheet.js
- src/nav/navActions.js
- src/reactions/MessageReactionList.js
- src/reactions/ReactionUserList.js
- src/webview/js/generatedEs3.js
- src/webview/js/js.js
- src/webview/webViewEventHandlers.js
- static/translations/messages_en.json
Issue #2252.
Discussion: https://chat.zulip.org/#narrow/stream/48-mobile/topic/reaction.20recipients
> Issue #2252. feature request: See who reacted with an emoji.

- tools/build-webview
Some cleanup done to the `tools/build-webview` script, partly in preparation for more interesting functional changes.
This includes a new option (for testing) and a minor bugfix.
> build-webview: script cleanup

- src/message/messageSelectors.js
- src/notification/index.js
- src/redux-persist-migrate/index.js
- src/utils/logging.js
- src/webview/MessageList.js
... and utilize it to (hopefully) collapse many of our existing errors into single issues.
> Add side-channel for Sentry logging

- src/account-info/AccountDetails.js
- src/common/OwnAvatar.js
Fix up a couple of minor inefficiencies discovered while poking at an unrelated bug.
> Minor tweaks

- .travis.yml
Fixed the test script to reenable Pirlo.
Sample result for the new flow can be seen at
https://app.pirlo.io/result/4f487c39-f6fe-48a2-8ccb-ab0ca3465171/details#steps
> Reenable Pirlo end to end testing #3766

- src/__tests__/exampleData.js
(Yes, this actually happened.)
> Test data: Eliminate possibility of collisions in randomly-generated user IDs

- flow-typed/@sentry/react-native_v1.x.x.js
- src/actionTypes.js
- src/api/apiErrors.js
- src/api/apiFetch.js
- src/boot/reducers.js
- src/boot/store.js
- src/diagnostics/InfoItem.js
- src/diagnostics/VariablesScreen.js
- src/message/messageSelectors.js
- src/outbox/outboxActions.js
- src/styles/tabs.js
- src/user-picker/AvatarList.js
- src/user-picker/UserPickerCard.js
- src/utils/jsonable.js
- src/utils/logging.js
- src/utils/objectEntries.js
- src/utils/url.js
- src/webview/js/js.js
Fix most, although sadly not all, errors reported by Flow 0.98.0.
A few such errors (mostly unused-suppression-comment warnings) remain, to be done in tandem with the upgrade itself.
In support of #3548.
> Flow 0.98.0

- docs/howto/build-run.md
- docs/howto/windows-wsl.md
Some minor tweaks to, and updating of, our experimental documentation for WSL.
> Windows WSL doc tweaks

- src/account-info/AccountDetails.js
- src/chat/Chat.js
- src/chat/UnreadNotice.js
- src/compose/ComposeBox.js
- src/emoji/Emoji.js
- src/message/NoMessages.js
- src/nav/ChatNavBar.js
- src/reactions/MessageReactionList.js
- src/start/RealmScreen.js
- src/title-buttons/ExtraNavButtonStream.js
- src/title-buttons/ExtraNavButtonTopic.js
- src/title-buttons/InfoNavButtonGroup.js
- src/title-buttons/InfoNavButtonStream.js
- src/title/TitleStream.js
- src/webview/MessageList.js
This fixes #3768, using the pretty clean workaround we eventually got to.
> connect [nfc]: Work around Flow bug by making types more explicit.

- .gitignore
- ios/ZulipMobile.xcworkspace/contents.xcworkspacedata
Clean up a little, to make the life of anyone testing experimental branches a little easier.
> Cocoapods preparation

- src/account-info/AccountDetails.js
- src/account-info/AccountDetailsScreen.js
- src/api/modelTypes.js
- src/autocomplete/TopicAutocomplete.js
- src/message/NotSubscribed.js
- src/streams/EditStreamScreen.js
- src/streams/InviteUsersScreen.js
- src/streams/StreamList.js
- src/streams/SubscriptionsCard.js
- src/title/ActivityText.js
- src/title/Title.js
- src/title/TitleGroup.js
- src/title/TitlePrivate.js
- src/topics/TopicListScreen.js
- src/utils/avatar.js
These are various type fixes mostly addressing the use of connectFlowFixMe, so that connect is used instead. They were discovered while working on https://github.com/zulip/zulip-mobile/pull/3765 but were unrelated enough to motivate a separate PR.
> Connect type fix

- src/message/messageActionSheet.js
- src/pm-conversations/filteredRecipientsForPM.js
- src/webview/html/messageHeaderAsHtml.js
Fixes https://github.com/zulip/zulip-mobile/issues/3874
Before: 
Now:
> messageActionSheet: Fix action sheet title for private messages.

- docs/howto/push-notifications.md
It will still be really valuable to explore the solutions proposed
near the end of this file.
> docs/howto/push-notifications: Add sandbox APNs workaround.

- src/actionConstants.js
- src/actionTypes.js
- src/boot/AppEventHandlers.js
- src/directSelectors.js
- src/events/eventMiddleware.js
- src/session/__tests__/sessionReducer-test.js
- src/session/sessionActions.js
- src/session/sessionReducer.js
Remove `isActive` from our Redux state.
~~(Blocked on #3727.)~~
> Remove `isActive`

- src/settings/__tests__/settingsReducer-test.js
- src/settings/settingsReducer.js
Discovered in https://github.com/zulip/zulip-mobile/issues/2138#issuecomment-589806328.
> Update stream notification setting when switching accounts

- src/chat/ChatScreen.js
Now without this styles too #3089 is not reproducible.
> chatScreen [nfc]: Get rid of reverse styles.

- src/common/Icons.js
- src/compose/ComposeMenu.js
'IconPlus' is reffering to "plus-circle" icon. But a plane plus
icon is available. So rename current 'IconPlus' to 'IconPlusCircle',
Add plus icon and name it "IconPlus".
> Icon: Fix IconPlus pointing to "plus-circle".

- README.md
I believe this change makes the project more welcoming to newcomers.
> readme: Make it more clear that contributions are welcome.

- src/search/SearchMessagesScreen.js
I was looking back at this code last week while studying #3868, which will make some other changes to it.  The logic was a bit complex to understand, but I didn't want to disturb the error-handling it's doing.  Then as I looked closer, though, I found that the error-handling behavior wasn't quite right!  Hence this series, which fixes that and also simplifies the code somewhat along the way.
This is ready for normal review, but I'd like to hold off actually merging in order to minimize conflicts for #3868.  Following review, I'll look at that one and merge only commits I think will make that PR easier on net to complete.  I can rebase the rest after that's landed.  (There's also one non-mergeable commit at the tip of this branch, just adding a small comment referring to how to rebase onto …
> search: Fix some error handling, and simplify a bit.

- src/search/SearchMessagesScreen.js
Fixes #3856.
The app no longer crashes on viewing the reactions from search results now.
> SearchMessagesScreen: Store fetched messages in Redux store.

- src/webview/js/__tests__/rewriteHtml.js
- src/webview/js/generatedEs3.js
- src/webview/js/js.js
- src/webview/js/rewriteHtml.js
- src/webview/static/base.css
- src/webview/webViewEventHandlers.js
- static/translations/messages_en.json
Add support for rendering 'time' mentions in message text. The
mentioned time is formatted to be human-readable, and tapping on it
shows an alert dialog with the original text.
**Screenshots**
Fixes: #4162
> webview: Add support for 'time' elements. 

- src/reactions/MessageReactionList.js
Gracefully render a blank screen and navigate back.
Fixes: #3803.
> MessageReactionList: Handle undefined message resulting from purge in REALM_INIT

- src/main/MainScreenWithTabs.js
- src/nav/navReducer.js
- src/users/userSelectors.js
> Fix logout crash, by rendering nothing in main screen if no data.

- ios/ZulipMobile.xcodeproj/project.pbxproj
- tools/ios
Fixes: #4100
See also [discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M4100.20Better.20choose.20when.20to.20build.20and.20upload.20Sentry.20info/near/1033355).
> Better choose when to build and upload Sentry info

- src/api/apiTypes.js
- src/message/fetchActions.js
- src/nav/navActions.js
- src/start/AuthScreen.js
- src/start/RealmScreen.js
Unfortunately, we'll need to do more—but this is a fairly straightforward bit of progress I think we've landed on.
From [discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M3745.20Server.20version.20to.20Sentry/near/930324).
> apiTypes [nfc]: Cut some require cycles.

- src/boot/replaceRevive.js
- src/common/UserAvatar.js
Following discussion yesterday [here](https://github.com/zulip/zulip-mobile/pull/4367#discussion_r550311033).
> Use function declarations at toplevel.

- src/third/redux-persist/persistStore.js
08b77bb79f went a long way in reducing unnecessary work being done,
but unfortunately I wasn't careful enough about what happens with
migrations, and it introduced a source of hard-to-diagnose bugs that
might show up when migrations are added.
In particular, it's appropriate and necessary to turn around and
save the result of `REHYDRATE` back to the disk in cases where there
has been a migration. See discussion [1].
Rather than just revert 08b77bb79f, though, introduce a condition
that lets us get the benefit of the optimization in the far more
common case (a startup without a migration, vs. a startup with one).
The way we do that does break the separation between our
redux-persist and redux-persist-migrate, by making it so
redux-persist knows about the specifics of redux-persist-migrate. …
> redux-persist: Fix a recent regression in handling migrations.

- src/account-info/AccountDetails.js
- src/common/PresenceStatusIndicator.js
- src/common/UserAvatarWithPresence.js
I have made 2 changes majorly
1. Gives a white background larger than the status indicator due to which no matter what will be the Avatar Image of the user the status indicator looks clear .
for example If the user's Avatar Image is greenish then the present indicator not looks that well 
Also above point can be easily understand by Greg's Issue #4306 
2. We need to check whether the status is offline or Its a Zulip's Bot and if it is then there is no need to add any white background as no status indicator is there but If we doesn't check then we get a white background over there 
So after the above 2 changes Avatars of user's in User's List looks like this
Fixes : #4306
> Avatar-UI : giving a white background and cornering the status Indicator

- docs/howto/ios-tips.md
- docs/howto/profiling.md
Here's a rough writeup of what I've learned from experimenting with the tool called `react-native-performance-monitor`. It links to a branch where I've encoded all the trickier steps.
@chrisbobbe, would you try these instructions out and see if you can get working results? If something doesn't work for you, describe it in chat and we'll debug. In particular I haven't yet tested this on iOS.
Then I think probably the best workflow is for you to add a commit on top of this one that adds any further steps you needed, clarifications, or other changes; and we can merge that.
With some further work, I think everything in the setup could be merged, too. If we find ourselves doing this regularly, we'll want to do that, because it's just a trade of work up front for a bit of work each time. We can …
> docs/profiling: Add a rough first doc on profiling and benchmarking.

- flow-typed/@react-native-community/async-storage_v1.x.x.js
- src/boot/ZulipAsyncStorage.js
- src/boot/store.js
- src/third/redux-persist/persistStore.js
Thanks to @gnprice for his investigation and diagnosis of this issue!
I've gone pretty light on detail in code comments, while being sure to link to the relevant conversation on CZO. I'm wary of muddling an already-subtle area of the code with another wall of text, especially for a temporary fix that we expect will be replaced with something more thorough soon.
Fixes: #4458
> Fix "t.get is not a function" on state.narrows at startup.

- docs/howto/debugging.md
- docs/performance.md
Some of these ideas come from [this discussion](https://chat.zulip.org/#narrow/stream/48-mobile/topic/webview.20log/near/1120527) on CZO.
> Improve the debugging doc a bit.

- src/account/AccountItem.js
- src/account/AccountList.js
I had a spare minute or two, so I converted these more or less at random (they're at the top of a search results for `extends PureComponent`) and thought I'd send it as a PR. 🙂
> Hooks: convert `AccountItem`, `AccountList`.

- src/emoji/EmojiPickerScreen.js
> emoji: Show toast on error adding reaction emoji

- src/account/AccountItem.js
- src/account/AccountList.js
- static/translations/messages_en.json
Fixes: #4579 
| | |
|---|---|
| <img src="https://user-images.githubusercontent.com/31806059/113324966-5eebe600-9335-11eb-8fca-52a10822790f.jpg" height="420"/> | <img src="https://user-images.githubusercontent.com/31806059/113325074-880c7680-9335-11eb-8098-6e5e1f5b3907.jpg" height="420"/>|
> Add sign-out label to account-list item in AccountPickScreen, Fixes: #4579

- src/account/accountsSelectors.js
- src/common/WebLink.js
- src/start/PasswordAuthScreen.js
> PasswordAuthScreen: Fix a crash.

- src/title/TitleStream.js
This adds an actionsheet when you long-press a stream title
> Stream title actionsheet

- src/account/AccountPickScreen.js
- static/translations/messages_en.json
> AccountPickScreen: Ask for confirmation when pressing on 'remove account'

- src/api/queueMarkAsRead.js
Two fixes from #4620, as requested by @gnprice.
> queueMarkAsRead fixes

- src/nav/NavBarBackButton.js
Provide a suitable icon for the back button. The icon will be
platform-specific i.e the name of the icon will be 'arrow-left'
for android and 'chevron-left' for iOS.
**On iOS**
> NavBarBackButton: Give the right icon for back button.

- src/common/PresenceStatusIndicator.js
> presence: Use theme background color.

- src/account/AccountItem.js
- src/account/AccountList.js
- src/account/AccountPickScreen.js
- src/common/SmartUrlInput.js
- src/nav/getInitialRouteInfo.js
- src/nav/navActions.js
- src/start/RealmInputScreen.js
- static/translations/messages_en.json
> Fix: Stop having `RealmInputScreen` flash by between `AccountPickScreen` and `AuthScreen`. 

- src/nav/AppNavigator.js
- src/withHaveServerDataGate.js
> Fix: Logout gives endless loading screen

- src/api/initialDataTypes.js
- src/api/modelTypes.js
- src/api/registerForEvents.js
- src/config.js
- src/events/eventToAction.js
- src/message/fetchActions.js
> events: Accept new `realm_linkifiers` format.

- src/autocomplete/EmojiAutocomplete.js
- src/autocomplete/PeopleAutocomplete.js
- src/autocomplete/StreamAutocomplete.js
- src/boot/AppDataFetcher.js
- src/boot/ThemeProvider.js
- src/boot/TranslationProvider.js
- src/chat/MarkAsReadButton.js
- src/chat/UnreadNotice.js
- src/common/PresenceStatusIndicator.js
- src/diagnostics/StorageScreen.js
- src/message/MentionedUserNotSubscribed.js
Several instances of #4837 that are pretty straightforward.
There are more of these easy ones, and I almost did those here, but then I figured this was already a big enough chunk to review. 🙂
> Use `useSelector` instead of `connect` in several places.

- src/nav/IconUnreadConversations.js
- src/nav/IconUnreadMentions.js
- src/settings/DebugScreen.js
- src/settings/LanguageScreen.js
- src/settings/LegalScreen.js
- src/settings/NotificationsScreen.js
- src/settings/SettingsScreen.js
- src/sharing/SharingScreen.js
Following #4844, toward issue #4837, here are some more that I did today.
> Use `useSelector` instead of `connect` in several more places.

- src/autocomplete/TopicAutocomplete.js
- src/chat/GroupDetailsScreen.js
- src/chat/UnreadNotice.js
- src/common/LoadingBanner.js
- src/main/HomeScreen.js
- src/sharing/ChooseRecipientsScreen.js
- src/start/IosCompliantAppleAuthButton/index.js
- src/streams/CreateStreamScreen.js
- src/title-buttons/ExtraNavButtonTopic.js
- src/title/TitleStream.js
- src/user-groups/CreateGroupScreen.js
- src/user-picker/UserPickerCard.js
- src/users/UsersCard.js
Following #4876, toward issue #4837, here are some more that I did today.
> Use `useSelector` instead of `connect` in more places.

- android/app/src/main/java/com/zulipmobile/generated/BasePackageList.java
- android/settings.gradle
- ios/Podfile.lock
- ios/ZulipMobile/AppDelegate.h
- ios/ZulipMobile/AppDelegate.m
- package.json
- yarn.lock
Anecdotally, the app seems much less laggy than usual on my iPhone after this branch. Not sure why. 🤷
> Upgrade `expo-*` packages and `react-native-unimodules` across major versions

- docs/howto/release.md
- docs/howto/translations.md
- tools/tx-sync
See
https://github.com/zulip/zulip-mobile/pull/4901#issuecomment-883697861
for what prompted this.
> i18n [nfc]: Document translation-sync process more.

- src/common/Screen.js
- src/common/SearchInput.js
- src/nav/ModalSearchNavBar.js
- src/search/SearchMessagesScreen.js
This PR does the prep work for implementing #4859 it changes the behavior of search from on query change to on submit.
Fixes: #4964
> Modify Search functionality 

- ios/Podfile.lock
- yarn.lock
I've tested on iOS and Android and things seem fine.
> deps: Run `yarn upgrade`.

- src/third/redux-persist/createPersistor.js
This takes care of the error-handling edge case I described at https://github.com/zulip/zulip-mobile/pull/4694#discussion_r691727392 . Along the way we make some small refactors to this code.
> persist: Retry failed writes on next update

- .flowconfig
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/zulipmobile/ShareFileAndroid.kt
- flow-typed/react-native-image-picker_vx.x.x.js
- ios/Podfile.lock
- jest/jestSetup.js
- package.json
- src/compose/ComposeMenu.js
- src/compose/__tests__/ComposeMenu-test.js
- yarn.lock
> deps: Upgrade react-native-image-picker to 4.1.1, the latest

- src/webview/html/htmlBody.js
- src/webview/js/generatedEs3.js
- src/webview/js/js.js
I tested the message-list on iOS, and I didn't notice any change in behavior. It seems like the kind of thing where regressions might be sneaky, though.
Related: #3851
> msglist-diffing: Add new div#msglist-elements

- android/app/src/main/java/com/zulipmobile/notifications/NotificationUiManager.kt
For detailed discussion of choosing this particular pattern, see:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/notification.20vibration.20pattern/near/1284530
This also makes the first time we're discarding an old notification
channel / category and making a new one, in order to change the
settings that can't be changed on an existing channel.  So add a bit
of infrastructure to handle that: just look for channels that aren't
at the current channel ID, and delete them.
Before putting this in a prod release, I'd like to bunch it up with
setting a distinct notification sound too, to avoid repeatedly
clobbering users' settings.  But it's fine to do that for us few
alpha users, so that isn't an obstacle to merging this now.
Also delete the comments about settings being added recently …
> android notif: Set a distinct vibration pattern

- android/app/src/main/java/com/zulipmobile/MainActivity.kt
- android/app/src/main/java/com/zulipmobile/notifications/NotificationUiManager.kt
This takes care of the two followups discussed at https://github.com/zulip/zulip-mobile/pull/5146#discussion_r764447236 and https://github.com/zulip/zulip-mobile/pull/5146#discussion_r762350660 .
> android: Small refactors around handling intents

- flow-typed/react-intl_vx.x.x.js
- src/api/eventTypes.js
- src/boot/store.js
- src/common/Label.js
- src/common/NestedNavRow.js
- src/common/Screen.js
- src/common/TranslatedText.js
- src/common/ZulipBanner.js
- src/common/ZulipTextButton.js
- src/directSelectors.js
- src/events/eventToAction.js
- src/nav/ModalNavBar.js
- src/realm/__tests__/realmReducer-test.js
- src/realm/realmReducer.js
- src/reduxTypes.js
- src/settings/LegalScreen.js
- src/types.js
- src/utils/openLink.js
- static/translations/messages_en.json
And do a few cleanups/improvements along the way, as usual. 🙂
Greg, I'd really appreciate your help resolving a Flow error in the last commit. It would unlock the ability to bold the realm name where it appears inside a string we want translated.
> legal: Link to Zulip's terms and terms for the active realm

- src/chat/GroupDetailsScreen.js
- src/nav/navActions.js
- src/pm-conversations/pmConversationsSelectors.js
- src/title/Title.js
- src/title/TitleGroup.js
- src/typing/__tests__/typingSelectors-test.js
- src/user-groups/CreateGroupScreen.js
- src/utils/narrow.js
- src/utils/recipient.js
And to a few more places that that enables.
> recipient [nfc]: Preserve PmKeyRecipients through PM narrows

- src/main/MainTabsScreen.js
See discussion at
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/unread.20count.20is.20not.20visible.20properly.20in.20overlay.2E/near/1300099
> MainTabsScreen: Use white text in unread-PMs badge

- src/RootErrorBoundary.js
- src/api/notifications/savePushToken.js
- src/message/fetchActions.js
https://github.com/zulip/zulip-mobile/pull/5234 is another PR in this direction. After this one and that one, the major task will be to sort out various errors in our libdef files that will be newly flagged; see https://github.com/zulip/zulip-mobile/issues/5230#issuecomment-1040950000.
> More fixes to prepare for Flow v0.149

- src/types.js
- src/unread/UnreadCards.js
- src/unread/unreadSelectors.js
These come from looking at this code with @Fingel earlier today.
> unread [nfc]: Small cleanups

- src/webview/js/generatedEs3.js
- src/webview/js/js.js
- src/webview/js/script.js
- tools/generate-webview-js
The original motivation here was to add these block comments (/cc @Fingel), but looking at this code also caused me to notice these small cleanups to make.
> webview js [nfc]: Add comments about the structure of this code; and small cleanups

- ios/Podfile.lock
- yarn.lock
I've kicked the tires on my iPhone and things still seem to work as before. Charging the office Android device now.
Supersedes: #5254
> deps: Run `yarn upgrade`

- src/api/modelTypes.js
- src/api/users/updateUserStatus.js
- src/autocomplete/EmojiAutocomplete.js
- src/emoji/EmojiPickerScreen.js
- src/emoji/EmojiRow.js
- src/emoji/data.js
- src/reactions/MessageReactionsScreen.js
- src/reduxTypes.js
- src/user-statuses/UserStatusScreen.js
- src/user-statuses/userStatusesCore.js
- src/user-statuses/userStatusesModel.js
This aims to do two main things:
- Resolve a TODO in src/api/users/updateUserStatus.js about its inputs
- Cut out some duplicated work in EmojiPickerScreen
> emoji [nfc]: Tidy up some relevant code, before using it more

- package.json
- src/action-sheets/index.js
- src/utils/internalLinks.js
- static/translations/messages_en.json
- yarn.lock
Adds a "Copy link to topic" action to topics which places the full URL
to a topic on the system clipboard.
Currently this PR is built using a yarn link for @zluip/shared againt zulip/zulip main.
> topics: Add "Copy link to topic" action for topics.

- src/sharing/SharingScreen.js
> SharingScreen: Some correctness fixes

- .gitattributes
These were moved in 7ab5a5cd4.
> gitattributes: Suppress diffs on renamed Jest snapshot files

- src/compose/ComposeBox.js
There are some followups that I've noted in TODOs at the tip, but I thought it'd be good to send what I have so far on this.
> ComposeBox: Convert to a function component!

- package.json
- src/autocomplete/EmojiAutocomplete.js
- src/emoji/EmojiPickerScreen.js
- src/emoji/__tests__/data-test.js
- src/emoji/__tests__/emojiSelectors-test.js
- src/emoji/data.js
- src/emoji/emojiSelectors.js
- src/types.js
- yarn.lock
> Use shared code for emoji typeahead.

- .eslintignore
- .prettierignore
- flow-typed/react-native-webview_v11.x.x.js
- types/react-native-webview.js.flow
This finishes all the libdef work I've been tracking as blocking the Flow upgrade for #5230. 🙂
> react-native-webview libdef: Move to .js.flow file

- src/RootErrorBoundary.js
- src/notification/notifOpen.js
- src/webview/handleOutboundEvents.js
Just 12 errors remain (at current `main`) after this: [flow.txt](https://github.com/zulip/zulip-mobile/files/8508640/flow.txt)
This blog post will be relevant for those, as it was for these: https://medium.com/flow-type/sound-typing-for-this-in-flow-d62db2af969e
But they'll probably take some discussion.
> Fix some small things to anticipate Flow v0.158

- src/api/eventTypes.js
A quick followup from https://github.com/zulip/zulip-mobile/pull/5346/files/b1b6286344bea360257d9b8cf41207b3974f4c0f#diff-07bf5e0cd8d3c133fb42b7d6820b1bc8465dc0ad6ddff2a43caadcb41ac41c99 .
> event types [nfc]: Further deduplicate StreamUpdateEvent definition

- src/streams/__tests__/streamsReducer-test.js
From discussion: https://github.com/zulip/zulip-mobile/pull/5346#discussion_r854372456
> streamsReducer tests [nfc]: Make these a bit more compact

- src/compose/ComposeBox.js
~~For review after #5312 settles.~~ Done! 🙂
> ComposeBox conversion: some followups

- src/compose/ComposeBox.js
From https://github.com/zulip/zulip-mobile/pull/5327#pullrequestreview-949320152 .
> ComposeBox: small followups on useUncontrolledInput

- src/account-info/AccountDetails.js
This commit will allow the user to select the `username` and copy it.
Fixes: #5166
> AccountDetails: Add the feature to select and copy the `full_name`.

- src/__tests__/lib/exampleData.js
- src/api/initialDataTypes.js
- src/api/registerForEvents.js
Following #5351, where we did the `User` and `CrossRealmBot` parts of this.
> api types: Finish syncing `InitialDataRealmUser` with the doc as of FL 121

- src/reduxTypes.js
- src/settings/__tests__/settingsReducer-test.js
- src/settings/settingsReducer.js
- src/storage/__tests__/migrations-test.js
- src/storage/migrations.js
- src/webview/backgroundData.js
- src/webview/html/message.js
This just sets up some plumbing that we'll use.
Related: #5348
> msglist: Prep for showing reacting users when few

- src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.android
- src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.ios
- src/webview/__tests__/generateInboundEventEditSequence-test.js
- src/webview/html/message.js
- src/webview/static/base.css
- static/translations/messages_en.json
> msglist: Respect user's display_emoji_reaction_users setting

- src/common/Input.js
- src/compose/ComposeBox.js
- src/useUncontrolledInput.js
These will make ComposeBox a bit more efficient and more pleasant to work with, for #1975 (which we recently got another nudge for; see there) and for other issues. The file is down from 713 lines to 627 lines with this PR; not huge, but something.
> ComposeBox: Small cleanups (better type checking, move custom hook to new file, etc.)

- src/api/modelTypes.js
- src/users/userSelectors.js
> api: Add new custom profile field type, "Pronouns"

- src/message/messagesActions.js
This follows up on https://github.com/zulip/zulip-mobile/pull/5496#issuecomment-1272172102 , with a few NFC commits that factor out a couple of functions from within the new `doNarrowNearLink`.
> Refactor follow-/near/-links logic

- src/autocomplete/PeopleAutocomplete.js
- src/common/Icons.js
- src/user-groups/UserGroupItem.js
- src/users/UserItem.js
This is the PR Greg asked me to separate out of #5508; see https://github.com/zulip/zulip-mobile/pull/5508#pullrequestreview-1167785275.
Here's a new set of screenshots, since:
- I'm not sure if anything has changed in `main` since I opened #5508 
- The ["after" screenshot](https://github.com/zulip/zulip-mobile/pull/5508#issuecomment-1302629158) from that other PR, before splitting this out, is no good to use here, because this PR doesn't start using the bullhorn icon for wildcard mentions.
> Fix layout issues in user autocomplete

- src/lightbox/Lightbox.js
- src/notification/notifOpen.js
- src/sentry.js
- src/start/webAuth.js
- src/utils/__tests__/url-test.js
- src/utils/internalLinks.js
- src/utils/url.js
- src/webview/js/generatedEs3.js
- src/webview/js/rewriteHtml.js
Instead of repeating its implementation everywhere.
> url [nfc]: Use isUrlOnRealm where the logic calls for it

- src/boot/OfflineNoticeProvider.js
We hope to get a fix for this bug out today if possible, so, marking as P0.
> offline notice: Remove entrance/exit animation on Android

- src/action-sheets/__tests__/action-sheet-test.js
- src/action-sheets/index.js
- src/api/messages/getRawMessageContent.js
- src/api/modelTypes.js
- src/chat/ChatScreen.js
- src/compose/ComposeBox.js
- src/compose/ComposeMenu.js
- src/search/SearchMessagesCard.js
- src/utils/internalLinks.js
- src/webview/MessageList.js
- src/webview/__tests__/generateInboundEvents-test.js
- src/webview/handleOutboundEvents.js
- static/translations/messages_en.json
> compose: Offer a "Quote and reply" option

- src/streams/StreamItem.js
These are some stylistic cleanups to how we compute styles for this component, inspired by reviewing #5467. (/cc @dizzyjaguar)
> StreamItem [nfc]: Various style-style cleanups

- src/utils/__tests__/internalLinks-test.js
- src/utils/internalLinks.js
Hmm, Greg, I'd appreciate your help working out what to do with these tests. I don't want to lose your work, but I think most of the test cases are now unneeded with this change? Thanks!
> internalLinks [nfc]: Have isNarrowLink take a URL object

- ios/Podfile.lock
- ios/upload.plist
With this, I was finally able to do `tools/ios build` and
`tools/ios upload` without issue.
> ios: Specify provisioning profile in `ios/upload.plist`

- src/settings/languages.js
- static/translations/messages_en.json
This is now significantly translated.
> i18n: Offer Belarusian as a language choice

- .flowconfig
- package.json
- src/__tests__/lib/exampleData.js
- src/message/__tests__/fetchActions-test.js
- src/storage/__tests__/sqlite-test.js
- src/storage/migrations.js
- yarn.lock
This seems pretty straightforward to do.
> flow: Upgrade to v0.175.1

- src/compose/ComposeBox.js
- src/utils/internalLinks.js
> compose: Use new /dm/… link format in quote-and-reply, for recent servers

- src/autocomplete/PeopleAutocomplete.js
- src/autocomplete/WildcardMentionItem.js
It turns out that server support for this hasn't landed yet. Once it has, we'll know what feature level to condition on.
> compose: Remove @topic from autocomplete, for now

- src/typing/typingActions.js
See chat thread (same link as in a comment):
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/typing.20notifications.20constants/near/1665193
> typing status: Lengthen the hardcoded expiry period to 45s

- src/utils/__tests__/internalLinks-test.js
- src/utils/internalLinks.js
> internalLinks: Recognize "channel" as operator in narrow links

- src/title/TitleSpecial.js
- static/translations/messages_en.json
Fixes: #5832
| Before | After |
| --- | --- |
| ![D5D272A0-24C0-4ABB-B050-0695CEF95BC6](https://github.com/zulip/zulip-mobile/assets/22248748/b156a747-a283-4ef3-973b-6597fbbc4f5d) | ![9BEB182C-BECE-4884-AB7B-26B3A13DE205](https://github.com/zulip/zulip-mobile/assets/22248748/03ff2227-cdf5-4976-98af-5fbfcaf796d6) |
> ui: Rename "All messages" to "Combined feed"

- android/app/build.gradle
> android build: Set strict version 0.10.4 for RN's dependency SoLoader
