zulip/zulip-mobile

src/emoji/__tests__/data-test.js
src/emoji/data.js

Previously, emoji queries required an exact initial match. Instead,
match against the query-string's occurrence anywhere in the name.
This imperfectly mimicks the webapp's behavior, in that prefix-matches
are considered better than normal matches. The webapp leaves some
sort-ordering unspecified, however, and also has a set of "popular
emoji" which are always considered a good match if they're considered
a match at all. Properly mimicking the webapp is left as #3833.
Test data has been taken from the original PR #3836 by @sumukhah,
whose choice of sort order is also maintained to simplify tests.
Fixes #3948.
Co-Authored-By: sumukhah <sumukha214@gmail.com>

emoji search: Search for query-string anywhere in the emoji name.

---

src/common/GroupAvatar.js

Determine the color of text on group avatar by using foregroundColorFromBackground() this will help users to read the text properly when the background color is light.
Also replace the for loop in colorHashFromString() with a single line equation that will reduce the complexity from O(n) to O(1).
The for loop before resulted in a recursive equation: 
```hash(N) = hash(N-1) * 31 + name.charCodeAt(1)       , hash(0) = 0```
This actually is the sum of the first N terms in a Geometric Progression, for which a mathematical equation is already present.
The for loop ran till ```names.length```, whose value depends on the no.of members in a group. For a certain large value and above, JS wouldn't be able to calculate the value of ```hash``` and returns ```infinity```,  this happens in the equation …

group-pm: Improve the text color on group icons

---

src/settings/LanguagePicker.js

Dividers in the language picker screen isn't visible in night mode since they are black in color. Use OptionDivider instead. OptionDivider changes it's color with respect to the appropriate theme.
Fixes: #3986

ui: fix the visibility of dividers in dark mode

---

src/account-info/AccountDetailsScreen.js
src/chat/GroupDetailsScreen.js
src/nav/navActions.js
src/reactions/ReactionUserList.js
src/title-buttons/InfoNavButtonPrivate.js
src/title/TitleGroup.js
src/title/TitlePrivate.js
src/users/__tests__/userSelectors-test.js
src/users/userSelectors.js
src/webview/html/messageAsHtml.js
src/webview/html/messageTypingAsHtml.js
src/webview/js/generatedEs3.js
src/webview/js/js.js
src/webview/webViewEventHandlers.js

This is a rough initial PR. Feedback is appreciated. This was done to make pull #3878 mergeable, as per https://github.com/zulip/zulip-mobile/pull/3878#issuecomment-589911019.
This PR will partially address https://github.com/zulip/zulip-mobile/issues/3764.

Migrate navigateToAccountDetails and getUserIsActive to user IDs

---

src/webview/js/generatedEs3.js
src/webview/js/js.js
src/webview/webViewEventHandlers.js

Closes #3879.
This is a common pattern in messaging apps, and a feature I felt was missing.
I also created a selector  - `getUserForId` and wrote tests for it.
Tested that it works in varoius narrows, such as stream narrows, topic narrows, PM narrows, starred messages narow.

Add feature to view profile on tapping @mention for a user

---

src/compose/ComposeBox.js

- Provide max height in percentage so that it works in split screen mode,
and even when keyboards appears.
Fixes: #3977

composeBox: Limit maxHeight to '50%' of parent.

---

src/autocomplete/EmojiAutocomplete.js
src/emoji/Emoji.js
src/emoji/EmojiPickerScreen.js
src/emoji/EmojiRow.js
src/emoji/__tests__/data-test.js
src/emoji/__tests__/emojiSelectors-test.js
src/emoji/data.js
src/emoji/emojiSelectors.js
src/reactions/MessageReactionList.js
src/types.js

Messages contain emoji code with them in reactions. So use them instead
of relying on codes hardcoded in the app. This fixes the issue when
emoji names in app are outdated.
Fixes: #3716

emoji: Use parseUnicodeEmojiCode to render unicode emoji.

---

android/app/webviewAssets.gradle
ios/ZulipMobile.xcodeproj/project.pbxproj
package.json
src/webview/css/css.js
tools/build-webview
yarn.lock

This is a successor to #3744 and #3679, and fixes #2660.  It sets us up so that the message-list webview now uses KaTeX to show math formulas, just like the webapp does.
The commits that actually set up KaTeX, and then add some fixes to how it displays in certain cases, are @ray-kraesig's and taken from those previous PRs.  The major difference from those PRs is that it doesn't include the complex build-script infrastructure that those PRs added; instead it simplifies our existing `tools/build-webview` script somewhat and then extends it more modestly in order to accomplish what we need for KaTeX.  The approach is based on my [`rsync-refactor`](https://github.com/zulip/zulip-mobile/compare/master...gnprice:rsync-refactor) branch (to commit gnprice/zulip-mobile@6d98d01fb), from the #3679 …

Add LaTeX math support (v3)

---

src/chat/ChatScreen.js

In ChatScreen.js, message list is being rendered after compose box auto-complete is implemented inside composeBox, so whenever the autocomplete is rendered the message list is being rendered above it thus hiding the autocomplete.
This is fixed in this PR by rendering the MessageList before compose box.
----------------Before------------------------------------------------------------------------------After----------------

composeBox: fix auto-complete not showing

---

src/utils/__tests__/color-test.js
src/utils/color.js

colorHashFromString() now considers all charecters in the string it can also now return colors with red component in it. Also fixed the cases where the function returned #NaN for very long or empty strings.
Fixes: #3985

group-pm: fix colorHashFromString

---

src/account/accountsSelectors.js
src/types.js
src/users/usersActions.js

Zulip server versions >= 2.0.0-rc1 require user ID arrays in the
'to' argument for the typing endpoint, whereas we currently send
email arrays.
Check the Zulip version and use the appropriate format of the
argument, i.e., for versions >= 2.0.0-rc1 or when the Zulip server
version is undetermined, use user ID arrays, otherwise, use email
arrays.
Fixes #3732.

typing: Serialize recipients based on server version.

---

.eslintrc.yaml
src/presence/presenceReducer.js
src/utils/__tests__/presence-test.js
src/utils/presence.js

presence: Fix timestamp being Unix zero (50 years ago).
This is a user-visible symptom, but it's kind of a rare case that we
wouldn't expect to see normally. Sometimes, a user is displayed to
be "last active" 50 years ago, which is bogus. It turns out that it
only happens when a presence event is sent from the server (meaning
it should be as up-to-date as possible; we wouldn't expect it to be
more than a few seconds off), but it's more than 140 seconds old.
Presence events coming from the server don't have the `aggregated`
field, like presence objects do in the /register response and
presence report responses. So we have our own function,
getAggregatedPresence, to calculate it for us. This is analogous to
the status_from_timestamp function in the web app.
As suggested in the parent, a bug …

Fix bogus year-1970 timestamp in how we aggregate user presence

---

src/nav/ChatNavBar.js

There is a gap of 1px between navigation Bar and the top header in chat screen. This is caused by applying  bottomBorder on navBar. This PR removes this.
---------------------Before-----------------------------------------------------------------------After----------------------------

chatNavBar: fix gap between navBar and topmost header

---

src/pm-conversations/__tests__/pmConversationsSelectors-test.js
src/pm-conversations/pmConversationsSelectors.js
src/unread/unreadHuddlesReducer.js
src/utils/recipient.js

This is part of #4035, specifically the main part of it that's blocking #3535.
We have a function `getRecipientsIds` whose real meaning is that it computes the key to use to look up a PM conversation in our `unread` state-subtree, derived from the `unread_msgs` data structure from the server. This series gives it a more meaningful name, `pmUnreadsKeyFromMessage`; adds jsdoc and comments; and cleans up the interface and implementation a bit, including by switching from emails to user IDs (a case of #3764).

recipient [nfc]: Clean up and document how we compute `unread_msgs` keys.

---

src/actionTypes.js
src/events/eventToAction.js
src/reduxTypes.js
src/typing/__tests__/typingReducer-test.js
src/typing/__tests__/typingSelectors-test.js
src/typing/typingReducer.js
src/typing/typingSelectors.js
src/utils/__tests__/recipient-test.js
src/utils/recipient.js

I also manually tested that typing notifications are working, and the changes are reflected in the Redux state. Relevant tests are also made well-typed.
Closes #3930.
________
Currently, tests are failing due to (I believe) a Flow bug:
The type TypingState is defined as 
```js
export type TypingState = {|
[normalizedRecipients: string]: {
time: number,
userIds: number[],
},
|};
```
So, `initalState` should be a valid instance of TypingState:
```js
const initialState = deepFreeze({
'1': { time: 123456789, userIds: [1] },
});
const newState = typingReducer(initialState, action);
```
But Flow complains:
```
Cannot call `typingReducer` with `initialState` bound to `state` because property `1` is missing in  `TypingState` [1] but exists in  object literal [2].Flow(InferError)
```
That's …

[WIP] Consume user IDs rather than emails from typing-status events.

---

src/unread/__tests__/unreadSelectors-test.js
src/unread/unreadSelectors.js

We'd like to clarify and untangle most of the UI code in
UnreadCards, StreamItem, and elsewhere (part of that is #3767), but
the most pressing task is to minimally fix an issue where a stream
named "private" causes bugs for other users who are subscribed to it
and are viewing UnreadCards on mobile.
So, fix it at the source, where the `key` in the data is first
assigned, by adding a prefix. Fortunately, consumers of this data
don't ever expect that the `key` will be equal to the stream's name.
The magic string should never have been introduced in the first
place, and it should be removed as part of those larger refactors.
But the temptation to use it would probably not have existed, if
more careful thought had gone into the UI semantics here.
In particular, private messages and …

UnreadCards: Avoid collision between strings from users and a magic string

---

src/__tests__/lib/exampleData.js
src/outbox/__tests__/outboxReducer-test.js

Rewrite `outboxReducer-test.js` tests to be well-typed.
This incidentally fixes a few tests which weren't actually testing what they said they were testing. (Fortunately, fixing the tests didn't require changes to the code being tested.) Otherwise, this patchset should involve no interesting changes to the tests.

Add proper typing to Outbox reducer tests

---

src/message/messageActionSheet.js

Break `constructMessageActionButtons` up into two functions, depending on whether the message being processed is an Outbox message or not. Type this properly.
Extracted from PR #3978.

Refactor constructMessageActionButtons

---

src/utils/__tests__/async-test.js

Sometimes, `setTimeout(1000)` will fire after only 999 milliseconds.
This appears to be due to an upstream bug in Node.js itself [1].
Closes #4010.
[1] https://github.com/nodejs/node/issues/26578

async: Fudge test value to defeat flake in `sleep` test.

---

src/api/initialDataTypes.js
src/api/modelTypes.js

This bite-size PR is forked from https://github.com/zulip/zulip-mobile/pull/4046#discussion_r414889862.
---------------
api types: `realm_user_groups` is absent prior to v1.8.0.
This was already handled in runtime code, as of d64b7c84b, on
PR #2878, for issue #2859.
On the server, `git log --stat -p --reverse -S realm_user_groups`
reveals that 4c6a376fd, which is v1.8.0-rc1~2711, is the first
occurrence of 'realm_user_groups'.
Also comment on UserGroup type to highlight difference from group
PMs feature.

api types: `realm_user_groups` is absent prior to v1.8.0.

---

src/common/GroupAvatar.js
src/common/__tests__/initialsForGroupIcon-test.js
src/pm-conversations/GroupPmConversationItem.js
src/utils/__tests__/misc-test.js
src/utils/misc.js

When there are large no.of recipients or people with large
no.of initials in their names, the profile Icon is overflowed
with letters. This PR fixes this by taking only the first Initial
from each name and if no.of recipients is > 4 adding a '+'
charector to the end.
Fixes: #3939

group-pm: Fix profile icon breaking for large no.of recepients

---

src/nav/__tests__/navReducer-test.js
src/nav/navReducer.js
src/pm-conversations/__tests__/pmConversationsSelectors-test.js
src/pm-conversations/pmConversationsSelectors.js
src/realm/__tests__/realmReducer-test.js
src/realm/realmReducer.js
src/reduxTypes.js
src/utils/recipient.js

This fixes #4077, which was the root cause of the crash bug brought out by #4040; then restores the changes made originally in #4040.
See background in #4077 and details in commit messages.

Stop using fake blank data at login; and restore #4040

---

src/typing/__tests__/typingSelectors-test.js
src/typing/typingSelectors.js
src/webview/MessageList.js
src/webview/html/messageTypingAsHtml.js

Issue was caused beacuse ```getUsersByEmail``` couldn't determine the user-id of Welcome Bot. This is fixed in the PR by making use of ```getAllUsersByEmail``` instead.
Fixes: #4067.

typingSelectors: Fix selecting welcome bot in pm crashes the app

---

src/boot/store.js
src/utils/__tests__/url-test.js
src/utils/url.js

This does the following, to fix https://github.com/zulip/zulip-mobile/issues/3567:
> Things I expect we'll want to do to clean this up:
> 
> * Tweak fixRealmUrl so it strips any number of trailing slashes.
> * Add a migration that strips trailing slashes on realm in all existing accounts.
It also removes some "DEPRECATED" comments that don't seem to apply.

Strip any number of trailing slashes from realm URLs

---

src/webview/js/generatedEs3.js
src/webview/js/js.js

When the message list's viewport grows, we generally want to scroll up to keep its bottom edge aligned within the content, but we want to skip that when we're at the very bottom. We have logic to do all that, but it's pretty cryptic; this series starts by unpacking it.
If we're at the bottom and scroll up anyway, the effect would be exactly the symptoms in #3301.
Then it turns out that when we're at the bottom, the `scrollTop` value may not actually quite line up with where you'd think it should be. Empirically:
* On iOS (in Safari), it tends to be 1px beyond the bottom.
* On Android (in Chrome), it's not an integer, and can be a fraction of a px either beyond or short of the bottom.
So, allow for that when checking to see if we're at the bottom. We'd been testing for exact numerical …

Fix scroll-on-resize to avoid jumping from bottom

---

src/api/__tests__/apiFetch-test.js
src/api/apiFetch.js
src/api/registerForEvents.js
src/api/users/updateUserStatus.js
src/lightbox/downloadImage.js

This function did both less and more than it really needed to.
Pulled out of plumbing work for #4086.

Remove `objectToParams`

---

android/app/build.gradle
android/app/src/main/java/com/zulipmobile/CustomTabsAndroid.java
android/app/src/main/java/com/zulipmobile/CustomTabsHelper.java
android/app/src/main/java/com/zulipmobile/notifications/NotificationsModule.java
android/build.gradle
android/gradle.properties
package.json
tools/postinstall
yarn.lock

AndroidX, previously called the Android Support Library, is a collection of libraries developed by Android upstream which are bundled into an app at build time, rather than taken from the system on the device.  Some are quite central to a typical Android app.
Upstream has renamed the whole thing to AndroidX, and this goes with a renaming of tons of classes.  (Mostly to get them out of `android.*`, which was always very confusing because that's the same namespace used by the actual system packages.)  Docs: https://developer.android.com/jetpack/androidx/migrate
This could have been sticky, because lots of apps and lots of third-party libraries refer to these core libraries, and in a distributed ecosystem it's impossible for everything to update at once.  And because these are often so …

android build: Update to AndroidX.

---

src/webview/static/base.css

Fixes: #4042
This is based on https://www.interactiveaccessibility.com/blog/text-resizing-web-pages-ios-using-dynamic-type#.XqVIvpMzZ25
- Change font size in iOS setting to test this PR, Setting -> General -> Accessibility -> Larger text
- After changing text size, reload the webview. Changes are only effective when webview is re-rendered.
- It only works for text whose html element doesn't override `font-size` (like `.code`) and rely on parent (`body`) css styles.
Screenshots (iPhone X), when `font: -apple-system-body;` is applied to body:
- Max font size (Larger accessibility toggle is off)
- Min font size (Larger accessibility toggle is off)
Also works fine when Larger accessibility toggle is on

webview, css: Apply font: -apple-system-body; to body.

---

src/lightbox/Lightbox.js

As opposed to only when the visible image is tapped, as we
currently do.
This is done by simply adding another prop `onViewTap` ( for the
black part) in the react-native-photo-view component[1].
Note that `onTap` and `onViewTap` respond mutually exclusive
areas, the union of which makes up the entire component.
Closes #4098.
[1] https://github.com/alwx/react-native-photo-view#properties

ligthbox: Toggle header & footer on tapping the entire view.

---

src/webview/webViewEventHandlers.js

Previously, in-realm links copied to the clipboard didn't include
the realm domain, and were essentially invalid.
Now, the complete URL is copied to the clipboard.
Closes #4107.

message list: Fix copying links to clipboard.

---

src/start/AuthScreen.js

This fixes an issue noted in https://github.com/zulip/zulip-mobile/issues/3567#issuecomment-622574435 where we're duplicating slashes when we call social auth endpoints.
A better fix depends on https://github.com/zulip/zulip-mobile/issues/4081. The commit messages reflect that issue being blocked by the RN v0.61 upgrade, but Ray points out that we may be able to do it without the available JS library, and instead make a native plugin, in which case the issue is not blocked; discussion is ongoing.

Deduplicate slashes in social auth login endpoints

---

docs/howto/build-run.md

Adds command to clean gradle build, and link to upstream
troubleshooting docs.

docs: Add more troubleshooting info for build and run.

---

.prettierrc
.prettierrc.js

These two are small and NFC but mergeable before the RN upgrade, to make that PR easier.

More pre-RN 60 commits

---

src/lightbox/LightboxActionSheet.js
src/lightbox/downloadImage.js
src/lightbox/shareImage.js

Currently, the `downloadImage` function saves images with the
wrong names, extensions and MIME types. This commit fixes that
by introducing a new argument for the function - `fileName`,
and by determining the MIME type from the file extension.
Simply having the proper extension does not fix the issue, as the file is still interpreted as a text file by Android. The proper MIME type is still required.
Fixes: #4138
Fixes: #4137

lightbox: Download images with correct names and MIME types.

---

.flowconfig
flow-typed/react-native-url-polyfill_vx.x.x.js
package.json
src/start/AuthScreen.js
yarn.lock

Fixes: #4081 
I'll follow this up by creating an issue to fix the many uses of regexes and string concatenation; I think #4081 was mainly for settling on a workable solution.

Add `react-native-url-polyfill`.

---

src/common/FloatingActionButton.js
src/common/Icons.js
src/common/OptionButton.js
src/common/OptionRow.js
src/common/ZulipButton.js
src/start/AuthScreen.js

Before this change, if we write a `name` prop that mistypes an icon's
name, or refers to an icon that for any reason doesn't exist, Flow
won't give an error.  Now it will.
Was looking at this a couple of weeks ago in reviewing #3617 and experimenting with the code. Most of these changes are a set of followups I'd drafted then, and just cleaned up now.

Icons: Extend type-checking to the icon names, and small other cleanups.

---

docs/howto/build-run.md

Required after the RN 0.60 upgrade.

Update build-run instructions in docs

---

src/webview/MessageList.js

The resolution of #2914 in b0fc3177b was to show a "loading view"
(which was really just a blank rectangle of the appropriate theme
color) during the initial load of the WebView. During some debugging
of extremely long displays of this loading view, we found [1] that
it doesn't count as finished loading until all images have loaded,
which will regularly take quite a long time, and no content shows
until it's finished.
Instead, forget the "loading view" and just make the background
color of the WebView transparent. Empirically, this solution
wouldn't have worked work on iOS with `react-native-webview` v5.0.0
(where we were at b0fc3177b), but it does on v8.0.4, which we're on
now. It seems to work on Android at either version.
[1]: …

msglist: Make background transparent.

---

src/actionTypes.js
src/api/registerForEvents.js
src/chat/__tests__/narrowsReducer-test.js
src/chat/narrowsReducer.js
src/events/eventToAction.js
src/message/__tests__/messagesReducer-test.js
src/message/fetchActions.js
src/message/messagesReducer.js
src/unread/unreadHuddlesReducer.js
src/unread/unreadMentionsReducer.js
src/unread/unreadPmsReducer.js
src/unread/unreadStreamsReducer.js

I haven't yet tested end-to-end an actual bulk delete; I'm still looking for a way to do that in the UI on CZO. Maybe it's an admin feature, or it's not accessible through the UI yet?
Fixes: #4158

events: Add support for bulk delete_message events.

---

ios/ZulipMobile.xcodeproj/project.pbxproj
ios/ZulipMobile/Info.plist
ios/ZulipMobile/ZLPInfoProperties.h
ios/ZulipMobile/ZLPInfoProperties.m

Following discussion [1] about a SO answer (not currently the
accepted one) [2], we find it's not too hard, when we want the App
ID prefix (sometimes called the Team ID), to
1. Add a custom entry in ios/ZulipMobile/Info.plist that gets set to
that string at build time, and
2. Write some minimal Objective-C to add a native module that calls
an iOS API to grab that custom entry and exposes it to the
JavaScript.
We followed a very clear React Native doc [3] on how to do this.
We also considered using a different doc [4] that would have helped
us package our code up very conveniently for distribution to NPM,
with a third-party tool called `create-react-native-module`. The
output of that tool seemed to have all the appropriate metadata that
we're used to seeing in modules in the React Native …

ios native modules: Expose "AppIdentifierPrefix".

---

src/autocomplete/PeopleAutocomplete.js

Previously, our @-mention autocomplete had a bug, wherein it
failed to correctly mention the correct user if more than one user
had the same full name.
Now, if more than one users have the same full name, we now send
the user ID as well to ensure that the correct user is
@-mentioned.

people auto complete: Send user ID for users having same full name.

---

src/webview/MessageList.js
src/webview/js/generatedEs3.js
src/webview/js/js.js
src/webview/webViewEventHandlers.js
src/webview/webViewHandleUpdates.js

To help debugging #4156; see also discussion around https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M4156.20Message.20List.20placeholders/near/921700, where we'll have the debugging conversations.

MessageList long loading logs

---

src/common/ErrorMsg.js
src/start/RealmScreen.js
static/translations/messages_en.json

Show an error message when the user tries to enter an email in the
server URL input field, even before trying to connect to the
server.
Fixes: #4058

realm screen: Give early error when server URL is an email address.

---

src/__tests__/lib/exampleData.js
src/message/__tests__/messageActionSheet-test.js

Thanks @agrawal-d for upgrading the message action sheet tests in #3824 / 4670210f8 to be well-typed! And thanks @ray-kraesig for reviewing and merging that PR.
After reading that commit, I saw some ways that that test file could be further improved to reduce boilerplate and also to make the test data more typical and more fully coherent (e.g., stream name and ID properties agreeing with each other.) Some of those involve extending `exampleData` with new features. This PR is the result.
(@agrawal-d , I can't seem to add you as a requested reviewer -- perhaps you're not in the GitHub org? But please do take a look. :slightly_smiling_face: )

Extend exampleData to further clean up messageActionSheet tests

---

src/webview/js/InboundEventLogger.js
src/webview/js/generatedEs3.js
src/webview/js/js.js
src/webview/js/sendMessage.js

Prompted by Greg's suggestions at https://github.com/zulip/zulip-mobile/pull/4180#issuecomment-654466175.
There are a few differences to call out. If they're problematic, I'll fix them right away, of course!
> The log-long-load state and all the logic referring to that state could be encapsulated in a class
Since I was making a class anyway, and putting it in its own JS file, I didn't want to entangle that class with the DOM detail of whether the `message-loading` div was visible. Instead, I made it so you can call "start" and "stop" methods on the class. I think this will also be useful if we want to log based on other, unrelated states. The code added in `js.js` is still much smaller than in the old way.
> The `map` callback that produces `loggableEvents` could be pulled out and given a …

Improve long-loading logging code from the WebView.

---

src/account/__tests__/accountsReducer-test.js

With Flow v0.113.0, which we'll get in the RN v0.61 -> v0.62 upgrade
(#3782), red flags are raised about this test. Strangely, the test
was allowed to expect the `zulipVersion` on an Account to be
undefined. In fact, the type for it is `ZulipVersion | null`.
The test is based on the false premise that a REALM_INIT action
might not have a `zulipVersion` property. `RealmInitAction` states
that it will always be there, as a ZulipVersion instance. So, delete
the test. If we ever find that there's a legitimate case where it is
missing, we'll fix the RealmInitAction type accordingly, and a new
test can proceed from there.

accountsReducer: Remove unhelpful test.

---

android/app/build.gradle

Upgrades the fresco:animated-gif dependency in 'build.gradle' to
2.0.0 recommended by the official docs [1] to fix animated GIF
support in Android, which was broken after the recent React Native
upgrade.
[1] https://reactnative.dev/docs/0.61/image#gif-and-webp-support-on-android
Fixes: #4212

deps: Upgrade Fresco to recommended version for animated GIFs.

---

docs/architecture/react.md
src/ZulipMobile.js
src/boot/ThemeProvider.js
src/boot/TranslationProvider.js
src/chat/ChatScreen.js
src/common/Input.js
src/common/Label.js
src/common/LineSeparator.js
src/common/LoadingBanner.js
src/common/OptionButton.js
src/common/OptionDivider.js
src/common/OptionRow.js
src/common/Popup.js
src/common/RawLabel.js
src/common/Screen.js
src/common/SectionHeader.js
src/common/SmartUrlInput.js
src/compose/ComposeBox.js
src/main/MainScreenWithTabs.js
src/nav/ModalNavBar.js
src/nav/ModalSearchNavBar.js
src/pm-conversations/PmConversationsCard.js
src/reduxTypes.js
src/streams/StreamItem.js
src/styles/index.js
src/styles/theme.js
src/subscriptions/__tests__/subscriptionsReducer-test.js
src/types.js
src/user-groups/UserGroupItem.js
src/webview/MessageList.js

Fixes: #1946 
Fixes: #3994
A continuation of https://github.com/zulip/zulip-mobile/pull/4046, which has gotten cluttered with several unrelated conversations (sorry!). The work being done here isn't as complicated as the length of those conversations might suggest.
Greg has already merged several commits from that older PR, as he lists at https://github.com/zulip/zulip-mobile/pull/4046#issuecomment-622204993:
> I've gone and merged 10 of these commits, along with a small added commit at the end:
> f9caf224c SmartUrlInput: Switch to new React Context API for theme colors.
> a197c9916 StreamItem: Switch to new React Context API for theme colors.
> 64e142226 miscStyles [nfc]: Remove unused `color` in `miscStyles`.
> ecba735a7 StreamItem [nfc]: Readability refactor (no need to repeat object …

Stop using legacy Context API for styles (continued)

---

.eslintrc.yaml
.flowconfig
flow-typed/npm/react-native-image-picker_vx.x.x.js
ios/Podfile.lock
jest/jestSetup.js
package.json
src/compose/ComposeMenu.js
yarn.lock

Following discussion around [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/changes.20in.20generatedEs3.2Ejs/near/935879).
This includes
- Jest
- Sentry
- Flow
Two things from that discussion are left out, for now
- ESLint (see [what happened](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/changes.20in.20generatedEs3.2Ejs/near/954082); #4128 shouldn't have this problem)
- An "everything else" command, probably `yarn upgrade`; this would include the ESLint stuff, which causes problems as noted.

Slightly upgrade some chunks of our dependencies.

---

src/compose/ComposeBox.js
src/compose/ComposeMenu.js
src/utils/info.js
static/translations/messages_en.json

Check if we are caught up in the current narrow, and if so, show an
error when trying to send a message asking the user to try again
after some time.
This prevents the user from possibly responding to a very old
message when the messages after it have not been loaded yet - this
can lead to the reply being out of context without the sender
realizing it.
Fixes: #3800

compose box: Show error on sending message when not caught up.

---

src/api/messages/__tests__/migrateMessages-test.js
src/api/messages/getMessages.js
src/webview/__tests__/webViewHandleUpdates-test.js
src/webview/html/__tests__/render-test.js

In a revision of my work for #4157, I noticed that there were some necessary changes to some test files, and some of these files haven't been type-checked or taken advantage of the work we've put into `src/__tests__/lib/exampleData.js`.
Rather than continue editing these files in this unstable state, pave the way for better edits by type-checking them and using that example data. 🙂  And fix a few bugs I've noticed.
The revision that informed these changes was one where the type for `avatar_url` on the `Message` type (not just that field on the `User` type) was changed. I *think* this might be a direction we'll go in (e.g., the type might be a union of all subclasses of `AvatarURL` except `IdleAvatarURL`); I'm thinking of the discussion around …

Prep commits for new `avatar_url` handling (#4157)

---

docs/architecture/react.md
src/boot/TranslationProvider.js

This reverts commit 68ca7468.
We were too quick with this, unfortunately. The `FormattedMessage`
component, straight from `react-intl`, is a consumer of
`IntlProvider`, using the old Context API. So we still need the
`key` hack.
See discussion [1].
We should then move forward with upgrading `react-intl` to v3, which
uses the new Context API. With that, we won't need the `key` hack.
[1] https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Language.20picker.20regression/near/974627

Revert "translation context: Eliminate `key` hack (the last one!)."

---

src/api/index.js
src/api/subscriptions/getSubscriptionToStream.js
src/autocomplete/AutocompleteView.js
src/common/ZulipButton.js
src/compose/ComposeBox.js
src/compose/MentionWarnings.js
src/message/MentionedUserNotSubscribed.js
static/translations/messages_en.json

Fixes #3373.
**Summary of Changes**
* We use the endpoint `/users/{user_id}/subscriptions/{stream_id}` to get the subscription status.
* On non-PM screens, we show a warning when someone unsubscribed is mentioned.
* This warning shows up with a nice animation.
* Pressing the subscribe button subscribes the user and dismisses the warning.
* Tapping on the warning dismisses it.
* Multiple warnings can be shown at a time.
Web app equivalent, for comparison:

Warn on @-mentioning someone who won't see it because not subscribed

---

src/boot/TranslationProvider.js
src/compose/MentionWarnings.js
src/message/messageActionSheet.js
src/types.js
src/webview/webViewEventHandlers.js

This allows us to stop using the `intl.formatMessage` API in its most extra-verbose form.  (When there are variables to interpolate, both `defaultMessage` and `id` are required, even though for us they're the same thing -- because while react-intl will fall back to `id` as the message when a translation isn't available, it will do so literally, without any interpolation. @agrawal-d pointed this out at https://github.com/zulip/zulip-mobile/pull/4175#discussion_r459261420 .)

i18n [nfc]: Add interpolation support to our `_` wrapper.

---

src/common/ZulipButton.js
src/compose/MentionWarnings.js
src/message/MentionedUserNotSubscribed.js

This follows up on some of the UI points I noted in this comment before merging #4101: https://github.com/zulip/zulip-mobile/pull/4101#issuecomment-669764675
Specifically, going through that comment in order:

UI tweaks on mention-unsubscribed warning

---

android/app/build.gradle
android/app/src/debug/java/com/zulipmobile/ReactNativeFlipper.java
android/app/src/main/java/com/zulipmobile/MainApplication.java
android/build.gradle
android/gradle.properties
android/gradle/wrapper/gradle-wrapper.properties
android/gradlew
android/gradlew.bat
docs/howto/build-run.md
ios/Podfile
ios/Podfile.lock
ios/ZulipMobile.xcodeproj/project.pbxproj
ios/ZulipMobile.xcodeproj/xcshareddata/xcschemes/ZulipMobile release-mode.xcscheme
ios/ZulipMobile.xcodeproj/xcshareddata/xcschemes/ZulipMobile.xcscheme
ios/ZulipMobile/AppDelegate.h
ios/ZulipMobile/AppDelegate.m
ios/ZulipMobile/main.m

Most of #3782.
I expect this to include the complete set of pre-upgrade changes that correspond to template-app changes as highlighted in the [upgrade helper diff](https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.2) that we plan to make (note that some required changes to our own code, like those needed for the Flow version change, will naturally not show up in the diff—and not all of these are included here). A list of exceptions to those changes in the diff is at https://github.com/zulip/zulip-mobile/issues/3782#issuecomment-683235466. A few post-upgrade commits from that diff will be done in a different PR, https://github.com/zulip/zulip-mobile/pull/4247.
I'm more confident about the completeness and the ordering of the template-app-diff-related changes than …

Pre-RN v0.61 -> v0.62 upgrade changes

---

src/webview/static/base.css

When the Markdown implementation on the server was upgraded in the
3.0-dev period, one subtle change was that code blocks started looking
like <pre><code>...</code></pre> instead of just <pre>...</pre>.
As a consequence, our CSS rules that were meant to apply to inline
code snippets started applying also to the text inside a code block.
Most conspicuously, we started showing not only a block-level border
around the whole code block (as intended), but also an inline border
around just the text inside the block.  That means a border starts on
the left of the text; runs above and below it to the end of just the
text on the line; then the border lines break and resume at the start
of the next line; etc., until wrapping around the right end of the
text on the last line.  We also showed a …

msglist css: Fix inline border on text inside code blocks.

---

docs/howto/translations.md
tools/tx-pull
tools/tx-sync

This brings the process for cleanly syncing with Transifex down
much closer to a single command.
That in turn will hopefully help us do it routinely right after
merging any change that adds or modifies message strings, so that
translators who are active can more consistently have an
opportunity to supply translations before the new message strings
appear in even one release.

i18n: Add script tools/tx-sync to automate more steps.

---

src/nav/AppNavigator.js

A followup to https://github.com/zulip/zulip-mobile/pull/4249; see https://github.com/zulip/zulip-mobile/pull/4249#pullrequestreview-490239568.
New in the recent React Navigation upgrades to v3 and v4, there's
now a transition animation when the loading screen exits. We don't
want to prolong the effect of the loading screen [1], so, get rid of
that exit animation.
Most accurately, we want to target the exit of the loading screen
and disable the animation there. But it seems that the
`animationEnabled` switch in `navigationOptions` operates on the
*entrance* of particular screen; I haven't found a similar option
for the *exit* of a particular screen.
A good workaround, to the extent that it's practical, would be to
tell all screens to disable their entrance animations if and only if …

nav: Don't show a transition animation between 'loading' and 'main'.

---

src/webview/static/base.css

For many aspects of the message list's layout and styling, the relevant CSS rules are scattered through the file. That can make it hard to get a clear picture of how things work, or to compare to their counterparts in the webapp where applicable (i.e. for message content.)
These changes add somewhat more order to the CSS rules. There's still plenty of opportunity to clean them up further.
I was moved to make these changes by working in the CSS for #4258, and so I developed them on top of that fix; it's the first commit of this branch.

msglist css [nfc]: Group and reorder CSS rules for better readability.

---

.travis.yml
docs/howto/build-run.md

We've been using this for local development for a little while,
and all seems well.
The major visible benefit to this upgrade is that startup times are
much improved:
https://github.com/zulip/zulip-mobile/issues/3780#issuecomment-639804863
which means everything we do from a script becomes much faster.
Fixes: #3780

deps: Upgrade to Node v12, in setup docs and in CI.

---

src/__tests__/lib/exampleData.js
src/account/__tests__/accountsReducer-test.js
src/account/accountActions.js
src/account/accountsReducer.js
src/actionTypes.js
src/api/initialDataTypes.js
src/api/settings/getServerSettings.js
src/boot/store.js
src/start/RealmScreen.js
src/types.js

Following [#14658](https://github.com/zulip/zulip/pull/14658), we now obtain `feature level` from Zulip server and store it in Redux. This is designed to provide a simple way for mobile apps to decide whether the server supports a given feature or API change.
Closes #4049.

Store server feature level in Redux

---

src/start/AuthScreen.js
src/webview/js/generatedEs3.js
src/webview/js/js.js

Explanations in the commit messages.
For the second (doubled slashes in Apple auth endpoint), following Greg's comment at https://github.com/zulip/zulip-mobile/pull/4265#issuecomment-697040991—chat.zulip.org seems perfectly happy to accept the double-slash version, like it did before cfebe3f53752968235e33ee428e2239025b5c11c 😆. At first I was confused about why it seemed to work both before and after my commit here. Anyway, that's probably why.

Fix a few more regressions from #4235.

---

src/compose/ComposeBox.js

This is a regression caused by something that was missed in
fd4debbae; we partly but incompletely removed our use of
`getWrappedInstance` with a react-redux API change. From that commit
message:
"""
So, make that change, including the implied removal of
`getWrappedInstance`; that bit of UI works fine on Android and iOS
after that removal.
"""
It looks like "that bit of UI" was something other than sending a
message, and I didn't do a full-project search for the term
`getWrappedInstance` in that revision. This should be the last of
them now.
Fixes: #4270

ComposeBox: Fix a crash on sending a message.

---

src/chat/ChatScreen.js
src/nav/__tests__/navSelectors-test.js
src/nav/navSelectors.js
src/session/__tests__/sessionReducer-test.js
src/session/sessionReducer.js

(Moves us closer toward https://github.com/zulip/zulip-mobile/issues/3804.)
-----
As noted in discussion [1], we haven't been using quite the right
information to decide whether it's time for a ChatScreen to fetch
new messages. As Greg says, there,
"""
[T]he condition we'd like to have governing this isn't "is this
ChatScreen showing the same narrow that's topmost or last", but
rather "is this the topmost or last ChatScreen".
"""
To grab that bit, we first considered [2] something like adding a
unique ID to each ChatScreen, which seems hacky.
But while I was doing the recent React Navigation v3 and v4
upgrades, I came across this `withNavigationFocus` HOC, which
provides an `isFocused` prop [3], which looks more or less exactly
like what we'd want. "Is this ChatScreen focused" isn't …

ChatScreen: Get `isFocused` from React Navigation.

---

android/gradle.properties
ios/Podfile
ios/Podfile.lock

See discussion [1], where Greg reported that 7c7271598 introduced an
issue where uploading images from the camera was broken on Android.
The issue is facebook/react-native#28551; it seems to be a problem
specifically with Flipper's "network" plugin [2].
The discussion on that issue links to facebook/flipper#993, which
suggests [3] upgrading Flipper to 0.39.0. So, do. On Android, it may
be necessary to do a `cd android && ./gradlew clean` after this
commit.
It's nice that we can upgrade Flipper independently of React Native;
it seems this will stay possible [4].
[1] https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Flipper/near/1042657
[2] https://github.com/facebook/react-native/issues/28551#issuecomment-611085378
[3] https://github.com/facebook/flipper/issues/993#issuecomment-61 …

flipper: Upgrade Flipper to 0.39.0.

---

android/app/src/main/AndroidManifest.xml
android/build.gradle

This change will be required in order to upload new releases to the
Play Store, effective 2020-11-01, a couple of weeks from now.
The change causes Android 10 and later to apply to our app a number
of behavior changes introduced in that version, documented here:
https://developer.android.com/about/versions/10/behavior-changes-10
Further discussion in #3665.
Fixes: #3665

Update to target Android 10 / API 29.

---

.eslintrc.yaml
tools/formatting.eslintrc.yaml

Things I noticed in the course of making the edits in 88cafe4df, that can perhaps make future edits to this config a little easier.
This is `eslint [nfc]` because it makes no functional changes even *to* the ESLint config; it just touches comments and whitespace.

eslint [nfc]: Give comments more room to breathe; regularize indentation.

---

tools/build-webview

On Windows (in Git Bash) there's no /dev/stdin; but this works
instead, as we learned here:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/issue/near/1047294
(Things still aren't working there as a whole, but we seem to get
past one error and reach another one.)
Conversely, this exact construct `--filter='. -'` appears in an
example in the rsync man page, even at the ancient rsync 2.6.9
that Apple provides on macOS.
Suggested-by: @andersk

webview build: Spell stdin as `-` for reading rsync filter rules.

---

src/autocomplete/PeopleAutocomplete.js
src/chat/GroupDetailsScreen.js
src/pm-conversations/PmConversationList.js
src/reactions/ReactionUserList.js
src/sharing/ShareToPm.js
src/user-picker/UserPickerCard.js
src/users/UserItem.js
src/users/UserList.js
src/users/UsersCard.js

These changes were sitting in an old branch of mine from February where I experimented with prototyping a major overhaul of the `Narrow` data structures. These are quite independent of that and easily pulled out, and help us advance #3764 (converting from using emails to using user IDs); so might as well get them in.

UserItem [nfc]: Use more whole user objects, fewer bags of properties

---

src/__tests__/lib/exampleData.js
src/chat/__tests__/narrowsReducer-test.js
src/message/messagesActions.js
src/notification/__tests__/notification-test.js
src/notification/extract.js
src/notification/index.js
src/notification/notificationActions.js
src/notification/types.js
src/pm-conversations/__tests__/pmConversationsSelectors-test.js
src/pm-conversations/pmConversationsSelectors.js
src/reduxTypes.js
src/utils/__tests__/internalLinks-test.js
src/utils/__tests__/narrow-test.js
src/utils/internalLinks.js
src/utils/narrow.js
src/utils/recipient.js

This grew out of revising #3889 -- after https://github.com/zulip/zulip-mobile/pull/3889#discussion_r510523367 it was clear that more tests were needed on this code, and also I rediscovered the `isMessageInNarrow` function which already does something very similar to what one of my commits in that PR was seeking to do. The branch basically looks like:
* I set about overhauling that function's tests, making them table-driven so they're far more focused and more compact in the source.
* Then I added a bunch more test cases, now that they're just a line of code each, and now that it's easy to see what all the existing tests are doing and see what cases aren't covered.
* Some of the tests failed!
* This led to a range of bugfixes: some in our example data for testing, but also the potentially …

Fix some "is message in narrow" bugs, and test much more thoroughly

---

src/__tests__/lib/exampleData.js
src/chat/__tests__/narrowsSelectors-test.js
src/chat/narrowsReducer.js
src/chat/narrowsSelectors.js
src/events/doEventActionSideEffects.js
src/outbox/outboxActions.js
src/topics/__tests__/topicsSelectors-test.js
src/types.js
src/utils/__tests__/narrow-test.js
src/utils/narrow.js

This grew out of #3889. It follows #4294 by returning to the outbox code, and includes versions of all the changes made in #3889.
Along the way it fixes additional bugs, and the "Replace narrowContains" commit turns out to fix some bugs of its own. (That is, the old implementation turns out to be outright buggy. Meanwhile the new implementation here is from #4294 and well tested, and avoids the bugs in #3889's new implementation.)
Fixes: #4298
Fixes: #4301

outbox: Fix some bugs from Narrow confusion; remove Narrow

---

src/webview/js/js.js
tools/generate-webview-js

These were kind of tucked away in the middle of a bunch of logic.
Perhaps more importantly, they had a comment pointing to js.js but
nothing vice versa -- so they weren't discoverable when updating
our canonical list of supported platforms.
And in fact, we didn't remember this line and update it when we most
recently updated that list, in c953bc336 a few weeks ago... nor the
time before that, in b3eced058 a year ago... and the latter commit
came just a few weeks after we wrote this code in the first place.
So, apply those two updates; and pull these minimums out with more
explanation, and linked both to and from the canonical list in js.js.
This update doesn't cause any change to the generated output; in fact
it turns out that there are no Babel plugins at all that are affected
by …

webview build: Update target browser versions, and clarify.

---

.flowconfig
src/caughtup/__tests__/caughtUpReducer-test.js
src/sharing/ShareToPm.js
src/sharing/ShareToStream.js
src/start/IosCompliantAppleAuthButton/index.js

The RN v0.63 upgrade issue is #4245. There'll likely be quite a bit more work to do for Flow when we get closer to doing that upgrade, but this is a start! 🎉

Fix a few Flow complaints we'd get with RN 0.63 and Flow 0.122.0.

---

flow-typed/@sentry/react-native_v1.x.x.js
src/utils/__tests__/zulipVersion-test.js
src/utils/logging.js
src/utils/zulipVersion.js

We include a few tags here:
- `rawServerVersion`: Just what it sounds like.
- `coarseServerVersion`: E.g., 2.1.x or 3.x
- `fineServerVersion`: E.g., 2.1.0 or 3.2
(Note that our numbering conventions changed, effective with 3.0, so
3.x and 4.x are each the same level of granularity as 2.1.x or
2.0.x.)
Also, update our custom libdef to include `scope.setTags`, which we
use here.
Fixes: #3745

logging: Send server version to Sentry.

---

docs/style.md
src/webview/css/cssNight.js
src/webview/html/htmlBody.js
src/webview/html/messageAsHtml.js
src/webview/js/generatedEs3.js
src/webview/js/js.js
src/webview/static/base.css

Prompted by an issue discussed on CZO at
https://chat.zulip.org/#narrow/stream/48-mobile/topic/Weird.20timestamps/near/1075475.

msglist: Rename `timestamp` class to `msg-timestamp`.

---

docs/style.md
package.json
src/api/modelTypes.js
src/chat/__tests__/narrowsReducer-test.js
src/chat/narrowsSelectors.js
src/events/doEventActionSideEffects.js
src/lightbox/Lightbox.js
src/message/__tests__/fetchActions-test.js
src/message/messageActionSheet.js
src/outbox/outboxActions.js
src/pm-conversations/pmConversationsSelectors.js
src/topics/topicActions.js
src/types.js
src/unread/unreadHuddlesReducer.js
src/unread/unreadPmsReducer.js
src/utils/__tests__/message-test.js
src/utils/__tests__/narrow-test.js
src/utils/__tests__/recipient-test.js
src/utils/message.js
src/utils/narrow.js
src/utils/recipient.js
src/webview/html/messageHeaderAsHtml.js

This starts us using Flow's support for an assertion function named `invariant`, which I learned about recently: https://github.com/facebook/flow/issues/6052
The immediate inspiration is the last commit in this series, a small test cleanup which clears things up for #4327. I thought a bit about more substantial ways to make use of it, and landed on a refactoring of how we handle the notorious `display_recipient` property on messages: at the end of this branch, when we consume `display_recipient` we always do so through a pair of helpers in `recipient.js`, which explicitly check our assumptions and return well-typed results.
There's also a few other cleanups in here which either came up as prerequisites for the main changes, or were suggested by them and quick to add in.

Introduce `invariant`; use it to handle display_recipient more cleanly.

---

src/account-info/AccountDetailsScreen.js
src/chat/__tests__/narrowsReducer-test.js
src/chat/__tests__/narrowsSelectors-test.js
src/chat/narrowsSelectors.js
src/compose/MentionWarnings.js
src/compose/__tests__/getComposeInputPlaceholder-test.js
src/compose/getComposeInputPlaceholder.js
src/message/NoMessages.js
src/message/messageActionSheet.js
src/message/renderMessages.js
src/notification/__tests__/notification-test.js
src/notification/index.js
src/outbox/outboxActions.js
src/pm-conversations/PmConversationList.js
src/title-buttons/InfoNavButtonGroup.js
src/title-buttons/titleButtonFromNarrow.js
src/title/Title.js
src/title/TitleGroup.js
src/title/__tests__/titleSelectors-test.js
src/typing/__tests__/typingSelectors-test.js
src/typing/typingSelectors.js
src/unread/unreadSelectors.js
src/user-groups/CreateGroupScreen.js
src/users/UsersCard.js
src/users/usersActions.js
src/utils/__tests__/internalLinks-test.js
src/utils/__tests__/narrow-test.js
src/utils/internalLinks.js
src/utils/narrow.js
src/webview/html/messageHeaderAsHtml.js

We have two "constructors" `privateNarrow` and `groupNarrow` for 1:1 PMs and group PMs respectively, but they end up building basically the same data structure.  Then in a lot of places in our code we have control flow to handle the group-PM case on the one hand and the 1:1 case on the other, and it ends up just saying the same thing twice to treat them both the same way.  (In a few places, like `getNarrowFromMessage`, we have no such logic and already implicitly rely on the fact that they're the same underneath.)
In general the Zulip model is that group PMs and 1:1 PMs are very much alike, and the Zulip API generally treats them alike.  So let's move toward more consistently handling them alike, and only having conditionals to distinguish between them when we actually want to do …

narrow: Treat group PMs and 1:1 PMs more symmetrically.

---

src/account-info/AccountDetails.js

fixes: #4307
Greg pointed out in the issue  #4307 that status symbol is slightly misaligned and should be place before name as in zulip's Web UI
so I placed the status symbol to the left of the name and also adjusted the alignment (slightly lowers the status symbol)
Also more explanation is given in the above issue

status symbol aligned before name and lowering its height

---

flow-typed/jest_v26.x.x.js
src/message/messageActionSheet.js
src/utils/__tests__/narrow-test.js
src/utils/narrow.js

narrow: Add `getNarrowsForMessage`.
We've never had a function for getting all the narrows that a
message appears in. Such a function will be important
algorithmically for avoiding a performance regression with the
EVENT_NEW_MESSAGE action if/when we start storing `state.narrows` as
an `Immutable.Map`; see discussion of this strategy at
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.60Immutable.2EMap.60.20performance.20for.20.60state.2Enarrows.60/near/1068912.
Might as well put it in `narrow.js` and make it reusable, too.

narrow: Add `getNarrowsForMessage`.

---

jest/jestSetup.js
src/boot/loggingContext.js
src/boot/store.js
src/common/PresenceStatusIndicator.js
src/message/messagesActions.js
src/notification/__tests__/notification-test.js
src/notification/extract.js
src/notification/index.js
src/notification/notificationActions.js
src/typing/__tests__/typingSelectors-test.js
src/typing/typingReducer.js
src/typing/typingSelectors.js
src/utils/__tests__/internalLinks-test.js
src/utils/__tests__/recipient-test.js
src/utils/internalLinks.js
src/utils/logging.js
src/utils/narrow.js
src/utils/recipient.js
src/webview/html/messageHeaderAsHtml.js

This follows on some work prompted by #4317, begun in #4330.  I have a longer branch on top of this which is still in development, which does much more to encapsulate the fiddly details of how we describe PM conversations, and as a result takes care of most of #4035 which has been the main obstacle to #3133.  This PR contains the changes from that branch which are ready and stand on their own.
Among these changes are some small bugfixes, and other cleanups in areas of the code where the larger branch will do further work.  This branch starts with a couple of infrastructural changes to smooth the way for using error logging in more parts of our code.

narrow/recipient: Fix more bugs, and prep for bigger refactors

---

src/account-info/AccountDetailsScreen.js
src/chat/__tests__/narrowsReducer-test.js
src/chat/__tests__/narrowsSelectors-test.js
src/compose/__tests__/getComposeInputPlaceholder-test.js
src/notification/__tests__/notification-test.js
src/notification/index.js
src/pm-conversations/GroupPmConversationItem.js
src/pm-conversations/PmConversationList.js
src/pm-conversations/PmConversationsCard.js
src/pm-conversations/__tests__/pmConversationsSelectors-test.js
src/pm-conversations/pmConversationsSelectors.js
src/title/__tests__/titleSelectors-test.js
src/types.js
src/typing/__tests__/typingSelectors-test.js
src/unread/UnreadCards.js
src/unread/unreadSelectors.js
src/user-groups/CreateGroupScreen.js
src/users/UsersCard.js
src/users/usersActions.js
src/utils/__tests__/internalLinks-test.js
src/utils/__tests__/narrow-test.js
src/utils/internalLinks.js
src/utils/narrow.js
src/utils/recipient.js
src/webview/html/messageHeaderAsHtml.js

This is the larger refactoring branch foreshadowed by #4332, following up further on #4330.  This takes care of most of #4035 which has been the main obstacle to #3133, and brings us much closer to being able to handle #4333.
The main thrust of this series is to further centralize responsibility for the fiddly details of how we describe PM conversations.  In particular, at the end of this series:
* All PM narrows we construct, outside of test code, use data that is verified -- with the help of the type-checker -- to have the right set of users, including or excluding self in a consistent way.
We've previously had a number of bugs where these didn't match.  The last few of those were fixed in #4294; this part doesn't change any behavior, but effectively consolidates those fixes.
* All PM …

narrow/recipient: Always centrally filter and sort PM users, and verify that.

---

package.json
src/__tests__/lib/exampleData.js
src/boot/store.js
src/caughtup/caughtUpReducer.js
src/caughtup/caughtUpSelectors.js
src/chat/__tests__/fetchingReducer-test.js
src/chat/__tests__/narrowsReducer-test.js
src/chat/__tests__/narrowsSelectors-test.js
src/chat/fetchingReducer.js
src/chat/fetchingSelectors.js
src/chat/narrowsReducer.js
src/chat/narrowsSelectors.js
src/drafts/__tests__/draftsReducer-test.js
src/drafts/__tests__/draftsSelectors-test.js
src/drafts/draftsReducer.js
src/drafts/draftsSelectors.js
src/message/__tests__/fetchActions-test.js
src/reduxTypes.js
src/topics/__tests__/topicsSelectors-test.js
src/utils/__tests__/narrow-test.js
src/utils/narrow.js
src/utils/recipient.js
src/webview/html/messageHeaderAsHtml.js
src/webview/webViewEventHandlers.js

The main motivation for this change is that it will help us switch to a more sensible type for narrows in our code, rather than the existing arrays of operator/operand pairs -- we'll no longer be coupling our data structures to the details of those values.  In particular we intend to make the Narrow values more appropriately structured, and to replace emails and stream names with user IDs and stream IDs: #4333.
As setup for changing how we encode narrows as string keys, we encapsulate doing so into a central function `keyFromNarrow`, and replace all the `JSON.stringify` calls that really meant "encode this narrow to use as a key" with calls to that function.
Along the way I discovered a bug in our encoding and decoding of narrows, #4338, which this fixes.
Fixes: #4338

narrow: Encode our own structured keys instead of JSON.

---

src/common/UserAvatarWithPresence.js
src/lightbox/Lightbox.js
src/lightbox/LightboxHeader.js

As Greg points out, the effect of this default prop has been to
suppress the presence-status indicator for the sender in the
lightbox header. And since that omission is quite unlikely to be
intentional, we should fix it by passing down the sender's email.
So, do.
[1] https://github.com/zulip/zulip-mobile/pull/4230#discussion_r542953311

UserAvatarWithPresence: Remove dubious default prop for `email`.

---

src/utils/__tests__/avatar-test.js
src/utils/avatar.js

Following some profiling with Chrome DevTools, and [discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/user_avatar_url_field_optional/near/1081038) on CZO, keep going in the direction of deferring `new URL` computations, since the computations done in `api.registerForEvents` have made the initial fetch take quite a lot longer after #4230 than before, and URL computations were observed to be a big part of that in profiling.
The above measurements are taken with release builds on my 4+ year-old iPhone 6s running iOS 13.7, on CZO, at notable commits (see the chart's key):
- 998947d807 (narrow [nfc]: Unexport pmNarrowFromEmails!) — Before #4230
- c642677685 (registerForEvents: Start sending `user_avatar_url_field_optional`.) — Tip of #4230
- Then each commit in this …

Address a performance regression from #4230 by deferring `new URL` computations.

---

src/__tests__/lib/exampleData.js
src/utils/__tests__/url-test.js
src/utils/avatar.js
src/utils/url.js

This follows up on #4344 to address part of the remaining performance regression from #4230.
We still construct URL objects in the `get` methods, lazily and memoized; but never up front when simply taking in all the initial data from the server, or the rehydrated data we've stored.  This should save a further slice of time in the initial load.
To do so, we introduce predicates `isUrlAbsolute` and `isUrlPathAbsolute`, which have very simple implementations but clearly defined semantics in terms of the URL Standard.

    avatar: Remove remaining URL construction for initial load.

---

src/autocomplete/TopicAutocomplete.js
src/compose/ComposeBox.js
src/topics/topicActions.js
src/topics/topicSelectors.js

Fixes : #2750
**The Problem** - Topics list was fetched for the current stream each time the TextInput was focussed, irrespective of if we have fetched the data before or not. Take a look at #2750 for more...
**Video of the problem -**
https://user-images.githubusercontent.com/36705866/102719650-2e97b300-4315-11eb-90d4-c6a4a15fcb39.mov
**Fix** - Now we fetch data only once for a specific stream. The query is made each time we move to a different stream
**After fixing-**
https://user-images.githubusercontent.com/36705866/102719838-68b58480-4316-11eb-90f1-b5e7b3a45f78.mov

Prevent fetching topics list if we already have them

---

src/boot/store.js
src/chat/__tests__/narrowsSelectors-test.js
src/compose/__tests__/getComposeInputPlaceholder-test.js
src/notification/__tests__/notification-test.js
src/notification/index.js
src/notification/notificationActions.js
src/title/__tests__/titleSelectors-test.js
src/utils/__tests__/narrow-test.js
src/utils/internalLinks.js
src/utils/narrow.js

This follows on #4342 and its predecessors, and accomplishes part of #4333: at the end of this PR, we now have user IDs in our internal representation of PM narrows.
After this, in the next PR or two we'll go on to switch all the various places we consume narrows to use the IDs instead of the emails -- which as mentioned at https://github.com/zulip/zulip-mobile/issues/4035#issuecomment-746896403 will include completing #4035 -- and stop storing emails in our narrows at all.
Thanks to all the prep work in the preceding several PRs, not much actually has to change in this one -- we've already quite thoroughly encapsulated the details of the Narrow type, and also eliminated nearly all the places where we were constructing PM narrows without passing a user ID to the constructor along with an …

narrow: Switch to a reasonable representation, and store user IDs

---

src/webview/MessageList.js

The default WebView `decelerationRate` is `fast`, which slows down momentum scrolling through messages significantly. This changes it to `normal` which is the native rate on iOS and makes it behave like other apps, allowing for much faster scrolling.
Test Plan: confirmed that this has the expected scroll momentum on an iPhone 12.

webview: Use native scroll deceleration on iOS

---

src/chat/__tests__/narrowsSelectors-test.js
src/chat/narrowsSelectors.js
src/events/doEventActionSideEffects.js
src/topics/__tests__/topicsSelectors-test.js
src/unread/unreadSelectors.js
src/utils/__tests__/narrow-test.js
src/utils/__tests__/recipient-test.js
src/utils/narrow.js
src/utils/recipient.js

This is the next PR, following #4346, in our series straightening out how we identify narrows and especially PM narrows. It takes some further steps toward #4333 and #3764, converting some narrow-consumers to use user IDs rather than emails; and it completes the last remaining pieces of #4035.
Along the way, we fix some bugs that potentially hit if a user changes their email address, so that we potentially have data reflecting both their old and new email addresses. This will probably be a recurring feature of many of the individual conversions to using user IDs that make up #3764.
Fixes: #4035

recipient: Finish reconciling the ways we identify a PM conversation

---

src/__tests__/lib/exampleData.js
src/chat/__tests__/narrowsSelectors-test.js
src/common/Icons.js
src/common/Input.js
src/common/Label.js
src/common/RawLabel.js
src/common/ZulipStatusBar.js
src/message/__tests__/fetchActions-test.js
src/pm-conversations/PmConversationList.js
src/pm-conversations/PmConversationsCard.js
src/pm-conversations/__tests__/pmConversationsSelectors-test.js
src/pm-conversations/pmConversationsSelectors.js
src/reduxTypes.js
src/topics/__tests__/topicsSelectors-test.js
src/types.js
src/unread/UnreadCards.js
src/utils/__tests__/narrow-test.js

After taking care of #4035 (cleanly handling PM recipients, in place of our complex old handling of them) with my series of PRs up to #4356, I'm taking a look back at #3133/#3535, to start using the recent_private_conversations data structure, which had been blocked by that work.
Ray had a PR #4116 that sought to do some of that. Some of it goes in some of the same directions as I've since done with my recent PRs for #4035, and there are some parts that I don't think are helpful or needed. But there are other changes there that were and still are useful. Here I've rebased those changes, and added some related commits of my own.
After this, I'll return to Ray's further PR #4104 (which builds on the changes in #4116) to see what parts of that are also helpful to use now.

Refresh the still-useful parts of #4116, on path to using recent-PMs data

---

jest/jestSetup.js
src/utils/__tests__/internalLinks-test.js
src/utils/internalLinks.js

After studying closely the URL Standard and its definition of the [syntax](https://url.spec.whatwg.org/#url-writing) and [parsing algorithm](https://url.spec.whatwg.org/#url-parsing) for URLs in order to write some small predicates like `isUrlAbsolute` for #4345, I took a fresh look yesterday at some of our URL-processing code that we've been wanting to fix for a while, i.e. #4146.
Here's a branch fixing one tangly part of that code: the `isInternalLink` function, used for deciding whether a link the user tries to follow in a message is one we should try to interpret within the app to navigate to some other conversation, or is one we should instead handle more generically, with a download or going out to the browser.
We make the changes in a series of very small steps, so that we can spot …

isInternalLink: Clarify, fix bugs, add tests, move to use URL object

---

src/chat/narrowsSelectors.js
src/common/GroupAvatar.js
src/common/UserAvatar.js
src/common/UserAvatarWithPresence.js
src/compose/ComposeBox.js
src/compose/__tests__/getComposeInputPlaceholder-test.js
src/compose/getComposeInputPlaceholder.js
src/outbox/outboxActions.js
src/title/Title.js
src/title/TitleGroup.js
src/title/TitlePrivate.js
src/users/UserItem.js
src/users/__tests__/userSelectors-test.js
src/users/userSelectors.js
src/utils/narrow.js

This is the next tranche of changes in the series of PRs up to #4356. It converts several more of the places we use the emails from a PM narrow to use user IDs instead. Along the way we make some other conversions from user IDs to emails, as well as other cleanups in the code we're operating on.

narrow: Convert more email usage to user IDs

---

src/boot/replaceRevive.js

As Greg suggests, at
https://github.com/zulip/zulip-mobile/pull/4348#discussion_r548764896.
Also add some comments / jsdoc.

replaceRevive: Use switch/case for what's interesting in `replacer`.

---

src/chat/GroupDetailsScreen.js
src/chat/narrowsSelectors.js
src/nav/navActions.js
src/title-buttons/InfoNavButtonGroup.js
src/title-buttons/InfoNavButtonPrivate.js
src/title-buttons/titleButtonFromNarrow.js
src/users/UserItem.js
src/users/__tests__/userSelectors-test.js
src/users/userSelectors.js
src/utils/__tests__/narrow-test.js
src/utils/narrow.js

This is the next tranche after #4361.
There's some additional places the new `UserItemById` can be used, much like `UserAvatarWithPresenceById`. In a draft branch I've converted those, but haven't finished following the chain of further simplifications that those enable. Those will come in a future PR.
After this PR, there's just a handful of places remaining where we consume the emails from a PM narrow. We'll shortly eliminate those, and then stop storing emails in `Narrow` values altogether.

narrow: Convert more emails to user IDs

---

tools/android
tools/build-webview
tools/bump-version
tools/changelog
tools/checkout-keystore
tools/fmt
tools/info
tools/ios
tools/postinstall
tools/run-android
tools/test
tools/tsort-modules
tools/tx-pull
tools/tx-sync
tools/upgrade
tools/verify-webview-js

This is more portable, allowing me to run the install script on NixOS, which
does not have a `/bin/bash` binary, but does have `/usr/bin/env`. Any system
that has `/bin/bash` should have `/usr/bin/env` as well.

Switch shebang to use /usr/bin/env

---

src/common/UserAvatar.js
src/react-redux.js
src/utils/avatar.js

As discussed yesterday, around [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/302.20redirect.20for.20avatar/near/1089508).

Use auth headers in `ImageBackground` to get a FallbackAvatarURL.

---

docs/howto/shared.md
docs/howto/yarn-link.md
package.json
src/api/modelTypes.js
src/typing/__tests__/typingSelectors-test.js
src/typing/typingReducer.js
src/typing/typingSelectors.js
src/users/usersActions.js
src/utils/narrow.js
src/utils/recipient.js
yarn.lock

This follows #4364 and the chain of PRs that led to that one.
It eliminates one of the two remaining places we use the emails from a PM narrow, in the typing-status code. Along the way it pulls in https://github.com/zulip/zulip/pull/16987 and some other changes to the code shared from the webapp.
The last remaining consumer of the email data in a PM narrow is an important one: it's where we actually fetch messages from the server, or rather in `apiNarrowOfNarrow` where we prepare the `ApiNarrow` value we'll use to do so. As documented in the tip commit of this PR, the server only started accepting IDs there in Zulip Server 2.1. So we can't eliminate that code, or the code that stores emails into `Narrow` values in the first place, until we drop support for server versions 2.0.x and older. …

narrow: Convert typing-status code to all user IDs

---

docs/howto/debugging.md
src/webview/MessageList.js
src/webview/js/generatedEs3.js
src/webview/js/js.js
src/webview/js/script.js

Setting innerHTML triggers an asynchronous render of the DOM. On iOS this reliably happens _after_ the code that comes immediately after the `innerHTML` set. This means that if we calculate a scroll position right after a content update, we can get the wrong `scrollHeight` and present the wrong position.
A nested `requestAnimationFrame` callback reliably runs code after the `scrollHeight` is updated, so use that to get the accurate scroll target.
References:
https://twitter.com/rauschma/status/1288868746682081285
https://macarthur.me/posts/when-dom-updates-appear-to-be-asynchronous
Test Plan: Manually loaded streams on iPhone 12 (iOS 14.3)
Fixes: #4357
I don't have an Android device to test on, but I suspect this will resolve or improve at least some variants of #3457 and #3921.

webview: Fix race when setting scroll position

---

src/third/redux-persist/createPersistor.js
src/third/redux-persist/persistStore.js

The expensive part of persisting the state to disk is running
`stringify` (see replaceRevive.js). While #4348 brought this time
from almost 2000ms down to, perhaps, 300ms on one account on my
device [1], that's still a long time, especially for work that
doesn't need to be done.
See discussion [2] for this solution.
[1] https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.60remotedev-serialize.60.20and.20.60jsan.60/near/1083700
[2] https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.60remotedev-serialize.60.20and.20.60jsan.60/near/1089466

redux-persist: Stop saving `REHYDRATE` payload to disk.

---

android/build.gradle

Release notes here:
https://developer.android.com/studio/releases/gradle-plugin#3-5-0
No major potentially-incompatible changes identified there.
Part of the RN v0.62 -> v0.63 changes to the template app [1],
corresponding to facebook/react-native@e1e081b00.
[1] https://react-native-community.github.io/upgrade-helper/?from=0.62.2&to=0.63.3

android build: Upgrade Android Gradle Plugin to v3.5.3.

---

package.json
yarn.lock

Part of the RN v0.62 -> v0.63 changes to the template app [1],
corresponding to facebook/react-native@82e823933.
That RN commit upgrades a few other deps; we don't take those
changes, for the following reasons:
- We're already past ^7.6.2 of @babel/core.
- We don't currently use @react-native-community/eslint-config
(though we're considering it, in #4119).
- We don't currently use babel-jest.
- We're already past ^25.1.0 of jest.
- We're already past ^0.58.0 of metro-react-native-babel-preset.
Run our usual `yarn yarn-deduplicate && yarn`, as prompted by
`tools/test deps`.
[1] https://react-native-community.github.io/upgrade-helper/?from=0.62.2&to=0.63.4

deps: Follow @babel/runtime upgrade from RN template app.

---

src/webview/js/generatedEs3.js
src/webview/js/js.js

After extensive testing, it's clear that we only need one call in order to reliably get the `scrollHeight`. I also confirmed that the jank is gone in an Android emulator, but I left the conditional intact as it works reliably without rAF at all on Android.
References: #4370

webview: Call requestAnimationFrame once on iOS.

---

src/webview/js/generatedEs3.js
src/webview/js/js.js
src/webview/js/rewriteHtml.js
src/webview/js/spoilers.js
src/webview/static/base.css

Support for creating spoilers was recently added to Zulip[1].
Currently, spoilers render as visible by default on the app.
Add functionality to handle spoilers properly - spoilers are
collapsed by default, and can be toggled by tapping on the header.
Also, if a header is missing, the text 'Spoiler' is added as the
header.
The implementation is similar to [1], but the JavaScript was
rewritten to work without jQuery.
[1] https://github.com/zulip/zulip/commit/1cb040647b37f9f2269c2b39ae6495830f49ac4b
Fixes: #4155

webview: Add support for displaying spoilers.

---

src/boot/store.js
src/chat/narrowsSelectors.js
src/compose/getComposeInputPlaceholder.js
src/message/fetchActions.js
src/outbox/outboxActions.js
src/title-buttons/titleButtonFromNarrow.js
src/title/Title.js
src/unread/unreadSelectors.js
src/utils/__tests__/narrow-test.js
src/utils/narrow.js
src/utils/recipient.js

This is the next in the long chain of PRs #4330, #4332, #4335, #4339, #4342, #4346, #4356, #4361, #4364, and most recently #4368. This one completes a major objective of all that refactoring: at the end of it, we no longer store emails in Narrow values.
After this change, the portion of #4333 that's about PMs, emails, and user IDs -- aka the portion of #3764 that's about narrows -- is complete.
Still open from #4333 is to convert stream and topic narrows from stream names to stream IDs.  I'm hopeful that that will be simpler: (a) unlike the situation for PMs, there's just one stream mentioned at a time, so there's no question of sorting, and (b) there isn't the "include self or not" complication that's bedeviled much of our code related to PMs.  In other words, stream and topic narrows …

narrow: Stop storing emails!

---

src/common/UserAvatar.js

This fixes #4388 with a quick workaround.  The underlying issue is
still present -- we shouldn't have this component mounted at all in
this situation.  But fixing that may involve some tricky changes to
our navigation, and this is a high-severity issue -- a crash in an
essential flow for using the app for many people -- so we want to fix
it promptly even if the underlying fix takes some time.
Fixes: #4388

UserAvatar: Fail gently on bug where auth info is missing.

---

.eslintrc.yaml
src/__tests__/collections-test.js
src/caughtup/caughtUpReducer.js
src/collections.js
src/compose/ComposeMenu.js
src/message/renderMessages.js
src/utils/__tests__/recipient-test.js
src/utils/avatar.js
src/utils/logging.js
src/utils/recipient.js
src/webview/js/generatedEs3.js
src/webview/js/js.js

I wrote up today a draft branch that will take care of #3133, replacing the previous #3535 and #4104, to use the server's handy `recent_private_conversations` feature in order to populate the "PM conversations" screen both more completely and more efficiently.
Along the way -- actually while rebasing and studying #4104, before I decided it'd be better to take a different approach than it or #3535 did -- I discovered a bug in `pmKeyRecipientsFromIds`: it's supposed to work whether the input contains or excludes self, but it doesn't live up to that spec in the case of a self-1:1. This has been a latent bug because all of the representations for PM conversations that we deal with so far represent the self-1:1 thread with a singleton list, not empty. But the `recent_private_conversations` …

Fix a `recipients` bug, preparing to use recent-PMs data

---

src/__tests__/lib/exampleData.js
src/actionTypes.js
src/api/initialDataTypes.js
src/api/modelTypes.js
src/boot/__tests__/__snapshots__/replaceRevive-test.js.snap
src/boot/__tests__/replaceRevive-test.js
src/boot/reducers.js
src/boot/replaceRevive.js
src/boot/store.js
src/chat/__tests__/narrowsReducer-test.js
src/config.js
src/message/__tests__/fetchActions-test.js
src/message/fetchActions.js
src/pm-conversations/__tests__/pmConversationsModel-test.js
src/pm-conversations/__tests__/pmConversationsSelectors-test.js
src/pm-conversations/pmConversationsModel.js
src/pm-conversations/pmConversationsSelectors.js
src/reduxTypes.js
src/utils/recipient.js

This fixes #3133 -- making a lot more PM conversations visible on the "PM conversations" screen -- by using the nice `recent_private_conversations` data structure that the server introduced in version 2.1, precisely in order to support fixing #3133.
This PR replaces #3535, and #4104 which was partly based on a rebase of #3535. There's one commit in here which derives from those two PRs; but upon rebasing #4104 and studying it, I decided it'd be better to take a different approach for most of what it needs to do.
Most fundamentally: instead of maintaining the data in the exact same format as it came over the wire as JSON, we arrange it on receipt into a data structure that's optimized for efficiently maintaining and using. The "store it like it came over the wire" approach is the one we …

Get and maintain a handy optimized data structure of recent PM conversations

---

src/common/FloatingActionButton.js
src/compose/ComposeBox.js
src/nav/ChatNavBar.js
src/nav/ModalNavBar.js
src/nav/ModalSearchNavBar.js
src/nav/NavBarBackButton.js
src/nav/NavButton.js
src/nav/NavButtonGeneral.js

**Why and how the change was made**
This PR proposed to add captions for visually impaired users. I added captions for buttons like back button and send button. I used React Native's accessibilityLabel prop to add captions. 
**Tests done**
I tested this app on both simulator and on the actual device, and it worked well for both the scenarios.
**Fixes #4232**

accessibility: Added captions for visually impaired users

---

tools/build-webview

On Windows (at least in Git Bash, which is our recommended way to set up the dev environment on Windows), the absolute paths end up looking like `/d/zulip-mobile/…`.  When one of those gets passed to rsync, it somehow decides to interpret it as a remote location, where the leading `/d/` means to go to a remote host called `d`.  Naturally, that doesn't work out.
To solve the problem, use relative paths.
This is made slightly tricky by the fact that the two different arguments we pass to rsync come to us in the form of paths relative to two different locations: the sources we want to copy are at particular places relative to the source tree, while the destination directory comes from the command line and is therefore relative to the current directory the script was started with.  So we …

tools/build-webview: Work in terms of relative paths.

---

src/common/UserAvatar.js
src/utils/avatar.js

See discussion at
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/302.20redirect.20for.20avatar/near/1097413.
In #4367, I'd assumed that it would be fine to include the auth
headers even when they're unnecessary. That turns out not to be
true: the s3 backend doesn't want them.
Fixes: #4401

UserAvatar: Don't send auth headers to s3 backend.

---

src/autocomplete/PeopleAutocomplete.js
src/chat/GroupDetailsScreen.js
src/pm-conversations/PmConversationList.js
src/reactions/MessageReactionList.js
src/reactions/ReactionUserList.js
src/sharing/ChooseRecipientsScreen.js
src/sharing/ShareToPm.js
src/sharing/send.js
src/users/UserItem.js
src/users/UserList.js

This is the small series of followup conversions I mentioned at #4364. Not on a critical path to our major data-refactoring priorities, but a small nice cleanup.
The branch doesn't end up eliminating the old UserItem. (Or making private, really -- the code wasn't going to be deleted in any case, because it does most of the actual work of the new UserItem, which just wraps it with `connect`.) That's because it turns out that in one place, the autocomplete suggestions, we actually make use of the ability to supply fake synthetic users that don't exist in the users data.
That's likely not the best way that could work, at either a UI level or a code level. But doing anything about that would be a bigger project than this series otherwise is, and doesn't seem like it has a big payoff compared …

user: Convert to UserItemById from whole-User-taking UserItem

---

src/actionTypes.js
src/animation/AnimatedRotateComponent.js
src/boot/TranslationProvider.js
src/common/SlideAnimationView.js
src/message/messagesReducer.js
src/notification/__tests__/notification-test.js
src/start/RealmScreen.js

On #4245, the issue for upgrading to React Native v0.63, I [said](https://github.com/zulip/zulip-mobile/issues/4245#issuecomment-753239808):
> Much of the work has already been done, but the new Flow version that we'll take along with it has lots of issues with our use of react-navigation, so I've been hoping to finish #4296 (for which #4300 is open) before taking up the RN upgrade again.
Well, #4296 has been resolved! As we'd hoped, the new Flow version (0.122.0) doesn't complain about anything that has to do with react-navigation anymore, which brings us closer to being able to take the Flow version along with RN v0.63.
This branch whittles down the new Flow version's output to the single warning below, with the helpful comment that we can remove a $FlowFixMe along with the upgrade.
``` …
```

Anticipate and fix a few Flow errors we'd get with RN v0.63 and Flow 0.122.

---

src/common/UserAvatarWithPresence.js
src/events/eventToAction.js
src/title/TitlePrivate.js
src/users/UserItem.js
src/users/userSelectors.js

Along the way, add `tryGetUserForId` as a non-throwing variant of `getUserForId`, and use it in a couple of existing spots where we already do something equivalent.
Fixes: #4422

autocomplete: Fix crash in showing avatar for pseudo-users

---

src/sharing/ShareToPm.js
src/users/UserItem.js

This is a quick followup to #4424, to make the cleanups discussed at https://github.com/zulip/zulip-mobile/pull/4424#discussion_r562757466 .

UserItem: Clean up onPress logic a bit

---

src/chat/narrowsReducer.js
src/message/__tests__/messagesReducer-test.js
src/message/messagesReducer.js

Discovered while working on #4390, which was recently merged.
-----
messagesReducer: Address a performance TODO for EVENT_NEW_MESSAGE.
Using the recently added `getNarrowsForMessage`.
And leave bidirectional comments with narrowsReducer so that we
never end up with messages in `state.narrows` that don't exist in
`state.messages`.

messagesReducer: Address a performance TODO for EVENT_NEW_MESSAGE.

---

.eslintignore
src/__flow-tests__/README.md
src/__flow-tests__/nav-test.js
src/react-navigation.js
src/sharing/ShareToPm.js
src/sharing/ShareToStream.js
src/sharing/SharingScreen.js

This is a followup to #4393, which I discussed doing [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/React.20Navigation.20v5.3A.20param.20types/near/1057943), while that was in draft state, and was later discussed again [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/React.20Navigation.20v5.3A.20Planned.20follow-up/near/1098326) after it landed.
The type of `props.route.params` is very much like the type of a React component's `props` itself: it's part of the definition of the component's interface, and the most natural place for it to live is next to the definition of the component.
With React Navigation upstream's guide for using type-checking:
https://reactnavigation.org/docs/typescript/
(of which I'm looking at the 5.x version; sadly those docs …

nav types: Add and demo RouteProp, to keep route-param types next to props

---

src/message/messagesActions.js
src/notification/__tests__/notification-test.js
src/notification/index.js
src/notification/notificationActions.js
src/pm-conversations/pmConversationsSelectors.js
src/utils/__tests__/internalLinks-test.js
src/utils/__tests__/recipient-test.js
src/utils/internalLinks.js
src/utils/recipient.js

We've had recently a couple of warnings regularly showing up when
running tests.  Generally we should keep our test suite clean of
warning spew, partly to keep our own development experience good
and partly to help us notice new warnings so we can investigate,
in case they're telling us about potential new bugs in the app.
This PR fixes them, by converting a bit more of our code to handle
users purely by ID.  I ended up writing a surprisingly long commit message
for one of these commits, so I'll copy it here just lightly edited:
---
The two warnings are very similar; here's one of them:
```
PASS  src/notification/__tests__/notification-test.js
● Console
console.warn
pmKeyRecipientsFromIds: missing data on user
125 |
126 |     if (config.enableErrorConsoleLogging) {
> 127 | …
```

user: Convert more code to IDs-only, fixing warning-spew in tests

---

src/ZulipMobile.js
src/__flow-tests__/types-test.js
src/api/__tests__/queueMarkAsRead-test.js
src/api/uploadFile.js
src/autocomplete/PeopleAutocomplete.js
src/boot/__tests__/reducers-test.js
src/boot/replaceRevive.js
src/boot/store.js
src/chat/flagsReducer.js
src/compose/ComposeBox.js
src/compose/ComposeMenu.js
src/compose/MentionWarnings.js
src/emoji/Emoji.js
src/events/doEventActionSideEffects.js
src/message/__tests__/messageActions-test.js
src/message/__tests__/messagesReducer-test.js
src/notification/__tests__/notification-test.js
src/notification/index.js
src/pm-conversations/pmConversationsSelectors.js
src/presence/presenceReducer.js
src/redux-persist-migrate/index.js
src/unread/UnreadCards.js
src/users/UserList.js
src/utils/__tests__/internalLinks-test.js
src/utils/avatar.js
src/webview/MessageList.js
src/webview/html/template.js
src/webview/js/js.js

When we start using Flow v0.137+, along with React Native v0.64
(that's issue #4426), we'll be asked to specify what rule(s) we're
suppressing with each suppression comment. Conveniently, the
warnings will tell us the applicable rule(s) we need to write down.
So, having peeked ahead at the warnings seen in the RN 0.64.0-rc.2 
world, get a head start on doing so. There will probably be more of
these (we haven't yet started enforcing the requirement now, so some
unmarked `$FlowFixMe`s will naturally accumulate), but we might as
well get this chunk out of the way.

flow [nfc]: Mark specific rules that are being suppressed.

---

src/chat/ChatScreen.js
src/common/ZulipStatusBar.js
src/lightbox/Lightbox.js
src/lightbox/LightboxScreen.js
src/nav/ChatNavBar.js
src/nav/ModalNavBar.js
src/nav/ModalSearchNavBar.js
src/start/LoadingScreen.js
src/title/__tests__/titleSelectors-test.js
src/title/titleSelectors.js

This is the second PR in the series that began with #4428.
It converts some more components to Hooks-based components, to prepare for future work, and it also makes some preparatory changes to `ZulipStatusBar`, which I'd like to focus on in the next PR in this series. (`ZulipStatusBar`, I've found, isn't the best place to put logic that handles the safe-area view at the top; that PR will relocate that logic.)
I found that I could reasonably include a fix for #4267 in this PR, to help it land sooner. The status bar still appears in the lightbox after this PR, despite passing `hidden` to the lightbox's `ZulipStatusBar`. I'll get to the bottom of that, later, but it's orthogonal to what's really needed for fixing #4267:
1. having the lightbox header clear the unsafe area at the top (which …

Clean up navigation logic (2/x).

---

src/boot/replaceRevive.js

This is only latent because, so far, we only use
`ImmutableMapNumKeys` for `state.messages`. Greg confirms that it
would be very surprising if a message could have an ID of zero [1].
[1] https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/replaceRevive.20bug/near/1112480

replaceRevive [nfc]: Fix a latent bug caused by a sketchy null check.

---

src/title/TitlePrivate.js

**Changes done**
I specified a width of 250 for the Text component in ```TitlePrivate```. This width will make sure that the truncated part (ellipsis "...")  doesn't overlap with the InfoButton of the app bar.
**Before**
**After**
Fixes: #4469

Handle the "Overlap" part of the user name in the app bar

---

src/compose/MentionWarnings.js

**What was the error?**
The **unformattedMessage** in **getUserFromMention** was giving undefined which was the cause of the crash.
**How I solved this issue?**
Since on mentioning the **group** in the ComposeBox was providing the same error. I used a constant called **splittedMessage** which splits the string through "*". This computation can provide me an array of length either 3 or 5. Thus, according to the size, I specified which index's value is further needed in the code. Hence, the bug was solved. 
**Before**
**After changes**
No error
Fixes: #4460

crash: Fix crash in getUserFromMention as unformattedMessage gives undefined.

---

src/ZulipMobile.js
src/account/accountActions.js
src/common/FullScreenLoading.js
src/main/MainTabsScreen.js
src/message/fetchActions.js
src/nav/AppNavigator.js
src/nav/__tests__/navSelectors-test.js
src/nav/getInitialRouteInfo.js
src/nav/navActions.js

See [discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M4453.20.22Tried.20to.20use.20NavigationService.20before.20appContaine.2E.2E.2E/near/1111344).
@gnprice, feel free to make any tweaks as you see fit (or ask me to, and I will). Also, let me know if you'd like to try a different approach, of course. 🙂 
Fixes: #4453

Fix "Tried to use NavigationService before appContainerRef was set".

---

flow-typed/@sentry/react-native_v2.x.x.js
ios/Podfile.lock
package.json
src/boot/StoreProvider.js
src/redux.js
src/utils/logging.js
yarn.lock

We discovered [1] that we'd only been including the server version
tags when making a `logging.foo` call. This excludes the large
volume of Sentry events that come from uncaught exceptions.
So, set the tags on the global scope, and be sure to keep them
up-to-date by listening for changes to the server version stored in
Redux.
[1] https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M4458.3A.20.22t.2Eget.20is.20not.20a.20function.22.20on.20state.2Enarrows.20at.20sta.2E.2E.2E/near/1119488
[2] https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Custom.20tags.20for.20Sentry's.20exception.20tracking/near/1121623

StoreProvider: Set server version tags on global scope, not one-off scope.

---

src/common/ZulipStatusBar.js
src/nav/ChatNavBar.js

Color.darken() can return a color that is rounded in a way that causes
this error when used:
`StatusBar._updatePropsStack`: Color hsl(186.39999999999998, 51.9%, 70.9%) parsed to null or undefined
This seems to be because something cannot handle a color with that many
decimal points of precision. This doesn't result in a visible bug (my
guess is that it gets passed in as a string, and then the rendering
engine can handle it just fine, although I haven't validated that), but
it does create a bunch of noise in the logs, which this commit fixes.

StatusBar: Fix bug causing invalid color names

---

src/emoji/__tests__/data-test.js
src/emoji/data.js

This allows the user to use the system emoji picker to select reaction
emoji, should they prefer that to typing the emoji name.
There is some complexity around skin-tone modifiers that this commit
does not attempt to address, see the comment for details.
Fixes #3961.

emoji picker: Allow searching for literal emoji.

---

src/actionTypes.js
src/subscriptions/__tests__/subscriptionsReducer-test.js

We don't use this, and Tim reports [1] that the server would like to
get rid of it.
[1] https://chat.zulip.org/#narrow/stream/3-backend/topic/stream.20administrators/near/1124276

actionTypes: Remove `email` from `EventSubscriptionUpdateAction`.

---

.eslintrc.yaml

This fixes a problem where format-on-save had stopped working for
me, probably after updating vscode-eslint. I'd been getting this
error:
```
Error: Error while loading rule 'jest/no-deprecated-functions':
Unable to detect Jest version - please ensure jest package is
installed, or otherwise set version explicitly
Occurred while linting
/Users/chrisbobbe/dev/zulip-mobile/src/compose/ComposeMenu.js
at detectJestVersion
(/Users/chrisbobbe/dev/zulip-mobile/node_modules/eslint-plugin-jest/lib/rules/no-deprecated-functions.js:38:9)
at create
(/Users/chrisbobbe/dev/zulip-mobile/node_modules/eslint-plugin-jest/lib/rules/no-deprecated-functions.js:61:256)
[...]
```
Now I don't get that error, and format-on-save works again.
See these issues:
- jest-community/eslint-plugin-jest#686
- …

eslint: Specify Jest version in config.

---

src/account-info/AwayStatusSwitch.js
src/common/OwnAvatar.js
src/unread/UnreadCards.js

~~See discussion [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/converting.20to.20Hooks/near/1111919). The use of `connect` in these components instead of `useSelector` has been contributing to a crash.~~
(Never mind; I've got a fix for this open in #4454, where we add a `connect` in `MainTabsScreen`. Still, might as well not lose the work of Hooksifying these components, so I'll leave this PR open.)

Convert three more components to use Hooks and `useSelector`.

---

src/streams/StreamItem.js
src/streams/TopicItem.js

To simplify translating some user-facing strings. `StreamItem`, at least, will need two contexts: the theme context and the translation context. With the new Context API, a class component can't declare multiple `contextType`s. But Hooks components work just fine with two different `useContext` calls (see [example](https://reactjs.org/docs/hooks-overview.html#other-hooks)).
From [discussion](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Adding.20Accessibilty/near/1113306).

Convert `StreamItem` and `TopicItem` to use Hooks.

---

src/actionTypes.js
src/subscriptions/__tests__/subscriptionsReducer-test.js

A quick followup to #4501.
We already ignore this in favor of `stream_id`.  On the server side
we intend to stop sending it soon, because neither mobile nor
terminal is using it:
https://chat.zulip.org/#narrow/stream/3-backend/topic/stream.20administrators/near/1124277
While we're here, also reorder the remaining properties a bit to be
more logically in general-to-specific order.

api types: Drop `name` from subscription update events.

---

src/webview/handleOutboundEvents.js
src/webview/js/generatedEs3.js
src/webview/js/js.js

I have updated the details object to include additional 
userAgent property which returns browser version during errors.
This PR closes #4452 
In **react-native terminal**:
In **adb logcat**:
In **app**:

webview errors: Report browser version

---

docs/architecture/platform-versions.md
src/webview/js/generatedEs3.js
src/webview/js/js.js
src/webview/js/rewriteHtml.js

HTMLTimeElement is supported from 62 in chrome android.
So, I checked whether it exists or not and ended the function if it doesn't exist
as it prevents the error which has further impacts as mentioned by @gnprice 
in #4451 
This PR closes #4451

webview errors: Terminate if HTMLTimeElement is undefined

---

.gitignore
tools/generate-logos

A followup to #4476.
* Fix it so that `git status` stays clean unless something changed.
* Document explicitly how we keep the output tracked in Git.
* Switch `make_one_android_icon` to something like named parameters rather than positional, as it now has 6 of them.
(@im-adithya fyi)

Some tweaks to tools/generate-logos

---

src/utils/__tests__/internalLinks-test.js
src/utils/internalLinks.js

This commit allows for the internal links to be of the form:
https://chat.zulip.org/#narrow/stream/3/topic/send_message.20API. Previously, only internal links of the form:
https://chat.zulip.org/#narrow/stream/3-backend/topic/send_message.20API were supported. 
Fixes #4185

internal_link: allow streamID without stream name

---

src/account-info/ProfileScreen.js
static/translations/messages_en.json

On the profile pic screen when we click on `logout` button then we suddenly logged out without any confirmation message or without any `Alert` which is not that good their must be an `Alert` message before someone logged out like in other apps.
So this PR added an `Alert` message before logout so that if user mistakenly clicks on logout button then it will not suddenly logged out. Attaching a video below which shows that logout `Alert` box
https://user-images.githubusercontent.com/56453541/108977036-27db4280-76ae-11eb-84e7-7e43e03910b0.mp4
Also we can add a spinner or loader before logging out to prevent that rapid log out effect @chrisbobbe @gnprice whats your opinion about that
Fixes: #4496

Adding Alert for logout

---

src/webview/static/base.css

Currently a markdown table having long text gets cut off from the right side
instead of scrolling.
Added horizontal scrolling effect.
**ScreenShots/Media**:
https://user-images.githubusercontent.com/42652941/111325017-4e7b1080-8691-11eb-8d26-9b935eddf39a.mp4
Fixes : #4530
Signed-off-by: rajprakash00 <rajprakash1999@gmail.com>

Markdown tables: Add horizontal scrolling.

---

ios/Podfile.lock
package.json
yarn.lock

By downgrading react-native-vector-icons while we wait for oblador/react-native-vector-icons#1311 to land, as @WesleyAC suggests at https://github.com/zulip/zulip-mobile/issues/4521#issuecomment-797219057.
This PR downgrades to 7.0.0, instead of 6.4.2, following my observations at https://github.com/zulip/zulip-mobile/issues/4521#issuecomment-800448323.
I haven't seen any noticeable regressions from doing the downgrade.
One thing stands out in the changelog: a claim that 8.0.0 has better Xcode 12 compatibility. It doesn't go into detail (though I believe oblador/react-native-vector-icons#1251 is meant), and I was able to build and run for iOS with version 7.0.0 of react-native-vector-icons, in both debug and release modes, using Xcode 12.4. So possibly there was a wrong diagnosis, or …

Fix appearance of "@" icon in the home screen.

---

tools/deps

`/usr/bin/env bash` is more portable than `/bin/bash`.

tools/deps: Fix hashbang

---

src/message/__tests__/messageActionSheet-test.js
src/message/messageActionSheet.js
src/webview/handleOutboundEvents.js

This will allow us to use the shared messageActionSheet code in the
React Native parts of the codebase, rather than only the webview parts
of the codebase. It's also generally a cleaner and more type-safe
approach.
The test coverage for this seems not great, but I manually tested
clicking on most of the buttons on both styles of action sheet in the
app.

ActionSheets: Refactor to tighten up types

---

src/message/messageActionSheet.js

This deduplicates a bit of code, notably the try/catch and the alert on error.
A small followup to https://github.com/zulip/zulip-mobile/pull/4541#pullrequestreview-622564692 .

action sheets [nfc]: Factor out makeButtonCallback.

---

android/app/src/main/java/com/zulipmobile/notifications/NotificationsModule.java
src/notification/index.js
src/notification/notificationActions.js

There are further, more involved improvements we'd like to make, but this should fix an important bug amplified in v27.158 where Android hasn't been registering for push notifications. See discussion around https://chat.zulip.org/#narrow/stream/48-mobile/topic/.60remoteNotificationsRegistered.60.20listener.20too.20late/near/1147378.
I've also included a tweak to comments in `initNotifications` that I expect are orthogonal to the fix.

Fix getting Android push token on startup.

---

src/webview/static/base.css

Currently a long LaTeX equation gets cut off from the right
instead of scrolling.
So, add horizontal scrolling effect.Also take care of bug
involving vertical cut off of superscripts in same way as
zulip web https://github.com/zulip/zulip/pull/17829 .
**Screenshots/Media**:
https://user-images.githubusercontent.com/42652941/112796727-004e1000-9088-11eb-9111-8640b2b2c530.mp4
Fixes: #4017
Signed-off-by: rajprakash00 <rajprakash1999@gmail.com>

webview styles: Let LaTeX equations scroll horizontally.

---

src/__tests__/lib/exampleData.js
src/api/messages/getMessages.js
src/api/modelTypes.js
src/message/__tests__/fetchActions-test.js
src/message/messagesReducer.js

(Removed some outdated text here as our thinking proceeded.)
There's a site in the last commit where the handling for `subject` isn't great, and things get worse at that same site when I try to do `subject_links`; it seems to panic a bit (complaining about things other than `subject_links`; it's like it's forgotten some things it would otherwise know) unless I remove the code that gives `subject_links` a new value. So I'll pause on this for today and take a fresh look tomorrow (and you could give it a go if you like 🙂).
But what do you think of this general approach, @gnprice? I think it's similar to what you proposed [in CZO](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.60PmMessage.60.2C.20.60StreamMessage.60.20types.3F/near/1126689) but it doesn't use `MessageBase`; in …

Make `PmMessage` and `StreamMessage` types.

---

src/users/userSelectors.js

The one check we had would be perfectly sufficient in a world where
we used a reliable form of storage for keeping data from the server
on the device between runs of the app.  It does not suffice given
our model with redux-persist.
This doesn't fix the problem -- that will take something more
fundamental -- but it hopefully mitigates the worst consequences.
In particular, empirically we already reasonably gracefully handle
in the unreads view and the PM-conversations view a situation where
either `state.unreads` or `state.pmConversations` refers to streams,
subscriptions, or users that we don't have data about:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/Android.3A.20White.20screen/near/1151982
Fixes: #4587

user: Expand checks in getHaveServerData.

---

src/RootErrorBoundary.js
src/ZulipMobile.js

ZulipMobile: Add and use RootErrorBoundary.

---

src/RootErrorBoundary.js

RootErrorBoundary: Separate explanatory text from tappable button.
As Greg suggests as a followup to #4585 [1].
[1] https://github.com/zulip/zulip-mobile/pull/4585#issuecomment-812746788

Error-boundary followup (after #4585).

---

src/account/AccountItem.js

(A proposed followup to #4583; tagging @vaibhavs2. 🙂 See screenshots of the current layout at that PR.)
The previous position of this text looked just a little odd: to my
eye, it didn't play nicely with the vertical centering of the
trash-can icon. Now, it joins the existing left-aligned labels as
the last child of the `styles.details` View.
I'm not sure I've arrived at the best layout choice, but at least
there can be no question about vertical centering. It also makes the
code slightly easier to reason about, since it mostly fits into an
existing pattern: it's just like the existing left-aligned labels,
except it's italic instead of bold (which I like).

AccountItem: Tweak the layout of "Signed out" text.

---

ios/Podfile.lock
package.json
yarn.lock

No breaking changes are identified in the release notes:
https://github.com/react-native-cameraroll/react-native-cameraroll/tags.
Fixes: #4425

deps: Upgrade to @react-native-community/cameraroll v4.0.4.

---

android/app/src/main/java/com/zulipmobile/notifications/FCMPushNotifications.kt

This adds a setShowWhen method to set timestamps
to true as it is set to false by default.
More information can be found [here](https://developer.android.com/reference/android/app/Notification.Builder#setWhen(long))
Fixes: #4595

notifications: Add Timestamp.

---

src/pm-conversations/PmConversationsScreen.js
static/translations/messages_en.json

**Changes Proposed**
Changed the "Create Group" label to "Group PM" to avoid confusion. Also added the string in `static/translations/messages-en.json`
Discussion of this in [CZO](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/create.20group.20button/near/1153997)

PmConversationsScreen: Change "Create Group" label to "Group PM".

---

src/webview/js/generatedEs3.js
src/webview/js/js.js
src/webview/static/base.css

Previously, we marked messages as read as soon as 20px of the message
was visible. However, this is a poor experience: messages are marked as
read before the user has seen the entire message. It's also different
from what the webapp does: in the webapp, it's impossible to mark a
message as read by scrolling until the bottom is in view.
We can't just change `isVisible` to do this, since that's used in
someVisibleMessage, which is used to find a message for resetting the
scroll position - my understanding is that that assumes that if there
are any messages loaded, at least one will be visible. However, it's
possible for a single large message to be the only thing that's visible,
but we don't want to mark it as read, since the bottom hasn't come into
view yet. Hence, this commit adds a …

webview: Mark messages as read when bottom comes into view

---

src/api/modelTypes.js
src/compose/ComposeBox.js

Including a new comment on the `subject` field on our `Message` type, and fixes for some at least latent (though possibly not-super-common?) bugs.

Baby steps toward detangling `ComposeBox`.

---

src/message/messageActionSheet.js

This is the same thing that the (i) menu on the stream title currently
displays. Since we plan to remove that icon soon, allowing people to
access it here makes sense.

Add "Stream settings" to HeaderActionSheet

---

src/message/messageActionSheet.js
static/translations/messages_en.json

Followup as noted at https://github.com/zulip/zulip-mobile/pull/4612#issuecomment-815340027.
See also [discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Warn.20if.20user-facing.20strings.20untreated/near/1156609), where I mentioned briefly a way we might automate something to help us remember to do this, since it's so easy to forget (especially since the `_(...)` call isn't right there in front of you).
(I haven't included that in this PR; if it seems too complicated, we can move on to other things. I've added some code comments that might be a bit useful, possibly not.)

Translate some user-facing strings added to an action sheet.

---

src/webview/static/base.css

This adds transparency to the a tag and background-color
onpress after converting the button into a circle with
border-radius 50% so as to remove the default highlight
on tap.
Fixes: #3996

webview: Remove highlight on scroll-to-bottom.

---

src/__tests__/lib/exampleData.js
src/actionTypes.js
src/api/eventTypes.js
src/chat/__tests__/flagsReducer-test.js
src/chat/__tests__/narrowsReducer-test.js
src/chat/flagsReducer.js
src/chat/narrowsReducer.js
src/events/eventToAction.js
src/unread/__tests__/unreadHuddlesReducer-test.js
src/unread/__tests__/unreadMentionsReducer-test.js
src/unread/__tests__/unreadModel-test.js
src/unread/__tests__/unreadPmsReducer-test.js
src/unread/unreadHuddlesReducer.js
src/unread/unreadMentionsReducer.js
src/unread/unreadModel.js
src/unread/unreadPmsReducer.js

eventToAction: Use `op` on `update_message_flags` when possible.

---

src/events/eventToAction.js

Chris asked if adding this error was still a good idea:
https://github.com/zulip/zulip-mobile/pull/4581#discussion_r607315106
as most event types will get by OK in this case.  It's a bug if we
hit this case, but perhaps we'd rather learn of such a bug without
causing an event to fail that didn't have to.
After merging the PR but while writing a reply to the comment, I
realized that there's a useful middle ground: we can log an error
without actually immediately failing.

event: Log error but don't throw, if no active account at eventToAction.

---

src/utils/__tests__/avatar-test.js
src/utils/avatar.js

("More", since we fixed others in #4305.)
(cc @timabbott if you're interested; thanks for your help in the [chat thread](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M4614.20Avatars.20pixelated.20in.20user.20view/near/1156704).)
I think we can still end up with a pixelated image if we use the `/avatar/{user_id}` / `/avatar/{user_id}/medium` redirect and the image we end up with happens to be from Gravatar; I'm not aware that this endpoint forwards the default-vs.-medium size preference on to Gravatar, and there doesn't seem to be a way to pass an integer size, like we do when getting a Gravatar image directly.
But #4614 was pretty high-impact on zulipchat.com, so I'm glad to have that fixed, and to have the other, lower-impact improvement that follows in the branch, for …

Fix more avatar pixelation issues.

---

package.json

When running `yarn` with git bash on windows, it errors with `tools\postinstall' is not recognized.`
Adding ['bash' before `tools/postinstall`](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Setting.20up.20development.20environment.20for.20zulip-app/near/1102688) resolve this.
Fixes: zulip#4427

Add "bash" to `tools/postinstall`

---

src/diagnostics/TimingScreen.js
src/main/MainTabsScreen.js
src/nav/AppNavigator.js
src/withHaveServerDataGate.js

(Continuing from #4601, an earlier draft.)
As discussed:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/Android.3A.20White.20screen/near/1149960
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/converting.20to.20Hooks/near/1112199

ChatScreen: Add have-server-data gate.

---

src/unread/__tests__/unreadModel-test.js
src/unread/unreadModel.js

See commit messages, #4684, and/or [chat thread](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/syncing.20read.2Funread.20state/near/1166265).

unread: Revert "Use state.messages to optimize updating stream unreads."

---

.gitignore
android/sentry.properties
docs/howto/release.md
ios/sentry.properties
src/config.js
src/sentry.js
src/sentryConfig.js

There's a step in the process I've had for making releases which hasn't been written down in the release how-to doc, partly because it feels like kind of a silly way of doing it: I have a local branch with a commit that just fills in a couple of secrets, and I rebase it atop each release commit before building.
Here, convert one of the things that branch was doing into a more reasonable approach, and document it. And I didn't as easily find today a way to replace the other thing the branch was doing with some more reasonable approach, so for that one just document the existing local-branch solution.

sentry: Document, and partly clean up, handling Sentry in release process

---

src/emoji/__tests__/data-test.js
src/emoji/codePointMap.js

The Zulip emoji database has codepoint sequences for these emoji that
aren't actually valid emoji sequences according to the Unicode spec.
Some browsers accept the forms we've been using, but others don't.
In particular, newer Chrome versions don't, since about 2019.
We discussed fixing the server's data here in 2019:
https://chat.zulip.org/#narrow/stream/3-backend/topic/unicode.20emojis/near/758828
but never did, and then didn't come back to this.  Hopefully it
will get fixed sometime, but first let's just work around it here.
Fixes: #3517
---
Diagnosing this issue today caused me to look back at an earlier related report #3395. That one turns out to have a very similar fix, so I've just added that on to this PR:
---
emoji: Fix `:a:`, `:b:`, `:o:`, `:p:` to have emoji-style presentation. …

emoji: Fix keypad emoji, overriding broken codes from server's list.

---

src/boot/store.js

(Related: #4491)
I think the effect of not having this migration, at this point,
isn't as bad as a crash. But we should have added such a migration
in 4efdcda7a, when we removed the only mechanism (the REALM_ADD
action) by which accounts could end up with the empty string at
`.email`. There, we implicitly introduced the invariant that no
accounts would ever have an empty `.email`. Had I made this more
explicit, I might have remembered to do the migration.
Luckily, 1af58afb1 (from later in the same PR) ensured that we'd
never take an account object with an empty-string `.email` and make
it the active account. If you tapped an in-progress-account item in
the list, typed good credentials, and logged in successfully, a new
account object would get created, with non-empty `.email` (and …

migrations: Add one that should have been added in #4491.

---

src/webview/static/base.css

The webapp styles the `<h1>` through `<h6>` tags to be all the same size,
bold, and underlined. This commit makes them look similar on mobile,
instead of the goofy giant text from the default sytlesheet that we had
previously.
old
new
webapp

css: Style headings to be similar to webapp.

---

src/caughtup/caughtUpReducer.js

When we made a request for a narrow, we would overwrite the CaughtUp
state for that narrow in the other direction - i.e. if we were fetching
old messages, then we would forget that we've seen the most recent
message.
This commit fixes that by only updating each bit of the CaughtUp state
from false to true (on a fetch-messages result), and never the other
way around.

caughtUp: Fix bug that overwrote CaughtUp state.

---

src/autocomplete/PeopleAutocomplete.js
src/pm-conversations/PmConversationList.js
src/pm-conversations/PmConversationsScreen.js
src/unread/UnreadCards.js
src/users/UserList.js
src/users/__tests__/userHelpers-test.js
src/users/userHelpers.js
src/webview/MessageList.js
src/webview/generateInboundEvents.js
src/webview/html/contentHtmlFromPieceDescriptors.js
src/webview/html/messageAsHtml.js
src/webview/js/generatedEs3.js
src/webview/js/js.js
src/webview/static/base.css
static/translations/messages_en.json

The continuation of #4678. I moved the CaughtUp fix to #4698, since that's somewhat orthogonal (although this PR doesn't work terribly well without it).
All of the comments by @gnprice in #4678 should be resolved in this.

Muted users: part 2

---

tools/lib/ensure-coreutils.sh

In particular this lets it work with a default Homebrew install on
macOS ARM, which uses /opt/homebrew (hooray!) rather than their
unfortunate older choice of taking over /usr/local.
Debugging thread here:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/Error.20running.20zulip-mobile.20app/near/1158901

ensure-coreutils: Work with arbitrary Homebrew prefix.

---

src/webview/static/base.css

We don't want messages that are muted and hidden to show the user that
they are mentioned in the message.

css: Don't show mention highlight for muted messages.

---

src/account-info/AccountDetails.js

The user should know their local time, and always be "Active now", so
it's just clutter to show these.

AccountDetails: Hide local time and last active for current user.

---

src/nav/ChatNavBar.js

The BRAND_COLOR is a pretty aggressive color, that doesn't look good as
text. Instead, just use the default text color.
before:
after:

ChatNavBar: Don't use BRAND_COLOR for text.

---

ios/Podfile
ios/Podfile.lock
ios/ZulipMobile.xcodeproj/project.pbxproj

Builds are failing with Xcode 12.5, and mine auto-updated this morning; here's a fix. (And a follow-up commit that resolves an unrelated issue.)
I've marked this P0 because iOS development/testing for any purpose (e.g., code review) is halted, for me and for anyone else whose Xcode got (auto-)updated; please let me know if this is wrong. I don't think Apple lets you downgrade Xcode after upgrading?

flipper ios: Pin to some specific versions, to fix build with Xcode 12.5.

---

src/boot/store.js
src/common/Icons.js
src/common/WebLink.js
src/lightbox/LightboxActionSheet.js
src/lightbox/shareImage.js
src/message/messagesActions.js
src/reduxTypes.js
src/settings/LegalScreen.js
src/settings/SettingsScreen.js
src/settings/settingsReducer.js
src/start/AuthScreen.js
src/start/CompatibilityScreen.js
src/start/webAuth.js
src/utils/openLink.js
static/translations/messages_en.json

Open links in external browser

---

src/boot/TranslationProvider.js
src/common/TranslatedText.js
src/main/StreamTabsScreen.js
src/sharing/SharingScreen.js

As discussed around
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Warn.20if.20user-facing.20strings.20untreated/near/1156727,
this seems pretty low-risk and high-reward.
-----
Also a follow-up commit that removes some places where we were passing `defaultMessage` to a `FormattedMessage` component. Those aren't suppressing any errors; I did check that the strings there were all in messages_en.json. But our habit has been to use `Label` instead of using `FormattedMessage` directly, so, do that.

intl: Highlight in dev user-facing strings not added to messages_en.json.

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/zulipmobile/HandleSendIntent.kt
android/app/src/main/java/com/zulipmobile/MainActivity.kt
android/app/src/main/java/com/zulipmobile/sharing/SharingModule.kt
src/autocomplete/StreamAutocomplete.js
src/autocomplete/TopicAutocomplete.js
src/sharing/ShareToStream.js
src/sharing/SharingScreen.js
src/sharing/index.js
src/sharing/send.js

Fixes #117
Continuation of work done in #4196 
- Rebased #4196 resolving merge conflicts.
- Enabled share intent so that Zulip appears in Share menu in Android.
- Somewhere between the works of #4196 and the current version of the app, the version of React Navigation was changed from v2 to v5, a major upgrade happened in React Navigation from v4 -> v5, because of this sharingScreen was broken since now params needed to be explicitly passed down Tab.Screen in its initialParams prop so added that.
See more details [here](https://reactnavigation.org/docs/upgrading-from-4.x/).
- Changed file name of the file that gets uploaded/displayed in message when shared to Zulip, previous functionality just took the last element of sharedFileUrl.split('/'), sometimes this file name did not have an …

[android] share to Zulip from other apps

---

src/common/Icons.js
src/common/UserAvatar.js
src/common/UserAvatarWithPresence.js
src/users/UserItem.js

This commit shows a placeholder for the name/avatar of a muted user in the reactions list (and anywhere else that uses `UserItem`, but I think we've filtered out muted users in most of the other places `UserItem` shows up).
I've pulled in a modified version of a FontAwesome icon for this, and I'm not sure exactly what attribution is required for it — would love to hear thoughts on that.

Muted users placeholder in reactions screen

---

src/common/OfflineNotice.js

Before:
After:
-----
An offline state shouldn't be an error / failure state. The app's
capabilities will be reduced, so the user needs to be informed --
but it's not quite right to use a color that conveys that something
unhandled or unexpected has happened.
And switch to the theme-appropriate text color so it shows up in
light mode.

OfflineNotice: Use gray background instead of red, to be less jarring.

---

tools/postinstall

This takes several seconds each time I run `yarn`.

postinstall: Don't run `pod install` unless it's necessary.

---

src/unread/__tests__/unreadHuddlesReducer-test.js
src/unread/__tests__/unreadMentionsReducer-test.js
src/unread/__tests__/unreadModel-test.js
src/unread/__tests__/unreadPmsReducer-test.js
src/unread/unreadHuddlesReducer.js
src/unread/unreadMentionsReducer.js
src/unread/unreadModel.js
src/unread/unreadPmsReducer.js

Previously, the main (only?) case where we wouldn't add a message to
unreads was if we were the one who sent it. This check was not correct -
instead, we want to check to see if the message has the "read" flag,
which is set by the server.
In the past, these checks were very close to the same (with the
exception of "Notification Bot" announcing a stream that you created,
which would be "read" for you), but with the addition of muted users,
the check is now incorrect.
This commit removes the logic to not mark a message as read when we are
the one who sent it, and instead just looks at the server flag, since
that should be the canonical place for that information to be.

unreads: Don't add messages with "read" flag to unreads.

---

jest.config.js
jest/presetAndroid.js
jest/presetIos.js
jest/restorePromise.js
jest/savePromise.js
src/message/__tests__/fetchActions-test.js
src/message/fetchActions.js

This supersedes the first part of #4193, which has grown unwieldy. I'm hoping this smaller PR will be easier to review, and then I'll follow it up with another PR (EDIT: #4754) to finish the work of #4193. 🙂
Related: #4165

Prep for timing out the initial fetch.

---

ios/ZulipMobile/AppDelegate.m

This is the result of searching #3116 for (1) clearly useful things that (2) haven't grown stale.
It's possible that we may have more to do before we start using Swift in our iOS code, but we should probably address that closer to the point where it becomes necessary, to avoid the risk of writing something that'll just go stale and need to be changed in the future.

Modernize / strip dead code (a little bit) from AppDelegate.m.

---

android/app/src/main/AndroidManifest.xml

Fixes: #4722
All of the relevant documentation is given in https://developer.android.com/guide/topics/manifest/uses-feature-element, it explains how play store filtering works and what a developer can do to control that.
gist is explained in the commit message of https://github.com/zulip/zulip-mobile/commit/199b73b6a72fe4f3c74fdba6e5a305bea13b67c1 of this PR.
> Google Play filters which app to display to a user based on `uses-sdk`,
`uses-permission` and `uses-feature` tags.
> In case `uses-feature` is not declared `uses-permission` is used to do
this filtering, and by default it treats the permission it needs as a
compulsory requirement for the app. Hence our app will not show in play
store for devices without the hardware of concern.
> With `uses-feature` we override the filtering done …

Fix bug in AndroidManifest that prevented play store from displaying Zulip to certain user as an installable app.

---

src/__tests__/lib/exampleData.js
src/chat/__tests__/flagsReducer-test.js
src/chat/__tests__/narrowsReducer-test.js
src/chat/flagsReducer.js
src/message/__tests__/messagesReducer-test.js
src/outbox/__tests__/outboxReducer-test.js
src/pm-conversations/__tests__/pmConversationsModel-test.js
src/topics/__tests__/topicsSelectors-test.js
src/unread/__tests__/unread-testlib.js
src/unread/__tests__/unreadHuddlesReducer-test.js
src/unread/__tests__/unreadMentionsReducer-test.js
src/unread/__tests__/unreadModel-test.js
src/unread/__tests__/unreadPmsReducer-test.js
src/unread/__tests__/unreadSelectors-test.js
src/unread/unreadHuddlesReducer.js
src/unread/unreadMentionsReducer.js
src/unread/unreadModel.js
src/unread/unreadPmsReducer.js

This follows up on the thread at https://github.com/zulip/zulip-mobile/pull/4710#discussion_r626113834.
We replace the "action fragments" idea with more-flexible factory functions. In particular all the places in test code where we used `eg.eventNewMessageActionBase` to create an `EVENT_NEW_MESSAGE` action now make a call to the new `eg.mkActionEventNewMessage` which subsumes it -- and unlike the old fragment, the new factory can ensure that `action.message.flags` is always present, as it should be.
Then that in turn lets us clean up some app code, in reducers, that had provided bogus default behavior in case of a missing `flags` in order to accommodate tests that didn't supply one.

example data: Better support EVENT_NEW_MESSAGE.

---

android/app/src/main/AndroidManifest.xml

Usage of `@react-native-community/netinfo` adds the permission
requirement for ACCESS_WIFI_STATE in the final AndroidManifest of
the app, which makes wifi hardware a compulsory requirement to
install the app.
Adding an appropriate `uses-feature` tag makes this requirement
optional.
This was discovered by looking into "Merged Manifest" option while
previewing `AndroidManifest.xml` in Android Studio.
Follow up to: #4724 as suggested by @gnprice.

[android] Make wifi hardware requirement optional. (follow up to #4724)

---

android/app/src/main/java/com/zulipmobile/notifications/NotificationsModule.java
src/notification/index.js

Quoting from commit of this PR:
> It is speculated that when an app quits android system does not
flush the entire memory of the app until absolutely necessary
(to facilitate faster startup next time). This also involves the
static variable `initialNotification`.
> This situation creates a problem when the app is started next time,
where it processes `initialNotification` again and falsely navigates
to its narrow.
Fixes: #4758

Make `getInitialNotification` a consumer.

---

src/common/UserAvatar.js

ed69e1ec0 inadvertently removed this when we switched away from
ImageBackground, but it seems like something that we should include,
since avatars will look better non-inverted, and inverting arbitrary
images isn't likely to be very useful for contrast/accessibility
reasons.
Fixes: #4765

UserAvatar: Ignore color inversion on iOS.

---

src/compose/ComposeMenu.js

It wasn't clear what this did, it's not like any of the other options in
the menu, and it's simpler to get to via the PMs tab.

ComposeMenu: Remove "create group PM" option.

---

.github/dependabot.yml
src/__flow-tests__/nav-test.js
src/unread/unreadModelTypes.js

Currently, dependabot will automatically open PRs to address
reported security vulnerabilities in packages. I'm interested to see
if it can help us be better about keeping our packages up-to-date in
general.
There are plenty of config options we can choose from (see the
linked doc). For now, I'm just curious to see what it does with this
simple config.

dependabot: Add config file.

---

package.json

We added it in 5b6014e83 to silence a peer-dep warning that
react-intl hasn't been throwing for a while:
https://github.com/formatjs/formatjs/issues/1382
Note that react-intl's package.json doesn't have prop-types in its
peerDependencies anymore:
https://github.com/formatjs/formatjs/blob/react-intl%405.8.6/packages/react-intl/package.json#L144-L147
The package is for runtime checking for React props; we don't need
it because we use Flow:
https://www.npmjs.com/package/prop-types

deps: Remove prop-types from devDependencies.

---

src/common/Icons.js
src/common/OptionRow.js
src/common/ServerCompatBanner.js
src/message/messagesActions.js
src/reduxTypes.js
src/settings/SettingsScreen.js
src/utils/openLink.js

Followups from #4679

---

src/actionTypes.js
src/boot/store.js
src/chat/narrowsSelectors.js
src/generics.js
src/message/NotSubscribed.js
src/notification/index.js
src/redux-persist-migrate/index.js
src/session/sessionReducer.js

This addresses the portion of #3452 (which we should do before the RN v0.64 upgrade, #4426) in our own code, while leaving 36 sites in the libdefs, to be treated in another PR.
Done by temporarily adding `implicit-inexact-object=warn` to our .flowconfig and fixing all the warnings it flags, as Greg recommends in https://github.com/zulip/zulip-mobile/issues/3452#issuecomment-657778760.
My focus has been to satisfy the lint rule kind of quickly, using exact (over explicitly inexact) when it's convenient and obviously correct. It's quite possible that more of these could have been made exact—but I don't expect this to cause any type-checking regressions, as explicitly inexact is equivalent to implicitly inexact to the type-checker.
Please give special attention to the last two commits—the …

Flow-related work on the path to RN v0.64 upgrade, part 2.

---

src/account/accountsReducer.js

These are some small tweaks in the handy new `restart`-event implementation added in #4707.

accountsReducer [nfc]: Followups on handling restart events

---

ios/Podfile.lock
yarn.lock

Notably, this includes an update to Sentry's SDK for React Native
that came out after the last `yarn upgrade` commit, in #4789, was
authored.
I got an error --
```
[!] CocoaPods could not find compatible versions for pod "Sentry":
In snapshot (Podfile.lock):
Sentry (= 6.1.4)
In Podfile:
RNSentry (from `../node_modules/@sentry/react-native`) was resolved to 2.5.0, which depends on
Sentry (= 7.0.0)
You have either:
* out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
* changed the constraints of dependency `Sentry` inside your development pod `RNSentry`.
You should run `pod update Sentry` to apply changes you've made.
```
-- so I ran `pod update Sentry`, and it went through. After that, I
ran `yarn` (with `pod install` getting run in …

deps: Run `yarn upgrade`.

---

src/common/RawLabel.js

This was causing a crash when trying to autocomplete a user group with a
blank name. The empty string was passed into RawLabel, which caused this
invariant to incorrectly trigger.
Instead of using `!!` to check for undefined, we can do `!= null`, which
will trigger for undefined and null, but not an empty string.
If you want to trigger this on CZO, just type `@test` into the composebox :)

RawLabel: Fix crash when text is empty string.

---

src/streams/TopicItem.js

nitpick
It was listed as
```javascript
onPress: (topic: string, stream: string) => void,
```
it Should be 
```javascript
onPress: (stream: string, topic: string) => void,
```

[nitpick] Fix parameter order for `onPress`.

---

src/streams/StreamCard.js
src/streams/StreamIcon.js
src/streams/StreamItem.js
src/title/TitleStream.js

These follow up on https://github.com/zulip/zulip-mobile/pull/4718#pullrequestreview-683615309 .
---
StreamIcon [nfc]: Revert "Don't show as muted when unsubscribed."
This reverts commit 532ff81e8.
Before that commit, it was already the case that we don't show the
"muted" icon when not subscribed to a stream:
* In `TitleStream` (the title in the app bar on a stream narrow),
this is arranged by `getStreamInNarrow`.
* In `StreamCard` (used by `StreamSettingsScreen`, this is arranged
by the following line in the `<StreamIcon … />` call:
isMuted={subscription ? !subscription.in_home_view : false}
* The remaining callers don't show streams that we aren't subscribed to.
Of those, the `StreamCard` logic hadn't been working until recently;
in 9dd501406 we introduced the regrettable …

Followups on stream settings #4718

---

src/webview/MessageList.js
src/webview/js/generatedEs3.js
src/webview/js/js.js

This is a performance optimization which according to my measurements
reduces the average load time from 487ms to 429ms, on the following
device:
* Pixel 3a
* Android 11
* Chrome 91.0.4472.101
* Release mode
Where load time was determined by calling `performance.now()` in
`componentDidMount` and again in `handleMessage` when the first ready
event is received, and comparing the results. The numbers above are an
average from 25 different runs. The standard deviation was also reduced,
from 58ms to 35ms.
This should still be as safe as it was before, since we still require a
roundtrip before exchanging any data, we just start that roundtrip in a
different place.
Starting the handshake from the webview does subtly change the
properties of the system, but not in a way that should cause any …

webview: Initiate 'ready' handshake from WebView.

---

src/chat/ChatScreen.js
src/message/messageSelectors.js
src/react-native-action-sheet.js
src/search/SearchMessagesCard.js
src/webview/MessageList.js

By adding a type-wrapper for `connectActionSheet`, and annotating the export of MessageList.js with `ComponentType<OuterProps>`, as @gnprice mentioned in [a recent discussion of Flow and `connect`](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Flow.20and.20.60connect.60/near/1098230).
I've removed the kind of hacky cases where we use the same name for an "outer" prop as we use for a prop that `connect` provides. Let me know if you see a better way to do this, and in particular, if you don't like the changes to `MessageList`'s interface. 🙂 
Also, in this one—
MessageList [nfc]: Remove htmlPieceDescriptorsForShownMessages prop (3/x).
—there's a potential performance regression, where we stop using a caching selector. After I'd removed that, it occurred to me that some of the …

Start type checking `MessageList`'s props.

---

src/notification/extract.js
src/notification/index.js

This is a small followup refactor after #4163.
---
We have this somewhat fiddly logic twice; better to have it
(and explain it) just once.

notif ios [nfc]: Factor out fromPushNotificationIOS.

---

src/topics/topicSelectors.js
src/unread/unreadModel.js
src/unread/unreadSelectors.js

This is a quick refactoring inspired by https://github.com/zulip/zulip-mobile/pull/4635#discussion_r652981999 .
There's a number of useful things we could do further in this direction, but stopping here for now in order to get this out.

unread [nfc]: Add `getUnreadCountForTopic`

---

src/common/CountOverlay.js
src/common/FullScreenLoading.js
src/common/LoadingBanner.js
src/common/ZulipTextButton.js
src/notification/notificationActions.js

A bug somewhere in our stack -- presumably Metro or one of its
dependencies -- means that in src/notification/notificationActions.js
the import from `.` was getting resolved not to the module built from
its neighboring `index.js` file, as it should… but to the module
corresponding to the directory `src/common/`.
That also happens to be the directory where our only other imports
from `.` are found.  Seems like the bug may involve the resolution
of `.` being inappropriately shared globally.
In any case, the bug goes away when we make the import reference a
little less special-looking, as `./`.
Thread: https://chat.zulip.org/#narrow/stream/48-mobile/topic/Notification.20Crash/near/1215247
Fixes: #4818

import: Work around broken imports of '.'.

---

src/api/queueMarkAsRead.js

This debouncing doesn't buy us a lot (the webapp doesn't do anything
equivalent, from looking at the network tab as I mark messages as read),
and we have a strong reason not to make this take too long - our unread
messages banner is based on when we get the flag updates back from the
server, so the sooner we send them, the more responsive it will be.
We added this debouncing in 70295bd in order to fix #374, which wasn't
solving a particularly active problem - it was in order to avoid
possible API rate limits. The default rate limit for the server is 200
requests per minute [1], which works out to a request every 300 ms.
Given that, doing a request every 500ms should give us plenty of
breathing room to also request messages/etc, even in the unlikely case
that someone is pretty continuously …

queueMarkAsRead: Reduce debouncing time to 500ms.

---

jest.config.js
jest/globalSetup.js
src/__tests__/lib/exampleData.js
src/message/__tests__/getHtmlPieceDescriptors-test.js
src/message/__tests__/messageActionSheet-test.js
src/message/getHtmlPieceDescriptors.js
src/types.js
src/utils/__tests__/date-test.js
src/utils/date.js
src/webview/MessageList.js
src/webview/__tests__/generateInboundEvents-test.js
src/webview/html/__tests__/__snapshots__/contentHtmlFromPieceDescriptors-test.js.snap.android
src/webview/html/__tests__/__snapshots__/contentHtmlFromPieceDescriptors-test.js.snap.ios
src/webview/html/__tests__/contentHtmlFromPieceDescriptors-test.js
src/webview/html/contentHtmlFromPieceDescriptors.js
src/webview/html/messageHeaderAsHtml.js

EDIT: See https://github.com/zulip/zulip-mobile/pull/4670#issuecomment-821586117 where I mention the cause of the CI failures.
-----
A continued resumption of #3913 (which has grown stale), toward #3851. Part 1 was #4406 .
This PR focuses on the refactor to flatten the funny shape of `HtmlPieceDescriptor[]`, and it has tests specifically aimed at confirming the refactor.
Those tests are snapshot tests, something I think it could be neat to explore. I'd like to know if there's a better file I can put them in (I've made a `contentHtmlFromPieceDescriptors-test.js` and put them there); they test how `getHtmlPieceDescriptors` and `contentHtmlFromPieceDescriptors` work together, not separately. But I don't think I run on enough caffeine to work with a filename that concatenates those names 🤔.

Clarify some message-list code (part 2).

---

src/api/__tests__/queueMarkAsRead-test.js
src/api/queueMarkAsRead.js
src/webview/handleOutboundEvents.js

This should fix the following errors, which I see not infrequently in
the console and in Sentry:
```
{
"httpStatus": 400,
"json": {
"code": "BAD_REQUEST",
"msg": "Invalid message(s)",
"result": "error"
},
"params": {
"body": "messages=%5B%5D&flag=read&op=add",
"method": "post"
},
"route": "messages/flags"
}
```

queueMarkAsRead: Don't do anything when array is empty.

---

src/webview/js/InboundEventLogger.js
src/webview/js/generatedEs3.js

`inboundEventItems[].scrubbedEvent` is getting reduced to
`[Object]`, which is accidental and unhelpful. The data should
already be scrubbed of sensitive information, so, send it in a way
that lets us read it.
See discussion at
https://chat.zulip.org/#narrow/stream/176-mobile-core/topic/.22Webview.20warning.22/near/1216411.

InboundEventLogger: JSON.stringify inbound event items.

---

src/webview/MessageList.js

This error wasn't something we expected to actually happen, but because
we set the threshold far too low, it's actually our most common error.
Given that we just changed the webview setup code in a way that we
expect to make this error more impossible than we previously thought, we
might as well just get rid of it and save ourselves the noise in Sentry.

webview: Remove "Possible infinite loop" error.

---

src/main/MainTabsScreen.js

This prevents the delay when loading a tab for the first time after app
open, which can often be significant.

MainTabsScreen: Turn off lazy loading.

---

static/translations/messages_en.json

This string appears in `src/chat/FetchError.js`.

i18n: Tag "Oops! Something went wrong." for translation.

---

src/account/AccountPickScreen.js
src/account/accountsSelectors.js
src/nav/AppNavigator.js
src/session/sessionReducer.js

An instance of #4837.
(The use of `navigation.canGoBack()` in the last commit in the branch is an independent, unrelated cleanup.)

AccountPickScreen [nfc]: Use `useSelector` instead of `connect`.

---

src/__tests__/lib/exampleData.js
src/message/__tests__/messageActionSheet-test.js
src/message/messageActionSheet.js
src/streams/TopicItem.js
src/subscriptions/subscriptionSelectors.js
src/title/TitleStream.js
src/topics/TopicList.js
src/topics/topicActions.js
src/unread/UnreadCards.js
src/webview/MessageList.js
src/webview/handleOutboundEvents.js
static/translations/messages_en.json

- Renamed `HeaderActionSheet` to `TopicActionSheet`
- Added **mark as read** option in the `TopicActionSheet`
- Wrote test cases to ensure it's visible only when the topic is not actually read.
- Modified `TopicActionSheet` code to use stream_id instead of stream names, refactored test cases and function calls to `showTopicActionSheet` accordingly.
This PR is an alternative to #4194 for marking topics as read.
For more context: https://chat.zulip.org/#narrow/stream/48-mobile/topic/mark.20as.20read
Related: #3918
Related: #3175
Fixes: #3244

Add mark as read option in TopicActionSheet and Modify TopicActionSheet to use `stream_id`.

---

src/directSelectors.js
src/reduxTypes.js
src/webview/__tests__/generateInboundEvents-test.js
src/webview/generateInboundEvents.js

I've played around with this and inspected the code, and I haven't found any obvious issues yet.
Related: #3851

generateInboundEvents: Remove early return on sending a 'content' event.

---

src/notification/index.js

We had a steady stream of errors in Sentry caused by differences between
the `known_urls` and `realm_uri`, where one of those had an extra `/` on
the end (or some more surprising junk, such as a `/join/` link). Since
we don't support running Zulip on a non-root path [1], we can simply
compare the domain instead of the href. This is probably more of a
band-aid than a real fix (we should figure out how the strange values
get into `known_urls` and fix that), but we might as well just check the
domain, since the path doesn't matter.
Related: #4309.
[1] https://chat.zulip.org/#narrow/stream/3-backend/topic/support.20for.20running.20on.20non-webroot.20url.3F

notifications: Match on realm domain, not href.

---

android/app/src/main/res/values/styles.xml

We need to test on Android 10 and record any changes; the linked doc says the dark theme is available in Android 10 (API level 29) and higher. I've tested on the office Android device, a Samsung Galaxy S9, but it's running Android 9 and I'm not sure it's time to upgrade it yet (I'm not sure if we can go back to Android 9 after doing so).
I found no visible changes in the app on Android 9 when switching the system-level dark theme setting on and off. I'm not sure how I was able to switch that setting on and off when the doc says that the Dark theme is available starting in Android 10. Anyway, best to test on Android 10.
@AkashDhiman, would you be interested in testing on a device running Android 10?
Related: #4426 
Related: #4009

android: styles.xml change for dark theme, on the path to RN v0.64 upgrade.

---

src/lightbox/download.js

Done in `downloadFileToCache`, the object passed to
`RNFetchBlob.config` contained some meaningless properties.
These property are technically the sub properties of the property
`addAndroidDownloads`. But we would want to remove them instead of
adding them there since these essentially configure the android
download manager to download the file, which we do not want in case
of this function.
Normally rnfb will use its internal implementation for downloading
based on the `OkHttp` android library.
Originally reported [here](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Sharing.20from.20lightbox.20broken.20on.20Android/near/1223148)

lightbox [nfc]: Remove meaningless properties in rnfb config.

---

flow-typed/@sentry/react-native_v2.x.x.js
src/utils/logging.js

captureException takes an Error object, and captureMessage takes a
string. It makes sense to use captureException when we have an
Error, then, and captureMessage when we have a string -- instead of
coercing both into a string and synthesizing a stack trace to
attach.
Greg said, about the comment "the static API's `captureException`
doesn't allow passing strings",
> [...] I think the idea of that comment is that we want to pass an
> `Error` when we have an `Error`, and just a string when we have
> just a string.
>
> And then implicitly it's looking for one method to use in both
> cases. Neither of those works, so they were both rejected.
>
> But the conditional seems like a fine solution to that problem.

logging: Use Sentry's captureMessage and captureException in logToSentry.

---

package.json
src/api/index.js
src/api/modelTypes.js
src/api/submessages/sendSubmessage.js
src/webview/css/cssNight.js
src/webview/handleOutboundEvents.js
src/webview/html/messageAsHtml.js
src/webview/js/generatedEs3.js
src/webview/js/js.js
src/webview/static/base.css
yarn.lock

This PR adds basic support for viewing and voting on polls.
Some notes:
* It's pretty ugly, largely because the underlying widget/submessage/polls code is ugly. I'm open to changing things where it's easy, but I don't want to go down the rabbit hole of cleaning up the fundamental way that polls work.
* I've implemented local echo, although I don't know how I feel about it — if the `sendSubmessage` fails, we wouldn't communicate that to the user. Happy to have thoughts on what the right approach is here. One thought is that maybe we want to change the background color, but not the number? That would be pretty ugly, but could communicate what's going on without building a bunch more UI. We could also add a loading spinner like we do on outbox messages.
* I have a `$FlowFixMe` for adding …

Add basic support for polls (viewing and voting)

---

src/sharing/SharingScreen.js

A followup to #4876; see https://github.com/zulip/zulip-mobile/pull/4876#discussion_r665058192.

SharingScreen [nfc]: Use `getHasAuth` instead of `tryGetAuth`.

---

src/lightbox/download.js

This is not required as 'path' with `CacheDir` fulfills the same
purpose as `fileCache`.
The difference is 'path' gives specific path to the file while
`fileCache` gives a randomly generated path (including the
filename and its extension). See [1].
We would want to preserve the filename and its extension while
sharing from lightbox and hence `path` is used instead of
`fileCache`.
Originally reported at [2] by Greg.
reference:
[1] https://github.com/joltup/rn-fetch-blob#download-to-storage-directly
[2] https://chat.zulip.org/#narrow/stream/48-mobile/topic/Sharing.20from.20lightbox.20broken.20on.20Android/near/1226489
**tested to verify that this is nfc.**

lightbox [nfc]: Remove `fileCache` property from rnfb config.

---

src/__tests__/lib/exampleData.js
src/boot/store.js
src/reduxTypes.js
src/session/__tests__/sessionReducer-test.js
src/session/sessionReducer.js
src/settings/DebugScreen.js
src/settings/SettingsScreen.js
src/settings/settingsReducer.js
src/types.js
src/webview/MessageList.js
src/webview/handleOutboundEvents.js
src/webview/html/html.js
src/webview/js/generatedEs3.js
src/webview/js/js.js
src/webview/js/script.js

Done by first passing `doNotMarkAsRead` information to webview then
migrating `doNotMarkAsRead` from debug setting to general setting.
Fixes: #4849
Fixes: #4850

Fix do not mark as read, and make it more visible

---

flow-typed/react-intl_vx.x.x.js
flow-typed/react-native-safe-area-context_vx.x.x.js
src/RootErrorBoundary.js
src/__flow-tests__/nav-test.js
src/boot/TranslationProvider.js
src/boot/__tests__/ZulipAsyncStorage-test.js
src/boot/reducers.js
src/events/__tests__/eventToAction-test.js
src/presence/presenceReducer.js
src/session/sessionReducer.js
src/utils/objectEntries.js
src/webview/html/template.js

Parts 1, 2, and 3 were #4518, #4520, and #4836.
This doesn't upgrade Flow at all or add any new config; it's just cleaning up some stuff that I noticed (one commit is another round like #4433, for example). These kinds of small messes could easily creep back in before we add config to prevent them for good, but might as well sweep things up as we see them.
After this, the work I see before the RN v0.64 upgrade (#4426) is:
- Types-first (as noted in the issue, we can probably do some selective suppressions there for now, but I'm not sure that'll hold in future Flow versions)
- Turning on `exact_by_default`
- (Maybe an issue with react-intl's libdef; see [discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/react-intl.20libdef/near/1228275))
For `exact_by_default`, I …

Flow-related work on the path to RN v0.64 upgrade, part 4.

---

src/search/SearchMessagesCard.js

SearchMessagesCard: Open to latest message in results, not earliest.

---

flow-typed/@react-native-community/async-storage_v1.x.x.js
src/boot/ZulipAsyncStorage.js
src/boot/__tests__/ZulipAsyncStorage-test.js
src/boot/store.js
src/reduxTypes.js
src/third/redux-persist/autoRehydrate.js
src/third/redux-persist/createPersistor.js
src/third/redux-persist/getStoredState.js
src/third/redux-persist/index.js.flow
src/third/redux-persist/persistStore.js
src/third/redux-persist/purgeStoredState.js

Prep work before new revision for #4694.

---

static/translations/messages_en.json

I got the following error when I ran `tools/tx-sync`:
```
Step 3: Upload strings to translate...
+ tx --quiet push -s
tx ERROR: Error received from server: Duplicate string key ('Oops! Something went wrong\.') in line 247
tx ERROR: Could not upload source file. You can use --skip to ignore this error and continue the execution.
tx ERROR: Error received from server: Duplicate string key ('Oops! Something went wrong\.') in line 247
```
Looks like maybe a rebase error when I was working on #4754. The
string was already added, in #4829.

i18n: Remove a duplicate message key.

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/zulipmobile/sharing/SharingHelper.kt
src/nav/navActions.js
src/sharing/ShareToPm.js
src/sharing/ShareToStream.js
src/sharing/ShareWrapper.js
src/sharing/SharingScreen.js
src/sharing/index.js
src/sharing/types.js
src/types.js

This PR makes changes to enable users to share multiple files.
Followup for https://github.com/zulip/zulip-mobile/pull/4757

[android] Multiple share to zulip / share to Zulip from other apps [part 3]

---

src/search/SearchMessagesCard.js
src/search/SearchMessagesScreen.js
src/webview/MessageList.js

I am concerned about the changes I made in the very first commit of this PR, search screen `MessageList` was being provided `HOME_NARROW` which was creating problems with my second commit. Is there a particular reason for why it was that way?
Fixes: #4852

Do not mark as read for Search and Special Narrows.

---

src/message/__tests__/messageUpdates-test.js
src/message/messageUpdates.js
src/webview/generateInboundEvents.js
src/webview/js/generatedEs3.js
src/webview/js/js.js

As discussed here:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/getMessageTransitionProps/near/1243171
This cleans up the structure of this code a bit, hopefully making it easier to work out exactly what it's doing and to change what it's doing.
The actual behavior is unchanged. Some of the conditions don't seem to make a ton of sense -- in particular they seem like they can at best be heuristics for what the names (converted here to comments) suggest they're trying to get at, and it's not at all clear (and there are no comments to explain) why those particular conditions should lead to these particular behaviors. So there's plenty of room to change the behavior from here; in particular, we don't need to give the existing code a lot of deference in being super careful about …

Simplify "update strategy" logic

---

src/__tests__/lib/exampleData.js
src/account/accountActions.js
src/actionTypes.js
src/api/apiFetch.js
src/api/apiTypes.js
src/api/checkCompatibility.js
src/api/notifications/forgetPushToken.js
src/api/notifications/savePushToken.js
src/events/doEventActionSideEffects.js
src/events/eventActions.js
src/message/fetchActions.js
src/message/messagesActions.js
src/notification/notificationActions.js
src/outbox/outboxActions.js
src/reduxTypes.js
src/streams/streamsActions.js
src/styles/index.js
src/subscriptions/subscriptionsActions.js
src/topics/topicActions.js
src/typing/typingActions.js
src/user-status/userStatusActions.js
src/users/usersActions.js

Toward #4907.
These are the four items I'd flagged as "tricky." Here, I follow Greg's suggestions for handling them at https://github.com/zulip/zulip-mobile/issues/4907#issuecomment-885992786. As it turns out, some of them are not all that tricky! 🙂

flow: Annotate some more exports.

---

android/build.gradle
docs/architecture/platform-versions.md
docs/developer-guide.md
src/webview/js/generatedEs3.js
src/webview/js/js.js
tools/generate-webview-js

As Discussed in [CZO](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Updating.20.60minSdkVersion.60/near/1236327), Last time (9-2020) we checked, the total
user base using API < 23 is less than 1 percent and hence it is
safe for us to update the API version (according to the [update
policy](https://github.com/zulip/zulip-mobile/blob/master/docs/architecture/platform-versions.md#android-and-ios-versions) [2] we have).
The advantage of this change would be simplification in some of the
code that we use / will be using which will be changed / added in
other commits.
The changes in this commit Involved:
* Changing `android/build.gradle`.
* Setting up chrome version to 44 (set according to what is
written in `platform-versions.md`).
* Modifications to the documentation.
Marking P1 …

android: Drop support for API < 23.

---

src/compose/ComposeBox.js
src/compose/MentionWarnings.js

For annotating the default export of `MentionWarnings`, for #4907, I think it actually may be easier to first convert it to a function component and remove the `connect` call. This is a little surprising because it had been on my list of components that I thought would be pretty tricky to convert.
I didn't find a way to get thorough type-checking of `MentionWarnings`'s methods that `ComposeBox` was calling on a `ref`, until I converted `MentionWarnings` to a function component. After this PR, we should get that type-checking, without having to manually repeat any types.
I tested the component on my iPhone and it worked as I expected it to.

MentionWarnings [nfc]: Convert to function component.

---

src/boot/AppEventHandlers.js
src/compose/ComposeBox.js
src/compose/ComposeMenu.js
src/presence/PresenceHeartbeat.js
src/reactions/MessageReactionsScreen.js
src/search/SearchMessagesScreen.js
src/sharing/ShareToStream.js
src/sharing/ShareWrapper.js
src/start/AuthScreen.js
src/start/DevAuthScreen.js
src/start/PasswordAuthScreen.js

With the exception of `MentionWarnings`, which I've opened #4942 for, and `ComposeMenu`, which we have #4796 for.
Related: #4907

Annotate most exported `connect`ed components.

---

src/api/eventTypes.js
src/api/initialDataTypes.js
src/api/modelTypes.js
src/api/transportTypes.js
src/mute/mutedUsersReducer.js

This largely covers the remaining types here, inspired by #4948, with the help of some Perl find-and-replace.
There isn't anything special about the API that means its objects and arrays should be read-only -- after all, the actual server itself can't possibly care. But we reuse a lot of these for Redux actions and for pieces of our Redux store, where we do want things to be read-only, so it's helpful to just consistently mark here too.

api types: Mark most remaining types read-only

---

src/third/redux-persist/createPersistor.js
src/third/redux-persist/getStoredState.js
src/third/redux-persist/purgeStoredState.js

`logging.warn` has the best chance of helpfully reporting an Error
object if we pass it as the first argument. In some of these cases,
we weren't even passing an Error at all, when we had one available
-- so, do so, and have it be the first argument.
The second argument should be a plain, JSONable object. So, make
that happen, too, so we don't get Sentry events with things like
"extra": {
"0": "u",
"1": "s",
"2": "e",
"3": "r",
"4": "G",
"5": "r",
"6": "o",
"7": "u",
"8": "p",
"9": "s"
}

redux-persist: Improve logging of errors.

---

src/account/AccountItem.js
src/users/userSelectors.js

This isn't itself server data -- it's what we use for acquiring server data -- which is why we didn't cover it when expanding these checks in 916dc4b28 / #4588.
But like the server data, it's something we assume is present when rendering the main UI of the app.  And because of the same issue #4841, the same lack of consistency in our data-storage model with redux-persist that caused #4587 and made that fix necessary, it's possible for it to be lacking data when the existing checks in this function all pass.
So, add a check for this too.
Also expand the comments in this function, particularly on the tricky balance it has to maintain. Some care is needed when adding checks here -- too much care, really, and I'd love to find a way to arrange things to make these delicate properties be more …

Check active account, too, in getHaveServerData

---

src/boot/store.js

Looks like this got lost in #4901.
As Greg points out [1]:
> I think this means a regression in the current beta: on upgrade,
> we'll effectively forget the user's choice of language, and revert
> to the default of English.
> The fix should be pretty simple: just add the missing migration.
>
> For non-beta users, it'll be as if it was never broken.
>
> For beta users who upgraded to version 166 or 167, and then
> upgrade to a version with that fix, the effect will be that we
> take the setting they had before the 166 or 167 upgrade, and
> revert to that setting. For most of them that will either have no
> effect (because they already went and changed the setting back to
> the same preferred language), or take them back from English to
> the language they want to be using… or both (because …

settings: Add migration for `state.settings.{locale -> language}.

---

src/message/fetchActions.js

I have a draft in progress for a better solution to this; see
discussion at
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/connection.20failed/near/1248170.
But for now this should fix an annoying situation that's so far been
observed on Alya's Android device, where a "Gave up trying to
connect" alert appears immediately on startup. The theory is that
the app stops making progress on the network request when the app is
backgrounded, while of course it doesn't stop approaching the
timeout. Then, when the app is foregrounded again, the request
hasn't succeeded but the timeout has fired, and the alert is shown.

initialFetchAbort: Don't kick user out if we have server data.

---

package.json
yarn.lock

This is a bump of two major versions. Nothing seems to go wrong (and if it did, I'd expect it to only affect Jest tests, and those still all pass). But in addition to removing a hack described in the commit message, this will let us iron out any wrinkles from those major version bumps soon, so we don't have to deal with them at the time of upgrading to a potential newer version that has explicit RN v0.64 support, with something like expo/expo#13549, for #4426.

deps: Upgrade jest-expo to 42.1.0, the latest.

---

flow-typed/react-intl_vx.x.x.js

When we upgrade Flow for the RN v0.64 upgrade (#4426), Flow understandably starts complaining about the `React_2` stuff in this libdef. We've had a TODO to deal with it; so, do that. From my experimentation so far, these changes should be enough to satisfy those complaints from the new Flow version with RN v0.64.
See discussion at https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/react-intl.20libdef/near/1228275.
Inheriting priority from #4426.

Fix react-intl libdef, on the path to RN v0.64 upgrade.

---

src/boot/ZulipAsyncStorage.js

The in-progress PR #4974 can help verify that these annotations are appropriate.
Related: #4907

ZulipAsyncStorage types [nfc]: Add a quick annotation, for types-first.

---

src/__flow-tests__/reactUtils-test.js

When we bump the Flow version along with the RN v0.64 upgrade (#4426), Flow will enforce having all of our Flow error suppressions indicate which specific error code they're meant to suppress. These few snuck in after we'd gone through the whole codebase and added those indications.
Inheriting priority from #4426.

flow: Add missing error codes in some new suppressions.

---

src/notification/index.js

There are a lot of users seeing this - more than I would expect to have
multiple accounts on the same server. I want to collect this data so
that we can have a more complete picture of what's going on in these
cases.
This is somewhat personal data (URLs of self-hosted realms), but we log
this same array elsewhere, so it's not changing the status quo
significantly to log it here.

notifications: Add more detail to "realm_uri ambiguous" error.

---

.flowconfig
flow-typed/@react-navigation/stack_v5.x.x.js

From Flow's perspective, we're fine to delay types-first until we're
on v0.143, which we'd normally take along with the RN v0.65 upgrade.
But, from experimentation, React Native v0.64's internal code seems
to have been written with Types-First, such that a few Flow errors
would show up if we tried to use RN v0.64 without Types-First
enabled. So, enable it, now that we can, and now that the RN v0.64
upgrade is on the horizon (#4426).
Fixes: #4907

flow: Enable Types-First mode, on the path to RN v0.64 upgrade.

---

__libdef-tests__/stack_v5.x.x-test.js
flow-typed/@react-navigation/stack_v5.x.x.js

This is a followup to the small type-safety regression in #4987.
See comment.  The underlying Flow bug is that $Shape doesn't
really work:
https://github.com/facebook/flow/issues/5702
Happily there is a workaround, namely `$Rest<T, {...}>`.
One might give that a handy alias, like `$Partial<T>` -- and
that's exactly what this libdef already does.  So just use it here.
Also add a type-test.  The most natural place for this might be a
folder like `flow-typed/__tests__/`, next to the libdefs themselves…
but if we do that, then every time we touch the file, Flow restarts
from scratch, just as it does for actual libdefs in `flow-typed/`.
Seems like something odd there.  But we can work around it by just
using a separate folder.

@react-navigation/stack libdef: Fix setParams by dropping $Shape.

---

package.json
src/__tests__/reactUtils-test.js

This is our first use of `react-test-renderer`. It piggy-backs on
our incorporation of Jest's "modern" fake-timer implementation in
PRs #4754 and #4931. That was handy!
I haven't yet found any test cases that fail with our
implementation. (And I'd been hoping to, to debug an unexpected
error!)
But I did try pasting in an earlier iteration of the hook's
implementation, from #4940, that Greg had found bugs in by reading
the code. Many of these tests failed on that buggy implementation,
which is a good sign.
Might as well keep these new tests, then, if they're not an
unreasonable maintenance burden.

reactUtils tests: Start testing `useHasStayedTrueForMs`.

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/zulipmobile/SentryUtils.kt
android/app/src/main/java/com/zulipmobile/ZLog.kt
android/app/src/main/java/com/zulipmobile/notifications/FCMPushNotifications.kt
android/app/src/main/java/com/zulipmobile/notifications/NotificationHelper.kt
android/app/src/main/java/com/zulipmobile/sharing/SharingHelper.kt
docs/howto/release.md
src/sentryConfig.js

This means we'll start seeing reports in Sentry of both uncaught exceptions, and error or warning cases we explicitly catch, in our Kotlin code just as we do already in our RN-based JS code.

Set up Sentry for Android-native code

---

src/__tests__/lib/exampleData.js
src/outbox/outboxActions.js
src/outbox/outboxReducer.js
src/types.js
src/utils/recipient.js

This expresses that the types of certain properties on `Outbox` vary together, and that they do so in the same way as on `Message`.
That in turn means that when we have a condition like `type === 'stream'`, Flow can infer that `display_recipient` will be a string (the stream name) rather than an array, and so on.
Also make some followup simplifications that this opens up.
(~~One upcoming place I suspect this will simplify the code a bit is at https://github.com/zulip/zulip-mobile/pull/4899#discussion_r703932340~~ Hmm, no -- that code wants `stream_id`, and that's something we don't yet have on `Outbox`: #3998. Ah well, this will simplify that code once we also have #3998.)

Distinguish types PmOutbox vs. StreamOutbox more fully

---

android/app/src/main/java/com/zulipmobile/notifications/FcmMessage.kt
android/app/src/test/java/com/zulipmobile/notifications/FcmMessageTest.kt
src/notification/__tests__/notification-test.js
src/notification/extract.js
src/notification/types.js

These fields are all present since Zulip Server 1.9, and two of them even since 1.8, so it's long past time we should be able to not worry about servers that don't send them. Having them always present will be helpful for the work @AkashDhiman is doing on our Android notification UI, as discussed here:
https://github.com/zulip/zulip-mobile/pull/4842#discussion_r685546372
---
~~This PR is a draft because before we start ignoring these notifications from old (pre-1.9) servers, I'd like to set things up so that we log warnings to Sentry when we do so. There's a couple of commits at the start of this branch aimed at doing that, but then I realized that they can't possibly work yet because the Sentry destination (aka "DSN" or "client key") lives only in the JS code, at `src/sentryConfig.js`, …

notif: Require sender_id, server, and realm_uri, rejecting ancient servers' data

---

src/chat/ChatScreen.js
src/compose/ComposeBox.js
src/message/NoMessages.js
src/message/fetchActions.js
src/outbox/outboxActions.js
src/types.js
src/utils/narrow.js

This makes #3998 mostly complete: the remaining steps will be to get a release with this change out, wait a few weeks, then make `stream_id` required with a migration to drop Outbox values that lack it, just as we did for `sender_id` before.
Along the way, we pin down some invariants about the different narrows involved in the compose code. I remember having to work through some of this same reasoning in order to verify some of the refactoring in #4773 (around the `onSend` callback, IIRC); hopefully the added jsdoc and asserts here will help memoize that work for the future, and also ensure the logic gets revised appropriately when we make changes that would affect its assumptions (like showing the compose box on a wider variety of narrows.)

Add stream_id to Outbox values

---

src/third/redux-persist/createPersistor.js
src/third/redux-persist/persistStore.js

I'd like this to be reviewed/merged after #4709. While that PR is advertised as just adding some tests, it also does its own cleanup of some stuff in redux-persist, so I'd rather not go through reordering it with this PR if it can be avoided.
-----
I ended up doing this more incrementally than I think we'd said I needed to, on the call today. But it's a tricky and important area, and it doesn't have any tests, so this'll hopefully make it easier to track bugs in review than if I'd done it in just a commit or two. I also found that this incremental approach wasn't unusually hard, after all—at least, not when making the changes to get to this point. (It might get harder later on.)
After this series of commits, I believe we give `AsyncStorage` instructions to write out the right updates, in …

Structure redux-persist code toward doing writes in batches with `AsyncStorage.multiSet`.

---

src/common/RawLabel.js

Since we've seen a violation:
https://sentry.io/organizations/zulip/issues/2645242607/?project=191284&query=is%3Aunresolved+%22pass+either+%60text%60+or+%60children%60%22&statsPeriod=14d

RawLabel: Make `invariant` slightly more helpful in Sentry.

---

src/api/apiErrors.js
src/api/apiFetch.js

The way these errors are handled in `apiFetch.js` and sent to
Sentry, if `data` is undefined then the corresponding property
just disappears in the Sentry breadcrumb.  That can be a bit
confusing when matching up the Sentry data with the source code.
Instead, use a string that says the data was invalid JSON.
(Which it was -- that's how `data` here can be undefined.)

api errors: Make the invalid-JSON case a bit more explicit

---

src/boot/ZulipAsyncStorage.js
src/boot/__tests__/ZulipAsyncStorage-test.js

We've always passed JSON-encoded data in the one place we actually
use this storage, inside the redux-persist code; and our `getItem`
has relied on that assumption for a long time.
But our tests for this module have been passing random strings
instead.  When those happen to start with a `z`, that collides
with our compression header, and the test flakes.
Document that requirement on this module's actual interface, and
add some debug asserts to enforce it.  That then makes the flakes
much easier to reproduce; fix those tests to conform to the
interface's requirements.
Fixes: #4994

ZulipAsyncStorage: Document and assert JSON requirement

---

src/message/getHtmlPieceDescriptors.js
src/utils/__tests__/recipient-test.js
src/utils/recipient.js

When making the changes in #5011, I saw the comment in `isSameRecipient` mentioning that it's in a hot loop where we're already doing too much computation. There's a description there of how we can fix that for all cases; but in the meantime, for the case where the user is just looking at a single topic or PM conversation we can skip calling this function entirely.

webview html: Skip expensive isSameRecipient where we can

---

src/account-info/ProfileScreen.js
src/account/accountsSelectors.js
src/boot/AppEventHandlers.js
src/common/ServerCompatBanner.js
src/events/eventActions.js
src/message/fetchActions.js
src/outbox/outboxActions.js
src/presence/PresenceHeartbeat.js
src/react-redux.js
src/reduxTypes.js
src/sharing/index.js
src/typing/__tests__/typingSelectors-test.js
src/typing/typingActions.js
src/users/usersActions.js
src/webview/MessageList.js

This is the first PR in a series produced from the branch described at https://github.com/zulip/zulip-mobile/issues/5006#issuecomment-924341909 .
This first PR doesn't yet get into the main substance of the changes. It collects a variety of small, mostly independent, prep commits needed along the way, that were quickest to polish into a PR and should be generally easy to review.

redux: Various small prep changes for multi-org support

---

src/account/accountsSelectors.js
src/caughtup/caughtUpSelectors.js
src/chat/fetchingSelectors.js
src/chat/narrowsSelectors.js
src/directSelectors.js
src/drafts/draftsSelectors.js
src/emoji/emojiSelectors.js
src/pm-conversations/pmConversationsSelectors.js
src/redux.js
src/reduxTypes.js
src/session/sessionReducer.js
src/subscriptions/subscriptionSelectors.js
src/unread/unreadModel.js
src/user-status/userStatusSelectors.js
src/users/userSelectors.js

This is the second PR in the series that began with #5016, produced from the branch described at https://github.com/zulip/zulip-mobile/issues/5006#issuecomment-924341909 .
At the end of this PR, we have a type PerAccountState which is distinct from GlobalState, exposing only the per-account parts of the data. A GlobalState can be freely used implicitly as a PerAccountState, but not vice versa. And to start exercising the distinction, most selectors have been marked as per-account, accepting a mere PerAccountState -- which also means that any selectors they go on to invoke must also be per-account.
The next steps in my draft branch after this PR are to convert the remaining selectors to be per-account where appropriate. Mainly this means those consuming `state.accounts` in …

redux: Distinguish per-account vs global state (1/n)

---

docs/architecture/realtime.md
src/__tests__/lib/exampleData.js
src/account/__tests__/accountsReducer-test.js
src/account/accountsReducer.js
src/actionTypes.js
src/api/initialDataTypes.js
src/api/messages/sendMessage.js
src/api/pollForEvents.js
src/chat/ChatScreen.js
src/common/ServerCompatBanner.js
src/common/ZulipBanner.js
src/config.js
src/events/eventActions.js
src/message/__tests__/fetchActions-test.js
src/message/fetchActions.js
src/outbox/outboxActions.js
src/realm/realmActions.js
src/session/__tests__/sessionReducer-test.js
src/session/sessionReducer.js

I'd like to make these improvements on the path to a better alternative to 6d2647f2730665215c68e3c0e98a7d8666e2314a. I think they're also good to do independently of my plan for that.
See discussion: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/connection.20failed/near/1248170
(screenshots coming soon)

Extract and improve reusable banner component; fix eventQueueId type; get feature level from /register

---

src/message/messageSelectors.js
src/pm-conversations/pmConversationsModel.js
src/pm-conversations/pmConversationsSelectors.js
src/unread/unreadHuddlesReducer.js
src/utils/recipient.js

This spun off of a draft I've been working on to resume message-list diffing. I've forgotten the specifics of why this cleanup is helpful or necessary for that work (and it would take some effort to go back and check), but I'm hoping it will still seem worthwhile without that context. 🙂 
Mainly, this PR takes a small handful of functions in `recipient.js` like this:
```js
/** The stream name a stream message was sent to.  Throws if a PM. */
export const streamNameOfStreamMessage = (message: Message | Outbox): string => {
if (message.type !== 'stream') {
throw new Error('streamNameOfStreamMessage: got PM');
}
return message.display_recipient;
};
```
And turns them into functions like this:
```js
/** The stream name a stream message was sent to. */
export const streamNameOfStreamMessage = …
```

Use PmMessage, StreamMessage, PmOutbox, StreamOutbox more, replacing runtime checks.

---

src/account/__tests__/accountsSelectors-test.js
src/account/accountsSelectors.js
src/boot/ThemeProvider.js
src/boot/TranslationProvider.js
src/common/OfflineNotice.js
src/common/ServerCompatBanner.js
src/common/UserAvatar.js
src/common/ZulipStatusBar.js
src/directSelectors.js
src/events/eventActions.js
src/lightbox/Lightbox.js
src/message/__tests__/fetchActions-test.js
src/nav/ZulipNavigationContainer.js
src/notification/notificationActions.js
src/outbox/outboxActions.js
src/reduxTypes.js
src/session/sessionReducer.js
src/settings/LanguageScreen.js
src/settings/NotificationsScreen.js
src/settings/SettingsScreen.js
src/start/IosCompliantAppleAuthButton/index.js
src/users/userSelectors.js
src/users/usersActions.js
src/utils/openLink.js
src/webview/MessageList.js

This is the next PR in the series after #5016, #5017, and #5023, produced from the branch described at [#5006 (comment)](https://github.com/zulip/zulip-mobile/issues/5006#issuecomment-924341909).
From the foreshadowing last time:
> After this PR, the conversion of `tryGetAuth` is still incomplete, so that's next up. Then we handle a few remaining selectors elsewhere, in particular those for `state.settings` and `state.session`.
That's this PR.
Next, continuing what we mentioned last time:
> After that, we'll convert thunk actions and React components so that they get a PerAccountState rather than a GlobalState.

per-account 3/n: Sort out remaining selectors

---

package.json
yarn.lock

No breaking changes are announced:
https://github.com/rpl/flow-coverage-report/releases.
Note that I haven't tested it at all to see if it still works,
because it's not part of our normal workflow and I'm not familiar
with its previously intended behavior.
Greg points out that it'd be useful to see what this tool has to say
now, but it's mostly been unused for a while:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Dependabot/near/1203387.
Anyway, apart from it being nice in general to be on the latest
versions of things, this also removes all five low-severity
vulnerabilities reported by `yarn audit` that implicate
flow-coverage-report.

deps: Upgrade flow-coverage-report to 0.8.0, the latest.

---

ios/Podfile.lock
package.json
yarn.lock

Only one announced change is labeled as breaking, and it doesn't
affect us; for discussion, see
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.40sentry.2Freact-native.20from.202.2E6.2E2.20to.203.2E1.2E1/near/1261502.
I've verified that we can still get Sentry events without any
special extra setup, on iOS and Android. On Android, that includes
events from the JS and from the Kotlin.

deps: Upgrade @sentry/react-native to 3.1.1, the latest

---

src/api/transportTypes.js
src/common/Screen.js

Each of these `+` marks means the property is read-only:
https://flow.org/en/docs/types/interfaces/#toc-interface-property-variance-read-only-and-write-only
In each case that's the behavior we want.  But in each case we
already have a `$ReadOnly<…>` around the whole object type, which
applies a `+` to each property:
https://flow.org/en/docs/types/utilities/#toc-readonly
So putting `+` on an individual property is redundant.  Take it out,
to avoid confusing people reading the codebase and trying to
understand what the various type annotations mean:
https://github.com/zulip/zulip-mobile/pull/5039#discussion_r724636461
(In each of these cases, we added the `+` marks at a time when there
wasn't a `$ReadOnly` there, and then added the latter as part of a
broad automated refactoring.)

types [nfc]: Remove some redundant read-only-property annotations.

---

src/compose/ComposeBox.js

task 1 and 2: the handleMessageBlur gets called when the user navigates away and when the compose box looses focus, sending the notification here fixes both issue-tasks.
task 3: by checking the message length in handleMessageChange the notification gets sent on emptying the input.
Fixes: #4811

a-compose-send: added more "not typing anymore" notifications

---

src/compose/MentionWarnings.js

The `handleMentionSubscribedCheck` function in MentionWarnings used to
bail out correctly only when the narrow was a 1:1 PM thread. This showed
an exception message when using quotations in groupPMs. Changing
`is1to1PmNarrow` instances to `isPmNarrow` inside MentionWarnings fixes
this issue.
Fixes: #4745

compose: Fix quoting exception message in GroupPM

---

src/autocomplete/StreamAutocomplete.js
src/streams/StreamItem.js
src/streams/StreamList.js
src/streams/SubscriptionsCard.js
src/streams/TopicItem.js
src/subscriptions/StreamListCard.js
src/topics/TopicList.js
src/topics/TopicListScreen.js
src/types.js
src/unread/UnreadCards.js
src/unread/__tests__/unreadSelectors-test.js
src/unread/unreadSelectors.js

This is an installment on #3918, converting from stream names to stream IDs; I'd taken a look at it recently following #5056.
In this PR, we make those conversions for the two components StreamItem and TopicItem: they now take the stream ID as a prop along with the stream name and other details, and pass the stream ID to their callbacks as well as the stream name and in TopicItem's case the topic.
This allows a couple of simplifications, to skip looking up the ID from the name in a couple of places where this code was already calling something that demands an ID. It also makes stream IDs available in various places we currently use names, including several Narrow-constructor call sites.

stream IDs: StreamItem and TopicItem props and callbacks

---

android/app/src/main/AndroidManifest.xml
android/build.gradle
src/lightbox/download.js

Along with moving us over to "scoped storage", which will be newly enforced on Android 11.
Fixes: #4283
Fixes: #4284

android: Update target SDK version to 30, i.e. Android 11

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/zulipmobile/ShareToZulipActivity.kt

This is an activity, not an intent, so its name should end with
"Activity" and not with "Intent".
We can also name it a bit more for what its purpose is at a
product level; the fact that it gets intents whose action is
SEND (and SEND_MULTIPLE) is expressed more clearly in the
relevant code in the manifest anyway.  Also add a bit of javadoc
to explain what's going on and why it doesn't look like it's
doing much.

android sharing [nfc]: Rename and javadoc the shim activity

---

src/webview/html/__tests__/__snapshots__/messageListElementHtml-test.js.snap.android
src/webview/html/__tests__/__snapshots__/messageListElementHtml-test.js.snap.ios
src/webview/html/header.js
src/webview/html/message.js
src/webview/html/time.js
src/webview/js/generatedEs3.js
src/webview/js/js.js

(And fix an unrelated bug where a _**[bold, italic link](https://www.chat.zulip.org/)**_ in a Zulip message failed to open when you tapped on it.)

msglist-diffing: Add and use new '.msglist-element' class in WebView HTML

---

src/__flow-tests__/generics-tests.js
src/actionTypes.js
tools/formatting.eslintrc.yaml

From the comment, it doesn't seem I thought this rule was a good idea
even in 2018, when I moved it from our top-level ESLint config to this
file that also applies in our prettier-eslint runs.
But mostly it just hasn't come up much.  It did again in a recent PR,
though:
https://github.com/zulip/zulip-mobile/pull/5084#discussion_r740514987
And it turns out it's quite easy to remove!  Just one place changes.
(Even the one place we've explicitly disabled the rule, it seems to
have no effect; must have applied to an earlier version or draft.)
So do so.

lint: Drop unhelpful rule flowtype/space-after-type-colon

---

src/account/AccountPickScreen.js
src/boot/HideIfNotHydrated.js
src/boot/ThemeProvider.js
src/boot/TranslationProvider.js
src/common/OfflineNotice.js
src/common/Popup.js
src/common/ServerCompatBanner.js
src/common/ZulipStatusBar.js
src/compose/MentionWarnings.js
src/lightbox/Lightbox.js
src/nav/AppNavigator.js
src/nav/ZulipNavigationContainer.js
src/notification/notificationActions.js
src/presence/PresenceHeartbeat.js
src/react-redux.js
src/reduxTypes.js
src/settings/LanguageScreen.js
src/settings/SettingsScreen.js
src/sharing/SharingScreen.js
src/start/IosCompliantAppleAuthButton/index.js
src/webview/MessageList.js

This is the next PR in the series after #5066, #5030, #5016, #5017, and #5023, produced from the branch described at [#5006 (comment)](https://github.com/zulip/zulip-mobile/issues/5006#issuecomment-924341909).
From the foreshadowing last time:
> Coming next, we'll convert React components to get a PerAccountState themselves.
That's the second half of this PR.
The first half tightens up the typing on thunk actions, which were the subject of part 4 (#5066): we had things so that a `GlobalDispatch` could be silently used as a `Dispatch`, and a `ThunkAction` as a `GlobalThunkAction`, and this completes that distinction so those conversions are no longer possible.
One recurring feature in this PR is adding fixmes: 3 of the 7 commits are small commits adding individual fixmes. Each of those is …

per-account 5/n: Sort out React components

---

.eslintrc.yaml
src/boot/StoreProvider.js
src/react-redux.js

This lets us catch bugs where, for example, a selector passed to
`useSelector` doesn't return the type that the caller wants it to.
Now that we have a distinction between `useSelector` and
`useGlobalSelector`, it also lets us catch bugs where `useSelector` is
mentioned but `useGlobalSelector` is what's actually wanted.  For the
moment these are both purely type-wrappers of the upstream
`useSelector`, so such a bug would have no effect at runtime... but in
the future a per-account state will be a different actual object from
a global state, so one or both of them will not pass its selector the
same state object as the upstream `useSelector` would, and then such a
bug would likely cause a crash.

lint: Redirect react-redux imports through our type-wrapper module

---

package.json
yarn.lock

And, as expected (see v27.170 in the changelog), we stop seeing a
few warnings in our regular dev workflow.
- When running Jest, we'd get the following warning, which was fixed
in expo/expo@24bce422c:
react-native/jest-preset contained different
transformIgnorePatterns than expected
- When running Yarn, we'd get the following warning, fixed by
removing a `resolutions` line, which we can now do (see below):
warning Resolution field "react-test-renderer@17.0.1" is
incompatible with requested version
"react-test-renderer@~16.11.0"
And remove some workarounds we'd had in place:
Remove `fbjs-scripts`, which we added in 42bb7128f. It looks like
the relevant issue was fixed in expo/expo@d46578571.
Remove a `resolutions` line, which we added in 4a5780d65. They've
released the relevant change to …

deps: Upgrade jest-expo to 43, which officially targets RN v0.64

---

android/app/src/main/java/com/zulipmobile/notifications/FcmMessage.kt
android/app/src/test/java/com/zulipmobile/notifications/FcmMessageTest.kt
src/__tests__/lib/exampleData.js
src/account/accountsSelectors.js
src/actionTypes.js
src/api/eventTypes.js
src/api/initialDataTypes.js
src/api/messages/getMessages.js
src/api/modelTypes.js
src/api/registerForEvents.js
src/api/settings/getServerSettings.js
src/api/streams/updateStream.js
src/api/subscriptions/setSubscriptionProperty.js
src/api/transportTypes.js
src/caughtup/__tests__/caughtUpReducer-test.js
src/caughtup/caughtUpReducer.js
src/common/ServerCompatBanner.js
src/events/eventToAction.js
src/message/fetchActions.js
src/notification/extract.js
src/notification/index.js
src/pm-conversations/pmConversationsSelectors.js
src/start/AuthScreen.js
src/start/__tests__/AuthScreen-test.js
src/streams/streamsActions.js
src/users/usersActions.js
src/utils/avatar.js
src/webview/static/base.css

The change here that caused me to look into this today was this one, after https://github.com/zulip/zulip-mobile/pull/5052#issuecomment-960296275 :
024853c2f caught-up: Drop legacy inference for servers pre-1.8
That turns out to delete for us a surprising amount of code! Especially in tests -- that was some subtle logic.
But then I also went and did a sweep to help lay the groundwork for other such changes, to make more use than we do of the assumption that the server is not ancient:
---
a0d86af95 api [nfc]: Use the greppable `TODO(server-N.M)` form consistently.
We've recently started to actually drop old conditionals that added
complexity and were needed for supporting old versions of the server.
To do more of that, it's good to have a systematic format we use when
marking that …

api: Start relying more on non-ancient servers

---

src/action-sheets/index.js
src/api/initialDataTypes.js
src/api/messages/deleteMessage.js
src/api/registerForEvents.js
src/boot/store.js
src/realm/__tests__/realmReducer-test.js
src/realm/realmReducer.js
src/reduxTypes.js

I set out to do a quick and easy fix for #2792 and #2793, but then I realized that it'd be best to have #3898 done for those. These are the commits that I did manage to make without that; I think changes like these are fine to make even if we don't get through all those issues right away.

message action sheet: Prep work for showing/hiding edit/delete buttons better.

---

tools/test

Shell variables are global by default.  Thankfully Bash has a feature
where you can at least make them local, if you remember to do so.
This fixes a bug since 1db6b89ed where running the `lint` suite would
clobber the `files` variable that remembered the `--diff` vs
`--all-files` vs default (since-branch-base) setting.  This meant that
later suites (jest, prettier, and deps, by default) would see an
invalid value for `files`.
For `jest`, this had the same effect as `--all-files`, making it
annoyingly slow for interactive use (but the same as we run in CI.)
For `prettier`, it would cause it not to run at all.
The other accidentally-global variables here didn't happen to collide
with anything, but best to do this consistently so they don't in the
future (and so we're more likely to remember …

tools/test: Use `local` throughout

---

src/webview/generateInboundEvents.js
src/webview/js/generatedEs3.js
src/webview/js/js.js

Instead of replacing all of what's in htmlBody.
This is a step we're doing on its own, on the way to message-list
diffing, for #3851. When this is released, we can get some empirical
confirmation that there's not some state being tracked somewhere in
the DOM that's under htmlBody but not under msglistElementsDiv, that
we're no longer resetting, since that could be a buggy experience.
We don't think there is any state like that, from brief testing and
reading the code.
The most likely-looking bit is whether the div#message-loading has
the "hidden" class or not, IOW, whether or not we're covering the
view with our "fetching messages" indicator. After all, before this
change, this event was setting that state based on a
`showMessagePlaceholders` boolean.
It should be OK that we're not doing …

webview: Have 'content' event only replace what's in msglistElementsDiv

---

ios/ZulipMobile/Info.plist

Looks like we missed this in eb37e6c78.

ios [nfc]: Finish cleaning up unused `AppIdentifierPrefix` logic

---

src/__tests__/lib/exampleData.js
src/account/accountsSelectors.js
src/boot/AppEventHandlers.js
src/boot/reducers.js
src/events/eventActions.js
src/notification/index.js
src/notification/notificationActions.js
src/reduxTypes.js

This is the next PR in the series after #5083, #5066, #5030, #5016, #5017, and #5023, produced from the branch described at [#5006 (comment)](https://github.com/zulip/zulip-mobile/issues/5006#issuecomment-924341909).
From the foreshadowing last time:
> Coming next, we'll tighten the distinction between `GlobalState` and `PerAccountState` in the same way as we did for `GlobalDispatch` and `Dispatch`.
That's this PR.
Then, continuing as described last time:
> After that, we'll start distinguishing plain actions: just like other areas of our code before the start of this PR series, most of them implicitly refer to the active account while others don't, and we'll start tracking which is which so that we can later reinterpret the former group as referring to whichever specific account their …

per-account 6/n: Stop letting GlobalState cast to PerAccountState

---

.gitignore
android/app/src/main/java/com/zulipmobile/MainApplication.java
android/app/src/main/java/com/zulipmobile/notifications/FCMPushNotifications.kt
android/app/src/main/java/com/zulipmobile/notifications/FcmListenerService.java
android/app/src/main/java/com/zulipmobile/notifications/NotificationHelper.kt
android/app/src/main/java/com/zulipmobile/notifications/NotificationIntentService.java
android/app/src/main/res/values/color.xml
android/app/src/main/res/values/strings.xml

The first 3 commits are updating some related code.
The next 4 commits are adding/removing some data structures to facilitate building up of this UI.
The last 2 commits are involved in changing the notification structure
- first one makes it so that the app shows 1 notifications per conversation.
- second one groups the notification.
Summary notification is not yet implemented correctly in this PR, and will show incorrect information (gives summary for all notifications on a summary notification for 1 realm) when API < 24 and user is logged in with multiple realms.
Some methods may no longer be needed, yet are not removed because they may prove useful in implementing other features.
This skips #4633 and fixes part of #2691, part of because summary notification is not yet implemented …

[Android] Improve notification UI.

---

android/app/src/main/java/com/zulipmobile/notifications/FCMPushNotifications.kt
android/build.gradle
docs/architecture/platform-versions.md
docs/developer-guide.md
src/webview/js/generatedEs3.js
src/webview/js/js.js
tools/generate-webview-js

Much like in #4938 for the previous bump.
As discussed in chat:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/platform.20versions/near/1278266
and following discussion at https://github.com/zulip/zulip-mobile/pull/4842#discussion_r692234996 .

Drop Android 6 Marshmallow support

---

android/app/src/main/AndroidManifest.xml

This commit fixes #5068
Switching between screen size or split screen causes Android AppComponent to be reconstructed and I'm initiate a restart.

Android: Fix AppComponent reconstructed on split screen

---

android/app/src/main/java/com/zulipmobile/notifications/NotificationUiManager.kt

`IconCompat.createWithBitmap` [1] expects a non-null Bitmap object.
Since abd605d0e, we've been directly passing the value returned from
our own `fetchBitmap` function, which sometimes returns null. It
seems like the symptom would be a failure to deliver a notification
when the value is null.
So, go back to not calling `IconCompat.createWithBitmap` unless we
get a non-null value from `fetchBitmap`.
See discussion at
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/sentry.20IllegalArgumentException.3A.20Bitmap.20must.20not.20be.20null.2E/near/1283842.
[1] https://developer.android.com/reference/androidx/core/graphics/drawable/IconCompat#createWithBitmap(android.graphics.Bitmap)

android notifs: Fix regression where notifs dropped when avatar not fetched

---

jest/jestSetup.js
src/api/apiErrors.js
src/api/apiFetch.js
src/notification/extract.js
src/utils/async.js
src/utils/logging.js

Prompted by noticing that we could be more informative here, after
seeing what looks like a failed API request in a Sentry breadcrumb,
but without an httpStatus:
https://sentry.io/organizations/zulip/issues/2799655412/events/6664a7f3171749279ff724b4e805a132/?project=191284
(The breadcrumb was first noticed by Tim while debugging an issue
that turned out to be unrelated:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/sentry.20IllegalArgumentException.3A.20Bitmap.20must.20not.20be.20null.2E/near/1283848.)

sentry: Add `error.name` and `error.message` in apiCall error breadcrumb

---

android/app/src/main/java/com/zulipmobile/notifications/FcmMessage.kt
src/notification/__tests__/notification-test.js
src/notification/extract.js
src/notification/index.js
src/notification/notificationActions.js
src/notification/types.js

Along with making the property required on APNs and FCM payloads.
I noticed the opportunity to do this after reviewing #5100 and #5105.
Fixes: #4631

notification: Use user_id to find account if multiple on same realm

---

src/__tests__/lib/exampleData.js
src/api/initialDataTypes.js
src/api/modelTypes.js
src/api/registerForEvents.js
src/config.js
src/message/fetchActions.js
src/webview/html/__tests__/__snapshots__/messageListElementHtml-test.js.snap.android
src/webview/html/__tests__/__snapshots__/messageListElementHtml-test.js.snap.ios

This started from the note here:
https://github.com/zulip/zulip-mobile/pull/4968#discussion_r696943253
to better explain how `initialDataTypes.js` is organized, and expanded as I noticed that the register-queue binding could be 
cleaned up to make its interface better reflect how it actually behaves.

api [nfc]: Explain InitialData more; simplify register-queue interface

---

src/common/ServerCompatBanner.js
src/common/ServerPushSetupBanner.js
src/settings/NotificationsScreen.js
static/translations/messages_en.json

In addition to the dismissable banner on the home screen that we started showing in #5090.
Related: #1507

notif settings screen: Always show server-push-setup-banner if it applies

---

src/compose/ComposeMenu.js
src/compose/__tests__/ComposeMenu-test.js

Checking the jsdoc on logging.info, it explicitly says it's not
meant for sending things to Sentry. So, use logging.warn, which is.

ComposeMenu: Change a `logging.info` to `logging.warn`, to send to Sentry

---

tools/checkout-keystore

We want to continue to the wait-then-delete commands.

checkout-keystore: Allow continuing if noise-grep command fails

---

src/actionTypes.js
src/message/__tests__/messagesReducer-test.js

This should help with #4840. Inheriting P1 from that issue.

action types: Sync update-message event type with doc

---

src/unread/__tests__/unreadModel-test.js
src/unread/unreadModel.js

unreadModel: Handle moving messages between topics/streams.

---

ios/Podfile.lock
package.json
yarn.lock

This is just a minor version that came out a month ago, which was
after our big v0.64 upgrade, #4991.
The changelog entry [1] has just one item:
- For Android, general fixes to Appearance API and also fixes
AppCompatDelegate.setDefaultNightMode(). For iOS, now works
correctly when setting window.overrideUserInterfaceStyle
([25a2c608f7](https://github.com/facebook/react-native/commit/25a2c608f790f42cbc4bb0a90fc06cc7bbbc9b95)
by [@mrbrentkelly](https://github.com/mrbrentkelly))
We don't use those mentioned APIs, so this should be fine and not
disruptive.
There are no changes to the template app.
Tested on my iPhone 13 Pro running iOS 15, and on the office Android
device (Samsung Galaxy S9 running Android 9), and I didn't encounter
any building or running failures, and nothing was obviously …

deps: Upgrade RN to v0.64.3, from v0.64.2

---

src/api/messages/messagesFlags.js
src/chat/MarkAsReadButton.js
src/unread/unreadModel.js
src/unread/unreadSelectors.js
src/utils/recipient.js
static/translations/messages_en.json

msglist: Offer bulk-mark-as-read button for PM conversations

---

.eslintrc.yaml
.flowconfig
.prettierignore
docs/THIRDPARTY
src/common/KeyboardAvoider.js
src/third/react-native/KeyboardAvoidingView.js

Fork React Native's `KeyboardAvoidingView` and apply a fix.
Fixes: #5162

ios: Fix app-unusable bug with "Prefer Cross-Fade Transitions" setting

---

src/autocomplete/TopicAutocomplete.js
src/drafts/__tests__/draftsSelectors-test.js
src/message/__tests__/fetchActions-test.js
src/message/__tests__/messageActions-test.js
src/message/messagesActions.js
src/sharing/ShareToStream.js
src/sharing/ShareWrapper.js
src/utils/__tests__/internalLinks-test.js
src/utils/__tests__/narrow-test.js
src/utils/internalLinks.js
src/webview/html/__tests__/header-test.js
src/webview/html/__tests__/messageListElementHtml-test.js
src/webview/html/header.js
static/translations/messages_en.json

This is the next installment after #5069 on #3918, converting from stream names to stream IDs.
In this PR, we take care of getting stream IDs available at most of the remaining Narrow-constructor call sites that will need them:
* in ShareToStream and related code;
* when parsing an internal link to find a narrow to navigate to;
* in lots of unit tests where we had constructed narrows using a string literal directly for the name, and now we take the name from some actual `Stream` object.

stream IDs: sharing, links, tests

---

src/actionTypes.js
src/message/__tests__/messagesReducer-test.js
src/message/messagesReducer.js
src/unread/__tests__/unreadModel-test.js
src/unread/unreadModel.js

This updates our type for `update_message` events (or the Redux actions we make for them, type `EventUpdateMessageAction` with `type: EVENT_UPDATE_MESSAGE`) to reflect the fixes and clarifications in zulip/zulip#20693, and updates our actual logic to match.
In particular this fixes two small bugs:
* If messages are moved to a different stream but without editing the topic, no `subject` property is included in the event, only `orig_subject`. Previously this would confuse the unread-messages data structure -- we'd wind up with those message IDs under a topic of `undefined` (rather than a topic string). I don't know what the symptom of that would be: whether the unreads screen would just forget about those, or show them with a topic like "undefined" or "", or would crash.
* When a message …

Update `update_message` event expectations

---

tools/checkout-keystore

Thanks to Anders for the suggestion:
https://github.com/zulip/zulip-mobile/pull/5144#issuecomment-985778181
I wasn't sure if /dev/fd/N was available on macOS, but indeed it
seems to be, and this `>(…)` Bash syntax works just fine there.
(Even in the ancient /bin/bash that Apple ships.)
This sure is simpler to read!  Really not much different from
the usual case of applying a grep to a command's stdout.  More
shell-style, in the spirit of shell pipelines, while the `coproc`
approach feels lower-level.
I kept the grep command pulled out separate from the main `sq`
command, as a tiny shell function, in order to have a place to put
the comment explaining what it's there for.
Suggested-by: Anders Kaseorg <anders@zulip.com>
/cc @andersk

checkout-keystore [nfc]: Use less-fancy Bash for filtering stderr

---

src/events/eventToAction.js

Manually tested that uploading an image before this commit generates
an error "Unhandled Zulip API event" on the debug console, and after
this commit no longer does so.
Fixes: #4687

event: Explicitly ignore `attachment` events

---

src/api/apiErrors.js
src/api/initialDataTypes.js
src/api/modelTypes.js
src/api/notificationTypes.js
src/api/transportTypes.js
src/notification/extract.js
src/notification/index.js
src/utils/avatar.js

This follows up on #5100, eliminating the various wrinkles we had for accommodating servers older than 1.9. This comprises:
* 1 for before Zulip 1.7 (released 2017-10)
* 3 for before Zulip 1.8 (released 2018-04)
* 4 for before Zulip 1.9 (released 2018-11)
The changes turn out to be entirely to types and comments. In 401b3a2e339139b59c7415e0abbbba6bbbe13e63 (#5100) we removed a significant amount of actual runtime logic that was for pre-1.8 servers, but I guess for this range of server versions we've already taken care of everything like that.
Zulip Server 2.0 will be a bigger deal: in particular it introduced user IDs and stream IDs in a number of places, as alternatives to emails and stream names.

api [nfc]: Start relying on server 1.9+

---

src/actionTypes.js
src/message/messagesReducer.js

Future server versions may start sending `user_id: null` for these,
rather than omitting it:
https://chat.zulip.org/#narrow/stream/378-api-design/topic/.60update_message.60.20event/near/1309241
To future-proof this code for that case, have it treat the update
as a stealth-edit if one of these fields is null, as well as if it's
omitted.

message: Handle server stealth-edits a bit more broadly

---

src/action-sheets/index.js

Spotted these while looking at where `flags` is used from
BackgroundData.
We use both these properties in other places, even in this file,
so these don't let us do anything like remove things from the
background data outright.

action-sheets types: Simplify BackgroundData uses slightly

---

src/common/FloatingActionButton.js
src/common/Touchable.js
src/compose/ComposeBox.js
src/sharing/ShareWrapper.js
static/translations/messages_en.json

Like 630a543de87355dcae67f5eeffd9051738cde1a6, but for the compose box instead of the share-to interface.
We could have done something like bb90a7e48f89881fbfd6c6fed64ccc050f10ea9a to the `FloatingActionButton`, where we add an `isPressHandledWhenDisabled` prop. But we already know that we don't want to keep using that component here, because the button isn't a FAB at all. So, stop using it.

compose: Explain validation errors on press of disabled submit button

---

src/webview/html/header.js

This reverts most of commit 9d05bbaf6fc9937ac9a776e28cbc988cc3b47b45 (from #5183).
We leave the test changes in place, because those just set up better
fixture data.
It's possible for the message list to show messages in streams that
we don't actually have data for: in particular, streams that our user
was previously a member of (and received some messages there while
they were), but no longer is, and can't see (because it's private and
they're not an admin, or because they're a guest.)  As a result, we
can't simply get the stream name here from our streams data.
There are a couple of ways we could go to fix the issue that commit
originally fixed, so that recipient headers get updated when a stream
is renamed; I'll discuss those in or linked from the issue #5206.
In the meantime, revert, …

Revert "webview html: Get stream name from stream, rather than message"

---

src/common/ServerCompatBanner.js
src/message/fetchActions.js
src/utils/__tests__/zulipVersion-test.js
src/utils/logging.js
src/utils/zulipVersion.js

This will let us get a better idea of how many (or few) users
will be affected as we drop support for an old version, or as
we remove compatibility hacks for old versions we already say
we don't support.
---
In particular, I have a draft branch to start relying on server 2.0+, following up on #5192. One of the main things it does is clean up how we send messages, to use stream IDs and user IDs instead of emails and stream names. That'll be a much-appreciated improvement… but it will also mean we break some pretty core functionality for any users interacting with a server that's still on a pre-2.0 version.
We announced rather a while ago, the middle of last year, that we were no longer supporting such old versions. We even started showing a warning banner for any users on such a server, …

    compat: Warn on unsupported or soon-unsupported server versions

---

.flowconfig
package.json
src/message/messagesReducer.js
src/outbox/outboxReducer.js
src/webview/MessageList.js
yarn.lock

This version fixes a bug I've noticed regularly, and am glad to see
gone:
> Improved inference of chained generic method calls, such as `Array`
> methods. For example, given `[1, 2].map(a => a).forEach(b => b)`,
> Flow now infers that `b` is a `number` rather than `any | number`.
https://github.com/facebook/flow/blob/main/Changelog.md#01400
This happens in a number of places in our codebase; the `userIds`
local in `pmUnreadsKeyFromMessage` is the first one I find just now
when I go look for one.
I believe this hasn't been likely to conceal type errors (and indeed
fixing it didn't reveal any.)  That's because the `| number` means
that anything consuming that data still needs to be prepared to handle
a `number`.  But it is disconcerting to have those `any`s showing up
regularly when …

flow: Upgrade to Flow v0.141.0

---

src/animation/AnimatedRotateComponent.js

This was always a silly-looking hack: what we really want is for
this animation to loop indefinitely, and we do that by saying it
runs for 1000 seconds.
It turns out that doing that makes it extremely slow to start up!
Specifically, in my desktop Android emulator (which is typically
1x-2x the speed of my physical Pixel 4), it takes about 500ms.
Worse: it blocks the entire JS thread while it does that.  So
the app's whole UI is stalled.
Because we use this at startup (in LoadingIndicator), it's been
adding that 500ms of lag (likely more like 1000ms on many devices)
to our startup time since forever.  Moreover, we use
LoadingIndicator in the "Connecting..." banner... which there's
*four* of, one on each of the app's main-screen tabs.  So when we
start loading -- which is promptly after each …

Fix major startup lag, by using Animated.loop instead of giant duration

---

.eslintrc.yaml
src/__flow-tests__/nav-test.js
src/api/realmDataTypes.js
src/common/ZulipButton.js
src/generics.js
src/react-native-action-sheet.js
src/react-native-safe-area-context.js
src/react-navigation.js
src/react-redux.js
src/start/IosCompliantAppleAuthButton/index.js
src/types.js
tools/fmt
tools/lib/eslintignore.sh
tools/test

This conflicts with our prettier config, and doesn't seem to be very
useful. It's disabled by default upstream, and was added in a1edcaa16
without any explanation. We frequently needed to disable it.
See https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/fmt.2Ftest.20prettier.20mismatch/near/1326785

Remove flowtype/generic-spacing lint.

---

src/webview/MessageList.js
src/webview/__tests__/generateInboundEventEditSequence-test.js
src/webview/generateInboundEventEditSequence.js
src/webview/generateInboundEvents.js
src/webview/html/messageListElementHtml.js

I noticed this in `messageListElementHtml` while writing up the new `docs/howto/new-feature.md`. Then it propagates to a small nice change in the message-list diffing code.

msglist: Stop checking narrow where we no longer need to

---

src/styles/tabs.js

This should cut down the Flow errors with Flow v0.149.0 by 69.
Flow errors before (155): [before.txt](https://github.com/zulip/zulip-mobile/files/8065928/before.txt)
After (86): [after.txt](https://github.com/zulip/zulip-mobile/files/8065927/after.txt)

react-nav config [nfc]: Un-deduplicate bottom and top nav default configs

---

src/__tests__/lib/exampleData.js
src/action-sheets/index.js
src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.android
src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.ios
src/webview/__tests__/generateInboundEventEditSequence-test.js
src/webview/generateInboundEventEditSequence.js
src/webview/generateInboundEvents.js

And a bugfix caught by one of the new tests!
I'm going down the list at https://github.com/zulip/zulip-mobile/pull/5188#issuecomment-1009484564, and Greg's comment on [CZO](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/msglist-diffing.20tests/near/1320910):
> These do give us a reminder that it'd be good to have HTML snapshots testing those features of the message list, though:
> * reactions
> * polls
> * starred messages
> * muted senders
This PR does those HTML snapshots in those four bullet points, and most of this part of https://github.com/zulip/zulip-mobile/pull/5188#issuecomment-1009484564:
> And for within a given message:
> 
> * Add/remove reactions to a message.
> * Update a poll's data.
>   
>   * Hmm, I wonder if our existing shortcut I mentioned here: [Implement …

msglist-diffing: More tests! 🛠️

---

src/events/eventToAction.js

Putting the event type into the error message will cause Sentry
to split these up as separate Sentry issues by event type, which
will make it much easier to quickly see what types are missing
and which of those are most frequent.
On the other hand, other than the type there's really no information
that we need here from the event; the type tells us what case we need
to add.  (For some event types, the code to handle it will be further
subdivided by `op`, but that'd be a separate conditional or switch
and wouldn't reach this default case anyway.)  So drop the rest.
Also add a comment noting that this isn't the only way that events go
unhandled, linking to the issue about that.

event: Log less, but better organized, on unhandled events

---

src/__tests__/lib/exampleData.js
src/api/modelTypes.js
src/autocomplete/StreamAutocomplete.js
src/common/Icons.js
src/nullObjects.js
src/storage/__tests__/migrations-test.js
src/storage/migrations.js
src/streams/StreamCard.js
src/streams/StreamIcon.js
src/streams/StreamItem.js
src/streams/StreamList.js
src/title/TitleStream.js
src/types.js
src/unread/UnreadCards.js
src/unread/__tests__/unreadSelectors-test.js
src/unread/unreadSelectors.js

This PR ensures that when a stream is web-public the icon representing
it is displayed as a globe - unless the stream is private or muted in
which case those icons take precedence.
This PR addresses one part of https://github.com/zulip/zulip-mobile/issues/5014

streams: Decorate web public streams

---

src/main/MainTabsScreen.js
src/main/StreamTabsScreen.js
src/reactions/MessageReactionsScreen.js
src/sharing/SharingScreen.js
src/styles/tabs.js

While reading #5234, noticed this followup opportunity.
/cc @chrisbobbe

react-nav config [nfc]: Further simplify bottom-tabs and top-tabs configs

---

src/third/redux-persist/getStoredState.js

As discussed in the office today.

redux-persist: Stop erroring on a case we've seen empirically

---

ios/Podfile.lock
package.json
yarn.lock

This release reportedly fixes the issue that made the "@" icon look
weird (the issue that was keeping us below 7.1.0):
https://github.com/oblador/react-native-vector-icons/pull/1311#issuecomment-1038258615
I've checked on iOS and Android, and the icon looks right at this
version.
See changelog:
https://github.com/oblador/react-native-vector-icons/releases
A few breaking changes were announced, but none that would affect
us:
- Icon.TabBarItemIOS convenience component removed as it was removed
from React Native core.
- Breaking change: Drop support for
react-native-web/react-native-desktop aliasing.
I didn't notice anything wrong with the icons on a quick tour of the
app at this version, on iOS or Android.

deps: Upgrade react-native-vector-icons to 9.1.0, the latest

---

package.json
yarn.lock

I think we still don't trust the maintainers to have a strategy on
breaking changes (see earlier bumps of this dep), so we'll still
leave out the caret here. But I've kicked the tires on iOS and
Android and this seems to be fine.
See changelog:
https://github.com/formatjs/formatjs/blob/main/packages/react-intl/CHANGELOG.md
Nothing listed there looks likely to be breaking.

deps: Upgrade react-intl to 5.24.6, the latest

---

src/boot/StoreProvider.js
src/message/fetchActions.js

We've been updating these only after the reducers do their work.
But there's quite a bit of surface area in the reducers -- and
particularly so in the handling of REGISTER_COMPLETE actions.
So we do sometimes have bugs that cause exceptions there.
When we do, make sure we get accurate information about what
Zulip server versions might be involved in triggering them,
to help with debugging.

logging: Set server-version tags immediately on fetch

---

src/__tests__/lib/exampleData.js
src/actionTypes.js
src/api/eventTypes.js
src/api/misc.js
src/api/modelTypes.js
src/caughtup/__tests__/caughtUpReducer-test.js
src/caughtup/caughtUpReducer.js
src/chat/ChatScreen.js
src/chat/__tests__/narrowsReducer-test.js
src/chat/narrowsReducer.js
src/events/doEventActionSideEffects.js
src/events/eventToAction.js
src/message/__tests__/messagesReducer-test.js
src/message/messagesReducer.js
src/nav/navActions.js
src/reactUtils.js
src/unread/__tests__/unreadModel-test.js
src/unread/unreadModel.js

The main things this does are:
* Fix an existing bug where if you have a ChatScreen and all the messages go away, we'll show NoMessages and get stuck there (until the user navigates out of the screen and back in), even if our `state.caughtUp` correctly says that we actually don't know if there are any messages in the narrow.
* This is a bit of an edge case today, but would get much more easily triggered after the other changes.
* #2688
* #5251, or rather the most conspicuous part of it; I'll open followup issues for the rest.
Fixes: #2688 
Fixes: #5251

Mostly handle topic edits / stream moves

---

android/app/build.gradle
android/app/src/main/java/com/zulipmobile/notifications/FcmMessage.kt
android/app/src/main/java/com/zulipmobile/notifications/NotificationUiManager.kt
android/app/src/test/java/com/zulipmobile/notifications/FcmMessageTest.kt
docs/style.md
src/api/notificationTypes.js
src/api/subscriptions/subscriptionAdd.js
src/diagnostics/StorageScreen.js
src/notification/__tests__/notification-test.js
src/notification/extract.js
src/notification/notifOpen.js
src/notification/types.js
src/pm-conversations/PmConversationList.js
src/sharing/ShareWrapper.js
src/unread/UnreadCards.js
src/unread/__tests__/unreadSelectors-test.js
src/unread/unreadSelectors.js

This follows #5246, #5223, #5205, #5183, #5069, #5056, #5000, and #4635 in switching us over from identifying streams by their names to doing so with their stable numeric IDs: #3918. This prevents buggy behavior when a stream gets renamed.
At this point the bulk of the work has been done already. The previous PR in this series, #5246, marked with `TODO(#3918):` all the remaining places we needed to fix. This PR then eliminates each of those in turn. Mostly this means parsing and using stream IDs when present in notifications; that's followed by a handful of trivial fixes.
As forecast at https://github.com/zulip/zulip-mobile/issues/3918#issuecomment-1026479673 , there remain some places where we use stream names that should be IDs, but these are limited to interacting with the server in …

Fix all remaining stream names to be IDs, modulo server support

---

src/__tests__/lib/exampleData.js
src/action-sheets/__tests__/action-sheet-test.js
src/action-sheets/index.js
src/topics/__tests__/topicsSelectors-test.js
src/unread/__tests__/unread-testlib.js
src/unread/__tests__/unreadModel-test.js
src/unread/__tests__/unreadSelectors-test.js
src/webview/MessageList.js
src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.android
src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.ios
src/webview/__tests__/generateInboundEventEditSequence-test.js
src/webview/__tests__/generateInboundEvents-test.js
src/webview/backgroundData.js
src/webview/generateInboundEventEditSequence.js
src/webview/handleOutboundEvents.js
src/webview/html/__tests__/header-test.js
src/webview/html/header.js
src/webview/html/message.js
src/webview/html/messageListElementHtml.js

This makes a series of cleanups to the action-sheet code and its tests, in preparation for #5202 adding another option to one of the action sheets.
The first part of the branch pulls a selector `getBackgroundData` out of MessageList and uses that to replace the ad-hoc code for constructing a BackgroundData in exampleData.js. That's done here because the action-sheet tests wanted it; it also covers the first step or two of the plan discussed at https://github.com/zulip/zulip-mobile/pull/5225#discussion_r803329533 for the message-list-diff tests.
A followup to do sometime is to take the other action sheet, the one in `LightboxActionSheet.js`, and fold it into using the same system we have for these other action sheets. (That doesn't necessarily mean moving it to this file; it might be best …

Clean up action-sheet code and example BackgroundData

---

src/action-sheets/index.js

Provide visual feedback to the user when they copy a link to a topic to
the clipboard in the form of a toast displaying the message: "Link
copied".

streams: Show toast confirming topic link copied.

---

src/action-sheets/index.js
src/utils/internalLinks.js
static/translations/messages_en.json

Adds a "Copy link to stream" action to the stream action sheet which
copies the full URL to a stream narrow to the system clipboard.
Fixes #5154.

streams: Add "Copy link to stream" stream action.

---

src/api/messages/sendMessage.js
src/api/messages/updateMessage.js
src/api/modelTypes.js
src/chat/ChatScreen.js
src/message/__tests__/messagesReducer-test.js
src/webview/html/header.js

The bulk of the places we mention "subject" are direct references to
either the property of that name on `Message` or somewhere else in
the server API.  Most of those, and in particular `Message#subject`,
are still that way in the current API.
Those will be an annoying giant conversion, so I have no desire to be
in a rush to do them.  In particular, for any given piece of API, I
won't want to make a conversion before we've at least settled on the
API change so that we can convert to what we know is the future API.
However, there are a handful of places where we say "subject" to
mean "topic" and it's entirely internal to the mobile app.  So
here we go ahead and fix those.
---
And in the handful of places where the API change has already happened on the server and we didn't already have a …

topic [nfc]: Fix internal references to "subject"; add TODO-server for others

---

src/webview/html/message.js

In the case of `poll_data.PollData` this isn't strictly necessary,
but for some other modules it's essential -- for example while
`typing_status.update` is a perfectly reasonable name, importing
that with a name of simply `update` would be terribly confusing.
Best to just be consistent.

shared [nfc]: Import shared code consistently like web does

---

.vscode/settings.json
docs/howto/editor.md

This is needed in order for format-on-save to work; without it,
VS Code doesn't know whether to use this or its built-in TS/JS
formatter.
I'd had the same setting in my personal VS Code settings on my
main desktop, so hadn't noticed its absence.  But really it's a
project-specific fact that we use Prettier, so the project's
settings is where it belongs.

vscode: Specify what auto-formatter to use

---

src/__tests__/lib/exampleData.js
src/emoji/Emoji.js
src/user-statuses/userStatusesCore.js
src/user-statuses/userStatusesModel.js
src/users/UserItem.js
src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.android
src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.ios
src/webview/__tests__/generateInboundEventEditSequence-test.js
src/webview/backgroundData.js
src/webview/generateInboundEventEditSequence.js
src/webview/html/message.js
src/webview/js/generatedEs3.js
src/webview/js/js.js
src/webview/static/base.css

Following https://github.com/zulip/zulip-mobile/pull/5277#pullrequestreview-903615927.
Fixes: #4925

Display emoji statuses in more places!

---

src/chat/ChatScreen.js
src/events/eventActions.js
src/session/sessionReducer.js

And make a few other cleanups and comments.
Fixes: #5022
Related: #5009

Stop event-polling for an account when it's logged out

---

android/app/build.gradle
docs/howto/build-run.md
docs/howto/release.md
tools/changelog

The great bulk of the size of our APK comes from the native
libraries in it (most of all libjsc.so).  Those exist in a
separate copy for each of our 4 ABIs, but any given device
is going to use only one of those.
So, build a separate APK for each ABI.  The new APK for armeabi-v7a
(the most widely-supported) is 35.1MB, compared to 132.3MB for the
old all-in-one APK.
This has no effect for the many Android users who get our app via
the Google Play Store: there, we already upload an AAB, which
Google splits up into several APKs still more finely.  See #3547.
Fixes: #5295
/cc @IzzySoft

android build: Split up APKs per ABI

---

src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.android
src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.ios
src/webview/__tests__/generateInboundEventEditSequence-test.js

See https://github.com/zulip/zulip-mobile/pull/5225#discussion_r803329533.
Thanks to Greg's #5272, which pulled out a `getBackgroundData` that this uses.

msglist tests: Use Redux state in inputs, not background data

---

src/users/UserItem.js

See the code comments, and see screenshots of the bug at
https://github.com/zulip/zulip-mobile/pull/5277#discussion_r826575976

UserItem: Fix recent regression where UnreadCount was misaligned

---

package.json
src/users/__tests__/userHelpers-test.js
src/users/userHelpers.js
yarn.lock

When invoking the typeahead filter for users it is desirable to be able
to see results for users with diacritics in their names even if the
filter does not contain the matching diacritics. This PR leverages
@zulip/shared typeahead module in order to strip diacritics out of the
filtering process, unless the user explicitly uses them in the filter.
Fixes: #3710

Typeahead remove diacritics

---

src/__tests__/lib/exampleData.js
src/chat/__tests__/narrowsSelectors-test.js
src/storage/__tests__/storage-test.js
src/users/__tests__/userHelpers-test.js
src/users/userHelpers.js
src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.android
src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.ios
src/webview/__tests__/generateInboundEventEditSequence-test.js
src/webview/html/__tests__/render-test.js

I was looking at the tests in `userHelpers-test.js` while reviewing #5292 (which added a few more tests there), and after merging that I wanted to make that file simpler and better set up to add more such tests.
Along the way I realized that `eg.makeUser` has a hidden gotcha in the `name` parameter, so I made a series of commits to untangle that.
There are still further improvements I might make to this file that I didn't get to today, but I think this is significantly better already.

Untangle eg.makeUser names; simplify some tests

---

flow-typed/react-intl_vx.x.x.js

Like we did for React Nav's libdefs in #5263. This will help us toward the RN v0.65 upgrade, #5230, by preparing to upgrade Flow.
Done by temporarily upgrading to Flow v0.149, which has [this bugfix](https://github.com/facebook/flow/blob/main/Changelog.md#01430) from Flow v0.143—
> * Previously, errors in library files were sometimes being missed due to a bug. This has been fixed, which may expose errors in library files that were not previously being reported.
—and going through the newly caught errors.
@gnprice, three of these errors remain after this branch. Would you be up for taking a stab at the best approach for them? You could add some commits if you see something easy, or else let me know a good direction and I'll do it. Thanks!
```
Error …
```

libdefs: Fix/suppress most glossed-over errors in react-intl libdef

---

.flowconfig
docs/howto/libdefs.md

As we move more and more modules into `.js.flow` files in this tree,
I wondered if we could avoid having to keep making this line longer
and longer to enumerate them.
Happily it seems we can!  I tested like so:
* Flow passes.
* If I edit something in `types/` in a way that should break a use
site in `src/`, I correctly get an error.
* Same if I instead edit something in `node_modules/react-native/`,
something we import directly from some path `react-native/…` --
the case covered by another of these `module.name_mapper` lines.
(I used the EditingEvent type imported by our SearchMessagesScreen
et al.)
* Same if I instead edit something in `node_modules` that has its
own Flow types.  (I used `@react-native-community/cameraroll`,
imported by our `src/lightbox/download.js`.)
* Same if I …

flow: Simplify module.name_mapper `types/` entry by generalizing

---

src/chat/ChatScreen.js
src/common/SmartUrlInput.js
src/reactUtils.js
src/start/RealmInputScreen.js
src/utils/__tests__/url-test.js
src/utils/url.js

(summary TODO)
Fixes: #5228
Supersedes: #4502

realm input screen: Offer nicer experience for copied URL

---

android/app/build.gradle
android/build.gradle
android/gradle.properties
package.json
src/api/apiFetch.js
yarn.lock

Prep for RN v0.65 upgrade

---

docs/howto/build-run.md
src/boot/store.js
src/storage/AsyncStorage.js
src/storage/CompressedAsyncStorage.js
src/storage/ZulipAsyncStorage.js
src/storage/__tests__/AsyncStorage-test.js
src/storage/__tests__/CompressedAsyncStorage-test.js
src/storage/__tests__/storage-test.js
src/utils/zulipVersion.js

This adds our own sound, nearly-drop-in replacement for RN's AsyncStorage.
The interface is (at least for now) nearly the same as the upstream AsyncStorage; it skips some methods we don't use, but when you call the methods it does have, it will always satisfy the spec for how the upstream AsyncStorage behaves.
The difference is that it also satisfies a tighter spec: each operation either happens completely or not at all.  No operation corrupts the database or has only partial effect, even if the process is killed or encounters I/O errors.
This is accomplished by using SQLite, and doing each operation in a transaction.  The upstream AsyncStorage does the same thing on Android; but on iOS, it uses an ad-hoc database which is susceptible to complete corruption if interrupted.
(Somehow I'd …

storage: Use SQLite to replace AsyncStorage

---

flow-typed/react-native-webview_v11.x.x.js

Discussion: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/react-native-webview.20and.20UIManager/near/1357825
When I started that thread, I assumed we'd be looking at converting the restated React Native types into actual imports of React Native types, which in particular means finding what the corresponding React Native types actually are.
Actually, I think we can just remove this stuff; see the commit messages for explanations. 🙂

react-native-webview libdef: Trim out some not-so-helpful definitions

---

src/common/ServerCompatBanner.js

Zulip Server 3.0 is now about 21 months old, well over the 18 months
we say we support.  So it's time we start nagging people to upgrade.
Cf. zulip/zulip#21779.

compat: Show "unsupported" banner for 2.1.x, too

---

src/common/ComponentWithOverlay.js
src/common/CountOverlay.js

This commit fixes `@` mention_count badge position.
Fixes: #5278

mention_count: Fixed `@` mention_count badge position correctly.

---

.flowconfig
docs/howto/profiling.md
ios/Podfile.lock
package.json
src/api/apiFetch.js
src/api/apiTypes.js
src/api/checkCompatibility.js
src/common/OfflineNotice.js
src/message/__tests__/fetchActions-test.js
src/webview/__tests__/generateInboundEventEditSequence-test.js
types/@react-native-community/netinfo/types.js.flow
yarn.lock

deps: Upgrade to RN v0.65!

---

src/users/UsersScreen.js

Keyboard Pops up unwantedly when you press `New PM` button and move towards the `UsersScreen`. This commit fixes this issue.
[See Discussion](https://chat.zulip.org/#narrow/stream/48-mobile/topic/keyboard.20issues/near/1303350)
Fixes: #5185

UsersScreen: Fixed the keyboard pop up unwantedly.

---

ios/Podfile.lock

These checksums appear on running `pod install` (or `yarn`, which
causes `pod install` to run), if I run it after removing
"ios/Pods/Local Podspecs". That's the case at current `main`, and
also at the recent RN v0.65 upgrade commit 72583b13c, but not just
before that commit.
Probably a4e941fe0 is related, and I should have remembered to try
clearing "Local Podspecs" when I did the RN upgrade. That would've
brought this to light at the time, and the new checksums would've
made it into the upgrade commit, where they belong.

ios: Update "SPEC CHECKSUMS" for DoubleConversion and glog

---

src/__tests__/lib/exampleData.js
src/api/modelTypes.js
src/api/streams/createStream.js
src/api/streams/updateStream.js
src/nullObjects.js
src/streams/CreateStreamScreen.js
src/streams/EditStreamCard.js
src/streams/EditStreamScreen.js
src/streams/streamsActions.js
src/users/userSelectors.js

On the path to a fix for https://github.com/zulip/zulip-mobile/issues/5250.

api: Sync updateStream and createStream with their API docs

---

src/__tests__/lib/exampleData.js
src/api/eventTypes.js
src/streams/__tests__/streamsReducer-test.js
src/streams/streamsReducer.js
src/subscriptions/subscriptionsReducer.js

After #5341, on the path to fixing #5250.

api: Sync update-stream event types with doc and align implementation

---

src/api/initialDataTypes.js
src/api/realmDataTypes.js
src/api/settings/getServerSettings.js

After #5346, on the path to fixing #5250. (#5351 is also currently open.)

api types: Sync more types with the API docs

---

src/streams/__tests__/streamsReducer-test.js

From discussion: https://github.com/zulip/zulip-mobile/pull/5346#discussion_r854633431
When writing this helper, if we leave out an annotation on its
parameter `event`, then we end up with a bunch of Flow errors:
* The type-checker sees that `event` can be any of several different
shapes, from the different call sites.
* It assumes that the type of `event` should be some one type -- just
as it normally assumes that any given parameter, variable, etc.,
should be some one type.  That type must therefore be a supertype
of all of those types from the call sites -- so, a supertype of
the union of those.
* Then that doesn't work (when the result of `mkAction` is eventually
fed to `streamsReducer`, which expects an `Action`), because there
is no branch of `Action` where that union type can go. …

streamsReducer tests [nfc]: Factor out a mkAction helper

---

src/api/settings/getServerSettings.js

Discussion: https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/.2Fserver_settings.3A.20.60realm_name.60.2C.20etc.2E/near/1334042

api: Make getServerSettings robust to server bug with missing realm_name

---

docs/howto/debugging.md
src/RootErrorBoundary.js

And add a section on using a test project in Sentry.

sentry: Pass all of `errorInfo` to `logging.error` after all

---

.github/workflows/ci.yml
docs/howto/build-run.md
package.json
tools/test

I've been using this for local development for a few weeks now,
and all seems well.  (That's longer than it needs to be; I just
hadn't come back to this to follow up.)
Node v12 is going EOL in just over a week, 2022-04-30, so it's
past time to make this upgrade official.
Also delete an old troubleshooting entry for a problem with Node v11
that was avoided by sticking to v10; and fix two other references to
Node v10 (where the problem was using an older version like v8) so
that they remain accurate now and for further upgrades in the future.
(At least until Node v1000.  On Node's current release cadence, that
will happen in a little under 500 years.  I think we can tolerate
having to tweak this check then.)
Fixes: #4263

deps: Upgrade to Node v16, in setup docs and in CI

---

src/__tests__/lib/exampleData.js
src/actionTypes.js
src/api/modelTypes.js
src/users/__tests__/usersReducer-test.js

After #5349, on the path to fixing #5250.

api types: Sync User and CrossRealmBot types with the doc, as of FL 121

---

.prettierignore
docs/howto/shared.md
package.json
src/emoji/__tests__/data-test.js
src/emoji/data.js
yarn.lock

This applies both to the typeahead in compose after you type a `:`,
and to the emoji search screen when you go to add a reaction to a
message.
The notable behavior change this gets us is nice behavior on spaces:
in your query you can now separate words with spaces, rather than
having to type underscores.  (It still works the same if you do type
an underscore.)
The main work here happened over on the shared side last week, where I fixed the one notable regression that the shared implementation had relative to our existing mobile implementation: https://github.com/zulip/zulip/pull/21871
Fixes: #4636

emoji: Switch to shared code for finding matches in typeahead/search

---

package.json
yarn.lock

To get chrisbobbe/react-navigation@b2343cb25, which I've published
to NPM in @zulip/react-navigation-bottom-tabs@5.11.16-0.zulip.1.
It cherry-picks react-navigation/react-navigation@d87857e5d, which
is a compatibility fix for RN v0.65 that React Navigation published
in v6 but didn't backport to v5.
So this fix will become unnecessary when we're on React Navigation
6; that's issue #4936.
A small handful of things went wrong when building the .d.ts files
for the publish to NPM, so some TypeScript types are lost, which is
fine because we don't use TypeScript. But the runtime code looks
like it's updated in the ways we'd want and expect.

deps: Temporarily use fork for @react-navigation/bottom-tabs

---

src/streams/CreateStreamScreen.js
src/streams/EditStreamCard.js
static/translations/messages_en.json

Show Alert when when we try to create a stream with an existing name.
Fixes: #5199

streams: Show alert when stream name already exists.

---

src/common/Icons.js
src/common/SelectableOptionRow.js
src/emoji/EmojiPickerScreen.js
src/streams/CreateStreamScreen.js
src/streams/EditStreamCard.js
src/streams/EditStreamScreen.js
src/streams/StreamSettingsScreen.js
static/translations/messages_en.json

I've got a draft for an input component that lets the user choose from more than two options, radio-button style, for https://github.com/zulip/zulip-mobile/issues/5250. These are some small improvements I've noticed while working on that draft.

stream settings: Prep for radio-button UI, to handle more than two privacy options

---

src/__tests__/lib/exampleData.js
src/api/modelTypes.js

In zulip/zulip@8ed605de1, we fixed the doc so that it correctly says
profile_data will be missing for bots because bots can't have custom
profile fields. Update our types (and make some test data more
representative) accordingly.

api types: Update User/CrossRealmBot about when profile_data is present

---

index.js
src/ZulipMobile.js

And add a note about a step specific to react-native-gesture-handler
that seems fine to omit for now.
See React Navigation's setup instructions at
https://reactnavigation.org/docs/5.x/getting-started#installing-dependencies-into-a-bare-react-native-project :
>   To finalize installation of `react-native-gesture-handler`, add
>   the following at the **top** (make sure it's at the top and
>   there's nothing else before it) of your entry file, such as
>   `index.js` or `App.js`:
> 
>   ```js
>   import 'react-native-gesture-handler';
>   ```
> 
>   > Note: If you are building for Android or iOS, do not skip this
>   > step, or your app may crash in production even if it works fine
>   > in development. This is not applicable to other platforms.
Well, better late then never, I guess. I …

react nav: Do an installation step we forgot about (oops)

---

src/api/initialDataTypes.js
src/realm/__tests__/realmReducer-test.js
src/realm/realmReducer.js
src/reduxTypes.js
src/storage/__tests__/migrations-test.js
src/storage/migrations.js

Following #5376, in which we synced `InitialDataRealmUser` with the doc, so that it includes `is_moderator`.

realm state: Store some realm settings, and `is_owner`/`is_moderator`, for web-public streams

---

src/__tests__/lib/exampleData.js
src/account/__tests__/accountsReducer-test.js
src/common/Icons.js
src/common/InputRowRadioButtons.js
src/common/SelectableOptionRow.js
src/common/SelectableOptionsScreen.js
src/message/__tests__/messagesReducer-test.js
src/nav/AppNavigator.js
src/pm-conversations/__tests__/pmConversationsModel-test.js
src/settings/LanguagePicker.js
src/storage/__tests__/CompressedAsyncStorage-test.js
src/streams/CreateStreamScreen.js
src/streams/EditStreamCard.js
src/streams/EditStreamScreen.js
src/third/redux-persist/persistStore.js
src/unread/__tests__/unread-testlib.js
src/user-statuses/UserStatusScreen.js
src/users/__tests__/usersReducer-test.js
src/utils/__tests__/recipient-test.js
src/utils/__tests__/zulipVersion-test.js
src/utils/misc.js
src/webview/__tests__/generateInboundEventEditSequence-test.js
static/translations/messages_en.json

~~This includes my current revision for #5360, which we hope to merge soon.~~ Done!
-----
For #5250, we'll need to let the user choose one among more than two
options. That'll call for a radio-button-style input, rather than a
switch.
So, make a new component InputRowRadioButtons, and use it for an
input labeled "Privacy", replacing the SwitchRow input labeled
"Private".
And, to support that component, write and wire up a new
SelectableOptionsScreen.

StreamSettingsScreen: s/Private/Privacy/; use radio buttons, not a switch

---

android/app/build.gradle

See
https://github.com/facebook/react-native/issues/32735#issue-1077061487
, where this workaround is copied from, and see a later comment on
the same issue saying that the official fix will arrive in RN v0.68.
Using Android Studio, Greg and I found that the version of soloader
that was pulled in before was 0.10.1. (Under the Packages list, we
went to Libraries/com/facebook/soloader, opened a random file, and
saw the version in Android Studio's title bar.)

android: Work around issue with "open failed: EACCES (Permission denied)"

---

src/common/Icons.js
src/streams/StreamItem.js
src/streams/SubscriptionsCard.js
src/subscriptions/StreamListCard.js
src/utils/info.js
static/translations/messages_en.json

Fixes: #4658
Hey @chrisbobbe!,
* I've tested the functionality and it is working, though it took so much time but I was able to complete. It would be a great help if you take a look at that.
* Here, I've used `Pressable` component of `react-native` instead of `TouchableOpacity`, because, when I looked into the docs there was not any prop named `disabled` for `TouchableOpacity`. So, I thought, may be `Pressable` would be a great choice.
* I will change the variable names, once the review will be done.
* Also, It would be great help if you could give me the idea of size of the icons, because when I looked into the [Switch](https://github.com/facebook/react-native/blob/main/Libraries/Components/Switch/Switch.js) component of `react-native`, there was no any reference of size of the `Switch` …

Changed UI for Subscription status for `All streams`

---

src/__tests__/permissionSelectors-test.js
src/api/initialDataTypes.js
src/api/modelTypes.js
src/api/permissionsTypes.js
src/permissionSelectors.js
src/realm/__tests__/realmReducer-test.js
src/realm/realmReducer.js
src/reduxTypes.js
src/storage/__tests__/migrations-test.js
src/storage/migrations.js

Things to call attention to in review:
- To duplicate code or not (esp. look at `permissionsSelectors` tests)
- `FullMemberOrAbove` not yet implemented correctly (!)—err on the side of more or less permissive? Or go ahead and implement properly?
- Bit of awkward realmReducer code, handling the event, explained by comment "Ignore create_stream_policy, if offered for backwards compatibility, if one of these is present." Keep, just to be safe, or verify that we can simplify?
Thanks!

permissionSelectors: Add getCanCreatePrivateStreams and getCanCreatePublicStreams

---

src/__tests__/permissionSelectors-test.js

Could some unintended behavior in addDays have caused the flake
discussed at
https://github.com/zulip/zulip-mobile/pull/5401#issuecomment-1148836433
?
In any case, this seems better because we don't have to think about
what special logic addDays might have.

permissionSelectors tests: Stop using date-fns to mock waiting period

---

src/__tests__/lib/exampleData.js
src/action-sheets/__tests__/action-sheet-test.js
src/action-sheets/index.js
src/api/modelTypes.js
src/common/ServerCompatBanner.js
src/common/ServerPushSetupBanner.js
src/compose/ComposeBox.js
src/directSelectors.js
src/message/fetchActions.js
src/permissionSelectors.js
src/realm/__tests__/realmReducer-test.js
src/reduxTypes.js
src/streams/EditStreamCard.js
src/streams/StreamSettingsScreen.js
src/streams/TopicItem.js
src/title/TitleStream.js
src/webview/backgroundData.js

And mark the non-live-updating properties as deprecated.

permissions: Use live-updating `role` property for all role checks, when available

---

flow-typed/prettier_v1.x.x.js
src/__tests__/lib/exampleData.js
src/api/eventTypes.js
src/api/modelTypes.js
src/api/realmDataTypes.js
src/api/streams/createStream.js
src/api/streams/updateStream.js
src/chat/ChatScreen.js
src/common/InputRowRadioButtons.js
src/common/Touchable.js
src/common/ZulipStatusBar.js
src/generics.js
src/react-navigation.js
src/realm/__tests__/realmReducer-test.js
src/settings/__tests__/settingsReducer-test.js
src/types.js
src/user-statuses/UserStatusScreen.js
src/users/__tests__/usersReducer-test.js
src/users/userSelectors.js
src/users/usersReducer.js
src/webview/html/message.js
types/react-intl.js.flow

Such a nicer syntax!  This is available to us now that we've
upgraded Prettier:
https://github.com/zulip/zulip-mobile/pull/5393#issuecomment-1151612888
and Flow before that:
https://github.com/zulip/zulip-mobile/pull/5398#discussion_r890444882
Leave in place a number of uses of $ElementType in TsFlower output.
The right way to update those will be for TsFlower to switch to
emitting the new syntax.

flow [nfc]: Convert $PropertyType and $ElementType to indexed-access syntax

---

ios/Podfile.lock
package.json
yarn.lock

We introduced this line in a7d19c0ed "deps: Force sqlite3 to use a
recent node-gyp", at a time when the sqlite3 package unnecessarily
required a much older version, node-gyp@3.x.
There's now a sqlite3 release (which we've taken) that updates that
dependency to node-gyp@8.x, the same thing our resolution was
requiring.  So drop the resolution and let the package's own metadata
govern from here.
This doesn't immediately change what version we actually use anywhere.
Before and after the change, `yarn why node-gyp` reports:
=> Found "node-gyp@8.4.1"
info Reasons this module exists
- "sqlite3" depends on it
- Hoisted from "sqlite3#node-gyp"
…
=> Found "ttf2woff2#node-gyp@9.0.0"
info This module exists because "@vusion#webfonts-generator#ttf2woff2" depends on it.

deps [nfc]: Drop resolution for node-gyp under sqlite3

---

src/__tests__/lib/exampleData.js

This was coming out as "2014-04-00" 1/30th of the time, which isn't
a valid date string.
As a result, when we go to parse that string in
getHasUserPassedWaitingPeriod or in its tests, it comes out as NaN
and things go haywire.  This caused the flake #5404.
Fix by making the day run from 1 through 30, instead of 0 through 29.
Fixes: #5404

example data: Fix date_joined on users to always be valid

---

src/settings/LanguagePicker.js

- Let's sort the languages, by locale, rather than put English first and the rest in English alpha order.
- When I search, then try to make a choice, it seems to take two taps -- one to dismiss the keyboard, the next to actually choose it. Let's make it take just one tap.

PR #3231 follow-up. settings: Build a better UI for choosing language.

---

src/api/initialDataTypes.js
src/realm/__tests__/realmReducer-test.js
src/realm/realmReducer.js

The introduction of this property isn't mentioned in the API docs
(it's from just before the time when we started being systematic
about such things), which is why we'd had it unconditionally here
in the type.
But from Sentry we know that ee74a9481, which started consuming
this data (and went to beta with v27.187), introduced an error for
a small number of users.  Looking at the server's commit history,
the property was introduced at this point.  Presumably any user
seeing this error is therefore on a pre-2.1 server.  (I believe
the symptom they see is that fresh server data never loads.)
So, mark this property as optional in the types, and add the tiny
bit of fallback code required to handle its absence.
At some point in the future we'll start refusing to handle data from
very old …

realm: Handle missing realm_default_external_accounts before 2.1

---

src/api/eventTypes.js
src/api/messages/getMessages.js
src/api/modelTypes.js
src/events/eventToAction.js
src/message/__tests__/messagesReducer-test.js
src/realm/__tests__/realmReducer-test.js
src/realm/realmReducer.js
src/reduxTypes.js
src/storage/__tests__/migrations-test.js
src/storage/migrations.js

For the plan, see the jsdoc and multi-part TODO added to `Message['edit_history']` in the second commit.
Maintaining an up-to-date `Message['edit_history']` is on the path to #5306.

messages reducer: Sketch a plan for keeping Message.edit_history current

---

docs/architecture/realtime.md
src/ZulipMobile.js
src/account-info/ProfileScreen.js
src/account/accountActions.js
src/account/logoutActions.js
src/boot/AppDataFetcher.js
src/boot/StoreHydratedGate.js
src/events/eventActions.js
src/haveServerDataSelectors.js
src/message/fetchActions.js
src/nav/getInitialRouteInfo.js
src/notification/notifOpen.js
src/reduxTypes.js
src/session/__tests__/sessionReducer-test.js
src/session/sessionActions.js
src/session/sessionReducer.js
tools/formatting.eslintrc.yaml

This is the next PR in my series toward better offline handling for the `/register` request.
We've long thought that the current logic is complex and fragile;
see for example
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Stuck.20on.20loading.20screen/near/907688

events: Remove brittle `needsInitialFetch` system

---

src/emoji/codePointMap.js

This reflects the change made in zulip/zulip@89b5a36e1 /
zulip/zulip#19537 .  Without this change, when adding a reaction
the options on our emoji-picker screen include two with this emoji:
🎉 congratulations
🎉 tada
If you pick the "congratulations" version when talking to a server
that has that server-side change, then adding the reaction fails.
This produced a user bug report:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/can't.20react.20with.20emojis/near/1394252
(It's a good thing we include the emoji code as well as the name
in the request; if we didn't, the symptom would instead be that
you end up leaving the reaction ㊗ instead, which seems worse.)
There are more changes in that server commit -- among them,
assigning the name "congratulations" to that other emoji ㊗,
and …

emoji: Cut `congratulations` alias to reflect server update

---

src/boot/TranslationProvider.js
src/common/Input.js
src/common/SelectableOptionRow.js
src/types.js
src/webview/__tests__/generateInboundEventEditSequence-test.js

As described at https://github.com/zulip/zulip-mobile/pull/5427#discussion_r907750949 . This encapsulates a common bit of logic needed in code that accepts a LocalizableText.
#5427 adds one more call site that would benefit from this. So after either this or #5427 is merged, the other should be updated to apply this change at that call site.

i18n [nfc]: Handle LocalizableText in `_`

---

src/api/messages/__tests__/migrateMessages-test.js
src/api/messages/getMessages.js
src/api/modelTypes.js
src/events/__tests__/eventToAction-test.js
src/events/eventToAction.js
src/message/__tests__/fetchActions-test.js
src/message/__tests__/messagesReducer-test.js
src/message/fetchActions.js
src/message/messagesReducer.js

Following the plan we made in #5422.
I'm not sure I'm quite happy with the last commit, where we set `edit_history` to `null` based on `allowEditHistory`. I've put the condition on `allowEditHistory` out to the edge (`eventToAction`, `api.getMessages`)…but that means plumbing `allowEditHistory` out to the edge. Is that OK?

messages state: Maintain `edit_history` to be reasonably current

---

android/app/src/main/java/com/zulipmobile/MainActivity.kt
ios/Podfile.lock
react-native.config.js
src/ZulipMobile.js
src/boot/ZulipSafeAreaProvider.js

This greatly improves performance on Android with many screens on
the nav stack!  On iOS, the effect is less dramatic, but still
significant.
Chris investigated this back in 2020 (#4111), and sent a draft PR
to enable it (#4161), but we never followed up, oops.  Better late
than never.
Experiment to repro the perf difference:
1. push like 30 ChatScreen screens to the stack, by following a
loop of internal links;
2. go to one with some backlog (by following the "up" icon to the
stream message-list);
3. try scrolling around.
Before, on Android: extremely laggy.  Also pretty laggy even just
following those links, after the first few.
After: pretty much as smooth with 30 screens on the stack as with the
first one.
On iOS, things seem to already be about as smooth with 30 screens as
with one, …

nav: Enable react-native-screens

---

src/unread/__tests__/unreadHuddlesReducer-test.js
src/unread/__tests__/unreadModel-test.js
src/unread/__tests__/unreadPmsReducer-test.js
src/unread/unreadHuddlesReducer.js
src/unread/unreadModel.js
src/unread/unreadPmsReducer.js
src/utils/recipient.js

This follows up on #4790 (/cc @WesleyAC) to handle group PMs and to add a workaround for https://github.com/zulip/zulip/issues/22164 . 
Also make a couple of small cleanups that I didn't include in the #4790 branch.
Fixes: #5361

unread: Finish handling mark-unread events

---

src/main/MainTabsScreen.js

Fixes: #5448 
Rename "Conversations" to "Private messages" (tablet UI).

Fixes: #5448 Rename "Conversations" to "Private messages" (tablet UI)

---

src/account-info/ProfileScreen.js
src/main/HomeScreen.js
src/main/MainTabsScreen.js
src/nav/ModalNavBar.js
src/nav/ModalSearchNavBar.js
src/pm-conversations/PmConversationsScreen.js
src/streams/SubscriptionsScreen.js

From discussion: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Regression.20in.20.22Streams.22.20screen/near/1412459
Regression introduced in 9d11e787f and not yet released.
There was [another thing going wrong](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Regression.20in.20.22Streams.22.20screen/near/1412491) which we fixed by upgrading `react-native-safe-area-context` to latest, in #5455.
The first commit is a rewrite of https://github.com/zulip/zulip-mobile/pull/5197/commits/1b5506a2f184cb28e7504cbae04a7012a4c8d8ff (on a draft PR) for current `main`.
Screenshots below, from my iPhone 13 Pro. You'll have to use your imagination to fill in the physical features of the screen that occupy the insets: the four corners are rounded, and there's a notch in the …

SubscriptionsScreen: Fix iOS regression where title looks wrong

---

src/message/messagesActions.js
src/utils/__tests__/internalLinks-test.js
src/utils/internalLinks.js

The goal of this PR is to make `getMessageIdFromLink` correctly return `message_id` from `/near/{message_id}` in a narrow link, so we can rely on it for #5306.
Since much of the work in that function is done by `getPathsFromUrl`, this gives some close attention to that function, cleaning it up and giving it a jsdoc. I've also proposed a plan for its further development with some TODOs.

internalLinks: Fix bugs in getMessageIdFromLink

---

src/common/NestedNavRow.js
src/common/SwitchRow.js
src/streams/SubscriptionsScreen.js
src/styles/miscStyles.js

And (experimental) use `NestedNavRow` in place of new duplicated code at the bottom of `SubscriptionsScreen`, from 9d11e787fd10d5ef07d7b1d8e02127c922e189c7.
See https://github.com/zulip/zulip-mobile/pull/5443#issuecomment-1192014031 for rationale.

layout: Fix warts in NestedNavRow and SwitchRow

---

.eslintrc.yaml

As planned; see discussion:
https://github.com/zulip/zulip-mobile/pull/5393#discussion_r893924345
With allowAsProps: true, it turns out that none of our code is
actually flagged as problematic.
See doc:
https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unstable-nested-components.md

eslint: Enable react/no-unstable-nested-components

---

src/user-statuses/UserStatusScreen.js
static/translations/messages_en.json

This implements the mobile counterpart to zulip/zulip#22828, 'Add an
"At the office" default status".

user status screen: Add "At the office" option, to follow web app

---

src/api/modelTypes.js
src/users/__tests__/userSelectors-test.js
src/users/userSelectors.js

Draft PR because the API isn't yet final. This uses the API from the current server-side prototype, https://github.com/zulip/zulip/pull/21588 .
Fixes: #5363

user: Show highlighted custom profile fields first

---

src/api/messages/getSingleMessage.js
src/message/messageSelectors.js
src/message/messagesActions.js
src/utils/__tests__/internalLinks-test.js
src/utils/internalLinks.js

Implementing the algorithm described in the issue and on CZO:
https://github.com/zulip/zulip-mobile/issues/5306#issuecomment-1198441223
> When a user clicks a `/near/` link in a message,
>
> 1. Get the message, either from our local data structures or
>    (failing that) from a single-message fetch, using the API added
>    in zulip/zulip#21391.
> 2. If the message is currently in the stream and topic encoded in
>    the `/near/` link, open the topic narrow for that stream/topic,
>    and scroll to the message*.
> 3. If the message was *at some point* in the stream and topic
>    encoded in the `/near/` link, according to its `edit_history`,
>    open the topic narrow for the stream/topic that the message is
>    currently in, and scroll to the message*.
> 4. Otherwise (i.e., the message …

messagesActions: Follow tapped /near/ links through message moves

---

src/reactUtils.js
src/webview/MessageList.js
src/webview/SinglePageWebView.js

In `MessageList.js` we have quite a bit of code that's really not about the message list in particular at all -- it's infrastructural, security-hardening code for having a webview that stays at some given static HTML and can't navigate elsewhere. This code has a very different character from the rest of the file, where we're doing important things like deciding what to show in the message list and keeping it updated.
By being in the midst of the actual message-list code, it gets in the way of reading, understanding, or modifying that code. Conversely, being entangled with the message-list code makes *this* code more complex to work with than it need be. Clarify things by separating it out.
I actually wrote a draft branch in this direction back in 2020-02. World events then intervened …

msglist [nfc]: Separate out "single-page webview" code from "message list" code

---

src/__tests__/lib/exampleData.js
src/account-info/AccountDetails.js
src/account-info/AccountDetailsScreen.js
src/account-info/ProfileScreen.js
src/api/initialDataTypes.js
src/api/modelTypes.js
src/api/permissionsTypes.js
src/realm/__tests__/realmReducer-test.js
src/realm/realmReducer.js
src/reduxTypes.js
src/storage/__tests__/migrations-test.js
src/storage/migrations.js
src/users/__tests__/userSelectors-test.js
src/users/userSelectors.js

Add prop showEmail to AccountDetails component.  When showEmail is true Account details will attempt to display the user email if available.
Add getDisplayEmailForUser to userSelectors which returns the user email if available or null if not defined or available by realm policy.
Add unit tests for above function.
Tested in iOS simulator 15.2 using using the chat.zulip.org
server and the recurse.zulipchat.com server.
Fixes: #5400

Add user email to profile display

---

src/actionTypes.js
src/api/eventTypes.js
src/api/messages/messagesFlags.js
src/api/modelTypes.js
src/chat/__tests__/flagsReducer-test.js
src/chat/flagsReducer.js
src/reduxTypes.js
src/storage/__tests__/migrations-test.js
src/storage/migrations.js
src/unread/__tests__/unreadHuddlesReducer-test.js
src/unread/__tests__/unreadMentionsReducer-test.js
src/unread/__tests__/unreadModel-test.js
src/unread/__tests__/unreadPmsReducer-test.js
src/utils/narrow.js
src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.android
src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.ios

We hadn't actually written down in our API types the set of valid flags on a message. Do that, and make some related cleanups along the way.
In particular, also cut from our `state.flags` type a bunch of flags that existed in 2017 but are now long dead, and which the mobile app never used.
This all came up in the course of working on #5364, as I looked at the `messagesFlags` API binding. I think in the end we [likely won't use](https://chat.zulip.org/#narrow/stream/378-api-design/topic/mark-as-unread.20request/near/1431173) that binding for implementing that feature, but the cleanups seem helpful anyway.

Clean up set of message flags

---

android/app/src/debug/AndroidManifest.xml
android/app/src/main/AndroidManifest.xml
android/app/src/main/res/xml/network_security_config.xml

In response to issue #3312. In Android, allow trusting user-added CAs, while still deferring trust to public CAs for both zulipchat.com and zulip.chat.org.
Fixes: #3312

Trust user-added CAs on Android

---

src/settings/SettingsScreen.js
static/translations/messages_en.json

Following Alya's proposal at
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/mark.20as.20read.20setting.20.23M5469/near/1433721
Related: #5469

SettingsScreen: Make conversation-views-only hint text more concise

---

android/build.gradle

This fixes a build failure which started happening today due to an operational mistake in React Native release management:
https://github.com/facebook/react-native/issues/35204
Happily Gradle gives us a way to more precisely pin down what we want it to do when finding dependencies, which makes the build robust to this and any similar issue.  I've sent the same fix upstream for the template app:
https://github.com/facebook/react-native/pull/35208
See also where we spotted the issue in CI:
https://github.com/zulip/zulip-mobile/pull/5524#issuecomment-1304311466
and discussion in chat:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/build.20failure.3A.20libfbjni.2Eso.20duplicated/near/1459787

android: Fix build to get react-native only from local Maven repo

---

src/api/__tests__/queueMarkAsRead-test.js
src/api/index.js
src/api/messages/toggleMessageStarred.js
src/api/messages/updateMessageFlags.js
src/api/queueMarkAsRead.js
src/chat/MarkAsReadButton.js

This matches the name in the OpenAPI description.  It also makes a more grammatical phrase, and reads more naturally and informatively at call sites.
(The old name dates from before we had OpenAPI descriptions; it seems to be based on the URL path, which was a reasonable choice at the time.)
I noticed this while writing the prototype for #5364. But the eventual real implementation of #5364 is planned to not use this endpoint at all (in favor of a new API endpoint that will better give us what we need), so that this rename would be a bit off-topic there. Hence sending this as a small separate PR.

api.updateMessageFlags [nfc]: Rename from messagesFlags

---

.gitignore
.tx/config
docs/howto/translations.md
tools/tx-pull
tools/tx-sync

Transifex is turning off their old API, and in the process they're abandoning their longtime CLI client.  In its place is a new one, written in Go.  ("For speed", though hilariously it's actually a bit slower.)  Discussion here:
https://chat.zulip.org/#narrow/stream/58-translation/topic/Transifex.20client/near/1460621
Update maintainer-facing docs to reflect the new client, and our scripts and config to be compatible with it.  The config changes came from the handy `tx migrate` provided in the new client.
Maintainers should read the new setup instructions and migrate accordingly:
* Install the new `tx` client.
* Update the format of the `.transifexrc` file.  (The new `token` is the old `password`.)
* Move the `.transifexrc` file to `~/`, if it was in the worktree.

i18n: Update for new Transifex client

---

docs/architecture/react.md
src/RootErrorBoundary.js
src/boot/TranslationProvider.js
src/sharing/ShareToPm.js
src/sharing/ShareToStream.js
src/sharing/ShareWrapper.js
src/webview/MessageList.js
src/webview/SinglePageWebView.js
src/webview/backgroundData.js
src/webview/handleOutboundEvents.js
src/webview/js/js.js

A followup to #5523, as foreshadowed at https://github.com/zulip/zulip-mobile/pull/5523#discussion_r999046773 . This is the next step toward the message-list changes I'll want to make for #5364.
The tricky part here is the way we have MessageList seize the baton from React when it comes to updating the UI to reflect changes in data, and go take care of those updates by other means.
With a class component for MessageList, we've accomplished this by implementing `shouldComponentUpdate` to prevent re-renders. This has always been a bit of a latent bug, because that method's docs disclaim any guarantee of always preventing a re-render. In this branch, we:
* update some discussion around that use of `shouldComponentUpdate` to reflect changes that have already happened;
* then make some small …

msglist: Convert MessageList to a function component with Hooks

---

.eslintrc.yaml
src/__tests__/collections-test.js
src/collections.js
src/utils/__tests__/recipient-test.js
src/utils/presence.js
src/webview/__tests__/generateInboundEvents-test.js
src/webview/generateInboundEvents.js
src/webview/js/InboundEventLogger.js
src/webview/js/generatedEs3.js
src/webview/js/js.js

Ran into this while implementing #5364. But it also fixes an already-live bug, for when a user marks messages unread from a *different* client while they have a message list open.
Fixes: #5536

msglist: Update when messages marked unread

---

src/webview/MessageList.js

This follows up on #5524 by replacing the various props-providing higher-order components we have wrapping this component -- `connect`, `connectActionSheet`, `withGetText` -- with just more hooks. `MessageList` is now simply a function component, rather than a series of wrappers around an inner function component.
As a bonus, we clean up a pair of calls to `assumeSecretlyGlobalState`.
Like #5524, this is on the road to #5364.

msglist [nfc]: Convert the wrapper HOCs to more Hooks

---

src/api/messages/updateMessageFlags.js
src/api/queueMarkAsRead.js

queueMarkAsRead: Limit size of our requests
We're currently asking the server to mark a potentially unbounded
number of messages as read, all in a single request.  Instead,
limit the size of the request to 1000 messages at a time -- the
same number the web app uses.
Fixes: #3423
---
queueMarkAsRead: Stop using server's misleading "messages" list
It turns out that the actual behavior of this response property is
that it just echoes the same message IDs we listed in the request.
So we might as well use the list we sent, instead.
Moreover, if this did tell us only those messages that were actually
affected, then among the messages left out would be messages that a
retry would have no better shot at affecting: messages that are
already read, or have been deleted.
(In fact on current server …

Mark as read in bounded batches; ignore "messages" in response

---

docs/howto/build-run.md

From discussion on CZO:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/Android.20Build.20fails.20on.20MacOS/near/1452810

build-run doc: Add troubleshooting entry for odd, hard-to-debug build error

---

src/action-sheets/index.js
src/nav/navActions.js
src/streams/StreamItem.js
src/streams/TopicItem.js
src/title/TitleStream.js
src/webview/MessageList.js
src/webview/handleOutboundEvents.js

(I plucked this small PR from some work I did while dealing with #5489 but that didn't make it into #5489.)

action-sheets: Use `navigation` object instead of NavigationService

---

src/common/WebLink.js
src/settings/LegalScreen.js

This bug was reported in chat:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/Links.20in.20user.20profile/near/1466262
While we're at it, make the same adjustment for `LegalScreen`, where presumably the user's setting should also apply. The user taps a "link" (well, a `NestedNavRow`) that's supposed to open a web page:

WebLink: Use openLinkWithUserPreference instead of openLinkEmbedded

---

src/action-sheets/index.js

We already have comments saying the strings are UI strings that should be represented in messages_en.json. But this reinforces the point, and also lets you pass the kind of LocalizableText that is an object with `.text and `.values`.
(I plucked this tiny PR from some work I did while dealing with #5489 but that didn't make it into #5489.)

action-sheets types: Make Button's title/errorMessage LocalizableText

---

android/app/src/main/java/com/zulipmobile/MainActivity.kt
ios/ZulipMobile/AppDelegate.m

It turns out that when I did the Expo 44 upgrade in #5441, there were a few changes to Expo's template app that I didn't consider, because they weren't mentioned in the [upgrade guide](https://blog.expo.dev/expo-sdk-44-4c4b8306584a#8ff0) and I guess I didn't go and look at the actual commits.
Details [in chat](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Expo.2044.20small.20things/near/1452850), including the list of commits and how we filtered them down to these two changes.

Follow some Expo 43 -> 44 template-app changes, belatedly

---

src/chat/ChatScreen.js
src/common/KeyboardAvoider.js
src/compose/ComposeBox.js

ChatScreen: Fix blank strip between compose box and keyboard on iOS

---

src/action-sheets/index.js
src/chat/ChatScreen.js
src/compose/ComposeBox.js
src/webview/MessageList.js
src/webview/handleOutboundEvents.js
tools/test

We've had the name "files" for both a global representing the
user's choice of which files to operate on, and a local inside
the run_lint function.
This collision was there for a long time without causing a live
problem, and then started doing so with f3aad7ea2 where we moved
a function call that consulted the global so that it occurred
inside run_lint, with the local active.  (Bash "local" variables
are only sort of local -- they're dynamically scoped, rather than
lexically scoped.)
The effect of the issue is that the "lint" suite would always
succeed without checking anything, because `files_js` would
always produce no output.
Fix it by giving the global a longer, more explicit name, `opt_files`.
Also rename other options globals similarly.
Fixes: #5574 
---
This PR is a draft because …

tools/test: Fix regression that disabled ESLint

---

.flowconfig
package.json
yarn.lock

This is the Flow version used by React Native 68.
It's a surprisingly easy upgrade this time, following the recent Expo 45 upgrade (#5507), which caused `fbemitter` to be bumped such that it no longer used Flow's legacy "weak" mode, removed in Flow v0.166.

flow: Upgrade to v0.170

---

src/common/Screen.js
src/search/SearchMessagesScreen.js

The main change is this one:
```
Screen: Move padding into ScrollView's content area
Before, the vertical padding decreased the height of the window onto
the scrollable area.
Now, the vertical padding is *in* the scrollable area, and it can be
scrolled offscreen, giving more room for the actual content to show.
This is especially helpful on a phone in in landscape mode, where
vertical space is tight.
Affected screens are the ones where true is passed for `padding` and
`scrollEnabled` is true (or unset, because it defaults to true):
AccountPickScreen
AuthScreen
PasswordAuthScreen
RealmInputScreen
CreateStreamScreen
EditStreamScreen
```
All the rest are NFC refactors. Screenshots coming soon.

Screen: Move padding into ScrollView's content area

---

shell.nix

This works for me on NixOS 22.05.
(I haven't yet tested it on NixOS 22.11, which since Wednesday is now the latest release.)
```
#
#
```
/cc @WesleyAC @andersk

nix: Add a shell.nix file

---

src/__tests__/lib/exampleData.js
src/account/AccountPickScreen.js
src/account/__tests__/accountsReducer-test.js
src/account/accountsReducer.js
src/api/initialDataTypes.js
src/api/registerForEvents.js
src/api/settings/getServerSettings.js
src/events/eventActions.js
src/start/AuthScreen.js
src/start/RealmInputScreen.js

This will help with #5102 by making it convenient to have these API bindings validate the server version and throw a new error type with a name like `ServerTooOldError`.
(Those bindings are two of the ways we can learn about the server version. There is a third, that I know of: `'restart'` events, which happen when the server is upgraded. I suppose we'd also get one on server _downgrades_, and in theory, on downgrades where the server version crosses the two-old threshold in the wrong direction. But that seems unlikely.)

[toward #5102, refuse ancient servers] Parse `zulip_version` in api.getServerSettings and api.registerForEvents

---

android/app/build.gradle

This makes it a bit cleaner for going on to add another dependency. It should also slightly simplify future RN upgrades.
This comes from my draft branch toward #5117.

android build [nfc]: Organize dependencies a bit

---

LICENSE
README.md
package.json

Similar to https://github.com/zulip/zulip/pull/17176 .
This makes the whole LICENSE file an exact copy of the license,
which helps some software recognize that this is indeed the
Apache 2.0 license.  In particular, the `licensee` gem, which
is what GitHub uses to identify what license to display.

Strip copyright notice from LICENSE; update the one in README

---

src/account/accountActions.js
src/boot/store.js
src/notification/notifOpen.js
src/reduxTypes.js

As foreshadowed in some comments, and requested by @chrisbobbe [in chat](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/GlobalThunkExtras/near/1476519).
This is also one of the pieces we'll need for #5006.

redux [nfc]: Give an activeAccountDispatch to global thunk actions

---

src/api/initialDataTypes.js
src/chat/__tests__/flagsReducer-test.js
src/chat/flagsReducer.js
src/user-groups/__tests__/userGroupsReducer-test.js
src/user-groups/userGroupsReducer.js

(Marking P1 because this came up during work toward https://github.com/zulip/zulip-mobile/issues/5102, disallow ancient servers.)
Fixes: #5596
Fixes: #5597

model: Use Flow and example data for user-groups and flags model tests (and fix some bugs in live code!)

---

src/alertWords/__tests__/alertWordsReducer-test.js
src/alertWords/alertWordsReducer.js
src/api/eventTypes.js
src/mute/__tests__/muteModel-test.js
src/mute/muteModel.js
src/presence/__tests__/presenceReducer-test.js
src/presence/presenceReducer.js
src/unread/unreadHuddlesReducer.js
src/unread/unreadMentionsReducer.js
src/unread/unreadModel.js
src/unread/unreadPmsReducer.js

(Marking P1 because this came up during work toward https://github.com/zulip/zulip-mobile/issues/5102, disallow ancient servers.)

presence tests: Start type-checking; use example data

---

src/topics/__tests__/topicsReducer-test.js

(Marking P1 because this came up during work toward https://github.com/zulip/zulip-mobile/issues/5102, disallow ancient servers.)

topics tests: Start type-checking; use example data

---

src/account-info/CustomProfileFields.js

FYI @alya for the UX change.
Fixes: #5592

CustomProfileFields: Use `selectable` prop for text fields

---

package.json
yarn.lock

I believe we don't ever use the `expo` CLI.
The `expo-cli` package is apparently in maintenance mode. It doesn't and won't support Node 18, the current LTS:
https://github.com/expo/expo-cli/issues/4583
https://github.com/expo/expo-cli/pull/4281
That effectively gives it an EOL of 2023-09, the EOL date of Node 16, which is less than a year away.
There's a successor CLI in the works:
https://blog.expo.dev/the-new-expo-cli-f4250d8e3421
But since we don't actually use this CLI in the first place, we can wait to pick that up until we find a need for it.
As a bonus, dropping this sheds about 90MB from our node_modules tree.

deps: Drop expo-cli

---

android/app/build.gradle
android/build.gradle
android/gradle.properties
android/gradle/wrapper/gradle-wrapper.properties
docs/howto/build-run.md
package.json
tools/android
tools/gradle
tools/run-android
tools/test

Part of #5344.
Plus a handly little `tools/gradle` script, to save typing `cd android` and `cd ..` all the time when running Gradle tasks (and to simplify various scripts and docs by not having to track a different working directory.)

android build: Follow some changes from RN v0.68

---

android/app/build.gradle

This follows upstream's instructions:
> Note: the version listed above may not be updated in time. Please
check `ReactAndroid/gradle.properties` in the main repo to see which
fresco version is being used in a specific tagged version.
https://reactnative.dev/docs/0.67/image#gif-and-webp-support-on-android
except in an automated way.  Happily this is even reasonably clean.
Fixes: #5607

android: Fix animated GIFs in lightbox, by getting Fresco version automatically

---

docs/style.md
src/chat/__tests__/narrowsReducer-test.js
src/chat/__tests__/narrowsSelectors-test.js
src/message/__tests__/fetchActions-test.js
src/pm-conversations/__tests__/pmConversationsSelectors-test.js
src/storage/__tests__/replaceRevive-test.js

From discussion: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.60Immutable.2EMap.28.7B.20.5BSTRING_CONST.5D.3A.20.E2.80.A6.20.7D.29.60.20busted.20by.20Flow.20bug/near/1481093

flow: Forbid object-as-map when constructing `Immutable.Map`s

---

docs/style.md
src/alertWords/__tests__/alertWordsReducer-test.js
src/caughtup/__tests__/caughtUpReducer-test.js
src/chat/__tests__/fetchingReducer-test.js
src/chat/__tests__/narrowsReducer-test.js
src/chat/__tests__/narrowsSelectors-test.js
src/drafts/__tests__/draftsReducer-test.js
src/message/__tests__/fetchActions-test.js
src/message/__tests__/messagesReducer-test.js
src/outbox/__tests__/outboxReducer-test.js
src/pm-conversations/__tests__/pmConversationsModel-test.js
src/pm-conversations/__tests__/pmConversationsSelectors-test.js
src/session/__tests__/sessionReducer-test.js
src/session/sessionReducer.js
src/settings/__tests__/settingsReducer-test.js
src/settings/settingsReducer.js
src/storage/__tests__/replaceRevive-test.js
src/typing/__tests__/typingReducer-test.js

Oops, it seems I should have thought a bit harder for #5606. 🙂 In particular, this PR picks up some threads I dropped there:
- Give test coverage for all the reducers that use the new `RESET_ACCOUNT_DATA` action.
- Clear per-account `session` state on `RESET_ACCOUNT_DATA`
- Clear per-account `settings` state on `RESET_ACCOUNT_DATA`
Those interesting changes come after a string of code-style tightenings (and one "start using Flow" commit) for several of the test files they touch.
Fixes: #4446

(More) consistently clear old data on all ways of leaving an account

---

src/account-info/CustomProfileFields.js
src/common/WebLink.js
src/common/ZulipText.js
src/message/ReadReceiptsScreen.js
src/start/PasswordAuthScreen.js
src/start/RealmInputScreen.js
static/translations/messages_en.json

A resumption of #5601, which I accidentally closed abruptly by deleting the branch on my GitHub fork. 😵 Sorry for the confusion!
-----
This revision has changes for all the reviews before https://github.com/zulip/zulip-mobile/pull/5601#issuecomment-1347898717 _except_ these two:
@gnprice said at https://github.com/zulip/zulip-mobile/pull/5601#pullrequestreview-1214148293:
> The very last bit, the "Suggestion: [link]" line, is intriguing but I feel like I want to chew on it a bit more, and on the logic for exactly when and what suggestion we show.
@alya said at https://github.com/zulip/zulip-mobile/pull/5601#issuecomment-1347632620:
> I think if you tap on the URL suggestion, it should just auto-complete, but not connect until you press the "Enter" button. Maybe you wanted to auto-fill it …

(resumption) RealmInputScreen: Improve validation rules; give "What's this?" link about realm URL; offer dynamic suggestions

---

src/chat/__tests__/fetchingReducer-test.js
src/chat/fetchingReducer.js
src/topics/__tests__/topicsReducer-test.js
src/topics/topicsReducer.js
src/typing/__tests__/typingReducer-test.js
src/typing/typingReducer.js

This addresses the second item in the list at #5605:
> - [ ] `REGISTER_COMPLETE` should reset or replace all server data
>       and server-data metadata, but it isn't in some cases:
>       - server data: `topics`, `typing` (should reset)
>       - server-data metadata: `fetching` (should reset)
Although, I've left a comment on `fetchingReducer`, where doing so
felt a bit funny because morally it shouldn't be necessary.
Fixes-partly: #5605

model: Make REGISTER_COMPLETE reset some state we forgot about

---

src/common/WebLink.js

This fixes a regression introduced in 72280dd96, released in the v27.198 beta. The underlying ZulipText was throwing its error
`text` or `children` should be non-nullish
when the user navigated to a profile screen that tried to render a "link" type custom profile field, such as a GitHub link.

WebLink: Forward text prop to ZulipText, fixing CustomProfileFields crash

---

src/compose/ComposeMenu.js
src/lightbox/download.js
src/reactNativeUtils.js
static/translations/messages_en.json

Planned followup to https://github.com/zulip/zulip-mobile/pull/5474.
-----
We recently completed the feature of not immediately sending
messages with image uploads, in #5474. With that, it became possible
to send a message with multiple uploaded images in it. But you had
to go through the image-selection flow once for each of your chosen
images; see discussion:
https://github.com/zulip/zulip-mobile/pull/5474#pullrequestreview-1246356066
This gives a smoother experience by letting you choose multiple
images in one image-selection session.
Related: #2366
Co-authored-by: Akash Dhiman <akash.d0407@gmail.com>
-----
cc @alya for the UX change

compose: Allow image multi-selection, where supported

---

src/typing/typingReducer.js

We don't clear other server data on DEAD_QUEUE, plus there's already a client-side component that makes this feature fail gracefully in the presence of stale server data (a timeout to clear typing indicators).
Fixes-partly: #5605

typing model: Don't reset on DEAD_QUEUE

---

src/__tests__/permissionSelectors-test.js
src/account-info/AccountDetails.js
src/action-sheets/index.js
src/api/modelTypes.js
src/api/permissionsTypes.js
src/permissionSelectors.js
src/users/__tests__/usersReducer-test.js
src/webview/backgroundData.js
static/translations/messages_en.json

Fixes: #5534 
In my contribution, I made the user's role visible on the user's profile. The user can have one of 5 roles: Owner, Guest, Member, Admin and Moderator. I have also added some translations for the roles in French. Here are some screenshots

Fixed Issue #5534 : Show user role in profile

---

src/api/apiErrors.js
src/api/pollForEvents.js
src/api/registerForEvents.js
src/api/settings/getServerSettings.js
src/common/ServerCompatBanner.js
src/events/eventActions.js
src/haveServerDataSelectors.js
src/message/fetchActions.js
static/translations/messages_en.json

With an error alert that appears at the following points:
On submitting `RealmInputScreen` (titled "Welcome"):
On selecting a logged-out account in `AccountPickScreen` (titled "Pick account"):
When we get a `/register` response from the active account's server. (The first screenshot is what happens on launch; the second is what happens when you select a logged-in account in `AccountPickScreen`.)
The alert says:
Title:
> Could not connect
Body:
> {realm} is running Zulip Server {version}, which is unsupported.
The "Learn more" button goes to https://zulip.readthedocs.io/en/stable/overview/release-lifecycle.html#compatibility-and-upgrading but later we'll want to change that to a new page; that's https://github.com/zulip/zulip/issues/23842.
cc @alya for the UX change.
Fixes: #5102

api: Don't allow connecting to servers <2.0

---

metro.config.js
package.json
src/utils/logging.js
yarn.lock

Note: I've so far only tested by running `yarn start` and observing that that doesn't crash.

js bundle: Try not to minify classnames that end in Error

---

src/__tests__/lib/exampleData.js
src/account/AccountItem.js
src/account/AccountList.js
src/account/AccountPickScreen.js
src/account/__tests__/accountsReducer-test.js
src/account/accountActions.js
src/account/accountsReducer.js
src/account/accountsSelectors.js
src/actionTypes.js
src/notification/notifOpen.js
src/storage/__tests__/migrations-test.js
src/storage/migrations.js

This turned out to be independent of #5633.

Use `Identity` instead of index for `ACCOUNT_SWITCH` and `ACCOUNT_REMOVE`

---

src/account/accountMisc.js
src/message/MentionedUserNotSubscribed.js
src/settings/NotificationsScreen.js
src/settings/SettingsGroup.js
src/styles/constants.js
src/types.js
static/translations/messages_en.json

Now that this screen can put up an app-level warning about notifications (that they're disabled in system settings; this was #5627), I think it's even easier to wrongly think that these three settings—
- Notifications when offline
- Notifications when online
- Stream notifications
—are app-level rather than account-level. So, group them together and make it clear that they're per-account.
Also hide them when the server declares that push notifications are disabled; in that case they're useless and could cause confusion.
And add an "Other accounts" row that links to `AccountPickScreen`, titled "Pick account". (I have a draft branch queued up that will put a warning on this row if the server of some other account hasn't acked the push token.)
cc @alya for the UX change.

NotificationsScreen: Section off per-account settings

---

src/account/AccountItem.js
src/account/AccountList.js
src/account/AccountPickScreen.js
src/account/accountsSelectors.js
src/sentry.js

Small follow-up from https://github.com/zulip/zulip-mobile/pull/5634#discussion_r1086139477 .

account [nfc]: Specialize getAccountStatuses as a view-model

---

src/chat/UnreadNotice.js

Starting in the unreleased commit 35129e50e, the unread notice would literally say:
{unreadCount, plural,
one {{unreadCount} unread message}
other {{unreadCount} unread messages}
}
because we forgot to give `values`. Oops; fixed now.

UnreadNotice: Pass `values` in pluralized unread-count string, fixing bug

---

src/common/ServerCompatBanner.js
src/common/ServerPushSetupBanner.js
src/common/WebLink.js
src/lightbox/LightboxActionSheet.js
src/lightbox/shareImage.js
src/message/messagesActions.js
src/settings/LegalScreen.js
src/start/AuthScreen.js
src/start/CompatibilityScreen.js
src/start/webAuth.js
src/utils/__tests__/internalLinks-test.js
src/utils/info.js
src/utils/internalLinks.js
src/utils/openLink.js
src/webview/handleOutboundEvents.js
static/translations/messages_en.json

urls: Tell user when tapped link doesn't parse; fix a bug affecting iOS downloads

---

src/account/accountsReducer.js
src/mute/__tests__/muteModel-test.js
src/storage/__tests__/migrations-test.js
src/storage/migrations.js

In its handling of the actions REGISTER_COMPLETE, LOGOUT,
DISMISS_SERVER_PUSH_SETUP_NOTICE, and EVENT, the `accounts` reducer
has been making the unchecked assumption that there is an active
account.
When there isn't an active account (perhaps because the last account
was removed with ACCOUNT_REMOVE), the reducer has been creating
badly typed partial `Account`s, by creating an object from a spread
of `state[0]` which is `undefined`. For example, with
REGISTER_COMPLETE:
```js
{
...state[0],
userId: action.data.user_id,
zulipFeatureLevel: action.data.zulip_feature_level,
zulipVersion: action.data.zulip_version,
lastDismissedServerPushSetupNotice: action.data.realm_push_notifications_enabled
? null
: state[0].lastDismissedServerPushSetupNotice,
}
```
That will make an object with only …

accounts: Invariant that active account exists when we expect it to

---

src/sharing/ShareWrapper.js
static/translations/messages_en.json

ShareWrapper: Abort upload and show feedback when file upload fails

---

src/compose/ComposeBox.js

(This is a follow-up to #5661, in which we started showing similar feedback in the share-to-Zulip flow.)
Related: #5660

ComposeBox: Show more information on file-upload errors

---

src/api/transport.js

Anders points out on CZO [1] that non-ASCII UTF-8 characters are now
allowed in email addresses:
> From [RFC 6532 §3.2](https://www.rfc-editor.org/rfc/rfc6532#section-3.2):
> “The preceding changes mean that the following constructs now
> allow UTF-8: … 4. Domains.”
So, we need to accept those characters. Otherwise, you could have a
valid email address and be unable to make any authenticated API
requests in the app.
Use our handy helper function for base64 encoding that accepts UTF-8
as input.
[1] https://chat.zulip.org/#narrow/stream/378-api-design/topic/Non-ASCII.20email.2Fapi_key.3F/near/1300579

transport: Accept international email address when making auth headers

---

src/types.js

At some point this was on the path to my work to warn about push-token ack problems, but it seems not to be. Still, nice and easy to do.

types: Make Account object type read-only

---

src/caughtup/__tests__/caughtUpReducer-test.js
src/caughtup/caughtUpReducer.js
src/chat/__tests__/flagsReducer-test.js
src/chat/__tests__/narrowsReducer-test.js
src/chat/fetchingReducer.js
src/chat/flagsReducer.js
src/chat/narrowsReducer.js
src/message/__tests__/messagesReducer-test.js
src/message/messagesReducer.js
src/outbox/outboxReducer.js
src/streams/__tests__/streamsReducer-test.js

This addresses the following item in the list at #5605:
> - [ ] Some reducers don't have a comment saying why they reset
>       state on `REGISTER_COMPLETE` instead of taking data from its
>       payload:
>       - For example, `flagsReducer` should point out that
>         `messagesReducer` doesn't store messages on
>         `REGISTER_COMPLETE`, and `messagesReducer` should say that
>         it doesn't do that because we fetch messages with
>         `GET /messages`.
>       - (Probably plenty of other instances.)
Fixes-partly: #5605

model [nfc]: Comment on rest of REGISTER_COMPLETE handlers that reset state

---

src/account/AccountItem.js

| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/22248748/219826345-207ba0e4-b4d2-423a-b3aa-4be04157e182.png) | ![image](https://user-images.githubusercontent.com/22248748/219826364-da20a8b0-f0c7-41cd-8d72-7ca9e81af4a4.png) |
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/22248748/219826298-a532136b-e6bb-44b0-b07f-62e9caee06ff.png) | ![image](https://user-images.githubusercontent.com/22248748/219826280-8ebf8d92-2a85-4be8-9998-0b5e1e00c29b.png) |

AccountItem: Fix trash icon touch target's invasion of notif-warning icon's

---

src/reactNativeUtils.js

As of writing, we've seen this reported to Sentry from two installs of the app on iOS 16.2.
useAppState's callers don't try to take meaning from the returned value, they just use it in a useEffect dependency array. So they don't have to grow special logic to handle the new branch.

reactNativeUtils: Add 'unknown' branch to AppStateValues

---

src/api/apiErrors.js
src/api/fetchServerEmojiData.js

And choose a concrete subclass for the one place we were calling RequestError's constructor, which is really the Error class's constructor (with the one param `msg: mixed`) and so wasn't storing the passed `httpStatus` in its designated field.
See:
https://github.com/zulip/zulip-mobile/pull/5664#issuecomment-1433918758

api: Make RequestError explicitly abstract, in jsdoc

---

src/account-info/AccountDetails.js
src/account-info/AccountDetailsScreen.js
src/account-info/ProfileScreen.js
src/common/NestedNavRow.js
src/settings/NotificationsScreen.js
src/settings/SettingsScreen.js
src/user-statuses/UserStatusScreen.js
static/translations/messages_en.json

Before this, we were separating the line that showed the user's status from the line that led to the UI to change the status (a button linking to UserStatusScreen) -- with the "Invisible mode" switch in between.
Now, it's a single NestedNavRow that shows the emoji and status text, if any. Tapping it leads to the UserStatusScreen.
This means adapting NestedNavRow to accept an emoji or an icon, rather than just an icon, which seems fine.
-----
| Before (no status set) | After (no status set) |
| --- | --- |
| <img width=400 src="https://user-images.githubusercontent.com/22248748/219790586-d26f703f-88bc-4d54-9504-7d2335f4cb37.png" /> | <img width=400 src="https://user-images.githubusercontent.com/22248748/219790479-cb2ea8b3-2b98-46fe-8808-1535a8ca1ec9.png" /> |
Before / after (emoji status …

ProfileScreen: Put status and "Set a status" link in the same row

---

ios/ZulipMobile.xcodeproj/project.pbxproj

I think this is what has caused the App Store to think we support iOS 12 when we don't (issue #5672). This should have been bumped in 783e56b23 when we required iOS 14+.
Fixes: #5672

ios: Fix iOS "Minimum Deployment" to catch up with our iOS 14 requirement

---

ios/ZulipMobile-Bridging-Header.h
ios/ZulipMobile/ZLPConstants.swift
ios/ZulipMobile/ZLPNotifications.swift

This makes one change discussed on a video call today, and also a followup which was basically prompted by the first change: I noticed that `ZLPConstants` was depending on something in `UIKit` (because we're now happily forced to import `UIKit` in the `ZLPConstants` file instead of it being made available as a transitive dependency of some module that used to be in the bridging header), and that suggests a small change to the implementation; details in the commit.

ios: Clean up "bridging header"; fix possible latent bug in ZLPConstants

---

ios/ZulipMobile/AppDelegate.mm
ios/ZulipMobile/ZLPNotifications.swift
ios/ZulipMobile/ZLPNotificationsBridge.m
src/notification/NotificationListener.js
src/notification/extract.js
src/settings/NotifTroubleshootingScreen.js

I've noticed a bug lately where I tap a notification on iOS and it doesn't take me to the relevant conversation. It's only active when the app is open (in the foreground or background).
~~TODO: Testing on Android that the JS changes don't break anything (I plan to do this before merging, but the code is reviewable in the meantime).~~ Done!
Fixes: #5679

ios: Fix bug where tapping a notification didn't navigate to conversation

---

src/account-info/ProfileScreen.js
src/common/InputRowRadioButtons.js
src/common/NavRow.js
src/common/ServerPushSetupBanner.js
src/common/SwitchRow.js
src/common/TextRow.js
src/settings/LegalScreen.js
src/settings/NotificationsScreen.js
src/settings/PerAccountNotificationSettingsGroup.js
src/settings/SettingsGroup.js
src/settings/SettingsScreen.js
src/streams/SubscriptionsScreen.js
static/translations/messages_en.json

This makes two small UI changes:
- Nav rows that link to something outside the app, like the system settings app or a website, are marked with an "external-link" icon instead of the right-facing arrow icon.
- In the in-app notification setting screen, if the server isn't set up for push notifications, we now alert the user in the same way we show other per-account alerts, with a row in the "Notification settings for this account […]" section. Before, we were sticking a non-dismissable version of the `ServerPushSetupBanner` at the top of the screen. (The remaining, dismissable `ServerPushSetupBanner` on the home screen is untouched.)
Screenshots coming soon.

NotificationsScreen: Show server-setup alert like other per-account alerts

---

src/common/ServerPushSetupBanner.js

Somehow I got this conditional backwards when I wrote it in cb301ec23.

ServerPushSetupBanner: Fix conditional for showing admin-facing message

---

src/common/ServerCompatBanner.js
src/events/eventActions.js
src/message/fetchActions.js
src/settings/SettingsScreen.js

As Greg points out:
> Fundamentally this is information that isn't tied to a Zulip
> Server release (not a *current* one, anyway), so the most relevant
> version of it is just whatever is the latest we've merged.

compat: Link to latest, not stable, for server-support doc

---

package.json
yarn.lock

(Much like we did for @react-navigation/bottom-tabs in c0b17bd32.)
To get chrisbobbe/react-navigation@a588dcee9, which I've published to NPM in @zulip/react-navigation-stack@5.14.10-0.zulip.1.
It cherry-picks react-navigation/react-navigation@5a1987708, which fixes #5486, as noted there:
https://github.com/zulip/zulip-mobile/issues/5486#issuecomment-1261138257
So this fix will become unnecessary when we're on React Navigation 6; that's issue #4936.
Tested the bugfix on my iPhone 13 Pro running iOS 16.1, with and without "Debug with Chrome". The bug was fixed, and back navigation worked as expected, both with the swipe gesture and the back button.
Fixes: #5486

deps: Temporarily use fork for @react-navigation/stack

---

src/message/messagesActions.js
src/utils/__tests__/internalLinks-test.js
src/utils/internalLinks.js

I think this is another helpful simplification to this code; done when returning to this code for #5692.
-----
This puts the logic to recognize a "stream link" right next to the
logic for building a stream narrow, and likewise for topic narrows,
etc.
Now it's quicker to read what `Narrow` we construct for a given
`url` param. We don't have to click through `getLinkType` and wonder
whether anything surprising is done at that layer.

internalLinks [nfc]: Dissolve `getLinkType` / `LinkType` indirection

---

src/alertWords/__tests__/alertWordsReducer-test.js
src/alertWords/alertWordsReducer.js
src/api/initialDataTypes.js
src/message/fetchActions.js
src/mute/__tests__/muteModel-test.js
src/mute/muteModel.js
src/presence/__tests__/presenceModel-test.js
src/unread/unreadHuddlesReducer.js
src/unread/unreadMentionsReducer.js
src/unread/unreadModel.js
src/unread/unreadPmsReducer.js
src/user-groups/__tests__/userGroupsReducer-test.js
src/user-groups/userGroupsReducer.js

(We removed one such fallback in b94544258 / #5697, but there were more; remove those.)
This completes all our `TODO(#5102)`s in the code, referring to #5102.
Greg, I think you have a draft for handling some other `TODO(server-x)`s, possible with our current `kMinAllowedServerVersion` of 2.0? Not urgent, but perhaps we'll want to take care of those sometime.

model: Remove various fallbacks for ancient, sometimes prehistoric servers

---

src/common/ServerCompatBanner.js

The doc at
https://zulip.readthedocs.io/en/latest/overview/release-lifecycle.html#compatibility-and-upgrading
(kServerSupportDocUrl) now says 4.0, so bump kMinSupportedVersion to that.
And bump kNextMinSupportedVersion, which says it should be the next major version after kMinSupportedVersion.

versions: Bump kMinSupportedVersion to match kServerSupportDocUrl

---

src/api/modelTypes.js
src/utils/__tests__/internalLinks-test.js
src/utils/internalLinks.js
src/utils/narrow.js

(This is atop #5699.)
Fixes: #5692

internalLinks: Parse '/dm/…' and '/is/dm' in narrow links

---

package.json
patches/react-native+0.68.5.patch
tools/postinstall
yarn.lock

This gets the effect of facebook/react-native@52d8a797e but without having to upgrade to RN v0.69.
I believe this is the first time we've used patch-package. It's a band-aid, but at least I think an effective one, while we focus our time on the Flutter project.

deps: Use patch-package to fix Xcode build failure in react-native

---

src/api/initialDataTypes.js
src/presence/PresenceHeartbeat.js
src/presence/__tests__/presence-testlib.js
src/presence/__tests__/presenceModel-test.js
src/presence/presenceModel.js
src/reduxTypes.js
src/storage/migrations.js
src/users/userHelpers.js

This follows up on #5697 with a bit more modelification, and converts PresenceHeartbeat from a React class component to a Hooks-using function component. Then it adds `server_presence_ping_interval_seconds` and `server_presence_offline_threshold_seconds` to the API types, stores them in `PresenceState`, and uses them in place of the hardcoded 60 seconds and 140 seconds.
Fixes: #5669

presence: Use server's tuning parameters

---

android/app/src/main/java/com/zulipmobile/MainActivity.kt
android/app/src/main/java/com/zulipmobile/ReactExtensions.kt
android/app/src/main/java/com/zulipmobile/notifications/NotificationsModule.kt
android/app/src/main/java/com/zulipmobile/notifications/NotifyReact.kt
android/app/src/main/java/com/zulipmobile/sharing/SharingHelper.kt

Toward #5693.
This code is useful for the notifications subsystem, but it's not specialized to it. It's also used in our share-to-Zulip code. We want these functions to behave the same whether or not the build supports notifications, and ideally we don't want to repeat their definitions in different build variants.
So, move them out of `notifications/`.

android [nfc]: Move some non-notifications-specific code out of `notifications/`

---

android/app/src/main/java/com/zulipmobile/MainActivity.kt
android/app/src/main/java/com/zulipmobile/notifications/NotifyReact.kt

Toward https://github.com/zulip/zulip-mobile/issues/5693, after https://github.com/zulip/zulip-mobile/pull/5715.

android [nfc]: Move notif intent-handling function into notifications/

---

ios/Podfile.lock
jest/jestSetup.js
package.json
src/reactNativeUtils.js
src/utils/userAgent.js
yarn.lock

Oddly, on Android, react-native-device-info brings in some Firebase dependencies that we don't need:
https://github.com/react-native-device-info/react-native-device-info/blob/v8.7.1/android/build.gradle#L54-L64
Also this dependency seems to have caused a fair amount of complexity to keep around; see the output of
git log --grep='react-native-device-info'
Remove it, since we can get the same information in the same form from RN's Platform API.
To verify that it's all the same:
- For the "system name" piece (given previously by r-n-device-info's `getSystemName`):
- iOS:
- r-n-device-info was using Apple's UIDevice.systemName: https://github.com/react-native-device-info/react-native-device-info/blob/v8.7.1/ios/RNDeviceInfo/RNDeviceInfo.m#L142
- `Platform.constants.systemName` uses the same …

userAgent [nfc]: Use RN's `Platform` API; drop react-native-device-info

---

src/action-sheets/index.js
src/api/index.js
src/api/modelTypes.js
src/api/subscriptions/updateUserTopic.js
src/chat/__tests__/narrowsSelectors-test.js
src/chat/narrowsSelectors.js
src/mute/__tests__/mute-testlib.js
src/mute/__tests__/muteModel-test.js
src/mute/muteModel.js
src/topics/topicSelectors.js
src/unread/__tests__/unreadSelectors-test.js
src/unread/unreadSelectors.js

Fixes: #5362
Fixes: #5691
Fixes: #5726

Support unmuting topics in muted streams

---

src/compose/ComposeBox.js

compose: Decrease jank on message-input focus
By doing the setFocusState call unconditionally.
This piece of React state is meant to track when the topic input is
focused, when the message input is focused, and (with the
true-to-false transition debounced) when either is focused.
So if the message input is focused and we don't set that state (as
has sometimes been the case until now), it's not working as
intended. Fix that by making this setFocusState call unconditional,
like it is in handleTopicFocus.
This makes a visible improvement in the situation described by this
comment:
// We weren't showing the topic input when the user tapped on the input
// to focus it, but we're about to show it.  Focus that, if the user
// hasn't already selected a topic.
Before, focusState.either was being …

compose: Decrease jank on message-input focus

---

src/api/apiErrors.js

As Greg suggested almost a year ago:
https://github.com/zulip/zulip-mobile/issues/5102#issuecomment-1233446360
with the note that Server 3.0 was then over two years old.
This significantly increases the amount of backwards-compatibility code we can now simplify or sweep away: search for "TODO(server-3" or "TODO(server-2". (There are even a handful of straggling `TODO(server-1.9)`s.)
But unlocking those simplifications isn't the main aim here, since our efforts are focused on the new Flutter app, to replace this app:
https://github.com/zulip/zulip-flutter
Rather, the goal is just to continue incrementally nudging people toward current Zulip Server versions. In particular, when we release the Flutter app, we'll want to give it a floor of Server 4.0 or later, depending on when we release it.

api: Don't allow connecting to servers <3.0

---

src/common/ServerCompatBanner.js

Server 4.9 was released over 18 months ago:
https://blog.zulip.com/2022/01/25/zulip-server-4-9-security-release/
-----
Also a comment tweak to follow zulip/zulip#26522.

ServerCompatBanner: Bump kMinSupportedVersion to 4.10

---

android/build.gradle

This change will be required in order to upload new releases to the Play Store, effective 2023-08-31 (or 2023-11-01 if we request an extension).
Tested on an emulated Pixel running Android 13, but testing on a real device would be good too. (The office device I use only runs Android 9, though, so I can't do that myself.)
Fixes: #5453

android: Update targetSdkVersion to 33 (Android 13)

---

android/build.gradle

This reverts commit 6f44474a.
From a user report, we found that we now have to handle a new runtime permission for notifications, and the consequence of not doing so is that notifications stop working on Android 13. Ouch; that would have been good to see mentioned in the "behavior changes" doc:
https://developer.android.com/about/versions/13/behavior-changes-13#notification-permission-fgs-appearance
Discussion (starting with the user report):
https://chat.zulip.org/#narrow/stream/48-mobile/topic/.22This.20app.20does.20not.20send.20notifications.22/near/1634168

Revert "android: Update targetSdkVersion to 33 (Android 13)"

---

src/api/apiErrors.js
src/common/ServerCompatBanner.js

The latest 4.x, which is 4.11, was released on 2022-03-15, so it will turn 18 months old -- and so, become unsupported -- four days from now:
https://zulip.readthedocs.io/en/latest/overview/release-lifecycle.html#compatibility-and-upgrading
https://blog.zulip.com/tag/release-announcements/
So it's time to start nudging server admins to upgrade, with the nag banner.

api: Don't allow connecting to servers <4.0; show nag banner on <5.0

---

android/app/src/main/AndroidManifest.xml
android/build.gradle
src/notification/androidPermission.js
src/notification/notifTokens.js

Tested on an emulated Android Pixel XL running Android 13, and on the office Android device (Samsung Galaxy S9 running Android 9).
Screen recording of the "rationale" modal coming soon.
Fixes: #5753

android: targetSdkVersion to 33, this time handling new notifs permission

---

src/compose/ComposeBox.js

quote-and-reply: Set topic input when appropriate; focus message input

---

src/reactNativeUtils.js
src/settings/NotifTroubleshootingScreen.js

This could provide useful context, e.g., to diagnose issues like issue #4074, "Some device vendors break notifications".
Unfortunately, in my test using an emulated Pixel XL (results recorded in jsdoc), none of these three fields actually had anything like "Pixel XL" in it. Possibly we could get that from something like Android's `Build.PRODUCT`, documented as "the name of the overall product":
https://developer.android.com/reference/android/os/Build#PRODUCT
but React Native's Platform.constants doesn't expose that value or any other that seems likely, and we have more urgent tasks than plumbing things through React Native (like
<https://github.com/zulip/zulip-flutter>).

NotifTroubleshootingScreen: Add Android manufacturer/model info to report

---

patches/react-native+0.68.7.patch

RN merged this fix in main in facebook/react-native@10d55888c, but I made this patch from their v0.69 cherry-pick to get a smaller diff; that's facebook/react-native@37e8df1cd.

ios build: Fix Xcode 15 build issue by taking RN Ruby script patch

---

docs/changelog.md
docs/howto/release.md
tools/android

In the rush to get v27.213 out the door as a fix for #5757 — and partly because I was hopeful that the Sentry folks would be finding a fix soon — I made these changes directly on a release branch, rather than on main first and cherry-picking to a release branch.
Here they are for `main`, along with the changelog entry for v27.213.

Disable Sentry for now on Android (cherry-pick from v27.213)

---

src/api/__tests__/rawModelTypes-test.js
src/api/rawModelTypes.js
src/message/__tests__/fetchActions-test.js

Our code at the edge for transforming the old format of reactions,
with `user`, into the new format, with `user_id`, was depending on
`user` always being present.
Since `user_id` is documented as being added in Zulip 3.0:
https://zulip.com/api/get-messages#response
, and since #5747 we've been refusing to connect to servers pre-3.0,
we can assume `user_id` is always present and stop reading `user`.
Fixes: #4072

api: Stop assuming fetched messages' reactions have deprecated `user` field

---

src/action-sheets/__tests__/action-sheet-test.js
src/action-sheets/index.js
src/api/modelTypes.js
src/mute/__tests__/muteModel-test.js
src/mute/muteModel.js
src/storage/__tests__/migrations-test.js
src/storage/migrations.js

Fixes: #5769
This resolves the regression we would otherwise have when the server goes ahead with sending these. Our fallback behavior for values we don't recognize in the `user_topic` visibility policy (https://zulip.com/api/get-events#user_topic) is to treat them as not having a policy for that topic; which means that a followed topic in a muted stream would be treated as still muted, instead of unmuted.
There's still more to be done to fully implement this feature; that's tracked separately at #5770 and #5771.

Add "followed" user-topic state, as synonym of "unmuted"

---

docs/howto/release.md
ios/Podfile.lock
ios/ZulipMobile.xcodeproj/project.pbxproj
package.json
src/__tests__/sentry-test.js
src/sentry.js
src/utils/logging.js
tools/android
types/@sentry/react-native.js.flow
yarn.lock

~~Our hope here is to fix the Android crashes in #5757. Details in the commit message.~~
~~Edit, following https://github.com/zulip/zulip-mobile/pull/5765#issuecomment-1728612489: This did not fix it. [Subsequent testing](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Android.20crashes/near/1644202) showed that the crash still happens at this later version.~~
Edit, following https://github.com/zulip/zulip-mobile/pull/5765#issuecomment-1745954363: This PR was originally just an upgrade of `@sentry/react-native`. It still does that, but goes to a later version, where they added an `enableNdk` option, and it uses that option for the sake of #5766.
Fixes: #5766

Re-enable Sentry on Android, with `enableNdk: false`

---

src/settings/NotifTroubleshootingScreen.js

An alternative approach to #5720, to help us detect potential cases where the user thought they'd contacted support through the app, but we don't see an email on our side. (We're not aware of such cases yet, but in principle it could happen.)
It seems probably fine to do it at the "warn" level rather than "info". If someone sends one of these emails, it usually means something's not quite right with notifications somewhere, making "warn" probably at least as appropriate as "info" in more cases than not.

NotifTroubleshootingScreen: Make email-sent log line actually reach Sentry

---

android/app/build.gradle
docs/howto/release.md
tools/android

Fixes #5782.
I've tested, on a build with these changes and Sentry enabled, that:
* The APK is free of any native libraries that have an obvious
relationship to Sentry, in particular `libsentry.so` and
`libsentry-android.so` which appear without this change.
* In brief manual testing of the app, nothing goes obviously wrong.
So at least Sentry doesn't, say, cause a crash at startup whenever
it can't find `libsentry.so`.
* Upon adding some artificial warnings and errors, they show up in
the Sentry dashboard.  This includes `logging.warn` in JS; uncaught
exceptions in JS; `ZLog.w` in Kotlin; and an uncaught exception
in Kotlin in handling a notification.
I also tried an uncaught exception in Kotlin in a `@ReactMethod`
implementation, and that one didn't work.  But I think that's
mostly …

Re-re-enable Sentry on Android, this time with no libsentry.so

---

docs/howto/push-notifications.md

Ideally this change would have been part of a PR containing a48712a48510f7fb299611acc5d8207e2be26ff3 squashed with this, but the GitHub web UI tricked me into merging that change and I don't have permission to force-push to undo that.

docs: Replace git stash note with current information.

---

src/__tests__/lib/exampleData.js
src/api/initialDataTypes.js
src/api/realmDataTypes.js
src/realm/__tests__/realmReducer-test.js
src/realm/realmReducer.js
src/reduxTypes.js
src/storage/__tests__/migrations-test.js
src/storage/migrations.js
src/users/userSelectors.js

We can use this for #5804 and #5805.
-----
Four of the nine added `/register`-response fields seem to have a small documentation issue: https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/.60.2Fregister.60.3A.20fields.20missing.20.22Present.20if.20.5B.E2.80.A6.5D.22.3F/near/1707782
For three of them, I didn't find them mentioned in `#api design`:
`realm_can_access_all_users_group`
`realm_create_multiuse_invite_group`
`realm_move_messages_between_streams_limit_seconds`

api types: Update InitialDataRealm and RealmDataForUpdate to FL 237

---

src/account/__tests__/accountsReducer-test.js
src/account/accountsReducer.js
src/realm/__tests__/realmReducer-test.js
src/realm/realmReducer.js

This PR is stacked on top of my current revision for #5806.
Fixes: #5805

notifs: Live-update state of whether realm has enabled notifications

---

package.json
src/__tests__/lib/exampleData.js
src/__tests__/reactUtils-test.js
src/account/AccountItem.js
src/boot/TranslationProvider.js
src/common/ServerPushSetupBanner.js
src/reactUtils.js
src/realm/__tests__/realmReducer-test.js
src/realm/realmReducer.js
src/reduxTypes.js
src/settings/NotifTroubleshootingScreen.js
src/settings/PerAccountNotificationSettingsGroup.js
src/settings/SettingsScreen.js
src/storage/__tests__/migrations-test.js
src/storage/migrations.js
src/types.js
src/webview/MessageList.js
static/translations/messages_en.json
yarn.lock

Soon, we'll add a snoozable banner. But for now:
- Warning icon / subtitle text on the "Notifications" row on the settings screen
- Warning row in the notification-settings screen
- Warning icon on the "Pick account" screen
-----
(I reused some React Hooks testing infrastructure from an old draft branch I had lying around.)

notifs: Warn about notifications soon to be disabled (not yet with banner)

---

src/settings/PerAccountNotificationSettingsGroup.js

Servers with FL 217+ but not 234+ will send a payload to the bouncer that's missing realm_name, and the bouncer will error because it assumes realm_name is present. See API changelog:
https://zulip.com/api/changelog
So, require 234+. Like 217, 234 was released in Zulip Server 8.0, so the error dialog we give the user should still be accurate:
> Feature not available
> This feature is only available for organizations on Zulip Server 8.0+.

notif: For test-notification button, require FL 234+ instead of 217+

---

android/app/build.gradle

See discussion:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/release.20build.20missing.20JS.20bundle/near/1746718

android build: Update jsBundleDirRelease, fixing crash on startup

---

ios/Podfile
ios/Podfile.lock
ios/ZulipMobile.xcodeproj/project.pbxproj

Our build times could probably have benefited from this for a while now; we never got into the habit of actually using Flipper.
Anyway, do so now, since things would otherwise be busted with recent Xcode, as mentioned in a comment.

ios: Disable Flipper

---

ios/Podfile.lock
package.json
src/webview/js/generatedEs3.js
yarn.lock

Related: #5847
Stacked atop #5848 which allows testing on iOS with recent Xcode.
Manually smoke-tested on the office Android device and my iPhone.

deps: Run `yarn upgrade`, toward addressing Apple "privacy manifest" issue

---

src/compose/ComposeBox.js
src/users/userSelectors.js

String.prototype.replace and String.prototype.replaceAll interpret certain sequences such as $$ within a string provided as the replacement argument. Because of this, LaTeX delimiters $$ were turning into $, and other sequences could duplicate part of the existing draft.
Avoid this interpretation by providing a function.
Fixes: #5849

compose: Fix breakage of LaTeX delimiters in quote-and-reply

---

src/boot/TranslationProvider.js

Oops; this was missed because I didn't do end-to-end testing before we merged #5830.

ui: Condition UI-string "channel" terminology on >=255, not >255

---

src/boot/TranslationProvider.js
src/boot/streamChannelRenamesMap.js

Sentry is reminding us that we forgot to check if the active account has server data. Adding this check fixes a crash when `zulipFeatureLevel` is null because of not having server data right after login.

TranslationProvider: Fix crash on login, from non-null-FL invariant

---

src/boot/store.js
src/message/__tests__/messageActions-test.js
src/utils/__tests__/internalLinks-test.js
src/utils/internalLinks.js

Explanation in a comment, which quotes Greg in #5866.
Fixes: #5866

msglist: Handle topic permalinks (/with/<id>) just as we do /near/ links

---

src/outbox/outboxActions.js

outboxActions: Show dialog if message send fails with informative ApiError
This is our minimal support for #5870 in this legacy codebase.
Supporting it properly with a client-side check of the setting is
more effort than we can spare right now.
Probably more error handling is called for in general (like for
network or server issues), but #3881 ("Sending outbox messages is
fraught with issues") is complicated and it's probably best to leave
it be.
Fixes: #5870

outboxActions: Show dialog if message send fails with informative ApiError

---

src/webview/css/cssNight.js
src/webview/static/base.css
src/webview/static/images/loader-black.svg
src/webview/static/images/loader-white.svg
tools/build-webview

As expected, the only changes we need to make for thumbnail support #5875 are to the styling for the placeholder before a thumbnail is ready.
Along the way we also fix a quirk which I'd very occasionally spotted before and always looked wrong, but hadn't been a priority.
Thanks to @alexmv for help testing these changes. Chat thread: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/thumbnails/near/1892137
---
content: Use `object-fit: scale-down` to fit images, vs. `contain`
This matches the behavior of Zulip web.
The meaning of this value is that the image is either scaled
according to `contain`, or not scaled at all, whichever makes it
smaller.
In other words, we still scale down all the images we were scaling
down, but we stop scaling any images up, which tended to look a bit …

Style thumbnail placeholders nicely

---

tools/lib/ensure-coreutils.sh

It might be found at this path on Macs with Apple Silicon.
Discussion:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Xcode.20on.20new.20laptop/near/1937894

tools: In ensure_coreutils, add another place to look for Homebrew

---

android/build.gradle

The retired repo "jcenter" has been saying for years that it'll go away, and that seems to have happened. Take this dependency at a later version, which is available from Maven Central.
Fixes: #5888

android: Force me.relex:photodraweeview at v2.1.0

---

yarn.lock

Taking this upgrade because we learned from dependabot that it fixes a security issue:
https://github.com/zulip/zulip-mobile/pull/5887
The issue is in a dev-only indirect dependency, and even our development tools *probably* don't trigger it.  But I can't rule out that they might.
The yarn.lock diff from dependabot is a bit messy, though, so here's me doing the same upgrade directly.
---
Because this is an indirect dependency, `yarn upgrade serve-static` just does nothing.  (Seems like a bug / misfeature in Yarn.)
And I don't want to do a general `yarn upgrade` in this legacy codebase right now -- that would balloon into a larger task.
So, here's a fun technique to make the upgrade in a surgical way:
```
$ perl -i -0pe 's{^serve-static@.*?\n\K.*?^$}
{  version "1.16.2"\n}sm
' yarn.lock
$ …
```

deps: Bump serve-static to latest, 1.16.2

---

android/build.gradle

As we said on the last one of these, fc2dab717:
This setting is not to be confused with the targetSdkVersion. The
latter goes into the built manifest, and affects a wide range of
behavior, so bumping it requires careful testing. This is used
purely at build time, and should have no effect on runtime
behavior.
This value needs to be at least as high as targetSdkVersion, and we need to bump that to 34 soon (#5877). So, do this to prepare for that.
No build failures or warnings appeared for me with
tools/test native --all-files
.
Related: #5877

android: compileSdkVersion to 34 (Android 14)

---

package.json
src/webview/js/generatedEs3.js
yarn.lock

This is a library we use in tools/generate-webview-js , for producing the generated JS code to go in the message-list webview based on our several source files for it.
This upgrade gets us a large number of changes that don't matter to us because they have no effect on the output JS.  One of those is to fix an XSS vulnerability, CVE-2024-47068:
https://github.com/rollup/rollup/security/advisories/GHSA-gcx4-mw62-g8wm
which we learned about from Dependabot:
https://github.com/zulip/zulip-mobile/pull/5893
Even though the vulnerability doesn't affect us, it's good to upgrade past the fix to avoid having to ever re-evaluate whether it affects us. The fix is only in 3.x+, so go to the latest 3.x.
There's also one change affecting the output, which is that the `__esModule` marker goes away. …

deps: Update rollup to 3.x, from the last 2.x

---

tools/checkout-keystore
tools/postinstall

I ran into the `sq` changes by installing `sq` on my new laptop; this was the first release build I've done on it.

Some build fixes (changed `sq` API, and a missing file on iOS)

---

package.json
yarn.lock

This updates rn-fetch-blob to a version with one cherry-picked commit atop the v0.11.2 we were previously using:
https://github.com/zulip/rn-fetch-blob/commit/e17b2a51c
The rn-fetch-blob package itself is no longer maintained:
https://github.com/joltup/rn-fetch-blob/issues/863
There's a fork that is maintained, `react-native-blob-util`:
https://npmjs.com/package/react-native-blob-util
That fork addressed the Android 14 requirement to set an explicit RECEIVER_EXPORTED flag (#5903), merging a fix:
https://github.com/RonRadtke/react-native-blob-util/issues/303
https://github.com/RonRadtke/react-native-blob-util/pull/306
Our fix is cherry-picked from that one.
(If this app weren't a legacy codebase in maintenance mode, we'd take the time to upgrade this dependency more generally, probably …

deps: Use a patched rn-fetch-blob to fix Android 14+ crash

---

src/api/eventTypes.js
src/events/eventToAction.js
src/realm/__tests__/realmReducer-test.js
src/realm/realmReducer.js
src/user-groups/__tests__/userGroupsReducer-test.js
src/user-groups/userGroupsReducer.js
src/users/__tests__/usersReducer-test.js
src/users/usersReducer.js

Also move users between `state.users` and `state.realm.nonActiveUsers` in response to `realm_user`/`update` events that have `is_active`.
Fixes: #5899

user-groups: Remove deactivated users from groups

---

.github/workflows/ci.yml

JDK 11 is quite old now.
While here, update all the details of this stanza to match what we do in the zulip-flutter CI.
Fixes: #5913

ci: Update to use JDK 17

---

src/api/modelTypes.js
src/events/eventToAction.js

Tested on an iPhone simulator, connected to CZO. Before this change, I saw the message list not updating on reaction events (as Greg highlighted in the [chat thread](https://chat.zulip.org/#narrow/channel/378-api-design/topic/reaction.20data/near/2037736)). After this change, I saw the message list updating as expected when I added/removed reactions.
Fixes: #5911

api: On reaction events, stop assuming old `user` object is present

---

ios/Podfile.lock
package.json
yarn.lock

See issue:
https://github.com/getsentry/sentry-react-native/issues/3883
Reportedly, the first working version is 5.24.1. So, use `~5.24.1` for the range, pulling in 5.24.3.
With ^5.9.2, I was getting 5.36.0, which came with an Android build failure that looked like #5345.

deps: Upgrade @sentry/react-native to fix iOS build failure with Xcode 16

---

src/api/apiErrors.js
src/common/ServerCompatBanner.js

(The branch is misnamed; I realized after writing it that we can show the nag banner on 6.x too. 🙂)
api: Don't allow connecting to servers <5.0; show nag banner on <7.0
See 8552afce9 for the previous one of these.
The Zulip Server 5 release went out over 3 years ago, so the 4.x
releases are all long out of our announced 18-month compatibility
window:
https://blog.zulip.com/2022/03/29/zulip-5-0-released/
https://zulip.readthedocs.io/en/latest/overview/release-lifecycle.html#client-apps
So we can cheerfully refuse to connect to 4.x releases; our "Server
not supported" nag banner has been asking server admins on those
versions to upgrade since 8552afce9, which the changelog says went
out in v27.216, dated 2023-10-10.
The last 6.x release, 6.2, went out on 2023-05-19. That's also
outside the …

api: Don't allow connecting to servers <5.0; show nag banner on <7.0

---

docs/howto/dev-server.md
docs/howto/push-notifications.md

Chat thread: [#mobile-team > notifications from dev server @ 💬](https://chat.zulip.org/#narrow/channel/243-mobile-team/topic/notifications.20from.20dev.20server/near/2159855)
This is a companion change to:
* https://github.com/zulip/zulip/pull/34512
This name got cleaned up, hooray.  (A couple of years ago --
zulip/zulip@43b4f1057 -- but we use these instructions only
occasionally and update them less often than that.)
In particular PUSH_NOTIFICATION_BOUNCER_URL was replaced by
ZULIP_SERVICES_URL last year, in zulip/zulip@4a9314943.
I believe the need for a distinct EXTERNAL_HOST value when
registering the server with the bouncer came about as part of the
same work around the same time, though it may have been in a
different commit.
Also at some point the spelling of the flag got fixed to …

docs: Update instructions for dev server and testing push notifications
