zulip/zulip-mobile

- docs/developer-guide.md
The existing link in the README is broken! [This commit](https://github.com/zulip/zulip/commit/f6c4e46afebafdbfca8d83040e5d843212ca6245) suggests that the correct link should be this Read the Docs page.
Please feel free to change if this should point somewhere else instead. :)
> Fix broken link to server dev setup instructions

- package.json
- src/common/__tests__/__snapshots__/ZulipButton-test.js.snap
The CI build is failing because React Native has type errors when checked against the latest version of Flow.
> Downgrade version of Flow.

- package.json
- src/api/apiFetch.js
- src/lib/message.js
- src/message/MessageView.js
- src/message/__tests__/__snapshots__/renderHtml-test.js.snap
- src/message/__tests__/renderHtml-test.js
- src/message/renderHtml.js
- src/nav/MainScreen.js
- src/stream/StreamView.js
We need to pass the realm and auth header to the HTML renderer because some images and links are relative (such as '/user_uploads/..'). For these we need to (1) prepend a base url (the realm) and (2) send along our Authorization header.
I'm passing along this information as a `rewriteUrl` function in a `context` object, but perhaps there's a better approach.
> Improve message HTML rendering and add snapshot tests.

- src/start/RealmScreen.js
Searches user entry for "://" at the server login page.  If present, checks for "http" or "https" preceding "://".  If one of these is not found, an error is thrown.  If "://" is not found "https://" is prepended to the user entry.
> Added server parsing logic

- src/api/apiFetch.js
Throwing an error here crashes the app because it is uncaught so disabling for now until we have a more permanent fix.
Fixes #229
> Disable throwing error in setTimeout in `apiFetch`.

- src/common/styles.js
- src/main/MainScreen.js
- src/nav/MainNavBar.js
- src/title/Title.js
- src/title/TitleHome.js
- src/title/TitlePrivate.js
- src/title/TitleSpecial.js
- src/title/TitleStream.js
Change background color of navigation bar to the color associated with stream.
Fix:#245
Used `foregroundColorFromBackground` to determine the color of the title and drawer icons.
> Change Navigation bar color on narrowing to stream.

- src/reactions/ReactionList.js
We started tested zulip-mobile this morning and were getting an exception after login to our server with reactions being null, causing the app to fail to startup and be unusable.
This quick fix checks if reactions is actually defined, and if it isn't, follows the existing app logic to return null.
So far basic testing shows this allows us to complete the login process, load the main UI, and actually start to use the application.
> Fixing crash on startup where reactions was null upon login

- README.md
- docs/developer-guide.md
Added more detail to `docs/developer-guide.md`, based on my experience with installing the app on an iOS device for the first time. Not sure if we should make it more explicit.
Improved current docs readability - shorter line lengths (mostly for `cat`ting / reading GH on a mobile device), more whitespace.
> docs: Add more detail and improve readability.

- src/api/apiFetch.js
- src/common/LoadingIndicator.js
Added `StatusBar.setNetworkActivityIndicatorVisible(...)` in `apiFetch.js`.
Tested on iPhone 6S iOS 10.2.
Implements #320.
> api: Add network activity indicator.

- src/api/getMessages.js
- src/chat/__tests__/chatReducers-test.js
- src/chat/__tests__/chatSelectors-test.js
- src/chat/chatReducers.js
- src/chat/chatSelectors.js
- src/common/LoadingIndicator.js
- src/main/MainScreenContainer.js
- src/main/requestInitialServerData.js
- src/message-list/InfiniteScrollView.js
- src/message-list/MessageList.js
- src/message-list/messagesActions.js
- src/message/headers/PrivateMessageHeader.js
- src/message/headers/StreamMessageHeader.js
- src/message/headers/TopicMessageHeader.js
- Use first unread option when fetching initial data. This puts the user at the point of the last unread message instead of at the newest message.
- Maintain position in stream or topic when narrowing by clicking on a message header.
Fixes #228. Fixes #230.
> Get first unread on initial fetch. Use message anchor when narrowing.

- src/start/AuthScreen.js
This removes the Google auth button since it does not work in the
current build.
> Remove Google auth button.

- src/common/Screen.js
- src/common/styles.js
- src/main/MainScreen.js
- src/message/headers/MessageHeader.js
- src/message/headers/PrivateMessageHeader.js
- src/message/headers/StreamMessageHeader.js
- src/message/headers/TopicMessageHeader.js
- src/nav/MainNavBar.js
- src/nav/ModalNavBar.js
- src/title/Title.js
- src/title/TitleHome.js
- src/title/TitlePrivate.js
- src/title/TitleSpecial.js
- src/title/TitleStream.js
- Make BRAND_COLOR slightly darker
- Use dark text on light background in nav bar for non-narrowed views
- Add some margin around message headers
- Fix a few styling bugs
New look for Home:
This better distinguishes special views (like Home or Private Messages) visually from narrows to streams or topics.
> Style changes to nav bar and message headers.

- src/api/apiFetch.js
- src/api/pollForEvents.js
We sometimes need to fetch silently (for example, because `pollForEvents` long polls).
> Fix network activity indicator.

- src/api/apiFetch.js
- src/api/pollForEvents.js
- Timeouts are now correctly handled (consumers of `apiFetch` need to handle the error though)
- The network activity indicator is shown if there's any pending network request that hasn't finished
> Fix activity indicator and network timeouts.

- src/streamlist/StreamList.js
Fixes #342
Not showing any mute or private icon because we don't have info for isPrivate and isMute for all streams.
> Do not show mute icon in All Streams screen

- src/api/apiFetch.js
Network Indicator is only present in iOS so check
whether device is iOS or not before calling.
Fix:#347
> Added check before setNetworkActivityIndicatorVisible.

- src/message-list/MessageList.js
- src/message-list/renderMessages.js
- src/message/MessageBrief.js
- src/message/MessageContainer.js
- src/message/MessageFull.js
- src/utils/__tests__/narrow-test.js
- src/utils/narrow.js
> On message touch, do a narrow

- .eslintrc
- package.json
- src/api/apiFetch.js
- src/compose/MessageFormattingHelp.js
- src/start/RealmScreen.js
- src/utils/__tests__/date-test.js
A significant perf regression was introduced in eslint-plugin-spellcheck 0.0.7.
This decreases the total eslint run time from 100secs to 15secs.
> Downgrade eslint spellcheck to 0.0.6 for much faster perf + fixes

- src/main/MainScreen.js
Fixes #334 
Increased from default 0.05 to 0.1 as discussed.
Hopefully this works both for phones with screen protector and prevents the issue.
> Slide drawers only from edges

- src/store.js
We use 'redux-logger' in debug mode to log states and actions. This isn't useful unless running the JS remotely in Chrome Dev Tools, and it slows JavascriptCore to a crawl.
> Speed up debug build.

- src/account/AccountPickScreen.js
- src/nav/Navigation.js
- src/start/RealmScreen.js
The realm screen was always showing the URL of the first account regardless of the account that was selected on the 'Pick account' screen.
> Fix bug on realm screen.

- src/message/html/HtmlStyles.js
When pressing on a message, the highlight wasn't looking good when there were elements with solid backgrounds and borders.
This PR makes sure they look the same as before, but use transparency.
Now the highlight looks sweet instead.
> Make all backgrounds and borders partially transparent

- src/message-list/InfiniteScrollView.js
Change DEFAULT_START_REACHED_THRESHOLD and DEFAULT_END_REACHED_THRESHOLD
to higher value, now unfetched messages will be fetched earlier
and user won't see time spinner.
Fixes: #238.
> Make prefetching new messages earlier by increasing thresholds.

- src/message-list/MessageList.js
Fixes #383 
Search does not pass that function since we don't want to update read status.
> Do not call markAsRead if no function provided

- .travis.yml
PRs labeled with the "travis updates" label will receive build notifications from zulipbot.
**Usage:**
Comment `@zulipbot label "travis updates"` on a pull request to label the pull request with the "travis updates" label. When the Travis build of the PR is complete, zulipbot will post a comment on the build status.
**Note:** It is highly recommended that a "travis updates" label be created in the repository (if else, zulipbot will automatically add a default-colored "travis updates" label).
> Enable zulipbot build notifications.

- README.md
Since zulipbot is now deployed on this repo, it'd be nice to document it in README.md
> docs: Add zulipbot docs to README.

- src/__tests__/reducers-test.js
- src/app/__tests__/appReducers-test.js
- src/app/appReducers.js
- src/chat/__tests__/chatReducers-test.js
- src/chat/chatReducers.js
- src/events/__tests__/eventReducers-test.js
- src/mute/__tests__/mutetReducers-test.js
- src/mute/muteReducers.js
- src/realm/__tests__/realmtReducers-test.js
- src/realm/realmReducers.js
- src/streamlist/__tests__/streamsReducers-test.js
- src/streamlist/streamsReducers.js
- src/subscriptions/__tests__/subscriptionsReducers-test.js
- src/subscriptions/subscriptionsReducers.js
- src/users/__tests__/usersReducers-test.js
- src/users/usersReducers.js
- src/utils/__tests__/message-test.js
Based on 'events' PR.
* Ensure all states are reset when switching accounts
* Add tests for all reducers to confirm
> Improve Account Switch

- docs/developer-guide.md
I had a lot of confusion about the `.pbxproj` file when I first tried making changes and running those changes on the device. Otherwise, the reason is embedded in the changes themselves. I had much problem correcting my code review here #423, especially. It will also help eliminate any possibility of committing changes related to BundleIdentifier and Team.
> Docs: Add tip for developing in iOS

- src/account-info/AccountDetails.js
- src/account-info/AccountDetailsScreen.js
- src/api/queueMarkAsRead.js
- src/chat/__tests__/chatReducers-test.js
- src/chat/chatReducers.js
- src/common/ZulipButton.js
- src/main-tabbed/MainScreen.js
- src/main/MainScreen.js
- src/main/MainScreenContainer.js
- src/main/SideDrawer.js
- src/message/messagesActions.js
- src/nav/MainNavBar.js
- src/users/UserListCard.js
Some parts of the code were not updated to latest approaches.
* Extract doNarrow to an action, less passing of the function around
* Extract SideDrawer to new file
* Simplify MainNavBar and remove old and unused Navigation component
* Remove the manual fetchMessage calls in few places and replace with doNarrow
> Simplify doNarrow, MainNavScreen and fix inconsistencies

- src/chat/Chat.js
- src/message/NoMessages.js
Show No messages if messageList size is zero
and no fetching is in progress.
Fix:#518
`caughtUp` is true when we're at the last message in that direction. But if there are no messages then there is no sense of last message.
> fix: No messages is not being displayed.

- src/main/MainScreenContainer.js
- src/message/MessageContainer.js
- src/message/html/HtmlNodeTag.js
- src/message/html/HtmlTagA.js
- src/message/html/HtmlTagDiv.js
- src/message/html/HtmlTagItalic.js
- src/message/html/HtmlTagLi.js
- src/message/html/HtmlTagPre.js
- src/message/html/HtmlTagSpan.js
- src/message/html/HtmlTagStrong.js
- src/message/html/renderHtmlChildren.js
- src/message/renderMessages.js
- src/utils/__tests__/url-test.js
- src/utils/url.js
Fixes: #162
Redirects :
* stream, topic, private and special (example `is/starred` ) links
* message links (containing `near/<message_id>`)
* `#stream-name` to mentioned streams.
Added tests.
https://drive.google.com/open?id=0B4jK5QX65b0ZUEhiendsbDZrUGM
This pr uses the old doNarrow function which takes anchor as an argument. Once #523 is resolved, I'll fix the conflicts. Suggestions are welcome :).
> Redirect in-app links to appropriate messages and add tests.

- src/chat/Chat.js
- src/chat/UnreadNotice.js
- src/common/Icons.js
- src/main/MainScreenContainer.js
Fixes #349 
@borisyankov the onScroll surprisingly wasn't required in the implementation. `countUnread` handles the logic of when to show the indicator very well. I have added `position` prop to the `UnreadNotice` component which positions the notice on top or bottom of message list depending on what is supplies.
> Fix: Add indicator for when new message arrives

- src/store.js
Over the last 1-2 months, improvements on how the incoming data is handled means caching previous store data is now simple and seamless.
> Cache everything in store except 'app' reducer

- src/message/IconStarMessage.js
- src/message/MessageBrief.js
- src/message/MessageContainer.js
- src/message/MessageFull.js
For #418  .
A star is shown next to messages that user has starred. The alignment is proper with neighboring elements both in landscape and portrait.
> Fix: Shows star to indicate starred messages(#418)

- src/account/AccountItem.js
- src/account/AccountList.js
- src/account/AccountPickScreen.js
in AccountPickScreen.
https://github.com/zulip/zulip-mobile/issues/536
Now it looks like this
on clicking **Switch Account** => show tick/done icon (was shown before too)
on clicking **Logout** => show remove icon.
> Don't show tick/done icon if realm is logged out.

- src/chat/Chat.js
ComposeBox was being passed an undefined (and unused) onSend prop.
> chat: Remove unused prop passed to ComposeBox

- src/compose/ComposeText.js
This matches behavior of all other mobile apps:
* 'return' button instead of 'send'
* do not submit but create a new line
* do not lose focus on 'return'
> Fix compose text default keyboard button

- src/reactions/ReactionList.js
> Fix #597: Reaction list no longer misaligns on new row

- src/api/getMessages.js
- src/chat/__tests__/chatReducers-test.js
- src/chat/chatReducers.js
- src/message/messagesActions.js
- src/realm/realmActions.js
Fixes an issue with invalidating cached messages
* Add a new parameter to MESSAGE_FETCH_SUCCESS to optionally replace existing messages
* Initial message requests replace cached messages
> First message request replaces cached messages

- src/styles/theme.js
A recent merge undid an important change in zIndex of ComposeBox which results in unread notice to overlay ComposeBox. This PR undoes that change
> Increase ComposeBox zIndex to overlay unread notice

- src/common/Input.js
- src/compose/ComposeText.js
This fixes a critical bug that prevents sending of messages.
The fix is a general ref parameter passing from a custom Input component to the wrapped TextInput.
> Fix Input ref passing

- .eslintrc
- package.json
- src/chat/Chat.js
- src/message/MessageList.js
- src/message/messageActionSheet.js
- src/utils/message.js
- yarn.lock
Fixes #267, opened a PR in the server zulip/zulip#3983 for implementing the routes!
> Implemented Muting/Unmuting of streams and topics

- src/autocomplete/StreamAutocomplete.js
When there is no items in a # stream suggestion,
then there is a line coming up.
fix:#621
> Fix: Line shown when no # stream suggestion matches.

- src/chat/Chat.js
- src/chat/UnreadNotice.js
The PR aims at adding 3 states to unread notice, visible, hidden and peeking.
When the user is scrolled up and new message arrives the notice animates in stays for 2-3 seconds then goes into peeking mode.
Peeking mode is where the notice hides itself but not fully, just a thin blue bar at the very bottom of screen. This indicates there are new messages waiting below.
As new messages arrive and user is scrolled up the notice expands and goes again into peeking mode.
When user scrolls to the very bottom implying having read all the messages, the notice goes into hidden mode, no longer visible.
> Improvements to new messages Indicator

- src/chat/Chat.js
> Fixes #633: Remove ActionSheetProvider from root in the chat.js

- __tests__/ui-tests.js
- package.json
- yarn.lock
Currently test's for connection with server and login through dev auth backend is implemented 
http://chase-seibert.github.io/blog/2017/01/06/appium-react-native-quickstart.html is a great guide to get started with the appium testing
> Add integration testing using appium for the iOS 

- src/html/HtmlNodeTag.js
- src/utils/__tests__/url-test.js
- src/utils/url.js
Fixes: #603
support new span format and old img format for emojis
> Support new server emojis format.

- src/common/Icons.js
- src/title/TitleSpecial.js
While other narrows have the same icon in header as in navigation, Private Messages don't. Fixed that to show an envelope icon, as in the web app.
> Made sure private messages have the same icon everywhere

- package.json
- src/start/AuthScreen.js
- yarn.lock
v0.0.6 `eslint-plugin-spellcheck` runs in ~11 secs and v0.0.7 runs in ~89 secs
> Limit eslint-plugin-spellcheck to v0.0.6 due to perf issues.

- src/compose/ComposeBox.js
- src/compose/ComposeText.js
- src/compose/ModeView.js
- src/compose/ModeViews/StreamBox.js
- src/styles/theme.js
This is currently just for design suggestions and not for code review, after the correct design is finalized, I'll complete this! 
**First default screen**
**Stream**
**Private**
> New compose box design

- src/html/HtmlNodeTag.js
- src/html/HtmlNodeText.js
- src/html/renderHtmlChildren.js
- src/html/tags/HtmlTagA.js
Message text color set to black for Android.
Fix:#642
Android
iOS
> Apply bold, italic, links, strikethrough styles in messages.

- src/common/SlideAnimationView.js
- src/common/index.js
Added a slide animation view which will also help lightbox.
> Add slide animation view.

- src/chat/chatSelectors.js
This fixes a bug where the message list moved(reverses) during presence events.
> Prevent mutating msgs array in active narrow in getLastTOpicInActiveNarrow().

- src/compose/ComposeBox.js
- src/styles/theme.js
As suggested by Boris 
And removed the compose options for private narrow
> Hide mode changer as there is only one compose option: compose text

- src/autocomplete/EmojiAutocomplete.js
- src/autocomplete/PeopleAutocomplete.js
- src/autocomplete/StreamAutocomplete.js
fix: Currently on selecting row dismisses keyboard and click is not grabbed by row.
> Do not dismiss keyboard on clicking auto complete row.

- src/common/ZulipButton.js
Fixes #475 
Note that the android emulator runs a little slow.
> Entire ZulipButton is selectable in android

- src/compose/ComposeText.js
I think this should be done before release.
- Added border in the message box.
- Fixed the send button at the bottom.
Before Border: 
After border: 
Before send button : 
After send button :
> Improved messageBox

- src/autocomplete/AutoCompleteView.js
- src/common/Popup.js
- src/compose/ComposeBox.js
- src/compose/ComposeText.js
- src/emoji/EmojiRow.js
> Extracted auto complete pop up from ComposeText.

- android/app/build.gradle
- android/app/src/main/java/com/zulipmobile/MainApplication.java
- android/settings.gradle
- ios/ZulipMobile.xcodeproj/project.pbxproj
- ios/ZulipMobile/Info.plist
- package.json
- src/api/downloadFile.android.js
- src/api/downloadFile.ios.js
- src/light-box/share.js
Library used for download https://github.com/wkh237/react-native-fetch-blob.
It supports use of native download manager for android and file stream for large files in addition to features supported by https://github.com/itinance/react-native-fs.
> Add support for download and share.

- android/app/src/main/java/com/zulipmobile/MainApplication.java
- package.json
The newest version of this library 1.3.0 is incompatible with RN version less than 0.44 (after this commit https://github.com/alwx/react-native-photo-view/commit/af80c43cd39838a89ce4243fd675109561fd596c). Tested the changes on android and ios devices 👍
> Limit react-native-photo-view to v1.2.x.

- android/app/build.gradle
- android/app/src/main/java/com/zulipmobile/MainApplication.java
- android/app/src/main/java/com/zulipmobile/notifications/GCMPushNotifications.java
- android/app/src/main/java/com/zulipmobile/notifications/NotificationHelper.java
This is expanding notifications not complete yet.
Wanted some suggestions if this can be made better 
Expanded:
Default view:  (the latest message is shown here) What would be the most appropriate content text here?
> Grouped notifications into one and show the notifications as a list

- src/chat/__tests__/chatReducers-test.js
- src/chat/chatReducers.js
- src/message/MessageBrief.js
- src/message/MessageFull.js
- Update in edit_history.
- Use edit_history to determine whether message is editrd or not.
fix: edited tag is never showed when edited messages is fetched
from initial fetch because it does not contain edit_timestamp.
> Better handling of EVENT_MESSAGE_UPDATE.

- .eslintrc
- package.json
- src/autocomplete/PeopleAutocomplete.js
- src/users/__tests__/usersReducers-test.js
- src/users/__tests__/usersSelectors-test.js
- src/users/usersSelectors.js
Prioritizes people autocomplete in order of :- 
- starts with name.
- matches initial.
- contains in name.
- matches in email.
in a single iteration of users array.
> Prioritizes people autocomplete suggestions

- src/message/MessageBrief.js
- Fill screen whole width with the children of MessageBreif.
- Make whole content touchable.
messages link https://chat.zulip.org/#narrow/stream/test.20here/topic/message.20rendering
on [current master](https://github.com/zulip/zulip-mobile/tree/134ac5196aaa2e2d7b96ef94906f2eb865b46251) 
this PR
> fix: splitting message content in several lines.

- src/common/Screen.js
Fixes : #769 
Used ZulipStatusbar and backgroundColor as per theme.
This solves status bar issue in dark theme from : 
- RealmScreen
- AuthScreen
- DevAuthScreen
- AccountDetailsScreen
- AccountPickScreen
- SettingsScreen
> [Android] Fixes : #769  StatusBar color according to the theme

- src/main/MainScreenContainer.js
- src/message/MessageList.js
- src/message/headers/MessageHeader.js
- src/message/messageActionSheet.js
- src/message/renderMessages.js
This just prevents duplicate re-renders of `renderMessages`, `MainScreen` and `messageActionSheet`.
Some data
before
after
this was profiled during fetching of new messages using `MessageList.js`.
> Prevent duplicate re-renders of renderMessages, MainScreen, messageActionSheet.

- .eslintrc
- package.json
- yarn.lock
This would help in code situations like in 
`const { narrow, subscriptions, unreadPrivateMessagesCount, onPressStreams, onPressPeople, } = this.props;`
and converting it to 
```
const {
narrow,
subscriptions,
unreadPrivateMessagesCount,
onPressStreams,
onPressPeople,
} = this.props;
```
> Implement prettier for the project

- ios/ZulipMobile.xcodeproj/project.pbxproj
- src/api/registerPush.ios.js
The bundle ID was incorrectly labelled as com.zulip.Zulip when it
really should be org.zulip.Zulip.
> Fix bundle ID to be org.zulip.Zulip.

- src/message/headers/MessageHeader.js
As there are no options for it. Action sheet does not look good
with only cancel option.
> No need to show action sheet on long press privateMessageHeader.

- src/start/PasswordAuthView.js
- src/styles/theme.js
fixes : #864
Kind of reverting this PR #811 
iOS. 
Current master : 
Android : 
This PR : 
iOS:
Android :
> Fixes: #864 Aligns the forgot password to right in Android

- src/compose/ComposeText.js
Fixes : https://github.com/zulip/zulip-mobile/issues/879
> Disable SubmitButton if message contains only whitespace

- package.json
- yarn.lock
Not sure if other folks are getting this error 
```
Bundling `index.android.js`  100.0(1/1), done.
error: bundling: UnableToResolveError: Unable to resolve module `react-native/Libraries/Components/View/ViewPropTypes` from `/Users/kunall17/Project/react/zulip-mobile/node_modules/react-native-photo-view/PhotoView.android.js`: Module does not exist in the module map or in these directories:
/Users/kunall17/Project/react/zulip-mobile/node_modules/react-native/Libraries/Components/View
,   /Users/kunall17/node_modules/react-native/Libraries/Components/View
This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
1. Clear watchman watches: `watchman watch-del-all`.
2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
3. …
```
> Fix: Downgrade photoview dependency to 1.2.0

- src/users/UserList.js
this PR
How do we want to sort users?
- Using status (active, idle, inactive like in web). In this case name initials header will not be useful, we can have status headers.
- Using name. In this case name initial headers are nice.
- Combined. First creating sections according to names and then sorting each section according to status (active, idle, inactive).
> Fix: headers not being shown in user screen.

- package.json
- src/users/userSelectors.js
- yarn.lock
On running `npm run test:prettier` prints error like this 
```
> ZulipMobile@0.9.0 test:prettier /Users/kunall17/Project/react/zulip-mobile
> prettier-check  --single-quote --jsx-bracket-same-line --trailing-comma all --print-width 100 --parser flow `find src -name "*.js"`
Forgot to run prettier? There are files without correct code style:
src/users/userSelectors.js
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! ZulipMobile@0.9.0 test:prettier: `prettier-check  --single-quote --jsx-bracket-same-line --trailing-comma all --print-width 100 --parser flow `find src -name "*.js"``
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the ZulipMobile@0.9.0 test-pretty script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete …
```
> Use prettier-check to check if all files are formatted with prettier

- src/html/HtmlNodeTag.js
- src/html/HtmlStyles.js
[current master](https://github.com/zulip/zulip-mobile/tree/2abfbac30bf763aa34d37d8a139627cfb717b0de)
this PR
> Fix: center align of quote text and bullets.

- android/app/src/main/java/com/zulipmobile/CustomTabsAndroid.java
- android/app/src/main/res/anim/slide_in_left.xml
- android/app/src/main/res/anim/slide_in_right.xml
- android/app/src/main/res/anim/slide_out_left.xml
- android/app/src/main/res/anim/slide_out_right.xml
Part of https://github.com/zulip/zulip-mobile/issues/920
Android inbuit transition don't have transition like `android.R.anim.slide_in_right` and `android.R.anim.slide_out_left` . So i added the anim xml file to do so.
> Adds animation in Custom Tabs

- ios/ZulipMobile.xcodeproj/project.pbxproj
- ios/ZulipMobile/AppDelegate.m
- ios/sentry.properties
- src/ZulipMobile.js
- src/config.js
Now the react-native run-ios --configuration Release works now, without any changes
**Requires test from multiple people to make sure it works for everyone and not only my setup!**
> Fix release build through command line errors

- src/html/HtmlNodeTag.js
- src/html/__tests__/HtmlNodeTag-test.js
- src/html/__tests__/renderHtmlChildren-test.js
- src/html/tags/HtmlTagSpan.js
- src/html/tags/HtmlTagSpanMention.js
> Apply 'user-mention-me' styles to self mentions span.

- package.json
`Error: unterminated string constant in ./polyfill/Blog.js line 289`
Fixed in https://github.com/wkh237/react-native-fetch-blob/issues/455
> Fix react-native-fetch-blob package crash

- package.json
- yarn.lock
> Fix: Upgrade expo actionsheet due to BackAndroid being deprecated

- src/chat/__tests__/chatReducers-test.js
- src/chat/chatReducers.js
- src/chat/chatSelectors.js
This prevents some re-renders of Message related components during startup.
Added a test to cover this case.
> Avoid changing state when rehydrated messages same as incoming ones.

- .flowconfig
- package.json
- src/baseSelectors.js
- src/chat/__tests__/chatSelectors-test.js
- src/chat/chatSelectors.js
- src/compose/ComposeBox.js
- src/message/MessageBrief.js
- src/message/MessageFull.js
- src/message/MessageTags.js
- src/message/OutboxMessageContainer.js
- src/message/renderMessages.js
- src/outbox/__tests__/outboxReducer-test.js
- src/outbox/outboxActions.js
- src/outbox/outboxReducers.js
- src/types.js
- src/users/userSelectors.js
- src/utils/narrow.js
- yarn.lock
**Screenshot:** 
Last 3 messages are when server not running
> Use outbox messages to render messages to the chat screen

- package.json
- yarn.lock
The recent library version 1.4.0 has a bug.
Also submitted an issue for the same here https://github.com/alwx/react-native-photo-view/issues/84
> Fix: Limit react-native-photo-view to 1.3.x.

- src/message/InfiniteScrollView.js
This commit  https://github.com/facebook/react-native/commit/407ec0023fb3d292bcb2583c9a1bb6791f2e046d has finally made it to RN47 and now we can remove this logic. The sticky headers by default won't work when clipped views optimisation is enabled.
> Remove logic to disable sticky headers on android.

- android/app/src/main/java/com/zulipmobile/notifications/GCMPushNotifications.java
> Fix: NoSuchMethodError for builder.addAction

- src/baseSelectors.js
- src/message/InfiniteScrollView.js
- src/title/__tests__/titleSelectors-test.js
- src/title/titleSelectors.js
- src/utils/__tests__/getStatusBarStyle-test.js
Suppose we are in topic narrow and status bar is coloured
It shows like this on current master 
Now like this
> Change getTitle & getTitleTextColor according to current navigation route

- src/common/ZulipStatusBar.js
- src/utils/__tests__/getStatusBarColor-test.js
- src/utils/getStatusBarColor.js
> Fix: status bar backgroundColor in dark theme on Android.

- src/compose/ComposeMenu.js
- src/compose/ComposeMenuContainer.js
- src/compose/composeActionSheet.js
- src/message/messageActionSheet.js
- src/types.js
It changes the menu construction & hides the 'Toggle compose tools' in the topic narrow
> Rework ComposeMenu to have menu construction like message action sheet

- src/nav/navReducers.js
- src/start/AuthScreen.js
- src/start/DevAuthScreen.js
- src/types.js
I don't understand why `setAuthType` is required which was causing the bug! 
Still the in the dev auth screen the text Administrators & Normal users are not visible which I think is because of KeyboardAvoidingView doesn't detect any TextInput so no padding is added and the Administrators text is going under the toolbar in iOS (Not sure if this 100% true)
> Fix: Dev auth screen crashing on handleDevAuth()

- src/html/HtmlNodeTag.js
> Fix: code block aren't rendered properly.

- src/account-info/LogoutButton.js
Changing the state with `actions.logout()` & calling `actions.resetNavigation()` was returning undefined accounts in getInitialRoute, hence even if more than 1 account the app was navigating to RealmScreen
And the code isn't required and will now navigation to account picker screen!
> Navigate to Account picker screen after logout

- src/chat/UnreadNotice.js
Temporarily taking out the animation, to be added later as a separate component.
> Refactor animation in UnreadNotice

- src/start/OAuthView.js
- src/start/PasswordAuthView.js
- src/start/RealmScreen.js
- src/styles/theme.js
Added marginTop to fields in RealmScreen and AuthView.
Before
iOS
Android
After
> Fix: input fields are not properly visible.

- src/message/__tests__/__snapshots__/fetchActions-test.js.snap
- src/message/__tests__/__snapshots__/messageActions-test.js.snap
- src/unread/__tests__/unreadSelectors-test.js
- src/unread/unreadSelectors.js
Now it matches the unread counts shown by Zulip app/website.
> Fix: Don't count muted streams/topics in unread notice

- src/users/UserList.js
Tested on latest beta 2.1.33
We can enable in RN0.48 or so, if it gets stable.
> Removed sticky header from userList as they are not stable on scroll.

- src/i18n/extractString.js
- src/i18n/translations/messages_en.json
- src/message/MessageContainer.js
- src/message/MessageListFlatList.js
- src/message/__tests__/messageActionSheet-test.js
- src/message/headers/MessageHeader.js
- src/message/messageActionSheet.js
After this gets merged will convert the other local strings as well!
> Use translated strings in message action sheet

- android/app/src/main/java/com/zulipmobile/notifications/GCMPushNotifications.java
- src/boot/AppEventHandlers.js
- src/utils/notifications.android.js
Crashing when application in dead state occasionally, but working perfect if app in background
> Fix: Narrow to correct sender on notification press

- android/app/src/main/java/com/zulipmobile/AnchorScrollView.java
Fix: visibles id's not being send from AnchorScrollView.
Sorry, at that time I was only focussed no scroll events, forgot about visible id's.
> Fix: message not mark as read in Android.

- src/common/ImageAvatar.js
> [Android] Limit touchable area of avatars in message list.

- android/app/src/main/java/com/zulipmobile/AnchorScrollView.java
Problem was if message is quite long (not fully visible on screen) then it was not considered as visible child.
Fix: #1291
@kunall17 can you verify when you get some time. :) 
There may be other cases as well, this PR solves one such case. :)
> [WIP] [Android] Fix: unread count stuck at one on Android.

- android/settings.gradle
At line 21 there is already setting for `reactnativenotifications`
https://github.com/wix/react-native-notifications#android-1
> Remove duplicate react-native-notifications from settings.gradle

- src/settings/LanguagePicker.js
Fix: shift of list from center to top of the screen after few seconds.
> Added initialNumToRender prop in LanguagePicker.

- src/common/Screen.js
- src/group/GroupScreen.js
Fix: create button not visible.
Fix: whole screen is scrolling, only users list should scroll with sticky header on iOS.
> Fix: layout regressions in New Group Screen.

- src/unread/UnreadStreamsCard.js
- src/users/UserList.js
In RN 0.49 (or even in RN 0.48) sticky headers for Android are stable.
> [Android] Enable StickyHeaders in Unread and UserList.

- src/connectWithActions.js
Fix crashes when swiping back from screens. 
<details><summary>Bug demo gif</summary><p>
</p></details>
<details><summary>Stack log</summary><p>
```
navigation.dispatch is not a function. (In 'navigation.dispatch(_NavigationActions2.default.back({ key: backFromScene.route.key }))', 'navigation.dispatch' is undefined)
<unknown>
CardStack.js:218:28
<unknown>
AnimatedValue.js:267:29
__debouncedOnEnd
Animation.js:59:19
__invokeCallback
MessageQueue.js:347:19
<unknown>
MessageQueue.js:137:28
__guard
MessageQueue.js:265:6
invokeCallbackAndReturnFlushedQueue
MessageQueue.js:136:17
```
</p></details>
> Fix screen crashes

- src/nav/Sidebar.js
- src/nav/StreamTabsCard.js
This allows simpler navigation if someone is on the conversations tab they can narrow the home view
> Move the home, private, starred icons to root sidebar

- src/autocomplete/EmojiAutocomplete.js
- src/baseSelectors.js
- src/common/Popup.js
- src/directSelectors.js
- src/emoji/EmojiRow.js
- src/emoji/__tests__/getFilteredEmojiList-test.js
- src/emoji/getFilteredEmojiList.js
- src/types.js
- Fix: Autocomplete shodows not visible on Android.
- Show realm emojis in autocomplete.
- Show all items even if filter length is 0.
- This gives an idea what's the use of @, :, # keywoards.
- FB messenger, Slack, Whatsapp all have this.
Before
After
> Improve autocomplete

- .eslintrc
- src/title/TitleGroup.js
It takes some time to fetch users, until all are null having same email. So concat with index to get unique key.
> Fix: warning when list of null users is shown in GroupTitle.

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/zulipmobile/ZulipNativePackage.java
- android/app/src/main/java/com/zulipmobile/notifications/BadgeCountUpdaterModule.java
- android/app/src/main/java/com/zulipmobile/notifications/GCMPushNotifications.java
- src/boot/AppEventHandlers.js
- src/unread/unreadSelectors.js
This implements the change of badge count through JS, so if there are some unread messages after they close the app, we can display them in the badge.
And if a notification is received while the app is closed we can increment the badge count and display.
Which count should we display
-  PMs + Group messages + mentions
- PMs + Group messages + stream messages  ?
@timabbott @borisyankov
> Wrap ShortcutBadger as a module to be used in JS

- src/message/__tests__/__snapshots__/messageActions-test.js.snap
- src/message/__tests__/messageActions-test.js
- src/message/messagesActions.js
- src/utils/narrow.js
Small & sweet alernative for #1147 with more functionality.
> Handle invalid narrow.

- src/outbox/outboxReducers.js
Fix: unsent messages are being shown in another account.
Next task: will be to preserve outbox & club messages with `realm` and `email` so that app is not sending unnecessary requests via another account.
For now we can take this in and next task in another PR.
> Clear outbox on account switch.

- src/message/MessageListSection.js
- src/message/cachedMessageRender.js
Push header only if there is valid message under it. Don't push if it only contains times item.
Before
After
> Fix: extra message header is shown.

- src/animation/AnimatedComponent.js
- src/chat/Chat.js
- src/chat/UnreadNotice.js
- src/message/MessageList.js
- src/styles/theme.js
* Overlap it with message list, so when notice state toggles it does not scroll list.
* Toggle state with translational animation.
required for https://github.com/zulip/zulip-mobile/pull/1483
Also reduces unnecessary scroll events :)
> unread notice: Improve layout.

- src/message/MessageListWeb.js
- src/message/html/js.js
* Removed all arrow functions from webView, not supported on many Android devices (mainly of lower API).
* Add targetOrigin argument in postMessage method call. Required for Android.
> [Android] Fix: webView onMessage is never triggered.

- docs/developer-guide.md
I was working on the *Intro to Zulip Mobile Development* Google Code-in task, and I ran into the slight problem that I didn't have Yarn installed when setting up the development environment. 
This was not a major issue, as installing Yarn was simple and easy, but I thought it would be a good idea to make a simple change to the documentation so that others don't run into this minor inconvenience.
> Add git and Yarn installation to `docs/developer-guide.md`.

- src/message/html/js.js
Trailing comma is not allowed on Android.
(Another item added to list :p)
(will be creating a doc listing on this soon :))
> webView: fix js not working inside webView on Android.

- src/autocomplete/__tests__/getAutocompleteFilter-test.js
- src/autocomplete/getAutocompleteFilter.js
The AutoComplete View pops up when typing '@' to mention usernames, but when typing email addresses the same View pops up. This was fixed by checking whether the previous letter before the '@' is an empty space. This stops the view from showing as the letter before '@' would never be a space in an email.
Fixes:#1553
> Fix AutoComplete from showing up when typing Emails

- src/streams/StreamCard.js
https://sentry.io/zulip/zulip-mobile/issues/424931111/
> Fix: Subscription.color crash in StreamsCard

- src/common/ZulipStatusBar.js
- src/main/MainScreen.js
This is a part of #1606 that's being split off into its own PR (see #1606 for more details). It hides the statusbar when the user is in landscape mode. 
(Done for the *"Issue #1187 Slimmer nav bar in landscape mode"* Google Code-in task.)
> Hide the statusbar in landscape mode.

- src/nav/navReducers.js
Instead of pushing new route, because on navigating back doesn't make sense. As no account is selected.
> Reset navigation to AccountPickScreen on logout.

- src/nav/AppWithNavigationState.js
- src/utils/notifications.android.js
- src/utils/notifications.ios.js
As the current event callback method was not consistent for android, this will get the data after each launch in android and narrow on notification click 
tryInitialNotification in notifications.ios.js will be same as in #1643 which is to be tested by the provisioning profiles first!
> Use PendingNotifications for Android

- src/render-html/css.js
> webView: Fix bg color of brief messages containing self-mentions.

- src/unread/__tests__/unreadSelectors-test.js
- src/unread/unreadSelectors.js
Avoids adding the muted streams in getUnreadStreamsAndTopics as it results a blank tab 
Another way could be check if all the items in the array have true in the `isMuted` boolean, but would be a performance overhead!
> Fix: Don't add muted streams to UnreadStreamsCard

- src/render-html/es3.js
- src/render-html/js.js
- src/render-html/messageAsHtml.js
As only long press on msg-content needs to be considered (not headers, reations, tags avatar etc.).
> webView: Create helper method to validate target is msg-raw-content.

- src/common/ComponentWithOverlay.js
- src/common/UnreadCount.js
> Fix: misplaced unread count in overlay.

- src/compose/ComposeMenu.js
Now it doesn't break animation :)
> Fix: Compose menu icons are visible even in unexpanded state.

- src/common/PasswordInput.js
Checked in other apps. Usually small letters keyboard is popped for password fields.
> Fix capital letters keyboard is popped on password input focus.

- src/render-html/css.js
So that only our actionSheet is shown. Fix: two actions are shown on long pressing links.
> webView: [iOS] Prevent default longPress action on links.

- src/compose/ComposeBox.js
> [iOS] Fix: compose box message input text is not aligned properly.

- src/render-html/css.js
On master
* only half bullets are visible
* Left border of mention not visible 
This PR
> webView: Fix left side of the message content not completely visible.

- src/diagnostics/DiagnosticsScreen.js
As it returns same as the version visible on Play Store/App Store.
`getReadableVersion` concats `appVersion` & `buildNumber`
https://github.com/rebeccahughes/react-native-device-info/blob/2f4d19deb3d991b4397e81a15346ed4c5ba83efb/deviceinfo.js#L57
So I thinks it's better to show only `appVersion`. (which will not create confusion among users, version mismatch in app and store)
Thoughts?
@borisyankov @kunall17
> Use getVersion method to get app version.

- src/compose/ComposeBox.js
Test the bug: Type a message then change the narrow, then narrow back to previous one, and now send message. Now close app (forcefully). Now on opening again, compose box contains that draft.
Part of #1835.
> Delete drafts on sending message.

- src/main/MainScreen.js
- src/main/MainScreenWithDrawers.js
Dismiss keyboard when drawer opens via swipe and hanburger icon.
Fix Keyboard is not dismissed on swiping to open drawer on Android.
> Better handling of Keyboard on DrawerOpen.

- docs/getting-started.md
While setting up development environment with zulip-mobile I noticed a few issues in the getting started guide. Taking `package.json` as reference I've updated the documentation. 
Addresses #1905
> docs: Update getting-started guide

- src/main/MainTabIcon.js
- src/main/MainTabs.js
Again back to normal :)
iOS
Android
> Fix: tabs icons are not visible on Android.

- src/group/AvatarList.js
- src/lightbox/LightboxScreen.js
- src/session/sessionReducers.js
- src/settings/LanguageScreen.js
- src/settings/SettingsCard.js
- src/start/AuthScreen.js
- src/title/TitleGroup.js
- src/topics/topicsReducers.js
- src/types.js
- src/users/UserList.js
- src/utils/notifications.ios.js
- src/utils/timing.js
Much of our code that *looks* typed actually hasn't been.  We have a
lot of our types concentrated in this one file `types.js`, and we
haven't marked it as a file Flow should look at -- which means that
when we import a type from there, Flow treats that as a totally
unknown type.  Any property we get off of such a type, or the return
value from any method call on it, then gets the same untyped treatment.
So, mark the file with `@flow`.
Just doing that alone brings 1564 (!) errors.  (Figures based on a
version from the other day; may vary slightly after rebase.)  So in
order to make this mergeable, I dialed it back:
* out of about 77 types in the file, knocked out about 44 of them
back down to `any`
* added 5 more types, all as `any`
* sprinkled a couple of mysterious `any`s in …
> Include `types` in our type-checking

- src/common/SmartUrlInput.js
- src/start/RealmScreen.js
- src/styles/theme.js
* make sure the input is the same height as the autocomplete text (by adding 0 padding)
* do not use the 'placeholder' as it behaves suboptimally on Android
> Fix SmartUrlInput on Android

- src/boot/store.js
- src/nav/__tests__/navSelectors-test.js
- src/nav/navSelectors.js
Most competitive chat apps and most general purpose apps do not
persist deep navigation state between runs. It does not seem suitable
for us too. In future we should consider storing a single narrow
navigation as a possibly better solution.
> Do not persist navigation state between runs

- src/autocomplete/TopicAutocomplete.js
- src/chat/UnreadNotice.js
- src/chat/__tests__/chatSelectors-test.js
- src/chat/chatSelectors.js
- src/message/MessageListContainer.js
- src/message/messageSelectors.js
- src/message/messagesActions.js
- src/topics/__tests__/topicsSelectors-test.js
- src/topics/topicSelectors.js
- src/unread/unreadSelectors.js
This was suppossed to be part of #2020, but was missed at that time.
> refactor: Rename InActiveNarrow to forNarrow.

- src/boot/reducers.js
- src/directSelectors.js
- src/loading/loadingReducers.js
- src/types.js
Not all states can be distingished between being loaded but empty
and still loading. This new state will serve to differentiate
these two states. Later loading indicators based on it will be added.
> Add 'Loading' state and reducer

- src/start/RealmScreen.js
- src/utils/__tests__/url-test.js
- src/utils/url.js
This is so the input fits better on screen.
We will return the value back once we start hosting on `zulip.com`
> Shorten realm input placeholder to 'your-org'

- src/common/SmartUrlInput.js
Focus remains on the input, yet there is no keyboard.
Thus we need to first lose the focus and re-focus.
> Show keyboard if dismissed in realm input. Fixes #2058

- src/topics/TopicList.js
- src/topics/topicSelectors.js
Returning undefined from selector allows us to differentiate
between empty stream and topics not yet loaded.
> Fix: Show loading indicator for topics instead of message

- src/topics/__tests__/topicsSelectors-test.js
Returns undefined for non-existing streams to differentiate 'loading' from 'no topics' states.
> Add tests for getTopicsInScreen selector

- src/conversations/ConversationsCard.js
Conversation data may be fetched already but can not be shown
before users are loaded so show loading.
> Show loading for conversations if users data is loading

- src/common/UnreadCount.js
In many versions of Android this causes a crash for unknown reason
> Fix crash: revert 'ellipsizeMode' in UnreadCount

- src/nav/ModalNavBar.js
This makes it consistent with MainNavBar visually.
Adds a bit more space between the back button and the title.
When there is no back buton adds a left margin.
> Add ViewPlaceholder to ModalNavBar

- package.json
- src/api/apiFetch.js
- src/message/__tests__/fetchActions-test.js
- yarn.lock
Calling 'fetch' with invalid URL in iOS correctly throws an
exception. On Android though it throws inside Java code and
leads to a crash.
Ideally we will catch invalid URLs even earler, but this adds an
important guard clause and additional info in the exception,
ensuring it is thrown within our JS code.
> Check for URL validity in apiFetch

- src/conversations/__tests__/conversationsSelectors-test.js
- src/conversations/conversationsSelectors.js
Sorting by timestamp is generally correct but sometimes
the values are equal and sorting by message id is preferrable.
Additionally including the last message id helps us with upcoming
feature where we will display part of the last message text.
> Sort conversations by message id

- src/title/ActivityText.js
- src/title/TitlePrivate.js
- src/title/TitlePrivateContainer.js
Makes it reusable (will likely add it to AccountDetails too)
In rare cases we might not have presence data loaded, checks for
undefined and does not render if so.
Fixes #2104
> Extract activity text from TitlePrivate to separate component

- src/__tests__/baseSelectors-test.js
- src/baseSelectors.js
- src/topics/topicSelectors.js
This selector is used in several screens.
Returning an empty object prevents potential bugs.
Fixes #2114
> Do not return undefined from getCurrentRouteParams

- src/streams/StreamList.js
- src/unread/UnreadCards.js
Currently only few are rendered initially and its take
some time to render next batch. Easily obervable on
older Android physical devices.
*  90aa1f3
Actually in ea3b464
unread list was designed to be section list of section list,
so initalNumToRender was 2, but later it converted to single section section.
*  8074bd6
So for better user experience, render alteast as many
items which can fill screen.
For next level we can have something like get count dynamically according to the screen size. But will become complicated for now.
> Add initalNumToRender in unread & stream list.

- src/nav/MainNavBar.js
- src/nav/ModalNavBar.js
- src/nav/ModalSearchNavBar.js
Use connectWithActionsPreserveOnBack instead
of connectWithActions so that it do not
re-render unnecessary on navigating back.
This can be tested easily on Android, little bit old device.
It fixes the momentary flash of white color (from stream color)
in nav bar on navigating back to main screen.
In private narrow, back arrow is not visible for some millisecond
in transaction back to main screen.
In lightbox, it reduces re-render of header, when component
is about to unmount.
In search narrow, back arrow is not visible for some millisecond
in transaction back to main screen.
> Improve stability of navBar.

- src/common/Screen.js
> Fix input fields overlap with Nav bar in landscape mode (#2071)

- src/nav/__tests__/navSelectors-test.js
- src/nav/navSelectors.js
If current route is lighbox then also we can go back.
Created new selector isCurrentRouteIsLightbox, which
can be used to distinguish such cases and back arrow
button can be rendered accordingly.
Fix: #2127.
> navigation: Fix regression in getCanGoBack selector.

- src/title/TitleSpecial.js
* Increase icons size to 24.
* Align Label vertically center.
Before
Now
> titleSpecial: Improve style.

- src/chat/__tests__/chatReducers-test.js
- src/chat/chatReducers.js
- src/message/fetchActions.js
We used 'replaceExisting` value to determine if we should replace
current messages in fetched narrow with new messages.
This missed several key cases; we used it only on startup.
All cases where we need to replace data have an anchor of 0 or
Number.MAX_SAFE_INTEGER.
This is a fix for several erratic message list behaviors.
> fix: Replace data in narrow on anchor 0 or Max value

- src/typing/__tests__/typingReducers-test.js
- src/typing/typingReducers.js
This happened sometimes when two users are typing and one stops.
Unfortunately the unit-test covering that case was also wrong.
This also very likely fixes the repeated audio bug
> fix: Correct state mutation of EVENT_TYPING_STOP

- src/main/MainTabs.js
This fixes the bug of erratic behavior of Android hardware
back button. The issue was that the TabNavigator did intercept
the button even when other screens were opened.
This is a simple and definitive fix - the back button will no
longer move you between tabs. Some big apps do use it, some other
big apps don't. So we don't have a preference for either of the
behaviors (but the new one fixes our issue!)
> fix: Disable Android Back Button in Tabs

- src/utils/notifications.android.js
- src/utils/notifications.ios.js
* no need for async for handlePendingNotifications
* proper name for the event handler
* handlePendingNotifications() in iOS the same as Android
> refactor: Make notification handling more consistent

- src/common/Screen.js
The ScrollView wasn't scrolling in the Screen component and due to this, it was difficult to access the input fields in landscape orientation.
> screen: Fix scrolling in ScrollView

- src/types.js
types: topic property for the editMessage was missing in types. I added the missing property and fix flow type for editMessage.
> flow: Fix Flow types for EditMessage

- src/api/apiFetch.js
Fix: error message not being displayed in the failed edit
message dialog.
Before ([current master](https://github.com/zulip/zulip-mobile/tree/0c647303a266800355b8cabfdd4857c9fa300375))
https://chat.zulip.org/user_uploads/2/cd/inwDS-fao9JZN5FdjS7MSwXh/Simulator-Screen-Shot-iPhone-6-2018-03-31-at-04.47.49.png
This PR
> apiFetch: First check for bad response, then for ok response.

- package.json
- src/api/apiFetch.js
- src/start/RealmScreen.js
- yarn.lock
[current master](https://github.com/zulip/zulip-mobile/tree/0c647303a266800355b8cabfdd4857c9fa300375)
This PR
> Fix: button is enabled just after typing `https://` or 'http://' in the realm input.

- src/common/OptionRow.js
Added a divider above the "Night Mode" OptionRow in settingsCard. Also added padding to the Label component in OptionRow, so it matched the styling of Label component in OptionButton, which made both of them the same height.
Before:
After:
Also updated the developer guide, added the missing step to run `react-native start` before `react-native run-android` and a command to increase inotify watches to fix a common error while running `react-native start`.
UPDATE:
Screenshot before the OptionRow component was changed, notice the difference in height between the OptionRow and the OptionButton components beneath it.
> Made OptionRow and OptionButton the same height, and fixed Night Mode being squashed to the top

- src/types.js
Fix the type of settingState by adding 4 missing properties. I checked the reducer and realized that those properties were missing.
> flow: Fix flow types for SettingsState

- src/types.js
I printed out recipient and realized that the id property was missing.
> Flow: fix flow types for Recipient

- src/common/Screen.js
Revert bug introduced in #2184
> fix: MessageList in Search Screen not visible

- src/message/fetchActions.js
The more complicated async call remained from a previous
version of the function and is no longer needed.
> refactor: Simplify messageFetchComplete action creator

- src/boot/AppDataFetcher.js
componentWillReceiveProps is being deprecated soon.
The refactor has no disadvantages but in fact simplifies the code
> refactor: Rework AppDataFetcher to remove componentWillReceiveProps

- src/compose/__tests__/getComposeInputPlaceholder-test.js
- src/compose/getComposeInputPlaceholder.js
This never really looked good with the `#...:...` syntax, which looks
more like a leaked bit of code than like something intended for the
user to see.  Worse, when the topic gets a bit long, it overflows onto
a second line, which tends to get half-cut-off at the bottom and then
looks super broken.
Prevent that by just cutting the topic out entirely.  Fixes #1966.
These messages still don't feel quite right UI-wise, but we'll take
one step at a time.
Screenshot before:
and after:
> compose: Avoid repeating topic in placeholder.

- ios/ZulipMobile/Info.plist
Add `NSPhotoLibraryAddUsageDescription` key and
value to Info.plist. Now when user try's to download
photo from lightbox, dialog is popped to take permission.
This preference is considered while downloading next time.
When permssion is not allowed, CameraRoll throws error
which is then caught and can't download toast message is shown.
This fixes: app becomes unrespossive on selecting download
option in lightbox actionsheet when permission is not given.
Fix: #2216
https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html
> iOS: Ask for add photos to library privacy.

- src/render-html/generatedEs3.js
- src/render-html/js.js
This was missed when the sendMessage was introduced.
No functionality changes intended
> webview: Reuse sendMessage function in handleScrollEvent

- src/settings/NotificationsScreen.js
Added OptionRow component between the OptionRow components to match the
style of the main Settings screen.
Before:
After:
> notificationsScreen: Add OptionDivider

- src/settings/SettingsCard.js
The divider style was being suplicated in SettingsCard since the OptionDivider component already had the divider style. 
This fix replaces the divider style with the OptionDivider component.
> settings: Replace divider style with OptionDivider

- src/common/InputWithClearButton.js
In RN 0.55 TextInput for iOS is re-implemented from ground,
so this might introduced in that.
https://github.com/react-native-community/react-native-releases/blob/5d160a86c54163c3df5bdb07282c0de48bfe7acb/CHANGELOG.md#ios-specific-changes-1
So this is a quick fix for that.
> iOS: Fix textInput is not cleared on clicking clear button.

- src/boot/AppEventHandlers.js
- src/session/sessionActions.js
Currently the `getSafeAreaInsetsForRootView` returns only the data
we want, but it might change. Instead we decouple the return format
from our action parameters and pass only the safeAreaInsets object.
This also helps with Flow typing later
> refactor: Treat safe area insets more precisely

- src/utils/__tests__/date-test.js
- src/utils/date.js
This handles the case where presence data is not available
but the function is called anyways
Fixes #2242
> Handle presenceToHumanTime incorrect parameters

- src/compose/ComposeBox.js
Fixes #2273
* make sure not to reset reference to messageInput
* check if the reference to messageInput is defined before focusing
> fix: Do not throw if messageInput reference is undefined

- src/render-html/MessageListWeb.js
componentWillReceiveProps is being deprecated.
This moves the update call to shouldComponentUpdate
No functional changes intended.
> refactor: Do not use componentWillReceiveProps in MessageListWeb

- src/render-html/css.js
Remove flexibility of image heights.
This fixes an issue with images being different height while loading
and when loaded, thus messing up chat position.
> webview: Make images a fixed height

- src/streams/StreamScreen.js
Fixes the spacing between `OptionRow` components in the `StreamScreen` component by adding `OptionDivider`
Before:
After:
The commits described below has since been removed:
_The second commit adds OptionDivider between rows in TopicList and increases the padding from 8 to 16 to match components found in other menus such as OptionRow. The 3rd commit removes padding from TopicListScreen as it seems unnecessary since there is no text or other elements that would require padding._
> Fix: Spacing in StreamScreen

- src/render-html/MessageListWeb.js
- src/render-html/generatedEs3.js
- src/render-html/js.js
- src/render-html/webViewHandleUpdates.js
Send input messages as array of objects instead of several times
as a single object.
That increases performance, reliability and predictability.
There are several reports in the GitHub issues for React Native
that sometimes messages are not delivered when several sent in
quick succession. I could reproduce that, though very rarely.
Hopefully this code fixes that issue, but even if not, the
benefits remain.
> webvew: Batch webview input messages

- src/group/GroupScreen.js
We open Create Group screen with a keyboard open. That is OK.
But then tapping on a user as a first action hides the keyboard
but does not add the user.
Instead, tapping the user now adds it, and tapping outside the
user list will hide the keyboard.
> keyboard: Do not 'swallow' first taps in group screen

- src/streams/CreateStreamScreen.js
- src/streams/EditStreamScreen.js
Make sure we do not ignore the first tap on buttons in
Create & Edit screens, activate on first tap.
> usability: Create and Edit sream screen one-tap on buttons

- src/streams/EditStreamCard.js
A change that returned -1 instead of undefined for streamId
messed up the UI logic and it always tried to update a stream
even a non existing one wiht ID of -1.
Fixes #2288
> Fix create stream failing

- src/chat/__tests__/chatReducers-test.js
- src/chat/chatReducers.js
Fixes #2296
Two architecture choices done at different times clashed to produce
this incorrect (and covered by tests) behavior!
We didn't store incomming messages for which you don't have yet
keys in the message store. But since we also didn't store empty
response from narrowing this made sure we do not store any messages
sent to a narrow with no messages.
> fix: Store keys even for empty message gets

- src/chat/__tests__/chatReducers-test.js
Ensures messages are added to the PM special narrow
The test is already passing but it includes case not previously tested
> tests: Add a test for PM narrow to chatReducers

- src/group/GroupContainer.js
- src/users/__tests__/userSelectors-test.js
- src/users/userSelectors.js
Fixes #2289. Currently, while creating a group a user is free to add himself to the group chat, which by default is done. This is unnecessary and this option is also not available in other group chat apps like slack or WhatsApp groups.
> group: Remove oneself from new group user list.

- src/api/apiTypes.js
- src/api/users/getUsers.js
- src/types.js
- src/users/usersReducers.js
We need to have types for the incoming API data.
A good place to start is our User and its API counterpart.
All types will be prefixes with `Api` to distinguish them.
> flow: Create a file for API types and add ApiUser

- src/group/GroupCard.js
* add checks for user is found and listRef is defined
* setTimeout is now more predictable
If we are selecting a user, we scroll the avatar list to the end
to ensure the last item just added is visible.
Previously we had to wait for some time until the component updates.
We did wait for 300msecs (magic number). Ensuring that the component
already did update we use setTimeout only to allow the UI to refresh
but we no longer need to wait 300msecs.
> refactor: Make selection scrolling more precise

- src/api/apiFetch.js
- src/start/RealmScreen.js
- src/utils/url.js
Often it is useful to abstract where a function is coming from.
We have reworked the url validation function several times.
This will focus any further changes in one place.
We make sure to call the function a name that will not change
and currently just reuse isUrl.
> refactor: Abstract away where isValidUrl function comes from

- package.json
- src/utils/url.js
- yarn.lock
is-url validates only 'loosely' according to their own description.
Some important cases were missed (double dots etc.) and on
Android this results in a crash.
url-regex uses a very well tested and almost 'famous' regex:
https://gist.github.com/dperini/729294
As seen here it tests all tests but the '_' one:
https://mathiasbynens.be/demo/url-regex
We do not allow underscores in our subdomains and it is
very uncommon character to be used, also not valid in domain names.
> url: Replace is-url with url-regex for precise url validation

- src/utils/__tests__/message-test.js
- src/utils/message.js
When narrowed to a muted topic we should always show the messages
and hide them when in stream & home narrows.
Fixes #2206
> fix: Messages in muted topics should be visible

- src/compose/ComposeBox.js
This follows user feedback that the topic input looked disabled
and after a discsussion we agreed that it must be made more 'editable'
> ui: Make the topic input look less 'disabled'

- src/nullObjects.js
- src/types.js
- src/utils/misc.js
* refactor: Rename 'isStateGoingBack' to 'areStatesSeemsToBeEqual'.  a34d5f1
As it is custom implementation for `areStatesEqual` for connecting
component to redux store.
https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options
In this custom implementation, currently two cases are considered.
One is whether navigation is going back or not, that is new routes
count in less than previous one. And secondly is current and previous
states are equal. This method returns true when re-render is not
required even with state change, that is it is pretending
that states are same.
So 'areStatesSeemsToBeEqual' is better name for this method.
* connectReduxStore: Consider navigation intermediate transition state.  6b88176
Pretend that …
> Improve connect with actions call.

- src/users/__tests__/userHelpers-test.js
- src/users/userHelpers.js
We need more processing of presence data we get from the server
in order to get useful information.
We might want to do changes to the logic later, in  mobile
there does not seem to be a meaningful 'idle' state.
* status is offline if the aggregate presence is "offline"
* status is idle if presence timestamp is less than 1hr
* status is active if timestamp of last activity is less than 5mins
> Add statusFromPresence function

- src/users/UserList.js
- src/users/__tests__/userHelpers-test.js
- src/users/userHelpers.js
Start using statusFromPresence to correctly determine user list
sort order (first active, then idle, then offline).
Secondary sort when status is the same is done by name
> fix: sortUserList now correctly uses presence

- src/title/TitleGroup.js
- src/title/TitleGroupContainer.js
Pass presence and use it to display status in group chat screens
Increate avatar icon size for better consistency and so the status
dot does not hide half of the image.
> fix: Display user status in group screen title

- src/autocomplete/StreamAutocomplete.js
- src/streams/StreamCard.js
- src/streams/SubscriptionsCard.js
- src/types.js
- src/utils/message.js
Subscription becomes a super-type of Stream
This will clarify many cases as we almost always use only the
'stream' part of the data even when using subscriptions
> flow: Add types for Stream and Subscription

- src/streams/StreamCard.js
- src/streams/StreamScreen.js
- src/styles/theme.js
Reworked the UI of menus to achieve a more modern design consistent with Material Design guidelines.
Screenshot of settings screen before:
Screenshot of settings screen after current changes:
In night mode:
The `OptionDivider` component has been converted to a class based component in order to access `styles` via context like other common components.
Commit 8123dfc adds a padding around the version number in `DiagnosticsScreen` to make it look less crowded.
> Reworking UI of all menus

- src/unread/__tests__/unreadSelectors-test.js
- src/unread/unreadSelectors.js
We still count all unread messages in unread topics for topics
total unreads. But when totalling the stream unreads we do not
include them. This matches exactly the web app's behavior.
> fix: Do not include muted topics in stream unread count

- src/api/apiFetch.js
* handle both response error and error in json the same way
* do throw the whole response so the catcher has access to all fields
* verified, no changed to any other code needed, as currently none
of the try-catch-ers of fetch calls care about the error object
> error handling: Throw the whole response on fetch error

- src/events/eventActions.js
Instead of parsing the status text which was never a great idea
and does break when api response is translated.
The logic now is exactly the same as in the front-end app.
> Handle errors returned by event queue 18n-independently

- src/unread/__tests__/unreadSelectors-test.js
- src/unread/unreadSelectors.js
This already works in the Streams tab, adding the same functionality
to the Home (unread) tab. Tests changed to confim this new behavior.
> ui: Move pinned streams to top in Unread tab

- src/unread/UnreadCards.js
In the 'Unread' tab, if a stream has muted topics but all other
topics are read, hide them.
Add a keyExtractor property for performance purposes.
> ui: Hide streams whose only unread topics are muted

- src/users/__tests__/userHelpers-test.js
- src/users/userHelpers.js
Rework the 'too smart' approach to be consistent with the web app
which is mor important. Use OFFLINE_THRESHOLD_SECS = 140 if above
this threshold for the last activity the status is 'offline',
else it equals what was reported by the server.
> presence: Make status detection consistent with web

- src/chat/__tests__/chatReducers-test.js
- src/chat/chatReducers.js
For every narrow we have data for that is caughtUp at 'newer'
we store new incoming messages from the event polling.
Previously we determined if a message should be put inside a
narrow even if no messages were loaded for it. This is not needed
and even does not serve as a good cache because on narrowing
we throw it away and reload new messages.
This also simplifies the code and makes it more predictive.
> refactor: Do not store new messages in narrows not open

- src/render-html/css.js
After analyzing several competitors and specifically Slack I noticed
all our paddings are very small (factor of 1.5 to 2, but mostly 2)
This increases the padding between the message and the borders, and
makes the avatar size 10% smaller from 2.5em (37.5px) to 32px to
be consistent with the avatars outside the message list (and Slack)
> ui: Improve message rendering spacing and avatar size

- src/chat/chatReducers.js
- src/render-html/css.js
- src/styles/index.js
- src/styles/platform.android.js
- src/styles/platform.ios.js
We no longer use 2 of the constants and the other two are not
different between the platforms. Moved to a single place for simplicity.
> cleanup: Remove platform-specific UI constants

- src/unread/unreadSelectors.js
This is hopefully the final fix for this previously missed case.
Looks like we have some repeating logic in the unreadReducers,
and it will be a good idea to refactor soon.
> fix: Unread Notice component filters out muted topics

- src/api/registerForEvents.js
We already support calculating of user gravatars form their emails.
But we had the call to omit this extra data only for explicitly
getting users by `GET /users`. We now read them through the
`registerEvents` call so enable this setting there too.
> Enable client_gravatar for registerEvents

- src/streams/StreamItem.js
So that styles from context can be de-structured and can be used
easily. Like the same way we do in other components.
> refactor: Rename local styles variable to componentStyles.

- src/chat/__tests__/fetchingSelectors-test.js
- src/chat/fetchingSelectors.js
'needsInitialFetch' is a flag used to determine if we should fetch
data (via fetchEssentialInitialData and fetchRestOfInitialData)
The logic of 'isFetching' might have been correct in the past but now we
are using it differently. Remove the 'needsInitialFetch' flag from the
selector and keep only the fetching older & newer for current narrow.
> Fix isFetching selector logic

- src/group/AvatarList.js
We open Create group screen with a keyboard open. That is OK.
But then tapping on a avatar (in horizontal list at top) as a
first action hides the keyboard but does not deselect the user.
Instead, tapping the avatar now deselect that user, and tapping outside the
avatar list will hide the keyboard.
> keyboard: Do not 'swallow' first taps in avatar list.

- src/account/AccountList.js
- src/common/Screen.js
- src/group/AvatarList.js
- src/group/GroupScreen.js
- src/streams/CreateStreamScreen.js
- src/streams/EditStreamScreen.js
* the default value of 'never' is rarely a good choice
* the other option 'always' is good when we do not want the user
to be able to hide the keyboard (like on the password and realm screens)
* the one that is 'handled' is great as a default
Here we change the default value to 'handled', remove any property
that was manually setting it to that value, and remove several no
longer needed keyboardShouldPersistTaps in FlatLists.
> Change default value of keyboardShouldPersistTaps for Screen

- src/api/apiFetch.js
- src/events/eventActions.js
Fixes #2392
The error arises from trying to parse non JSON error message.
Implementing a true custom error class to throw seems quite tricky
since Babel does not support it (there are unreliable workarounds)
Instead, the Error message becomes 'API' and the response and code
are passed as properties of the thrown error object.
> Handle API errors and network errors differently

- src/render-html/renderMessagesAsHtml.js
Now that we use baseUrl, we no longer need to convert to absolute url
> Use relative URLs for avatars in message rendering

- src/render-html/generatedEs3.js
- src/render-html/js.js
Do not send scroll events while the 'loading' messages are shown
in webview. We just disable the scrolling and it is again enabled
when content is updated.
This fixes an issue marking messages as read even before they
are loaded (default of 0 to MAX_SAFE_INTEGER is sent)
> webview: Disable scroll events while 'loading' shown

- src/events/eventActions.js
- src/utils/__tests__/progressiveTimeout-test.js
- src/utils/progressiveTimeout.js
* replace 'sleep' inside 'startEventPolling' with it
* first call - no timeout
* each subsequent timeout is 2 seconds longer (2, 4, 6, 8, 10)
* at 10 seconds stop increasing timeout duration
* after 5 minutes reset and start at 0 again
> Add progressiveTimeout function

- src/streams/StreamIcon.js
- src/streams/StreamItem.js
- src/unread/UnreadCards.js
As we are already sending stream color via backgroundColor
prop. And we want text, icon color to be decided from the
background color.
This removes the confusion in stream item that text and
icon color should be taken either from color or backgroundColor.
> refactor: Remove color from unreadView streamItem.

- src/utils/__tests__/progressiveTimeout-test.js
This test deals with async timing, for which I had some reservations.
It seems I was right. This seems to fail from time to time when run
on CI. I did relax the checks and removed one of the upper limit ones
(< 2050).
If this version fails even once, we should remove the test.
> Make progressiveTimeout test less flaky

- src/render-html/webViewHandleUpdates.js
Move content update mssage to the end of the list.
This makes poisitioning more precise if another message happens
(since they hide/show elements)
> webview: Content update always as last message

- src/message/__tests__/messageUpdates-test.js
- src/message/messageUpdates.js
When determining if a new message wa loaded in getMessageTransitionProps
only consider true if the narrow remained the same.
> webview: Fix getMessageTransitionProps detecting new message

- src/message/messageUpdates.js
When determining update strategy, handle excplicitly the case when
newer or older messages were loaded. Previously we just did a fall
back to the default strategy.
> webview: Handle explicitly newer or older messages

- src/message/__tests__/messageUpdates-test.js
- src/message/messageUpdates.js
Previously we missed to discriminate the case when old messages
are invalidated and replaced with completely new ones.
If previous messages last message ID is older than the new messages
first message ID then the messages were completely replaced.
> Improve getMessageTransitionProps to detect replaced messages

- src/message/__tests__/messageUpdates-test.js
- src/message/messageUpdates.js
Fixes #2339
If we detect stale cache we replace messages completely.
Previously we did not properly catch this specific case and used
'preserve-position' strategy.
Instead, now we detect this case and position at anchor.
> webview: On messages replaced position at anchor

- src/streams/StreamItem.js
Remove the `unreadCount &&` check that is not even needed as
<UnreadCount /> component handles empty values by not rendering.
> fix: StreamItem fails to render when no unread data is loaded

- src/styles/index.js
- src/styles/theme.js
- src/styles/utilityStyles.js
* margin and padding based on a single constant
* utility padding styles
This is to unify the padding sizes in most of the places we use them.
Sometimes we can use custom sizes but rarely it is required.
This will help us make the spacing more consistent.
> ui: Extract padding & margin constants

- src/common/Centerer.js
- src/common/Screen.js
- src/settings/SettingsCard.js
- src/streams/StreamCard.js
Any specific style that is of the form `padding: {}` is replaced
with the utility styles introduced earlier.
> ui: Replace component padding styles with utility ones

- src/streams/StreamItem.js
- src/utils/color.js
This PR is just rework of #2036, with smaller, separate commits :)
#2036 is quite old and at that time we weren't following this commit style. So I thought of created new PR instead of pushing into that.
* refactor: Rename local styles variable to componentStyles.   a75ba2a
So that styles from context can be de-structured and can be used
easily. Like the same way we do in other components.
* streamItem: Improve logic to determine icon color. 0969136
If color is not undefined then use it else decide it from
background. As if someone is explicitly specifying color
then it is expecting it to be used, rather than computing.
Fix: stream icon color is black in all stream screen in dark theme.
* flow: Add null & undefined params type to foregroundColorFromBackground. 382419d
Return 'white' for …
> Fix: stream icon color in AllStreamList in dark theme. 

- src/streams/TopicItem.js
Initially the background color was set to copy the same background
of the topic header in the message list, but seems no one is making
the connection and instead it looks weird. Just remove this background.
> ui: Remove background from topic items

- android/app/build.gradle
Enables facebook/fresco which supports animated GIFs in Android.
React Native supports the library by default but does not include
it without us enabling it in the build.
> Add GIF support for Android

- src/compose/ComposeBox.js
Only fire event if draft was originally present and new message
effective (message.trim()) length is 0.
> drafts: Fix draftRemove action is always fired when chat screen pops.

- src/account/AccountPickScreen.js
Calling `switchAccount` action takes long and the user is not given
any indiction immediately. Use `setTimeout` to allow the UI to first
respond (the button will give feedback) and then call the action.
> ui: Allow UI to give feedback to user on account switching

- src/account/AccountPickScreen.js
- src/common/Screen.js
- src/search/SearchMessagesScreen.js
- src/start/AuthScreen.js
* screen: Fix scroll is not working. 9dd39e8
Apply flexed style to scrollView instead
of its content wrapper.
If it is applied on its content wrapper then there
is no scope of scrolling.
* search message screen: Fix messageList is not visible. 2f58180
Actually the issue is webView is not visible if it's direct
or indirect parent is scrollView. It can be easily tested
by surrounding message list with scrollView in chat.js.
We can make it visible by applying flex:1 style to scrollView
contentContainerStyle, but then it will broke scroll.
So in this commit this style is only applied for search message
screen.
> screen: Fix scroll is not working.

- src/utils/logging.js
- src/webview/MessageListWeb.js
- src/webview/js/generatedEs3.js
- src/webview/js/js.js
- src/webview/webViewEventHandlers.js
Add a new message type to webview and use it to pass any unhandled
exception back to the MessageListWeb component. Then send that data
via Sentry.
> error handling: Catch webview exceptions in Sentry

- src/webview/css/css.js
Sets 'absolute' position to the 'message loading' element so it
does not cause 'scroll' events to fire.
This improves on previous behavior by:
* not showing the 'scroll to bottom' button
* not sending extra 'scroll' events to messageListWeb component
> webview: Message loading state does not cause 'scroll'

- src/types.js
- src/utils/__tests__/notificationsCommon-test.js
- src/utils/notificationsCommon.js
For this to work we need to parse a string of comma delimited
numbers of the recipients. This data is not yet passed to the
function; we keep the function flexible and functional by making
the parameter of `usersById` optional.`
> Add support to getNarrowFromNotificationData for group narrows

- src/utils/__tests__/notificationsCommon-test.js
- src/utils/notificationsCommon.js
To do the group narrow, we get ids as input. We need to access the
users state to get these users emails. If a user does not exist
(disabled, deleted, just added but we haven't read that data yet?)
instead of throwing an error narrow to Home narrow.
> Handle narrow from group notifications when missing users

- src/boot/AppEventHandlers.js
- src/nav/__tests__/navSelectors-test.js
- src/nav/navSelectors.js
- src/users/userSelectors.js
- src/utils/notifications.android.js
- src/utils/notifications.ios.js
Pass `usersById` data to the newly updated `getNarrowFromNotificationData`
so it can calculate the correct group narrow.
Add empty `users` state to navSelectors tests as now the function
`getInitialNavState` depends on that data.
> notifications: Narrow to group narrows

- src/webview/css/css.js
While 'absolute' position was enough in iOS, Android still sends
scroll events. 'fixed' fixes this.
> webview: Prevent scroll events in Android while messages loading

- src/webview/MessageListWeb.js
- src/webview/webViewHandleUpdates.js
When the list of messages to send are an empty list we do not send
anything. Move this check from webViewHandleUpdates to the function
sendMessages so we can have the check run if called from elsewhere.
> refactor: Move message.length check inside sendMessages

- src/webview/MessageListWeb.js
- src/webview/js/generatedEs3.js
- src/webview/js/js.js
- src/webview/webViewEventHandlers.js
- src/webview/webViewHandleUpdates.js
We use postMessage to send messages to and from the webview.
Custom versions of that standard functions are injected by the
WebView component.
Sometimes, on Android (and seemingly not on iOS) it takes some time
for this custom JS to get injected, and we send our initial message
to the webview before it is ready. Thus the first message is not
delivered and often results in the 'infamous loading messages bug'
By checking for the function parameter count (window.postMessage.length === 1)
we can differentiate if the custom function is injected already or not.
Then we send a custom message back to our component.
> webview: Send a 'ready' message from webview js

- src/message/MessageListContainer.js
It is reduandant, it is never called. We already have it in
webViewEventHandler.
> clean: Remove old onScroll implematation from MessageListContainter.

- src/subscriptions/subscriptionsReducers.js
So that updated data is reflected in realm time.
If app is open and stream is updated then local cache
becomes inconsistent, stream name in streams and subscription
differs.
> subscription: Update subscription on EVENT_STREAM_UPDATE.

- src/topics/__tests__/topicsSelectors-test.js
- src/topics/topicSelectors.js
Instead of providing jut the basic topic list to the Topic screen,
get unread data from unreadStreams and isMuted from 'mute' state.
> Add unread and muted information to getTopicsInScreen

- src/utils/__tests__/progressiveTimeout-test.js
From time to time this test case fails, as it takes more than 100
msecs to run on CI. This change relaxes the check to be 'less than
1sec' and does not change the meaning of the test.
> test: Relax progressiveTimeout test criteria

- src/alertWords/alertWordsActions.js
- src/api/alert_words/getAlertWords.js
Also, do not require an auth parameter for the `initAlertWords` call.
> flow: Add types for `alert words`

- src/api/apiTypes.js
- src/api/focusPing.js
- src/types.js
Fixes the previously incorrectly typed call.
This is a special case for types, as usually we return not the
response but a property inside the response. In this case though
we both need the `presence` and `server_timestamp` thus we return
the whole response object.
> flow: Add types for API focusPing (presence POST)

- src/compose/ComposeBox.js
Implements #2463
Do not replace text to emoticons (like :) :P ;) etc.) on the client.
We do have this setting on the server-side now, it is configurabe
and more robust.
> Do not replace text to emoticons

- src/webview/webViewEventHandlers.js
It seems the thrown Error object expects a string.
With the previous implementation we are getting `[object Object]`
Now we stringify the details so we can receive them.
> webview: Fix webview exceptions details not sent to Sentry

- src/api/emoji_reactions/emojiReactionAdd.js
- src/api/emoji_reactions/emojiReactionRemove.js
- src/api/messages/sendMessage.js
- src/api/messages/updateMessage.js
- src/api/notifications/unregisterPush.android.js
- src/api/notifications/unregisterPush.ios.js
We do not use any of the responses from the post/patch API calls
currently. Yet we have specified (wrongly) some extraction
functions. This is likely caused by copy-pasting, as all of these
are wrong (but since unused not causing bugs).
Return the whole response for all these calls. Upcoming Flow types
for these calls will ensure proper use of these.
> api: Return whole response from post/patch API calls

- src/streams/StreamScreen.js
Fixes #2433
We were trying to retrieve the `mute` state from the `stream` value
but it is in the `subscription` one.
This also fixes not being able to change the mute state on muted stream.
> fix: Show stream is muted correctly

- src/api/apiFetch.js
Handle differently the cases where the server returns a 'not ok'
response (404, 500 etc.) vs successful response but with an error
code in the json.
This fixes a misleading exception where we try to JSON-parse an
HTML response from server.
> api: Handle differences in failed response and json

- src/start/PasswordAuthScreen.js
Fixes #2488
* make checking for errors in LDAP vs password simpler and less
error-prone
* do not disable 'Log in' button for LDAP if input is not email
(as it will not be, it will be a user name)
> fix: Correct error validation when logging in with LDAP

- src/animation/AnimatedComponent.js
- src/animation/AnimatedRotateComponent.js
- src/animation/AnimatedScaleComponent.js
- src/common/Centerer.js
- src/common/ComponentWithOverlay.js
- src/common/FlexView.js
- src/common/FloatingActionButton.js
- src/common/Input.js
- src/common/Label.js
- src/common/MultilineInput.js
- src/common/OptionRow.js
- src/common/PasswordInput.js
- src/common/RawLabel.js
- src/common/Screen.js
- src/common/SlideAnimationView.js
- src/common/SmartUrlInput.js
- src/common/Touchable.android.js
- src/common/Touchable.ios.js
- src/common/UnreadCount.js
- src/common/UserStatusIndicator.js
- src/common/ZulipButton.js
- src/lightbox/AnimatedLightboxFooter.js
- src/lightbox/AnimatedLightboxHeader.js
- src/lightbox/LightboxFooter.js
- src/lightbox/LightboxHeader.js
- src/nav/ModalNavBar.js
- src/nav/NavButton.js
- src/streams/StreamIcon.js
- src/types.js
- src/users/UserList.js
StyleObj used to be imported directly from `react-native`.
They removed it and converted the styling to `__internal*` naming
indicating they are not to be used elsewhere.
* rename from StyleObj to Style to better represent the type
* now a union
* can be boolean - just ignored (results of conditionals)
* can be number - a 'compiled' style represented as index
* can be an object
* can be an array of styles
> flow: Define Style type correctly

- src/utils/__tests__/avatar-test.js
- src/utils/avatar.js
Fixes #2493
Pass lower case emails to the gravatar hasing function
See http://en.gravatar.com/site/implement/hash/ for the specification
Related issue zulip/zulip@4abbfe9
> Canonicalize user email before producing gravatar

- src/webview/css/css.js
user-group-mention css styles are same as user-mention css
styles. So reuse it.
> webView: Add user-group-mention css styles.

- package.json
- yarn.lock
Modified the code and test cases in the parser repo here https://github.com/kunall17/zulip-markdown-parser/commit/e3cb658179dc14d1f117989abc3eb6cbf9560404 
Also added a CI to this repo.
This new update will generate HTML with the span tag's rather than img tag's as in the new updated markdown from the server (https://github.com/zulip/zulip/commit/5b5bcce0985f5b478a70b4b4bca4ea23e197d123) 
(Only changes regarding the emoji's and the other newer commits aren't updated in the parser repo!)
> Update zulip-markdown-parser to support the new emoji parsing

- src/api/apiFetch.js
- src/api/pollForEvents.js
We used to have a (not functioning well) timeout mechanism.
This parameter is a leftover of this feature, but is currently unused.
> cleanup: Cleanup unused 'shouldTimeout' API parameter

- src/account-info/AccountDetailsScreen.js
- src/actionTypes.js
- src/api/apiTypes.js
- src/api/users/getUsers.js
- src/autocomplete/PeopleAutocomplete.js
- src/chat/GroupDetailsScreen.js
- src/compose/__tests__/getComposeInputPlaceholder-test.js
- src/compose/getComposeInputPlaceholder.js
- src/conversations/ConversationGroup.js
- src/conversations/ConversationList.js
- src/group/AvatarList.js
- src/nullObjects.js
- src/outbox/outboxActions.js
- src/title/TitleGroup.js
- src/title/TitlePrivate.js
- src/types.js
- src/typing/__tests__/typingSelectors-test.js
- src/unread/unreadSelectors.js
- src/users/UserList.js
- src/users/__tests__/userHelpers-test.js
- src/users/__tests__/userSelectors-test.js
- src/users/__tests__/usersReducers-test.js
- src/users/userHelpers.js
- src/users/userSelectors.js
- src/users/usersActions.js
- src/users/usersReducers.js
- src/utils/__tests__/url-test.js
- src/webview/html/messageTypingAsHtml.js
We started using this concept in the beginning, matching the
API response to an internal more JavaScript-friendly format, that
was optionally could contain more data and be less API-dependent.
This turned out to be too much work, for too little benefit,
especially with the use of selectors.
The use of this remained for the users data structure and for
nothing else (we had User and ApiUser types)
* merge User and ApiUser into a single type
* do not map from ApiUser to User but keep data as-is
* replace all use of camelCase to snake_case
> refactor: Remove mapApiToStateUser

- src/nav/navActions.js
- src/start/AuthScreen.js
- src/start/PasswordAuthScreen.js
The previous logic was incorrect. LDAP does not automatically mean
the users will login with usernames.
Take the validation flag from server_settings.require_email_format_username
Also reverses the flag meaning from 'requires username' to 'requires email'.s
> Use `server_settings` to check if login is username or email

- src/caughtup/__tests__/caughtUpReducers-test.js
- src/caughtup/caughtUpReducers.js
- src/unread/unreadSelectors.js
We were not handling correctly the case where anchor is 0.
It is 0 when we request the messages around the first unread one.
Added tests to confirm it works for any case of incoming messages.
> Fix incorrectly calculating caughtUp

- src/title/ActivityText.js
*So that default text color is applied, i.e
according to theme if color passed in props is
undefined.
*Ideally we need to translate text, in both
activity text and message list (last edit timestamp).
Will be doing it in another PR.
Before
After
> activityText: Reuse RawLabel instead of Text.

- .flowconfig
This is to fix Flow checks failing.
We don't actually need this component anymore as the recently added
SafeAreaView in React Native.
> Ignore Flow checks for `react-native-safe-area`

- src/outbox/outboxActions.js
We were passing the incorrect field `email` instead of `sender_email`.
It is used to determine the user's avatar if avatar_url is `null`.
> Fix outbox message avatar (if gravatar)

- src/account-info/AccountDetails.js
This prevents crashes when user.timezone is equal to `''` and not `null`.
When timezone is not set, `user.timezone` is `''`.
While `null && true` returns `null`, `'' && true` returns `''` which causes the crash.
This condition has been replaced with a conditional, which should continue to work as expected even if the backend was changed to return `null` sometime in the future.
Closes issue #2534
> AccountDetails: wrapped timezone display in a conditional.

- src/topics/TopicListScreen.js
So that it doesn't repaints when nav isTransitioning or going back.
From #2455
> topic-screen: Connect to store with connectWithActionsPreserveOnBack.

- src/webview/js/matchesPolyfill.js
- src/webview/js/script.js
Fixes #2540
The Element.matches function is not supported on Android 4.4 causing
many interactions inside the webview to throw an exception.
> Add a polyfill for Element.matches

- src/chat/__tests__/flagsReducers-test.js
- src/chat/flagsReducers.js
This happens only on first app startup.
I had incorrectly assumed that `action.payload` will have the
form of an empty initial state object, but it is actually an
empty object, thus `payload.messages` is `undefined`.
> Handle no data in storage for flagsReducers

- src/message/MessageListContainer.js
- src/message/__tests__/messageActionSheet-test.js
- src/message/messageActionSheet.js
There are two set of options, one for message and another one for header.
Moved this logic to show respective options on message & header longPress
to messageActionSheet. Thus making render layer only responsible for
calling methods and rendering.
> refactor: Dump logic to message action sheet.

- src/types.js
As it is used in the code, ImageResources are simply
strings that contain a uri. They are not, however, an
object with a uri property, as the type comment suggested.
This is me getting my feet wet with Flow type annotations. I traced the code paths and in all cases, it looks like `ImageResource` is actually just a string. However, I'm wondering if in this case, instead of making it an alias for string, a better solution would be to actually use
```
export type ImageResource = {
uri: string,
}
```
and change the code to use the `uri` property instead?
Another question I have is if the suggested type definitions in the comments are human or machine generated.
> types: Give a real type for ImageResource.

- src/lightbox/LightboxContainer.js
- src/lightbox/LightboxScreen.js
- src/types.js
The `ImageResource` type was just an alias for `string`.
Therefore, we can just assign the `string` type directly
instead of `ImageResource`.
See #2561 for further discussion.
> types: Remove ImageResource type.

- src/message/NoMessages.js
This subtitle does not seem to make sense for specialNarrow and searchNarrow as one cannot start a conversation directly from these.
> Do not display 'Why not start the conversation?' for specialNarrow and searchNarrow

- src/nav/ModalNavBar.js
> ModalNavBar: Add marginLeft to title text if there is no back button.

- src/webview/js/generatedEs3.js
- src/webview/js/js.js
If the message list is too short no scroll event is ever fired.
That is why we manually send a scroll event in these cases.
Our logic is wrong though, `documentBody.scrollHeight` is never
smaller than `documentBody.clientHeight`, it is equal or greater.
The correct check is `===`.
> Fix Webview extra scroll event never fired

- src/webview/js/generatedEs3.js
- src/webview/js/js.js
When getting message id from an html element the value is returned
as string. We used to convert it to `number` every time we needed it.
Instead, we convert the value to number in one place and then we
do not need to convert it anywhere else.
> refactor: Make sure `getMessageIdFromNode` returns `number`

- src/unread/unreadSelectors.js
This fixes unread notice is not shown if bot is one
of the user in the narrow.
> unread-notice: Consider bots to get unread count.

- src/compose/ComposeBox.js
The compose menu is supposed to stay expanded for a short time.
When a users starts editing either the message or the topic we
collapse the menu. This is consistent with FB Messenger's behavior.
> ui: Collapse compose menu on message or topic edit

- .eslintrc.yaml
`eslint-plugin-spellcheck` does a strict check on `submessage` and
fails for the plural form.
> Fix ESlint warning

- src/common/MultilineInput.js
The component does not require it to function porperly.
We are also moving its only usage (in the compose box) to an
non-controlled component.
> flow: Make `value` property of MultilineInput not required

- src/config.js
Fixes #2591
This is a very simple and effective solution to the issue.
Alternatives were examined and found to be both complex and
have drawbacks. Waiting asynchronously for the users to load
would require a lot of rework and would lengthen the action to
potentially several seconds on mobile network.
Initially we were preserving most of the store keys but then went
for a more lean approach.
The app handles correctly the cases when users might not have yet
loaded on startup. An exception is narrowing to a group narrow.
When pressing a group notifications we get only the users' IDs and
need to map these IDs to users' emails so we can perform the narrow.
A future improvement to the narrowing functionality where we will
narrow by IDs will remove this dependency for us.
> Cache the 'users' state

- src/api/devGetEmails.js
- src/api/devListUsers.js
- src/api/index.js
- src/start/DevAuthScreen.js
- src/types.js
The dev_get_emails Zulip server endpoint has been renamed
to dev_list_users in zulip/zulip:73c3c94. The sole purpose
of this endpoint was to supply the frontend with a list of
users in the dev environment. Because it got renamed, the
mobile app dev login view broke.
This commit uses the new endpoint and also addresses changes
in the data structure returned by the endpoint.
I think `devListUsers.js` is not a great name. I chse it because I think it's best if it matches the API endpoint it is used for.
> Replace broken dev_get_emails endpoint with dev_list_users.

- src/autocomplete/PeopleAutocomplete.js
- src/autocomplete/StreamAutocomplete.js
- src/autocomplete/__tests__/getAutocompletedText-test.js
- src/autocomplete/getAutocompletedText.js
- src/user-groups/UserGroupItem.js
- src/users/__tests__/userHelpers-test.js
- src/users/__tests__/userSelectors-test.js
- src/users/userHelpers.js
- src/users/userSelectors.js
Implements #2596
* bots are also listed when autocompleting users
* user groups matching the filter are shown on top
* rework of the autocompleting functions to differentiate between user and user groups
> Add Autocomplete support for user groups

- src/animation/AnimatedComponent.js
Now the `composeMenu` doesn't overshoot before coming back to the intended width, and thus prevents text or placeholders from resizing due to this.
https://chat.zulip.org/user_uploads/2/e0/LAA4D-H2hTQ500VnsDgO4Vz5/easing.mp4
Fixes #2572
> Fix jerkiness in message list

- src/styles/tabs.js
Setting a border stops the ripple from overflowing. Setting elevation to 0 overrides the default elevation of the tabs to maintain the same aesthetic.
Fixes #2065 
Before:
After:
> StreamTabs: fix ripple overflow bug

- src/common/Input.js
Use styles from utilityStyles instead of styles defined locally for margins in EditStream, and set `underlineColorAndroid` of input to `BORDER_COLOR` on focus and `HALF_COLOR` when not focused. Previously the color was black, which didn't look right in night mode. Does not affect search input, composeBox input etc as the bottom border is not visible in these.
After changes the screen looks like this:
> Improvements to EditStream and Input

- src/account-info/AccountDetailsScreen.js
- src/chat/GroupDetailsScreen.js
- src/i18n/translations/messages_en.json
Changed title to "Recipients", and small refactor on how title was passed to `Screen`.
Fixes #2609
> Remove subheader in GroupDetailsScreen

- src/account-info/LogoutButton.js
- src/account-info/SwitchAccountButton.js
- src/account/AccountPickScreen.js
- src/autocomplete/EmojiAutocomplete.js
- src/autocomplete/PeopleAutocomplete.js
- src/autocomplete/StreamAutocomplete.js
- src/autocomplete/TopicAutocomplete.js
- src/boot/AppDataFetcher.js
- src/compose/ComposeMenu.js
- src/compose/ComposeMenuContainer.js
This cuts `connectWithActions` for:
* compose menu
* logout button
* switch account button
> Use standard Redux dispatch to replace most `connectWithActions`.

- src/account/AccountItem.js
The trash icon is annoyingly big, with too small a touch target.
Also, on iOS though not on Android, it renders below the
vertically-centered spot where it should be.  Fix those issues.
For reference for specific measurements, we look to Material Design.
This component is a list item, with two lines of text and a right-hand
icon, so refer to the section "Double line" here:
https://material.io/design/components/lists.html#specs
Other changes include:
* The text lines get 4px of padding between them.
* The items get a bit taller, and the corner radius adjusted to 4px.
> account switcher: Adjust layout toward Material guidelines.

- jsconfig.json
`jsconfig.json` tells VS Code that a project
is a js project and allows to configure
VS Code's settings for js projects.
The "allowJS" attribute is only relevant for
tsconfig.js files, but not jsconfig.js (where
it is automatically set to true). Previously,
our jsconfig.json still had a
`"allowJs": true` line, which VS Code complained
about. Thus it's safe and helpful to remove the line.
> VS Code: Fix jsconfig.json.

- src/compose/ComposeBox.js
We use `getComposeInputPlaceholder` to produce the placeholder.
Previously, we were passing this function only a list of users.
This produced the text `Message undefined` if addressing a bot.
Now, passing it a `usersAndBots` list fixes this issue.
> compose box: Fix placeholder text when recipient is a bot

- src/nullObjects.js
This makes the behavior consistent with the web app.
The change affects two concepts that both benefit from it:
* the nullObject should have had `invite_only` set to `false` anyway
* new streams will now be created as 'public'
> Make sure stream created is public by default

- src/common/SmartUrlInput.js
- src/start/RealmScreen.js
- src/utils/__tests__/url-test.js
- src/utils/url.js
This fixes an issue reported twice... we are being 'too smart'. 
The previous way to input a realm URL always tried to append a `.com` at the end of `something.something` assuming that it is an incomplete url in the form of `subdomain.domain.tld`.
Users hosting their Zulip server on `domain.com` could not enter their URL correctly.
This simplifies the logic and removes the code to append the extra `.com`
> Smarter smart url input. Fixes #2415

- src/webview/css/css.js
Select for any paragraph tag directly after another paragraph
tag using the adjacent sibling combinator, and add 1em of margin
above.
We use 1em in accordance with Material Design guidelines for
readability (see 'Paragraph spacing'):
https://material.io/design/typography/understanding-typography.html#readability
Fixes #2607.
> Add 1em of spacing between paragraphs in the same message.

- src/compose/ComposeBox.js
Sometimes message ref is undefined, so it is not focused. Thus
use editMessage object to check for topic input visibility.
> mesageEdit: Show topic input even in topic narrow.

- .eslintignore
- package.json
- src/__flow-tests__/types-test.js
- src/session/sessionActions.js
- src/streams/StreamScreen.js
- src/types.js
Originally, this set out to get flow into a state where it will complain about bugs like the one fixed in https://github.com/zulip/zulip-mobile/commit/d5e6a0bb2c66b793155d05a6b10be57bcdeb6a5a.
The issue here was the following `dispatch` call:
```js
dispatch(navigateToCreateStream);
```
`navigateToCreateStream` is an action creator, so it needs to be called before it can be dispatched. The correct `dispatch` call is
```js
dispatch(navigateToCreateStream());
```
I only succeeded partially. The dispatch bug described above seems to be in fact undetectable with the current implementation of Flow. On the other hand, the commits in this PR make Flow detect some other potential regression candidates, among some other things.
Why can't Flow detect the dispatch bug described above?
I tried to …
> flow: Make the `Actions` type work + various cleanups

- src/utils/notifications.android.js
- src/utils/notifications.ios.js
Fixes #2699
Narrowing to a notification on Android does try to position the
list at the message of the notification.
When running the app from a 'suspended' or 'not running' state
this does not work correctly as we are not anticipating that case
in `getMessageUpdateStrategy`.
Luckily, the fix is simple - according to discussions with Tim,
we want to focus on the first unread message.
Not passing a message Id to the `doNarrow` function does that.
If in future we decide to change the behavior back, we will
need to address this use-case and also make the behavior consistent
with iOS (which does not do that).
> notifications: Fix narrow-to-message position

- src/message/__tests__/fetchActions-test.js
- src/message/fetchActions.js
Fixes #2714
Narrowing from a notification is a special case, where we load
messages for the message narrow on startup.
We were not setting correctly the 'fetching' state and we were
displaying 'No messages' while actually loading new messages.
> fix: Show loading when narrowing from notification

- src/compose/ComposeBox.js
Use `handleMessageChange` and `handleTopicChange` in
`componentWillReceiveProps` to change `message` and `topic` input
values instead of setting the state manually.
This ensures consistency with other functions in the same component.
This changes the behavior slightly:
* for topic, we collapse the compose buttons
* for message, we do the same plus we send a 'typing' event to the
server
> compose: Make input value updates more consistent

- src/animation/AnimatedComponent.js
- src/chat/Chat.js
- src/chat/ChatScreen.js
- src/common/OfflineNotice.js
- src/common/Screen.js
- src/main/MainScreenWithTabs.js
Previously, the "No internet connection" banner was only
displayed in a topic narrow. This made it hard to know
if the app isn't loading because of a bug or because it
is disconnected.
Addresses #2721.
This is what the changes look like (animations are a bit laggy because of the screen recording; it looks a little better when going smoothly):
If we decide to merge this, `OfflineNotice` isn't really a Common component anymore, since it's designed specifically for the position on top of the screen. It's not used anywhere else, so that's fine, but we should move the file somewhere else.
> Display "No internet connection" banner on every screen.

- src/pm-conversations/GroupPmConversationItem.js
This is consistent with how we do it for 1:1 PM conversations.
Previously `GroupPmConversationItem` we try to retrieve all recipients
from the `usersByEmail` data. If not found we did substitute them
with a `NULL_USER`. This resulted in empty names.
Now, we first search for all users. If any of the users is not found
we do not render the component at all.
This has two benefits:
* a component with missing names looks broken
* even if we deduce the names from existing data we do not want to
render this, as we can not narrow to this conversation
> fix: Do not render group conversation with missing data

- src/emoji/EmojiPickerScreen.js
- src/i18n/translations/messages_en.json
- src/message/messageActionSheet.js
- src/nav/AppNavigator.js
- src/nav/navActions.js
This is a PR that aims to create an Emoji picker that can be used to add reactions to any message.
There was already a file called EmojiPicker.js that seemed to do nothing, so I decided make that into my component.
We can use the 'Add reaction' option in the action sheet to navigate to `EmojiPickerScreen` and tap on a reaction. The screen closes automatically after adding a reaction.
This PR also fixes the incorrect handling of realm emojis by the app.
Fixes #303
> Emoji picker

- docs/howto/debugging.md
- src/boot/middleware.js
As discussed in chat [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/subject/meeting/near/608506).
@gnprice
> docs: Add debugging tip for viewing Redux state diffs.

- package.json
Do this to make the CI fail on improperly formatted code, straying
`console.log()`s, etc. that might not be detected by test:prettier.
> tests: Make eslint error on warnings.

- src/session/__tests__/sessionReducers-test.js
On `loginSuccess` we set `needsInitialFetch` to `true`.
This was introduced in:
https://github.com/zulip/zulip-mobile/commit/8edbf8562481d759a0a16daf0fac028ca54b6114
The code was `needsInitialFetch: !!action.apiKey` which might
suggest that more is going on, but not really. `apiKey` is always
a non empty value if login succeeds.
This PR replaces the code to `true` to make it simpler and more
clear, but no behavior is changed.
Also, adds a test for `sessionReducers\LOGIN_SUCCESS`.
> refactor: Simplify `needsInitialFetch` logic

- src/ZulipMobile.js
- src/boot/TranslationProvider.js
The `import` command from `ES6` gets transpiled by Babel to `require()`.
Babel is enabled for the src/ directory. Since we use `import` wherever
Babel is enabled, replace the few stray instances of `require()` in src/.
> Replace `require()` with `import` where possible.

- src/common/Input.js
This property is not used in the component itself, nor
it is set anywhere else.
> cleanup: Remove unused 'clearButton' from `Input`

- src/message/messageActionSheet.js
Use the `Message` and `FlagsState` aliases.
> flow: Annotate ConstructActionButtonsType more precisely.

- src/streams/StreamScreen.js
Before it was only shown to admin. Checked on web app, anyone can add
anybody in the stream visible to him.
This makes behaviour consistent on web app and mobile app.
Fix: #2840
> streamScreen: Show 'Add subscribers' to all users.

- android/app/build.gradle
Useful information on Android versions can be found here:
https://en.wikipedia.org/wiki/Android_version_history
React Native allows us to support Android 4.1 and newer (API 16+)
We were claiming we support 4.1 but we haven't tested the app on
that platform version. Also, in our documentation we say we support
version 4.4
Now, making this official, we set the API support to 19.
Once published to the Play Store this will ensure users only on
supported versions can download the app.
> android: Make the minimal platform we support 4.4 (API 19)

- android/app/src/main/java/com/zulipmobile/MainApplication.java
- android/app/src/main/java/com/zulipmobile/notifications/GCMPushNotifications.java
- android/app/src/main/java/com/zulipmobile/notifications/MessageInfo.java
- android/app/src/main/java/com/zulipmobile/notifications/NotificationHelper.java
- android/app/src/main/java/com/zulipmobile/notifications/PushNotificationsProp.java
Previously it was saved as
```
LinkedHashMap<String, Pair<String, Integer>> conversations;
```
Now it is saved as
```
LinkedHashMap<String, List<MessageInfo>> conversations;
```
MessageInfo contains the content and the message id.
This commit does no visual changes, only changes the underlaying data structure and functions related to it.
> Change the data structure for saving notifications data

- src/autocomplete/TopicAutocomplete.js
Using a RegExp on user input crashes the app on invalid inputs like entering a
single `(`. The search seems to have been using a RegExp search only for
enabling case-insensitive search. This has now been switched to a simple
sub-string test using lower-cased strings.
Fixes #2857
> TopicAutocomplete: Use simple string match for topic filtering

- src/utils/__tests__/url-test.js
- src/utils/url.js
- src/webview/MessageListWeb.js
- src/webview/html/html.js
- src/webview/html/renderMessagesAsHtml.js
- src/webview/js/generatedEs3.js
- src/webview/js/js.js
- src/webview/js/script.js
- src/webview/webViewHandleUpdates.js
Implements #2876
Our current code works fine with the images in messages used before.
It doesn't work with the new, upcoming thumbnails. The reason is that our `appendAuthToImages` function is too rigid and does not recognize the new `img` tags (which have some extra `data` attributes and the URL is a bit different)
Instead of trying to parse arbitrary HTML or trying to limit what HTML the server renders, we can do the smart thing. This PR moves the functionality inside the WebView. It has quite an unfair advantage - a full-blown browser that perfectly recognizes HTML.
> Add support for new thumbnail format

- ios/ZulipMobile.xcodeproj/project.pbxproj
Updates the minimal iOS platform version supported up from
8.2 to 9.
This makes it official and the app will not be available for
download on iOS 8 devices. Our app currently crashes/exits on
startup without any reported error to Sentry or iTunes Connect.
This was verified both on a physical device and BrowserStack's
App Live.
We are not limiting our device support as all devices that run
iOS 8 can be upgraded to 9.
More information about devices and platform support:
http://iossupportmatrix.com/
https://everyi.com/by-capability/maximum-supported-ios-version-for-ipod-iphone-ipad.html
> ios: Remove support for iOS 8, make 9 the minimum

- src/api/apiFetch.js
- src/api/messages/updateMessage.js
- src/utils/url.js
Introduces a new function `encodeAsUriNoEmptyValues` and replaces the `encodeAsURI` used previously.
Now we do not pass empty values to the back-end API.
Also, fixes #2889
> Do not include empty values in API calls

- package.json
- yarn.lock
Fixes `yarn test:flow-coverage` not working.
`flow-coverage-report` 0.5.0 does not support the `flow-strict`
annotation and fails to run the coverage. 0.6.0 fixes that.
> Upgrade `flow-coverage-report` version

- src/compose/ComposeMenu.js
- src/emoji/EmojiPickerScreen.js
- src/emoji/EmojiRow.js
- src/start/AuthButton.js
This is for consistency with the rest of the project's components.
They were not set to extend `Component` intentionally but by mistake.
The only remaining and intentional component not extending `PureComponent`
is `MessageListWeb` that implements a custom `shouldComponentUpdate`.
> Make components extend 'PureComponent'

- src/account-info/AccountDetailsScreen.js
- src/common/Screen.js
- src/topics/TopicListScreen.js
Why this is removed? Because it was acting over smartly. This was
added to save redundant re-renders which were caused by nav state
change on pushing/popping route. But what if topics got fetched while
navigation is in a state of `isTransitioning`. It will ignore that
event and will not get re-rendered.
Also `topicListScreen` is not depended on the nav state, so even if
```
cur.nav.routes.length < prev.nav.routes.length
```
is removed then also there is no problem. As the prop supllied to
`topicListScreen` will not change and `shouldComponentUpdate` (as
`PureComonent` is used) will return false and save re-render.
Instead of using `connectPreserveOnBackOption`, we should make our
selector not to listen to nav state change (#2810). Which is a better
alternative for …
> topicListScreen: Remove `connectPreserveOnBackOption` from connect params.

- src/nav/ModalSearchNavBar.js
We don't need to use the `getNav` selector in `ModalSearchNavBar`
as we use it only to check if we can go back which is the purpose
of `getCanGoBack` selector.
This is good for maintainability but also helps with a potential
future removal of the Redux-React Native integration. This is the
last component that directly relies on the whole `nav` state.
The other is `AppWithNavigation` but it serves only for Redux
integration.
> Use `getCanGoBack` selector in `ModalSearchNavBar`

- src/compose/ComposeMenu.js
See the documentation: https://github.com/react-community/react-native-image-picker#options
Prior to this fix, it was impossible to send an image taken after directly launching the camera. There was no `fileName` property on the `response` object passed to `ComposeMenu.handleImagePickerResponse`.
In the React Native Remote Debugger, this manifested as a console warning that String.prototype.split was being invoked on an undefined value in `getFileExtension`.
On iOS, when sending a message via directly taking an image from the camera for the first time, iOS will ask for 3 permissions via modal - first, to access the camera, second, *after taking the image*, to add to the photo library, and third, to access the photo library (read and write). The first time  after granting these …
> image-picker: Set storageOptions.cameraRoll and storageOptions.waitUntilSaved.

- .eslintrc.yaml
- src/compose/ComposeMenu.js
- src/compose/__tests__/ComposeMenu-test.js
Copying the jsdoc comment I've written for `fixFileNameFromUri`:
```js
/**
* In 2017, Apple adopted a new standard image format, HEIF, which stands
* for High Efficiency File Format; Apple photos are named with the '.heic'
* extension. When an image file with the extension '.heic' is uploaded to the
* server,the image becomes unviewable within a message list. Interestingly,
* the `file` command line utility reports that images saved under this format
* are JPEG files, so there's likely some pecularity with how the server handles
* file uploads based on the extension.
*
* If an image file name has the '.heic' extension, and the uri of the image on a
* mobile device has an extension for the JPEG format, fixFileNameFromUri replaces
* that extension with '.jpeg'.
*/
```
This resolves #2178. …
>  compose: Fix image fileName from uri for HEIC image files.

- src/compose/ComposeBox.android.js
- src/compose/ComposeBox.ios.js
Using `componentWillReceiveProps` the way we did should not be
considered a best practice, and should not be used if better
options are available (there are other lifesycle events too).
We still need the `editMessage` comparison, though future rework
will make it not needed.
We don't need the `narrow` comparison though. It can never be true.
It used to be usable before, not anymore.
We get the prop down from several components. The hierarchy is:
ChatScreen > Chat > ComposeBox
ChatScreen gets the `narrow` value from the React Navigation's
`navigation.state.params`. This value does change only when a new
screen is created. So the same instance of the same screen will
never receive a different value. This comparison will always produce
`false`. Removing it!
This was confirmed both …
> cleanup: Remove unused drafts-related code

- .eslintrc.yaml
- src/chat/__tests__/chatReducers-test.js
- src/chat/chatReducers.js
- src/utils/narrow.js
Fixes #2677.
In the screenshot below, #2676 is still unresolved.
<p align="center">
</p>
I would label this with "bug" and "area: redux".
> Update is:starred narrow on EVENT_UPDATE_MESSAGE_FLAGS.

- package.json
With the new iOS and device releases, update the 'max' version
of iPhone (newest, largest) to be 'iPhone XS Max'.
> Update max iOS version to run on

- src/api/apiTypes.js
- src/caughtup/caughtUpReducers.js
- src/chat/flagsReducers.js
- src/message/messageReducers.js
- src/webview/webViewHandleUpdates.js
This continues, and implements the [design discussed](https://github.com/zulip/zulip-mobile/pull/2843#issuecomment-409558352), in #2843.
Merging the first two commits of this pull request will resolve #2676:
Before:
After:
To remove the `flags` property from messages in `state.messages`, my plan is to update the `flags` attribute for flow type for `Message` from `string[]` to `string[] | void`, and then figure out any necessary tweaks to processing in `caughtUpReducers`, `flagsReducers`, and `chatReducers`.
@gnprice
> Continue to improve starred messages.

- src/autocomplete/PeopleAutocomplete.js
Two user might have same name, but can't have same `user_id`. So use
id as key for each item of the list which is unique.
> peopleAutocomplete: Use `user_id` as key for each item in list.

- src/users/UserList.js
`user` has id with `user_id` instead of `id`.
Fix: #2967
> userList: Fix reg in getting user id for calculating `isSelected`.

- ios/ZulipMobile.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Xcode 9.3 adds a new IDEWorkspaceChecks.plist file to a workspace’s
shared data, to store the state of necessary workspace checks.
Committing this file to source control will prevent unnecessary
rerunning of those checks for each user opening the workspace.
Quote from here:
https://developer.apple.com/library/archive/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html#//apple_ref/doc/uid/TP40001051-CH1-DontLinkElementID_7
> Add `IDEWorkspaceChecks.plist`

- src/types.js
Issue in focus: #2052 
The commented out code replaced the previous type `any`.
On the way, it was found a couple of things were missing - routeName and params which was added along with their accurate types.
> Adding Flow types to NavigationState.routes()

- package.json
- yarn.lock
This fixes the long pending issue of text in options being cut on One
Plus and Oppo phones.
Fix: #2365
Before
After
> action-sheet: Update `react-native-action-sheet` to `^1.1.0`.

- android/app/src/main/java/com/zulipmobile/notifications/GCMPushNotifications.java
Before both debug and release build were having same icon and both
build can coexist at the same time in the phone. So it was hard to
figure out from which build notification is generated.
For now reusing the laucher icon of debug build as notification icon
of debug build. As this icon is not as per notification icon pattern,
it looks quite odd. But it saves extra overhead of new icon. Only
contributors will be having debug build, so this can be compromissed.
Also next we should try not to include debug launcher icon in release
APK.
Fix: #2863
> android notification: Use different icon for debug build.

- src/common/Popup.js
This is a quick fix to #2997. Set the height to 250 logical pixels, which is high enough to display about 5 list items.
Before:
After:
> autocomplete popup: Fix maximum height.

- src/lightbox/Lightbox.js
There is no `handleImagePress` prop that is passed to Lightbox. At the time of this commit, `handleImagePress` is a prototype method that updates local state.
> flow: Remove handleImagePress from Lightbox props.

- docs/developer-guide.md
XCode (I'm using 9.4.1 at the time of this commit) doesn't provide a simulator for iOS 8.0, and the vast majority of our iOS users stay updated to the latest OS, so the impact of this should be trivial.
> docs: Remove support for iOS 8.0.

- src/common/Touchable.js
`TouchableNativeFeedback` that we use on Android does not receive
any `style` props, that is quite inconsistent with `TouchableHighlight`
which we use on iOS.
Trying to set style props on a Touchable component does not have an
effect on Android, thus layout issues were introduced for Android-only in:
* AccountItem
* PasswordInput
* ZulipButton
> fix: Resolve layout issues with Touchable on Android

- src/webview/js/generatedEs3.js
- src/webview/js/js.js
Fixes #2905
`Array.from` is not available on all platform's WebViews we support.
One way to do this is to include a polyfill like this one:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill
Instead we'll use a simlper and sufficient approach - using `Array`'s `slice`
method called on the imageTags array-like object.
> webview: Do not use Array.from in WebView

- .travis.yml
This will help in tracking down the Android build, and make native
Android development faster.
Now:
* Main language on travis is JAVA.
* node v8 is installed via nvm.
* all the Android components which are used by zulip-mobile and it's
dependencies are installed.
Fixes: #3032
> travis: Build Android build. Fixes: #3032

- src/webview/js/generatedEs3.js
- src/webview/js/js.js
This commit fixes a change introduced in d8352d where we're falsely
returning early if the element is not an instanceof HTMLElement.
Some elements like the down arrow are svg elements so we add
that condition for the return statement.
> Webview: Fix over strict type check on click handler.

- .eslintrc.yaml
- android/app/build.gradle
- android/settings.gradle
- ios/ZulipMobile.xcodeproj/project.pbxproj
- jest/jestSetup.js
- package.json
- src/api/downloadFile.js
- yarn.lock
This fixes a blocker-issue with RN 0.57.2 that prevents the
project from building on Android.
The original project is no longer supported, but a very active
fork is being maintained and named as `rn-fetch-blob`.
This was manually tested and works fine. It contains multiple
fixes for issues that we do not have reports for, but feels nice
to auto-fix issues.
> dependencies: Upgrade `react-native-fetch-blob`

- src/api/apiTypes.js
- src/events/__tests__/eventMiddleware-test.js
- src/events/eventMiddleware.js
- src/unread/__tests__/unreadMentionsReducers-test.js
- src/unread/unreadMentionsReducers.js
We are calculating the unread mentions to be used in the UI but
are currently not used (should do that soon)
Due to not exposing this we have not caught an issue - the logic to
determine if the current user was mentioned in an upcomming  message
was incorrect. In fact, there is no `is_mentioned` key on the `message`
object, but the data is passed via a `flags` array.
This logic is already used correctly in `eventMiddleware.js`.
This PR replaces the incorrect code and fixes the tests.
> Fix: Incorrectly calculated unread mentions

- android/build.gradle
This error seems to have been related to dependencies in `jcenter()`.
```
FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find support-vector-drawable.aar (com.android.support:support-vector-drawable:27.1.1).
Searched in the following locations:
https://jcenter.bintray.com/com/android/support/support-vector-drawable/27.1.1/support-vector-drawable-27.1.1.aar
> Could not find livedata-core.aar (android.arch.lifecycle:livedata-core:1.1.0).
Searched in the following locations:
https://jcenter.bintray.com/android/arch/lifecycle/livedata-core/1.1.0/livedata-core-1.1.0.aar
> Could not find runtime.aar (android.arch.core:runtime:1.1.0).
Searched in the following locations: …
```
> Fix Android build error on macOS.

- docs/howto/push-notifications.md
I split the changes into two commits for a cleaner diff.
> docs/push-notifications: Add missing step for setting bouncer url.

- src/message/fetchActions.js
- src/nav/__tests__/navSelectors-test.js
- src/nav/navSelectors.js
Based on RN2 branch.
These are the first steps to remove React Navigation's dependency on Redux.
Some of them are a no-brainer. Some future ones would be a good idea too.
It is not yet clear if 100% Redux-less approach is ideal.
> Reduce use of Redux with React Navigation

- src/api/downloadFile.js
Fixes #2618.
The Zulip server generally requires authentication for uploading
and downloading images. Since React Native's webview doesn't support
setting HTTP Authorization headers at the moment, we pass the API key
as a query parameter. See zulip/zulip@5ddf261.
There was previously an `appendAuthToImages` utility method that was
added in cb31986 and then removed in 9e28ef2. However,
`downloadFile.js` is used only for images, so opt to just append the
api_key via string concatenation, which is simple and easy.
> Authenticate image downloads by appending an 'api_key' parameter.

- src/outbox/outboxActions.js
- src/outbox/outboxReducers.js
- src/types.js
Changes one of the intermediate steps when sending messages.
Fixes message list jumping and 'messages disappearing for a while'.
Our current outbox flow is:
1. Add outbox item and render it
2. Outbox item is sent and removed from outbox
3. New message given back by a server and we render
The problem is that at step 2 the message disappears.
On a fast network, this appears as a fast jump in the message list,
not ideal. On a slow network, this appears as a prolonged and buggy
looking 'message disappears after sending'.
Now we:
1. Add outbox item and render it
2. Send but do not remove from the list, instead mark as `isSent` to
prevent a duplicate if sending needs to be restarted
3. New message received, remove from outbox
> Improve outbox handling

- .travis.yml
- android/app/build.gradle
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
The debug build is working as expected (hurray!) with JDK 11 and API 28.
With these updates, I think the adjustment in #3079 is no longer necessary.
(@zulipbot add "area: Android")
> Update Android Studio components.

- src/start/AuthScreen.js
Fixes #3126
Adds a trailing slash to the `accounts/login/sso` path when doing
OAuth. The convention for the Zulip webapp is to include trailing
slashes in URLS.
The `accounts/login/social/github` just next to it is left as-is
because it actually does not work with a trailing slash currently.
> Use a trailing slash when doing a SSO login

- src/lightbox/LightboxActionSheet.js
- src/lightbox/downloadImage.js
- src/lightbox/shareImage.android.js
- src/lightbox/shareImage.ios.js
The first time a user attempts to download an image, permission to write to external storage (the SD card) should be requested. If permission is granted by the user, the image should proceed to download.
If permission is denied, the image will not be fetched, and the corresponding text 'Storage permission denied' is shown. Any subsequent time that a user attempts to download an image, a 'rationale' modal will appear with explaining why the app needs permissions, and the permission will once again be requested.
<p align="center">
</p>
If a user instructs that the permission not be asked for again, then subsequent attempts to download an image will only result in showing the text 'Storage permission denied', though the permission can always be changed via Android Settings.
<p …
> android: Request WRITE_EXTERNAL_STORAGE permission.

- src/message/__tests__/messageActions-test.js
- src/message/messagesActions.js
When we navigate to a new narrow if there are three cases regarding
the existance of messages:
* there are no messages
* there are messages
* there are currently no messages but fetching
In case of 3) we are showing a 'message loading indicator'.
Currently though, we are showing it quite rarely. This is caused
by us first navigating to the narrow and then staring to load new
messages (the logic is 'show if no messages but fetching').
We are smart enough to update that state even if the order is
navigation then loading, but it takes some time. Our new handshake
algorithm slows things down a bit too. Thus it seems we no longer
show the loading indicator in many cases.
The solution is simple and effective. First do the fetching, then
do the actual navigation to the narrow.
> Fix message loading indicators not showing

- src/webview/css/css.js
message_inline_reg images are mostly of preview of videos like dropbox
videos etc. Add same css as of twitter-image and message_inline_image.
On master (07354a3e78750cf3b6efdbc6d5809deea40cdc4b)
This PR
message link: https://chat.zulip.org/#narrow/stream/65-checkins/subject/Lily/near/650332
> webView, css: Fix height of message_inline_ref img.

- src/diagnostics/NotificationDiagScreen.js
Just a quick fix.
Before:
After:
> NotificationDiagScreen: Remove padding prop from screen component

- src/alertWords/__tests__/alertWordsReducer-test.js
- src/alertWords/alertWordsReducer.js
- src/mute/__tests__/muteReducers-test.js
- src/mute/muteReducers.js
- src/presence/__tests__/presenceReducers-test.js
- src/presence/presenceReducers.js
- src/subscriptions/__tests__/subscriptionsReducers-test.js
- src/subscriptions/subscriptionsReducers.js
- src/unread/unreadHuddlesReducers.js
- src/unread/unreadMentionsReducers.js
- src/unread/unreadPmsReducers.js
- src/unread/unreadStreamsReducers.js
- src/user-groups/__tests__/userGroupsReducers-test.js
- src/user-groups/userGroupsReducers.js
- src/users/__tests__/usersReducers-test.js
- src/users/usersReducers.js
Fixes #2859
The current behavior of reducers differs slightly. This PR makes sure all reducers behave consistently and predictably.
The `REALM_INIT` action is called when we receive data from the `register` API call. Most reducers do reset the state if they do not receive any data. Some don't. This PR makes sure that:
* a reducer does not leave the reducer with invalid data (`undefined`)
* does not preserve state but resets it
> Improve reducers' handling of `REALM_INIT`

- src/webview/css/css.js
Currently the 'friendly error' we show in production can easily
be mistaken for a normal header because of its background color.
Make the background red instead.
| Before | After |
| ---| --- |
| ![simulator screen shot - iphone 8 plus - 2018-08-19 at 21 52 03](https://user-images.githubusercontent.com/867242/44312573-49835100-a403-11e8-990f-bb1ab360e481.png) | ![simulator screen shot - iphone 8 plus - 2018-08-19 at 22 42 58](https://user-images.githubusercontent.com/867242/44312578-556f1300-a403-11e8-9426-2358381ceda8.png) |
> webview: Make WebView friendly error red

- docs/howto/build-run.md
Corresponding topic from chat [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Module.20.60lodash.2Eunion.60.20does.20not.20exist.20in.20the.20Haste.20module.20map).
> docs: Troubleshoot the error message for uninstalled dependencies.

- android/app/src/debug/res/values/strings.xml
- android/app/src/main/AndroidManifest.xml
What is this label?
> the one set by the parent component, is used when the component is
> presented to the user as having the capability described by the
> filter.
(https://developer.android.com/guide/topics/manifest/intent-filter-element#label)
Currently this intent filter is only used in the oAuth functionality.
So after selecting account in the browser, user is redirected to the
app with this intent. If multiple app are capable of taking this
intent (like in our case when both release and debug builds are
installed in the phone), then a pop up is shown by the phone OS,
letting user to select with which app he wants to procced. And this
label is used in this pop up. `filter_react_native` is totally
irrelevant, so change it to something relevant, which can be used
to differentiate both …
> android: Fix label of intent filter.

- src/nav/__tests__/navSelectors-test.js
- src/nav/navSelectors.js
- src/title/titleSelectors.js
As this selector, returns `routeName`, instead of route (which also
contains other route details too like route params). So definately
`getCurrentRouteName` is more appropiate name for this, it's give more
clarity of what's it returns.
Pulling this commit out from #2807.
> refactor: Rename `getCurrentRoute` to `getCurrentRouteName`.

- src/common/Screen.js
- src/streams/InviteUsersScreen.js
- src/user-groups/GroupScreen.js
When initially writing the Screen component, I was not aware of
the `scrollEnabled` property of `ScrollView`.
Replace the switching between a `ScrollView` and a `View` with
just setting the `scrollEnabled` to the correct value.
> Simplify Screen component, use only ScrollView 

- src/compose/ComposeBox.js
When `canSend` property is `false` we hide the ComposeBox component.
Then after it appears again the contents of both topic and message
Inputs are missing.
This issue exists only with our uncontrolled Input.
The cause is quite curious. We correctly initialize the components
on `componentDidMount`. So the component is working correctly on
initial render. What is messing it up is that if `canSend` becomes
`false` we do render a `null` (so nothing). This happens when we
are refreshing the state, on `APP_REFRESH` called on broken queues,
but can happen in other cases too (any case that makes `canSend` be
`false`).
When we show the component again, since we handle the show/no show
logic inside the component, the lifecycle event `componentDidMount`
is not called again. Thus we do not initialize …
> composebox: Do not unmount Input on hide

- src/users/UserItem.js
If user have not set custom (image) avatar then, we are required to
generate gavatar url (hashing email addredd) on the client side. So in
such cases we don't have avatar url. UserItem takes avatarUrl and
passes it to Avatar, in which it can be null/undefined. So make it
optional in UserItem too.
> flow, userItem: Make `avatarUrl` optional.

- src/chat/narrowsSelectors.js
Issue in focus: #2971 
Referred to f99bc35 for insight
Added flow types to getFirstMessageId, getLastMessageId, getLastTopicFromNarrow after going through their return value and their types mentioned in `zulip-mobile/src/types.js`
Tests Ran:
This is my first contribution to your organization and I have enforced everything I have read in CONTRIBUTION.md. I would like to apologize in case of any mistake i have made.
> Added flow types to some Selectors in narrowSelectors

- src/chat/GroupDetailsScreen.js
- src/diagnostics/NotificationDiagScreen.js
- src/diagnostics/StorageScreen.js
- src/diagnostics/TimingScreen.js
- src/diagnostics/VariablesScreen.js
- src/emoji/EmojiPickerScreen.js
- src/settings/LanguageScreen.js
- src/users/UsersScreen.js
Closes #3103
Both FlatList and SectionList offer as the main performance benefit
rendering a 'window' and not their whole contents. Sometimes in the
past, by mistake, we have rendered one of these in full height but
scrollable thanks to the ScrollView they are inside.
By analyzing all of our usage, I pinpointed the only major problem
we have, that resulted in a performance issues in the Emoji picker
and the `UsersScreen` (when one searches the 'all users' list),
which manifested as the list updating too infrequently during search.
Our default `Screen` behavior is to be 'scrollable' by default.
We should consider changing the default behavior. In the meantime
any screen that has a `FlatList` or `SectionList` directly inside
should switch to `contentScrollable={false}`.
> Fix a performance issue with some lists

- src/nav/AppNavigator.js
- src/user-groups/CreateGroupScreen.js
GroupScreen is more aligned to screen about group,
it has nothing to say about creating a group (which it is for).
GroupScreen looks too ambiguous here. So rename it to
`CreateGroupScreen` which conveys more details.
> refactor: Rename `GroupScreen` to `CreateGroupScreen`.

- src/common/Screen.js
A change in how `Screen` component works when not scrollable in:
https://github.com/zulip/zulip-mobile/commit/026814edd7f4a3a19b9486bd3c01b20f91c52cd0
and a fix to not render the whole `FlatList`s and `ScrollList`s:
https://github.com/zulip/zulip-mobile/commit/b0730a0636862f09d195c33be09d47776e449080
have revealed a bug - the `ScrollView` used inside the `Screen`
is not allowing its content to be scrolled.
To fix that, adding `flex: 1` is enough.
Tested all screens with `ScrollEnabled={false}` on both iOS and Android.
> Fix scroll in `Screen` when `scrollEnabled={false}`

- src/title/__tests__/titleSelectors-test.js
- src/title/titleSelectors.js
- src/utils/narrow.js
Fix #2797
* selector: Do not depend on selector to check narrow `isStreamOrTopic`.  ad77e44
Before we were depended on `getIsInTopicOrStreamNarrow` to check if
narrow is stream or topic in `getTitleBackgroundColor`. Which was
causing problem described here:
#2797 (comment)
Problem was: as soon as event arrives, it changes state. For very
minute time period the store data is invalid. And in this time
`getIsInTopicOrStreamNarrow` was called which returned false.
Also on going back, if nav bar backgound color becomes white and after
some time any event arrives, nav bar retrives back it's color.
For chat screen narrow will be defined so return color accordingly but
for other screens narrow will bot be defined and
`isStreamOrTopicNarrow` will return false. So there is no need to
consider …
> Fix Nav bar color changes to white on going back to stream/topic narrow from stream/topic info screen.

- src/common/ImageAvatar.js
- src/common/TextAvatar.js
The `TextAvatar` component is used for the avatar of group chats.
It did not show the same rounded corners as the single PMs.
This is supported and the issue was that we are not passing a `shape`
prop thus accidentally defaulting the value to `square`.
Set the default value for `shape` to `rounded` for both avatar
components to fix the issue and to better reflect our intent.
> avatar: Fix rounded corners not used for group chat icon

- src/message/messageActionSheet.js
As pointed in #3186 sometimes our unsent messages might get stuck
and not get sent. Also they can not be deleted.
The cause for the messages getting stuck is yet unknown but is
important to figure out).
Not being able to delete the messages has a simple fix though.
In fact, we already support that but incorrectly determine the
visibility of that opiton.
Remove the `isSentMessage` as a requirement for the 'Delete' option
and allow deletion of the outbox messages.
> outbox: Fix not being able to delete unsent messages

- src/utils/__tests__/progressiveTimeout-test.js
- src/utils/progressiveTimeout.js
After a closer look at `progressiveTimeout` with Greg, we found a
piece of logic is wrong, the timeout would not reset if it has
been more than 5 minutes since last timeout instead of the other
way around. Also, the logic was more convoluted than it could be.
This commit does:
* fix the timeout reset bug
* simplify the logic
* tweaks the timing values
> Rework and fix `progressiveTimeout`

- src/webview/css/css.js
- src/webview/css/cssEmojis.js
There was no good reason to keep the disable clauses in these files.
Details in each commit.
> Enable ESLint in `css.js` and `cssEmojis.js`

- src/actionTypes.js
- src/settings/LanguageScreen.js
- src/settings/NotificationsScreen.js
- src/settings/SettingsCard.js
- src/settings/__tests__/settingsReducers-test.js
- src/settings/settingsActions.js
- src/settings/settingsReducers.js
Added flow type to `FetchMessageAction` and `EventAlertWordsAction`.
For `FetchMessageAction`:
`FetchMessageAction` in a function that is used to invoke Redux dispatch. This function is defined in both synchronous and asynchronous sense in `fetchActions.js`: [async](https://github.com/zulip/zulip-mobile/blob/08f1bfdd0b4dcb2aaf734ef590e6a78ca386618a/src/message/fetchActions.js#L75) and [sync](https://github.com/zulip/zulip-mobile/blob/08f1bfdd0b4dcb2aaf734ef590e6a78ca386618a/src/message/fetchActions.js#L88)
Tests Ran:
Issue in focus: #2052
> Added flow type in actionTypes.js

- src/account-info/SwitchAccountButton.js
This is a silent type error that seems to have been introduced via https://github.com/zulip/zulip-mobile/commit/b37352ade06779ad77f334c091300c2370cd9ce2#diff-73a6ef41677e3bf406fce93366e99735.
> SwitchAccountButton: Remove unused prop `accounts`.

- src/drafts/draftsSelectors.js
Issue in focus: #2971 
I'm aware of the PR #3166, but `draftsSelectors` wasn't a part of original PR message. I went through the discussion and didn't find any mention of removing this entirely so I went ahead and typed the selector present in `draftsSelectors.js`.
Tests ran:
> draftsSelectors: Flow typed selector

- src/compose/ComposeBox.js
- src/compose/ComposeMenu.js
- src/topics/topicSelectors.js
Fixes #3130
Extract the code in `ComposeBox => handleSend()` that determines
the destination narrow to `getDestinationNarrow()`. Use this function
to pass the narrow to `ComposeMenu` which then uses that value when
uploading an image.
> Reuse the destination narrow logic when uploading images

- src/common/PasswordInput.js
- src/start/PasswordAuthScreen.js
This fixes an annoying issue that makes the size of the input
about half what it should be (on inspection 16px vs 33px for the
default one).
Tested on iOS and Android.
> Fix password input

- src/compose/ComposeBox.js
Fixes #3209
Back in #3065 we did introduce a new behavior for `ComposeBox` to
not unmount when one can't write to a narrow. I would not call it
a 'hack' as this approach should have worked fine (and would on web)
Seemingly it is throwing React Native off and showing the Autocomplete
visually above the WebView but below in the stack of 'touchable' targets.
Luckily, a better, less hacky approach is possible. Just use a familiar
style from the web: `display: 'none'`
> Fix Autocomplete sometimes not responding to touch

- src/message/fetchActions.js
Calling `sendFocusPing` without a `dispatch` does not work as
intended. All it does is return an action creator. Called as-is
there is no effect.
We need to dispatch this properly. A simple and effective fix.
Thanks to Marc who reported the issue:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/sendFocusPing.20Interval
> Fix `sendFocusPing` not actually working

- src/outbox/__tests__/outboxReducer-test.js
- src/outbox/outboxReducers.js
Fixes #3203
We do not delete sent messsages from outbox immediately on a
successful sending, but keep them in the outbox until we receive
the message from the server via our event queue.
There are two cases where this is a problem:
* the queue dies / gets stuck and we do not reveive that message
* the user quits the app before the response
The second option should be rare but totally possible. The first
option should be rare but currenlty is more frequent than optimal.
Removing the sent messages on initial fetch is a very safe and
conservative behavior. We might decide to do this more aggressively
in future but that might also lead to behavior confusing to the
user like "Where did my message disappear?"
> Remove sent messages from outbox on initial fetch

- src/api/apiFetch.js
`console.warn` takes string as parameter, not a object. Before we were
passing object, which again raised an exception and it was direclty
going to catch, instead of creating and throwing an error from
`makeApiError.`
> apiFetch: Fix regression in using `console.warn`.

- src/account-info/AccountDetails.js
We are using `ImageBackground`, which uses styles such as `position:
absolute`. Because it is capable of displaying text (/componenets)
over it. So styles such as `alignItems: center, flex: 1` were
resulting items to be present at vertically center of screen instead
of space below image.
By removing this styles and only keeping `justifyContent: center`,
works as expected.
Fix: #3228
> accountDetails: Fix layout regression.

- src/redux-persist-migrate/index.js
In `2` migration (c2ed78e7e6c9b46ed4c1cf0d0b66ae87b2b0ce40), we
dropped `result` & `msg` from the `state.relam.pushToken`. But now if
someone freshly installs the app, then there is not any initilization
of `realm` state, so it will throw undefined (as at the time of
applying `2` migration there is only `messages` & `narrows` in the
`state`, which are initialized in `1` migration). So make sure realm
state is present before accessing `state.realm.pushToken.token`.
> migrations: Fix regression introduced in `2` migration.

- src/lightbox/Lightbox.js
Fixes #3274
We are setting `zIndex` on the styles applied to header & footer
were making them go over the Action Sheet.
This property will not be needed if we move `PhotoView` before
these two components. This does not change the positioning as they
are overlaying it, with position `absolute`.
> Fix Action Sheet popping under Lightbox Footer on Android

- src/message/fetchActions.js
- src/nav/__tests__/navSelectors-test.js
- src/nav/navSelectors.js
This reverts commit
1d05ecdb8 fetch: Remove unused message fetch code in fetchEssentialInitialData.
The reasoning in that commit was mistaken in a couple of ways.
This still isn't the right design for handling this, but it
works for now, fixing the serious bug #3284 ; we'll sort it out better later.
> fetch: Revert "Remove unused message fetch code".

- src/chat/ChatScreen.js
Fixes #3273
A previous commit fixing a weird issue on Android inadvertantly
broke the iOS layout:
https://github.com/jainkuniya/zulip-mobile/commit/f142452b4fa66ea00fc49048c4b31b89fb4dbe6c
The ZulipStatusBar compoennt  is a difference between Android and iOS
as it has actual height on iOS but not on Android, we can never paint
in the status bar area of Android, we can change the color only.
This commit keeps the fix from the previous commit but simplifies it:
* removes the extra View, no need for the extra wrapper
* simplified the style, no need for the extra `flex`
* moved `ZulipStatusBar` to bottom because of `flexDirection: 'column-reverse'
> Fix broken layout in ChatScreen on iOS

- src/actionTypes.js
- src/api/messages/getMessages.js
- src/caughtup/__tests__/caughtUpReducers-test.js
- src/caughtup/caughtUpReducers.js
- src/chat/__tests__/fetchingReducers-test.js
- src/message/fetchActions.js
Fixes #3338
Previously we had to use custom caught-up logic to determine if we
have loaded the oldest or newest messages in a narrow.
Back-end now gives us that data while older versions do not.
Keep the old logic when the `found_newest` and `found_oldest`
values are not provided but use them directly if present.
> More robust caughtUp logic

- src/common/PresenceStatusIndicator.js
Update all presence UI to correctly, taking into account away status.
> Display presence status taking away status into account

- src/account/accountsSelectors.js
Use `reselect` in `getAccountStatuses`, so that it memorize accounts and
return same object for same value and saves re-render.
> accountPickerScreen: Fix re-render on every event of long poll.

- src/autocomplete/__tests__/getAutocompleteFilter-test.js
- src/autocomplete/getAutocompleteFilter.js
We only consider `@` when the preceding char is either ` `, `\n`, `:`
or `#`. Because every email as `@` in it and we don't want to trigger
suggestions in such cases.
Fixes: #3289
> people autocomplete: Fix it doesn't pop if `@` entered in new line.

- src/webview/css/css.js
Use `overflow: hidden` in the emoji `span` tag (webapp also uses it)
and increase `width` & `height` to `20`.
Fixes: #2693, #3321.
Before:
On iPhone 5s
On iPhone X
This PR:
On iPhone 5s
iPhone X
> webView, emoji, css: Fix Emoji rendering issue (twice, cut down).

- src/chat/narrowsSelectors.js
- src/message/NotSubscribed.js
- src/title/TitleStream.js
Issues in focus: #2971, #3166
Removed redundant messages word in the logical operation performed under getIfNoMessages and added flow type for it
Added flow type for getStream in narrow. This one was different because the selector returned either Subscription if the Stream was subscribed to before, or Stream + in_home_view=true if it was not subscribed to before. A type could have been declared for the latter case but it seemed unnecessary so instead, I used spread syntax to define the return type. 
Tests ran:
> Cleaned up flow type for selectors in narrowSelector

- src/user-groups/UserGroupItem.js
So that it can match color with the color of the text in both the
themes.
This PR:
on master:
> userGroupItem, icon: Set `color` according to the theme.

- android/app/src/main/java/com/zulipmobile/notifications/FCMPushNotifications.java
- android/app/src/main/java/com/zulipmobile/notifications/NotificationHelper.java
This is the client logic to correspond with the server code in zulip/zulip#11561 .
I believe this code is right, but it needs testing together with the server changes; holding off on merge until I've done that.
> android notif: Accept a batch of message IDs for `remove`.

- src/common/Icons.js
- src/main/HomeTab.js
- src/main/MainTabs.js
- src/title/TitleSpecial.js
This is a proposal for a quick resolution to #3063, discussed with and suggested by @gnprice.
Before:
After:
> Stop using the same icon for two different buttons on the main screen.

- src/user-status/UserStatusScreen.js
Server only supports status message with max length 60, and otherwise
throws error on updating it. So set max length in the input itself so
that user can enter status of only valid length.
> userStatus, input: Set max length to 60.

- src/config.js
The original values were changed several times and the currently
used ones are chosen conservatively to reduce issues we had in
the past.
We no longer have the positioning issues we used to have so it
makes sense to revisit these and change for better user experience.
These changes are a result of extensive testing and analysis.
>  Reduce waiting for messages to load by fetching more messages earlier

- src/account-info/AccountDetails.js
- src/api/modelTypes.js
- src/common/PresenceStatusIndicator.js
- src/title/ActivityText.js
- src/title/TitlePrivate.js
- src/users/__tests__/userHelpers-test.js
- src/users/userHelpers.js
- src/utils/__tests__/presence-test.js
- src/utils/presence.js
Implements #3384
* introduce the new 'Unavailable' status and do not treat it the same as 'Offline'
* render that new state exactly the same as on the web (a bit more tricky than the purely css solution)
* change the text for 'last active' if 'unavailable'
> Correctly display user's status when 'unavailable'

- android/app/build.gradle
- android/app/src/main/java/com/zulipmobile/MainApplication.java
- android/settings.gradle
- ios/ZulipMobile.xcodeproj/project.pbxproj
- package.json
- src/webview/MessageList.js
- yarn.lock
The `WebView` component is being moved out of `react-native`.
While it is still available from the main package, Its development has stopped and it is being deprecated (and soon to be removed completely)
The very same component is under active development and eagerly accepting PRs at `react-native-webview`.
This PR migrates to that package (and as separate commits does few more changes).
> Upgrade WebView

- src/message/__tests__/fetchActions-test.js
- src/message/fetchActions.js
The behavior of 'needFetchAtFirstUnread' is quite wrong.
First, we do the minimal work to fix #3441 in the first commit.
The rest of the work implements correctly the originally intended behavior.
> Fix a message loading bug and improve behavior

- src/autocomplete/AutocompleteView.js
- src/autocomplete/getAutocompleteFilter.js
- src/autocomplete/getAutocompletedText.js
- src/boot/TranslationProvider.js
- src/common/Centerer.js
- src/common/ComponentList.js
- src/common/ComponentWithOverlay.js
- src/common/FloatingActionButton.js
- src/common/Input.js
- src/common/KeyboardAvoider.js
- src/common/Label.js
- src/common/OptionRow.js
- src/common/PresenceStatusIndicator.js
- src/common/RawLabel.js
- src/common/Screen.js
- src/common/SmartUrlInput.js
- src/common/Touchable.js
- src/common/UnreadCount.js
- src/common/ZulipButton.js
- src/compose/ComposeBox.js
- src/lightbox/LightboxFooter.js
- src/nav/NavButton.js
- src/streams/StreamIcon.js
- src/styles/theme.js
- src/title/ActivityText.js
- src/types.js
This is another piece of #3399; sort of a continuation of #3450.
Basically I took a branch based on #3422, plus my changes in #3450, and looked at the type errors that remained. The errors that jumped out at me as either (a) potentially involving something subtle in the type system, or (b) being about code which has some subtlety and I remember writing, I investigated and fixed.
> More type fixes for RN v0.59 / Flow v0.92

- src/webview/js/generatedEs3.js
- src/webview/js/js.js
The existing `longPress` logic is very convoluted. It makes the user
study the code for a long amount of time to follow the state machine
and figure out exactly how the logic works. There are also a few
inconsistencies with respect to how the code handles events, in
particular `lastTouchEventTimestamp = Date.now()` in the `touchend`
listener, and a few more inconsistencies.
This commit aims to fix these inconsistencies by removing the
timestamp factor from `lastTouchEventTimestamp` altogether. It (the
replaced name being `touchActive`) acts as a flag for if the user is
touching the screen at present, which is an accurate indicator for
if the user wants to `longPress` (when the handler for longPress
triggers he would still be touching the screen if he wants to
longPress.)
Tested on Android …
> webview js: Improve `longPress` detection logic.

- src/autocomplete/PeopleAutocomplete.js
- src/boot/AppEventHandlers.js
- src/chat/GroupDetailsScreen.js
- src/compose/ComposeBox.js
- src/pm-conversations/PmConversationList.js
- src/settings/LanguagePicker.js
- src/settings/languages.js
- src/start/AuthScreen.js
- src/start/RealmScreen.js
- src/title/TitleGroup.js
- src/types.js
- src/user-picker/UserPickerCard.js
- src/users/UserItem.js
- src/users/UserList.js
- src/users/UsersCard.js
This PR adds Flow types that if missing, result in errors in the React Native 0.59 upgrade PR (not because of RN but because of Flow 0.92)
Can be merged separately. Prerequisite for #3422
> Add Flow types required for RN 0.59 migration

- src/__tests__/exampleData.js
- src/webview/html/__tests__/messageHeaderAsHtml-test.js
Make a start at some well-typed example data for tests.
This will help us to write unit tests that deal with large objects
like users and messages
* while passing genuine well-typed data,
* and with less repetition of boilerplate boring bits of data.
This contains enough to write the particular tests I wanted to write
today, but it's quite incomplete -- there are plenty more types of
objects, and also directions in which to customize the data, that we
might add to it for the sake of other tests.
Also, as the jsdoc comments announce, some of these property values
may not look anything like they would in a real user/message/etc.!
They match our types, and I've made them plausible values where I know
off the top of my head what values are plausible, but e.g. `User` has
`timezone: string`, …
> Helpers to make example data for tests

- src/streams/SubscriptionsCard.js
Removes several lines of code that have had no effect for a very
long time (since we had a drawer in the app)
The purpose of the code being removed was to show as 'selected'
a subscription, if it was the currently active narrow (this
component was rendered in the drawer)
This component now only serves as a Tab in StreamTabs. It never
receives a value for the 'narrow' property, thus it remains the
default `[]`. This in turn always sets `selected` to `false`.
None of the removed code had any effect except cluttering the code.
> Cleanup SubscriptionCard

- src/chat/UnreadNotice.js
Standalone, but also a prerequisite for #3471 because it removes the need for a Flow fix.
> UnreadNotice: Remove disused 'limited' property

- src/subscriptions/__tests__/subscriptionsReducers-test.js
- src/subscriptions/subscriptionsReducers.js
Fixes #3474
We are not recieving a subscription 'unsubscribe' event from the
server when a stream we are subscribed to is deleted and thus we
keep subscribed to non-exiting stream until the state is refreshed.
The ideal fix for this issue should be implemented on the back-end.
This code is compatible with eventual server-side fix that would
issue an unsubscription on stream deletion.
We require this code regardless of such a fix, as we would need
to support old and new back-end versions.
> subscriptionsReducers: Delete subscriptions when a stream is deleted

- src/start/DevAuthScreen.js
Since we introduced `makeApiError` the error displayed to the user
is saying simply 'API'. This change extracts the error message the
server returns, which is in `err.data.message`.
> Fix dev auth login error display

- src/utils/openLink.js
Encode url with `encodeURI` before passing it to safari view.
Refer issue thread for complete diagnosis.
Fixes: #3315
> safari view, iOS: Fix app crash when URLs contains non-ASCII.

- src/settings/LanguagePicker.js
List was capturing first tap to hide keyboard. So set
`keyboardShouldPersistTaps` as `always` in `FlatList`, to avoid
capturing of tap event by list.
References:
https://facebook.github.io/react-native/docs/scrollview#keyboardshouldpersisttaps
> languagePicker, search: Fix language is not selected on single tap.

- src/webview/css/css.js
The apparent spacing of the left margin is differing between a
`message-full` and a `message-brief` at the time of this
commit. This was due to merging a previous commit which incorrectly
replaced `2rem` to `40px` instead of the `32px` correct value. This
small commit fixes that.
Fixes #3508.
> message list: Fix difference in spacing.

- src/webview/css/css.js
- src/webview/css/cssNight.js
- src/webview/html/htmlBody.js
- src/webview/html/messageAsHtml.js
- src/webview/js/generatedEs3.js
- src/webview/js/js.js
Two problems have plagued user experience for a long time. One,
there is no separation between two different messages, that is, one
does not know when one message ends and another one begins. Two,
there are no timestamps displayed for brief messages.
This commit aims to solve both with a sliding label which shows the
timestamp of the message if clicked on it. We do this buy
introducing two elements under `message-brief`, `timestamp-container`
and `timestamp-label`.
Browsers, by default, increase the size of the viewport to fit the
size of any element inside it. This causes the horizontal size of
the viewport to increase if we attempt to 'slide' an element out of
the viewport. The only way to not allow the browser to increase the
size is if there were an element which always inside the …
> Add interactive timestamp to brief messages.

- src/webview/css/css.js
Before `img` height was in `vh`. So when viewport height changes,
`img` height also gets changed. Thus scroll position gets affected.
Now provide `img` height in `px`, so that it doesn't change on
viewport height change.
Note: on unread notice/keyboard show/hide, webView viewport height
changes.
References: https://developer.mozilla.org/en-US/docs/Web/CSS/length
Fix: #3264
>  webView,css:Fix scroll got disturbed when viewport height changes.

- src/webview/css/css.js
- src/webview/css/cssNight.js
- src/webview/html/messageAsHtml.js
- src/webview/js/generatedEs3.js
- src/webview/js/js.js
Shadows on time slide in timepills have been modified to be centric
instead of leaning toward the left. The changes in the shadow could
be found in the material.io design guidelines/source code, with 2dp
elevation
https://github.com/material-components/material-components-web/blob/master/packages/mdc-elevation/_mixins.scss.
The background matches the default message-list background, but has
a little more added contrast in order to differenciate the top of
the pill with the message list.
@gnprice here's the time pills edit asked for in [chat](https://chat.zulip.org/#narrow/stream/48-mobile/topic/message.20timestamps/near/754237)! (screenshots present there)
> time pills: Make slide-in time pills quieter.

- src/webview/js/generatedEs3.js
- src/webview/js/js.js
- src/webview/webViewHandleUpdates.js
* messageList, getUpdateEvents: Use `lodash.isequal` to compare object.
* web, msg read event: Make sure querySelectorAll never get empty selector
For more debug information, please refer #3544
> Fix: #3544. Fix empty selector is being provided to querySelectorAll.

- src/account-info/AwayStatusSwitch.js
- src/common/OptionRow.js
- src/common/ZulipSwitch.js
- src/settings/DebugScreen.js
- src/settings/NotificationsScreen.js
- src/settings/SettingsCard.js
- src/streams/EditStreamCard.js
- src/streams/StreamItem.js
- src/streams/StreamScreen.js
Before we were only deriving `valueControlled` (which is value of the
switch) on component mount (at the time of initializing state).
But if defaultValue props gets changed, then it's value will not get
reflected. Thus when subscription add event arrives, it's value is
propagated till switch, but we aren't taking defaultValue expect at the
time of mounting.
If we want to go with the convention that defaultValue can only be used
at the first time, then we need to use value prop. Which will make
things complicated, as when switch wants to update it will receive both
defaultValue and value from parent, and it will add some logic to handle
such situations.
Actually it is not default value, rather it is original value which parent
caller wants. Basically original value before user (may) make …
> zulipSwitch: Derive `valueControlled` from props change.

- package.json
- src/webview/js/generatedEs3.js
- src/webview/js/js.js
- src/webview/js/script.js
- yarn.lock
There is a complete rewrite of communication between webview and rn
component starting from 5.0.0
So use following as stated in the release notes
```
window.ReactNativeWebView.postMessage(data)
```
https://github.com/react-native-community/react-native-webview/releases/tag/v5.0.0
Also due to following change in https://github.com/react-native-community/react-native-webview/commit/f3bdab5
```
-￼    stringWithFormat:@"document.dispatchEvent(new MessageEvent('message', %@));",
+    stringWithFormat:@"window.dispatchEvent(new MessageEvent('message', %@));",
```
on iOS `document.addEventListener` stopped working. So change it to `window.addEventListener`.
This also fixes #3550, #3518.
> dependency: Upgrade react-native-webview to `^5.0.0`

- src/pm-conversations/GroupPmConversationItem.js
- src/users/UserItem.js
- src/webview/css/css.js
Changes the avatar sizes found everywhere in the application to 48px. Since this is the size used by most other comparable messaging applications, 48px seems like a good option to go for (other reasons explained in the commit/s).
In the first commit `.message-brief` is set to `padding: 0 16px 16px 73px`. While this 73 might seem like an arbitrary number, it's confusing to me and I don't know why this is the case, but that is the only one which makes the messages perfectly aligned.
> Avatar sizes increase to 48px globally.

- src/webview/css/css.js
- src/webview/css/cssPygments.js
This commit essentially takes the colors used in the webapp's SCSS
file for syntax highlighting (`pygments.scss`), and copies that into
the application. This makes the colors between the webapp and the
mobile application exactly the same and hence provides better parity
of experience!
Fixes #3524.
Relevant File from the webapp: https://github.com/zulip/zulip/blob/master/static/styles/pygments.scss
This has also been linked through a comment in the code.
> codehilite: Update values for syntax highlighting from webapp.

- src/compose/ComposeBox.js
> Fix compose box obscured by keyboard on long message, in stream view.

- src/__tests__/exampleData.js
- src/api/__tests__/queueMarkAsRead-test.js
- src/api/queueMarkAsRead.js
If there are multiple requests to mark messages as read with interval
less than 2s, and if there is no further request then later were
stuck in the queue. Becuase there was only one caller to
`messagesFlags`, which was only called by user scroll event.
So even after reaching at the end of message list, unread banner is
visible with some unread count.
So now set timeout to send read message flag to server.
Fixes: #3509
> queueMarkAsRead: Set timeout if there is mark request in less than 2s.

- docs/howto/build-run.md
The React Native documentation has changed slightly; adjust the references
in our documentation accordingly.
> docs/build-run: Update reference to React Native setup docs.

- .eslintrc.yaml
- src/api/modelTypes.js
Activate a linter in `eslint-plugin-flowtype` to warn about duplicate
keys in type declarations. Without this lint, flow does not warn when
a later-declared key in the same type shadows an earlier one, even
when the two are declared with incompatible types.
This presently only catches a duplicate parameter in modelTypes.js
(also fixed in this commit).
> lint: Add `flowtype/no-dupe-keys` to eslint

- src/chat/Chat.js
It got introduced in 9dc95ccba4cfb257a44e5e062ea7542035e34f9e, when we
were using native message list. Now we are no longer using this
variable, so remove it.
> clean up, chat: Remove unused `scrollOffset` variable.

- src/webview/css/css.js
The previous iteration of alert words was not ready accessable for
people with color blindness. As @jmandel reports, he wasn't able to
see the white text on the bright green background while in dark
mode.
This commit is a temporary fix for the issue, by reducing the alpha
of the background color in order to make the white text on it more
readable (in dark mode).
References #3531.
(does not fix the issue, just provides a temporary patch for it).
> css: Make alert-words more readable.

- src/utils/__tests__/url-test.js
This was slightly more involved than it probably should have been due to a tacit use of `undefined`. (See description of 88dd8d910.)
> Typify url-tests.js

- .vscode/extensions.json
- docs/howto/editor.md
This PR adds a configuration file for recommending extensions required for a smooth developer experience. It uses the default [feature](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions) in vscode to do so.
The doc `editor.md` has been updated to reflect this change.
Based on #3219.
> editor: Add config for recommended extensions.

- src/settings/SettingsCard.js
The settings card by itself looks a little empty. @timabbot
suggested that this was due to a label being absent from the
settings screen.
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/mascot/near/756544
Also added a separator to make things cleaner. Used a `Label`
component for including translations.
> settings card: Add header - Label and separator.

- src/api/modelTypes.js
When messages are fetched from server via GET `/messages`, then it
contains `id` as key in `user` of the reaction object. While reaction
add event has `user_id` in it.
As we weren't using this attributes anywhere, so there was no problem
and fortunately app never crashed.
> types: Describe current state of reaction object in redux.

- docs/howto/dev-server.md
- src/common/SmartUrlInput.js
- src/start/RealmScreen.js
- src/utils/__tests__/url-test.js
- src/utils/url.js
... and in the process, unify the URL parsing logic between `SmartUrlInput` and `url.js`.
This permits simpler use of the iOS simulator, which has also been documented.
> Allow user to specify "localhost:9991" as a realm

- src/chat/__tests__/narrowsReducer-test.js
- src/chat/narrowsReducer.js
- src/events/__tests__/eventMiddleware-test.js
- src/events/eventMiddleware.js
- src/unread/unreadMentionsReducer.js
- src/utils/__tests__/narrow-test.js
- src/utils/narrow.js
Fixes #3592.
I ran into some Babel issues with Jest and haven't been able to run the tests yet; could you please take a quick look at the logs (attached) to see if this is a known issue? Since I'm assuming everything works for people with development environments that have been set up for a while, and the error was thrown from code I didn't touch, there may have been a breaking change in a minor version of Babel or Jest that was triggered by the carat in package.json allowing silent minor version upgrades (e.g., "jest": "^24.8.0"), but that's just a guess until I can dig deeper or learn that it's a known issue.
[Issue 3592 Test Output (babel issue?).txt](https://github.com/zulip/zulip-mobile/files/3624392/Issue.3592.Test.Output.babel.issue.txt)
I'm proposing a change to the …
> Make new mentioned/starred messages appear in mentions/starred narrows

- docs/howto/dev-server.md
A naïve `vagrant halt` + `vagrant up [--provision]` doesn't suffice.
> docs/dev server: Add explicit vagrant restart command

- src/search/SearchMessagesCard.js
- src/search/SearchMessagesScreen.js
Enforce an ordering on resolution of asynchronous search requests by discarding any delayed, out-of-order responses.
Fixes #3058.
> search: prevent race conditions between subsequent queries

- docs/howto/build-run.md
Its absence is precisely diagnosed by relevant error messages and not difficult to fix, but we should still note it somewhere.
> Add Android NDK installation instructions

- src/boot/ZulipAsyncStorage.js
- src/notification/index.js
- src/outbox/outboxActions.js
- src/redux-persist-migrate/index.js
- src/utils/logging.js
- src/utils/sound.js
- src/webview/webViewEventHandlers.js
See commit messages for details.
I was moved to go and do this by some other work where I found I wanted to log warnings to Sentry, and was dissatisfied with the existing API.
> Migrate logging to new functions `logging.error` and `logging.warn`.

- package.json
- yarn.lock
This fixes a (hitherto silent) issue with our dependencies: `jest` and `jest-cli` were out of sync.
> deps: Bump zulip-markdown-parser to 1.0.6

- src/compose/ComposeBox.js
- src/users/usersActions.js
So that other user doesn't think that user is typing another message.
Set `lastTypingStart` as 0, when typing operation is stop, so that
immediate start typing event can be send to the server, if required.
> typingEvent: Report stop event to server on sending message.

- src/api/transportTypes.js
Mainly, refine "about version 1.7.0" to make clear that it is
present at 1.7.0 itself.  Also update the graf at the end for the
fact that once present it's present for all errors, not just some.
(A small followup to #3639 .)
> api errors: Small edits to discussion of `code`.

- src/webview/js/generatedEs3.js
- src/webview/js/js.js
Neither `String.startsWith` nor `String.includes` existed in the stock Android KitKat browser.
(Extracted from PR #3636.)
> webview js: add polyfills for Android KitKat

- ios/ZulipMobile.xcodeproj/xcshareddata/xcschemes/ZulipMobile release-mode.xcscheme
- ios/ZulipMobile.xcodeproj/xcshareddata/xcschemes/ZulipMobile.xcscheme
Also a couple of small cleanups.
Details, and background (most of which I just learned), in the first commit's long commit message.
These are byproducts of attempting today to make it possible to test push notifications in a build made directly from Xcode, without going through TestFlight. Haven't gotten that part working yet, but these seem independently helpful.
> xcode: Add a "run release mode" scheme.

- android/build.gradle
Per [1] and [2], update our target SDK version before the November
deadline.
Fortunately, there appear to be no changes listed that affect us. [3]
[1] https://developer.android.com/distribute/best-practices/develop/target-sdk
[2] https://android-developers.googleblog.com/2019/02/expanding-target-api-level-requirements.html
[3] https://developer.android.com/about/versions/pie/android-9.0-changes-28
> android: Update target SDK version

- jest.config.js
- package.json
- src/__tests__/metatests.js
- src/events/__tests__/eventActions--test.js
- src/webview/js/__tests__/appendAuthToImages.js
- src/webview/js/appendAuthToImages.js
- src/webview/js/generatedEs3.js
- src/webview/js/js.js
- src/webview/js/script.js
- tools/generate-webview-js
- yarn.lock
A comedy in three (somewhat intertwined) acts:
* Use Rollup to collect and collapse ES6 modules into a single file.
* Extend the Jest environment to allow mimicking a browser at an arbitrary URL.
* Extract a single function from the webview JS and test it.
> Enable modularization and testing of Javascript injected into webview

- package.json
- src/users/usersActions.js
- yarn.lock
(Draft, pending review/merge/upload of zulip/zulip#13315 .)
The shared code from the webapp now itself provides the interface we'd
constructed with this wrapper -- including jsdoc with all the same
information that was in the wrapper's jsdoc (indeed largely copied
from it.)  So, we get to cut out the wrapper entirely.
> Upgrade @zulip/shared to new, simplified typing_status API

- android/app/webviewAssets.gradle
- docs/howto/build-run.md
- tools/build-webview
- tools/lib/ensure-coreutils.sh
Sadly, this was more complicated than it looked, due to WSL/MSYS disagreements. (See comments.)
As a side effect, for the sake of script-maintainers' sanity, macOS users are now required to install `coreutils`.
> Fix invocation of bash script from Gradle on Windows

- android/app/src/main/java/com/zulipmobile/notifications/FCMPushNotifications.kt
- android/build.gradle
- docs/architecture/platform-versions.md
- docs/developer-guide.md
- src/webview/js/js.js
- tools/generate-webview-js
Much of this is data we already had in various places, pulled together into one; together with ways I'd been thinking about this but never written down in prose.
A thought I hadn't previously put together was:
* Among the complaints we hear from people who try using Zulip, we
rarely (possibly never?) hear that the app didn't support their
older device.  Meanwhile there are plenty of complaints we do hear
regularly!
And this reflects data I compiled for the first time while writing this up:
* Bug reports that turn out to be specific to an older OS version are
vanishingly rare.
* Of issues filed in the tracker, these seem to be <1% of them.
* Of reviews on Google Play, a small fraction are from older OS
versions, consistent with the distribution in our userbase, and
the ratings in these …
> Write up our approach to supporting old platforms; drop KitKat

- src/pm-conversations/PmConversationsCard.js
Because users are already cached, so that conversation list can be shown
by getting users from it.
This loader was added in 06c4de8e110fa5939c83b949333fae37e82fcfb3, at
that time user list was not cached in the redux.
Fixes: #3241
> pmConversationCard: Do not show loader while initial fetch is going on.

- src/webview/js/script.js
Extraneous trailing commas in function calls only became legal in ECMAScript 2017.
> webview js: fix prelude JS function call syntax

- src/api/apiFetch.js
This reverts commit a60a97a1ab5440e1b8221998a4c84623ded035eb.
Despite the commit order, this was originally written and tested
against the 0.x interface. In 1.x, these identifiers are no longer
available with this import method.
A future commit is planned which will incorporate this functionality
correctly, alongside Flow type declarations to ensure this does not
recur elsewhere.
> Revert "api: augment console.log with proper Sentry breadcrumb"

- .vscode/settings.json
New versions of the Prettier VSCode plugin (in particular, 3.8) have
started to complain about certain out-of-date settings in VSCode
config files.  Remove the relevant (or rather, now-irrelevant) config
option from our workspace.
Users may need to manually update their Prettier VSCode extension to
continue to format code with Prettier on save.
See, e.g:
- https://github.com/prettier/prettier-vscode/blob/62004a02b4/README.md#user-content-error-messages
> prettier: Remove old VSCode setting

- src/api/apiTypes.js
- src/api/settings/getServerSettings.js
- src/start/AuthScreen.js
- src/start/__tests__/AuthScreen-test.js
Most of the commits in this branch are just #3674 ; the last few are the part specific to this PR.
This is a draft because I haven't yet had a chance to test it end to end. Barring surprises there, though, I think the code is basically ready.
Fixes #3670 .
> Add support for SAML/etc auth

- src/notification/index.js
The registration failure event object is not a string; treating it as
such yielded only `[Object object]` in the console. Use the actual
type.
This type has been confirmed accurate for rn-notifications@1.5.0 (our
current version) and rn-notifications@2.1.6 (the latest available at
time of writing), as well as by inspection in the console after this
change.
> notifications: fix type of registration failure event

- src/actionTypes.js
- src/settings/settingsReducer.js
... and manually ensure that its declaration and use-site match.
(As seen Friday evening.)
> actions: fix typos in type of `notification_name`

- .eslintrc.yaml
Allow leading single underscores in object properties, as a stand-in for real private fields.
Also allow `for..of` loops and labeled statements. (I run into this about once a month, and end up going down a rabbit hole wondering why.)
> Linter tweaks

- src/chat/narrowsReducer.js
It turns out that `sort` without an explicit comparison function
has surprising behavior -- it converts everything to strings, and
compares the UTF-16 sequences.  So e.g.
> [11, 2, 22, 1].sort()
[ 1, 11, 2, 22 ]
This makes it acceptable really only for sorting strings, and even
then only for identifier-like strings.
For numbers, the right pattern is:
> [11, 2, 22, 1].sort((a, b) => a - b)
[ 1, 2, 11, 22 ]
A quick grep for nullary `sort` finds we've mostly handled this
correctly; but a quick grep finds one exception, where we're using
nullary `sort` on numbers.  It's the message IDs in a narrow, so
in fact we really are relying on keeping them in numeric order.
Fix the sort.
Happily this isn't a very common codepath, so it isn't likely many
users have hit this bug.
Fixes: #3752
> narrows reducer: Fix bad `sort` in an edge case.

- src/utils/__tests__/internalLinks-test.js
- src/utils/internalLinks.js
Links to narrows containing non-ASCII characters were not being fully decoded.
This should fix an error reported in Sentry: https://sentry.io/organizations/zulip/issues/1200774371/
> Fix decoding of internal narrow-links

- src/api/modelTypes.js
Narrow's `operator` field was originally optional to encompass a hack in the `TitleSpecial` and (former) `TitleHome` components. As that's long gone (see commit 806a131), we can tighten the type a bit.
> types [nfc]: remove optionality from Narrow::operator

- docs/howto/build-run.md
- tools/build-webview
Address three mostly unrelated Windows issues:
* Fix up the webview build script.
* Document a new explicit requirement to install `rsync`.
* Warn users to prefer Git Bash, rather than the Command Prompt, for now (#3776).
> Windows build issues

- src/boot/__tests__/reducers-test.js
- src/utils/__tests__/async-test.js
- src/utils/__tests__/url-test.js
Use jest-community helpers to compute certain properties, to provide
more precise information in case of failure.
(Inspired by a test flake for `sleep` in `async-tests`.)
> tests: push some complex expectations into Jest helpers

- tools/build-webview
The recent commit ca71acfbfc9843bce156bb161bd30f7ef076242a broke
webview builds on macOS by assuming that `readlink -m` was already
available.
Unfortunately, there's a Catch-22 here: we need $root to ensure we
have access to `readlink -m` in the first place! On the other hand, we
don't need a normalized form of $root, just something that will let us
run a script.
Delay normalization of $root until after `ensure-coreutils.sh` is run.
> webview build: unbreak recent macOS breakage

- src/api/apiErrors.js
- src/sentry.js
A 504 error _with_ JSON data is probably more surprising than one without.
> fetch: don't complain to Sentry about bad data in 5xx errors

- src/start/webAuth.js
- src/webview/js/js.js
I spent a lot of time at understanding the code and types but I was not able to discover any major new types as I feel most of them are already covered and many are just uncovered due to use of objects like window, document which does not have any typing.
This is my first PR at Zulip. I am very new to this codebase as well as TypeFlow due to which I have a few doubts which may be silly but I want someone to help me understand.
* In `src/common/icon.js`, we haven't mentioned types of `props`. Can anyone help me in extracting the possible properties of this object `props`? I traced its references and found some properties like `size`, `colour`. 
I also found `style` property in `props` which makes it really hard or even impossible to determine the type. Please correct me if I'm wrong.
Also, …
> Add Types (#2052): for url-parse and in js.js

- src/compose/ComposeBox.js
Fixes #3743.
This trims the topic string whenever the message text input is focused. Apart from preventing message with whitespace-only topic from sending, it will also remove whitespace from the start and end of the topic string like Zulip web version.
**GIF:**
> ComposeBox: Prevent message with whitespace-only topic from sending.

- src/message/messageActionSheet.js
Fixes #3528 
Earlier, a `reply` option was also shown in the messageActionSheet, which essentially performed no action, since the user is already in a topic narrow.
> MessageActionSheet: Remove reply option from ActionSheet when in a topic narrow

- .travis.yml
- src/compose/ComposeBox.js
Fixes: #3614
Now it looks like this:
- When unread notice is present, then it shrinks to a line. 
I am not sure, in ideal situation will it be visible fully or should we make it scroll up (hide behind navbar)
- When unread notice is not present
Behaviour is same on both Android and iOS
> composeBox, iOS: Fix msg input is not scrolled on typing.

- src/compose/ComposeBox.js
This reverts commit a2d6793aeac19259c205a175048f4017bf89ddcb.
Fixes #3820 (Send button never enabled in PMs), which was a regression
induced by the reverted commit.
Reopens #3743. Obviates and closes #3821.
> Revert "ComposeBox: Don't send message with whitespace-only topic."

- docs/howto/debugging.md
Adds information about `react-devtools`.
> docs: add react-devtools information

- src/message/messageSelectors.js
Followup to #3733. (This list isn't necessarily any shorter than the
list of all private messages.)
> logging: truncate list of unknown message IDs

- src/streams/EditStreamCard.js
button was referencing initialValue, when user clicks on that button it was not updating it's value
I have fixed it by changing current value of the button
Fixes:#3760
> Buttons on Create Stream: Fix Button UI not turns On clicking over,

- src/account-info/AccountDetailsScreen.js
- src/users/__tests__/userSelectors-test.js
- src/users/userSelectors.js
- static/translations/messages_en.json
Fixes #3551.
Two changes:
1. Deactivation status is shown.
1. Button text is "View private messages" instead of "Send private message"
**Before**: (Assume Cyphase is deactivated ) 
**After**:
I had to fiddle around a  lot to understand to get the relevant data, here is the reasoning why it is done in this manner:
- The get-all-users *is not* used by the mobile app to fetch user lists ( this is the list that contains is_deactivated data ). Instead, /register event queue is used.
- So, there is no direct way to get if a user is deactivated. However, `getActiveUsersByEmail()` returns only activated users, comparing it with current user can give us `is_deactivated`.
- A lot of informative and detailed comments are present in `/src/api/modelTypes.js:47` and  `/src/users/userSelectors.js`, the …
> account details screen: Display deactivation information for user

- android/app/build.gradle
Closes #3497.
GIFs weren't working on Android. This patch fixes that.
**Reason for changes**:
The earlier dependencies in build.gradle worked only for RN Version>0.60.
This configuration works for RN Version 0.59.
This is documented in the official docs for React Native 0.59 (https://facebook.github.io/react-native/docs/0.59/image#gif-and-webp-support-on-android)
> Lightbox: fix support for GIFs

- src/api/modelTypes.js
- src/api/registerForEvents.js
- src/message/fetchActions.js
- src/streams/StreamScreen.js
Updating the mobile app to respond to the overhaul of stream notification settings at #3449, so that a stream's notification setting can be null, instead of true or false. If null, it will default to the user's stream notification setting. The mobile app signals to the server that it will accept null by passing the following with the /register request:
```
client_capabilities: {
notification_settings_null: true,
}
```
(EDIT: now in new PR https://github.com/zulip/zulip-mobile/pull/3789) This also fixes all but one of the instances of connectFlowFixMe; one remains in ZulipStatusBar.js where the name `backgroundColor` is used for two different purposes and needs closer attention.
Also discovered (now at #3767) was a desire to stop reusing the StreamList component; it is currently used in …
> Stream settings user default

- src/compose/ComposeMenu.js
- src/compose/__tests__/ComposeMenu-test.js
> ComposeMenu.js: Handle null for fileName in response from ImagePicker.

- src/account-info/AccountDetails.js
Fixes #3816
**Before**: App crashed when viewing profile of a user whose timezone was invalid ( i.e Deprecated ).
**Now**: App does not display the user's local time, and does not crash.
> account details: Add error handling for unknown time zones

- src/compose/ComposeBox.js
Fixes #3743.
Trim the leading and trailing whitespace from topic when it is used by `getDestinationNarrow()` in `ComposeBox`. A consequence of this is that a whitespace-only topic gets converted to `(no topic)`.
Tested that:
- It works as expected.
- This mirrors the webapp behaviour, so it wont break things.
- Send button does not break in PM or group PM screens.
> compose box: Trim leading and trailing whitespace in topic.

- src/emoji/Emoji.js
Per the docs of the react-native-vector-icons package, this argument
is supposed to be the name of a font.  But there's no sign of a font
by this name actually appearing in the package, so it's hard to see
what passing it could actually mean -- instead, it just misleads the
reader by suggesting that this font is involved somehow.
And, empirically, the behavior is the same when this argument is
removed.  Tested in the reaction-list screen, in an emulated Pixel 3
running Android 10 and in an emulated iPhone 8 running iOS 13.
> emoji: Cut misleading ignored reference to an emoji font.

- src/webview/MessageList.js
Avoid a memory leak in the unlikely event that MessageList unmounts
less than 30ms after it mounts.
Discovered in https://github.com/zulip/zulip-mobile/pull/3848#issuecomment-580972016.
> MessageList: Clear ready retry interval on componentWillUnmount.

- src/chat/UnreadNotice.js
The height of UnreadNotice which was stucked on the top was
equal to the `paddingVertical` applied to it. So when it comes to shrink
RN was persisting padding.
Actually, this `View` wrapper is just a add on, not required. Styles can
be directly applied to `Animated.View`. So remove whis extra wrapper
from UnreadNotice, which fixes the issue.
Fixes: #3857
On this PR
> unreadNotice: Shrink height to 0 when compose box expands.

- src/message/messageActionSheet.js
This conditional does not mean the same thing as the old version!
The old version produced true for search narrows.
That would have been a bug, but... when we show a search narrow,
we actually pass `narrow={HOME_NARROW}` to `MessageList` (in
`SearchMessagesCard.js`), and so the `narrow` value that makes it
here is the home narrow.  So the bug is only latent, and this
commit makes no functional change.  Still good to fix latent bugs,
and to be explicit about the narrows where we *are* prepared to
offer the edit-message UI rather than try to list where we aren't.
> message actions [nfc]: Clarify which narrows offer "edit message".

- src/constants.js
Fixes: #3654.
The server correctly interprets this special number as indicating
that we want the latest messages (0 is used to request the oldest
messages). Later, we can conditionalize on the server version to
support the updated API merged in
https://github.com/zulip/zulip/pull/13747, that use the strings
'oldest' and 'newest' instead of 0 and 10000000000000000.
> Set LAST_MESSAGE_ANCHOR to 10000000000000000 (sixteen zeroes).

- src/api/messages/sendMessage.js
- src/outbox/outboxActions.js
Should fix #3729.
This is just a draft PR because it doesn't take into account the problem of what to do about existing messages in the outbox. (We *probably* don't want to flush a potential backlog of hundreds of messages all at once. Perhaps, during the following migration, we should drop messages stalled due to this bug that are more than a day old?)
> Permit use of commas in stream names

- src/webview/MessageList.js
This follows up on b2b274c4b with some further things we learned in
the discussion on its PR #3677, and in a pair of related chat threads:
https://chat.zulip.org/#narrow/stream/243-mobile-team/near/796432
Also add a couple more reference links, and adjust wording around
`file:///android_asset/` to avoid seeming to assert that it
corresponds to a directory really mounted somewhere in the filesystem.
> webview [nfc]: Further write up what we've learned about asset paths.

- src/types.js
- src/webview/html/messageAsHtml.js
Replace the hack in `Outbox` (which typed it as having certain fields
which it never possessed in practice) with a slightly more
sophisticated hack in the form of a compatible auxiliary type.
This closes a minor soundness hole (values of type `Outbox` could
incorrectly have been assigned the value `undefined` in those fields).
Perhaps more importantly, it also makes `Outbox` a `JSONable` type.
> types [nfc]: Add convenience type MessageLike.

- src/message/messageActionSheet.js
"See who reacted" option was listed first in message action options. then "Add reaction" was listed. This wasnt convinient for users. so interchanged their postions for the reason (i.e 'Add reaction'-'See who reacted').
Fixes: zulip#3871
> Fix Button Position: Options position in Message Actions

- src/message/messageSelectors.js
- src/search/SearchMessagesCard.js
- src/utils/message.js
- src/webview/MessageList.js
- src/webview/html/html.js
- src/webview/js/generatedEs3.js
- src/webview/js/js.js
- src/webview/js/script.js
- src/webview/webViewHandleUpdates.js
This clears up a swath of the confusion around the concept of "anchor" that I dug into following #3877 .
> Clean up the "anchor" values around the message list

- src/notification/index.js
APNs device tokens, as received through out iOS notifications library,
should be a hex string. Unfortunately, they're sometimes being sent to
the server as "[Object object]".
This is most likely due to the argument of `handleDeviceToken`
actually being an object, despite its typing as `string`, and being
improperly stringified by `encodeParamsForUrl`. However, it may
alternatively be the case that someone is mis-stringifying the object
before we get ahold of it, so log that case too.
This is work toward the resolution of #3672.
> APNs: log invalid device tokens, rather than sending them

- src/start/LoadingScreen.js
fix the status bar color in loading screen issue in https://github.com/zulip/zulip-mobile/issues/3860
> ui: Fix color of statusbar in loading screen.

- src/chat/Chat.js
- src/chat/__tests__/fetchingSelectors-test.js
- src/chat/fetchingSelectors.js
- src/chat/narrowsSelectors.js
- src/message/NoMessages.js
- src/message/fetchActions.js
- src/reduxTypes.js
- src/webview/MessageList.js
I sat down this afternoon to look at #3822 and #3802, and found I wasn't 100% sure under what conditions we show that "No Messages" message, and that it wasn't immediate to find out.
I dug into the code to answer that question, and this series of changes is the result. :slightly_smiling_face: They're all NFC refactors, and each step is simple; at the end, I think it's appreciably easier to reason about what's going on in this part of our UI.
> no-messages [nfc]: Clean up "fetching" selectors and "No Messages" UI logic.

- docs/howto/debugging.md
So people don't do the step unnecessarily.
> docs/howto/debugging: Move "you can skip this step" to top of the step.

- src/caughtup/caughtUpReducer.js
- src/chat/Chat.js
- src/chat/fetchingReducer.js
- src/chat/flagsReducer.js
- src/chat/narrowsReducer.js
- src/message/messagesReducer.js
Fixes: #3802.
When returning to the app after the event queue has expired, there's
a moment after stale data is purged when the app incorrectly
believes that an empty message list is the up-to-date state, and "No
messages! Why not start the conversation?" displays until fresh data
arrives.
Currently, state.messages and state.narrows are emptied on the
DEAD_QUEUE action, which is dispatched before the /register request.
Instead, preserve the stale data until /register completes, clearing
it in response to REALM_INIT.
In doInitialFetch, fetchTopMostNarrow, fetchPrivateMessages, and
(sometimes) fetchMessagesInNarrow are also dispatched after
/register to ensure the stale data is refreshed. All of these
already handle their loading states correctly, on a per-narrow basis
in state.fetching. …
> redux: Discard messages/narrows on REALM_INIT, not DEAD_QUEUE.

- src/common/ZulipStatusBar.js
- src/nav/ChatNavBar.js
- src/react-redux.js
- src/subscriptions/subscriptionSelectors.js
- src/title/__tests__/titleSelectors-test.js
- src/title/titleSelectors.js
Fixes #3451, as the final cleanup after most call sites were resolved in #3789.
The commit message on the most interesting step is:
---
status bar [nfc]: Fix connectFlowFixMe.
The thing that had made it gnarly to use our well-typed `connect` here was that we both took `backgroundColor` in as a prop of the outer component and then returned a `backgroundColor` from the `mapStateToProps` callback, to override the former as a prop on the inner component.
The same fact is also a source of complexity and surprise when trying to read the code as a human, because we're giving the same name to two slightly different things right next to each other.  Doubly so because those two things are a prop of a component passed to `connect` and the same-named prop of the resulting component -- and it's …
> Fix last `connectFlowFixMe`; and delete it!

- src/autocomplete/TopicAutocomplete.js
- src/chat/__tests__/narrowsSelectors-test.js
- src/chat/narrowsSelectors.js
- src/compose/ComposeBox.js
- src/drafts/__tests__/draftsSelectors-test.js
- src/drafts/draftsSelectors.js
- src/message/NotSubscribed.js
- src/message/messageSelectors.js
- src/message/messagesActions.js
- src/title/TitleStream.js
- src/topics/__tests__/topicsSelectors-test.js
- src/topics/topicSelectors.js
- src/webview/MessageList.js
part of #3015
Converted all to new style.
```
➜  zulip-mobile git:(issue-3015) perl -0ne '
print "$ARGV: $1\n" while (/^export const (\w+) = [^\n]*=>\s*createSelector/msg)
' src/**/*.js
```
> Issue #3015 Fix caching in "for narrow/streamId" selectors.

- src/__tests__/aux/lolex.js
- src/__tests__/metatests.js
- src/utils/__tests__/async-test.js
Separated out from #3727, with some improvements.
> Add Lolex for tests involving time

- src/api/modelTypes.js
- src/message/messageActionSheet.js
- src/pm-conversations/__tests__/pmConversationsSelectors-test.js
- src/pm-conversations/pmConversationsSelectors.js
- src/reduxTypes.js
- src/unread/unreadHelpers.js
- src/unread/unreadHuddlesReducer.js
- src/utils/recipient.js
- src/webview/html/messageHeaderAsHtml.js
This is a more substantial follow-up to #3931.
There's still plenty that's confusing about these interfaces, but I think this branch improves the situation a good bit.
I have some draft other changes, including to give `getRecipientsIds` a better name (turns out what it's really about is specifically for the "unread messages" data structure) and some jsdoc; to start cleaning up `normalizeRecipients` and `normalizeRecipientsSansMe`; and even to write down exactly what the story is for what appears in `display_recipient`! Those still require some further polish on a few points before they're ready to merge, though. And this branch is already more than I'd quite planned to do on this today. ;-)
> recipient [nfc]: Split up pm{Ui,Key}RecipientsFromMessage, and start on "unreads" keys.

- src/__tests__/exampleData.js
- src/webview/html/messageAsHtml.js
Originally part of #3912, in which this was performed manually. Candidate expressions were identified with a multiline search for `/==\s*undefined\s*\?/` and manually checked. (`null` was also checked for, but no simplifiable expressions using it were found.)
This revised commit was generated in part automatically, with a
temporary installation of jscodeshift. The resultant script:
* correctly excluded one item (`initialScrollMessageId`) noted to be incorrect in #3912;
* arguably correctly excluded another item (`ackedPushToken`) *not* noted to be incorrect;
* converted one item (`match_content`) in a technically-semantically-correct fashion that caused Flow to complain and required manual adjustment to fix;
* had to repeatedly reinvoke Flow via the shell to get type information; and
* …
> js [nfc]: Simplify expressions using `??`.

- src/__tests__/exampleData.js
- src/account/__tests__/accountsReducer-test.js
- src/account/accountActions.js
- src/account/accountsReducer.js
- src/actionTypes.js
- src/api/registerForEvents.js
- src/autocomplete/__tests__/getAutocompleteFilter-test.js
- src/autocomplete/__tests__/getAutocompletedText-test.js
- src/message/__tests__/messagesReducer-test.js
- src/message/fetchActions.js
- src/realm/realmActions.js
- src/start/RealmScreen.js
- src/types.js
- src/users/__tests__/userSelectors-test.js
- src/utils/__tests__/narrow-test.js
- src/utils/__tests__/zulipVersion-test.js
- src/utils/zulipVersion.js
This is WIP for the part of https://github.com/zulip/zulip-mobile/issues/3745 only concerned with storing the version number in Redux.
> Store server version in Redux (WIP for #3745)

- src/api/reportPresence.js
- src/boot/AppEventHandlers.js
- src/message/fetchActions.js
- src/presence/PresenceHeartbeat.js
- src/presence/__tests__/heartbeat-test.js
- src/presence/heartbeat.js
- src/users/usersActions.js
Rewrite, and possibly unnecessarily thoroughly test, the presence-heartbeat code.
Resumption of PR #3704.
Fixes #3699.
> Presence heartbeat (v2)

- android/app/src/main/java/com/zulipmobile/notifications/FcmMessage.kt
- src/actionTypes.js
- src/notification/__tests__/notification-test.js
- src/notification/extract.js
- src/notification/index.js
- src/notification/notificationActions.js
- src/notification/types.js
- src/session/sessionReducer.js
- src/utils/jsonable.js
* Correctly hook up to `react-native-notifications`. (Fixes #3672.)
* Verify (including by typechecking) the contents of APNs notification data.
* Remove some muddled [_sic_], now-unnecessary rectification code.
N.B.: The first commit here is a duplicate of the current #3906, and should be considered there.
> Local notification fixes

- docs/howto/translations.md
- flow-typed/translations.js
- src/i18n/locale.js
- src/i18n/messages.js
- src/settings/languages.js
This is part of #3895; this PR will update the current list to what it should be.
Doesn't yet work, I believe only because `locale.js` and `messages.js` aren't updated. Because @ray-kraesig is preparing a script to update those, I figure I'll hold off for a bit for that to be ready and save some effort. :)
See also the series of recent commits ending at 6775b4f44b35e70d03a93307ccd63af69b8c1d86, which documents this list and where the nontrivial parts of its data come from.
> Update list of offered languages

- src/boot/store.js
- src/i18n/messages.js
- src/settings/languages.js
Migrate `zh` to `zh-Hans`, and add support for `zh-Hant`.
Extracted from existing PR #3915.
> Support `zh-Hant`

- .eslintrc.yaml
- package.json
- yarn.lock
In abc043253, we disabled the only rule that remained enabled from
this plugin. So, remove the plugin. Leave the two existing
commented-out lines to enable other rules, which describe how we'd
like to potentially use them in the future. See:
https://github.com/zulip/zulip-mobile/pull/3901#discussion_r388026654
----------------
From https://github.com/zulip/zulip-mobile/pull/3901#issuecomment-596799693, where Greg said:
> I've also dropped the new commit that removes the eslint react-native plugin, because I realized that it doesn't yet remove it from package.json and yarn.lock 🙂 -- only from the eslintrc. That can be a good quick followup.
> eslint: Stop using react-native plugin.

- .prettierrc
The `babel-flow` and `flow` parsers produce subtly different ASTs, and Prettier's support for the latter is relatively poor.
In particular, when using the `flow` parser:
* ~~prettier/prettier#&zwj;5288: the private field sigil `#` is stripped.~~ *(Resolved.)*
* prettier/prettier#2597: type-declaration comments are promoted to inline type declarations.
This commit will enable some simple uses of private fields, but not all. See our commit 86a42582aace1b13f1e250b0a34835866b794e4a and its associated PR (#3725) for more detail.
The more important fix (and the one that can't be obtained by updating Prettier, at least not yet) is the second. This will allow us to rely on Flow's typechecking in scripts which will be executed directly by Node without a preliminary Babel run -- e.g., scripts …
> prettier: use Babylon (babel-flow) as the parser

- src/message/messageSelectors.js
- src/utils/__tests__/message-test.js
- src/utils/message.js
Please see the motivation for this at https://github.com/zulip/zulip-mobile/pull/3913#issuecomment-597910545, and in the commit message.
The second and third commits are marked [don't merge]. In removing these single-use helpers, I'm not sure whether the advantage of immediately simplifying the code (no more flipping back and forth between files, mainly) outweighs the concerns of a) losses in test coverage and b) future reusability, especially since a) the core logic of each is simple, and b) we haven't opted to reuse them since they were introduced over two years ago.
> Fix instance of #3457, "Narrow sometimes lands far in the past", for muted streams.

- src/presence/PresenceHeartbeat.js
- src/presence/__tests__/heartbeat-test.js
- src/presence/heartbeat.js
I reread this code closely today when thinking about [this bug report](https://chat.zulip.org/#narrow/stream/9-issues/topic/messages.20before.20status.20change/near/831348).
I didn't find anything that seemed like it could have caused it... a good outcome, because it turned out that came from the previous release, when this code looked quite different. :slightly_smiling_face: I did think for a while that I'd found something that possibly could have, because the way we avoid a certain problem is kind of subtle. Add a comment explaining the subtlety (complete with a state-machine diagram!), and a test for that case.
Also make a couple of changes that are mostly NFC in practice, but would improve the behavior in edge cases (or a hypothetical implementation change in RN), and that make the …
> presence: Fix some unlikely cases; add another test; draw state machine.
